### ISSUE TITLE
Spike: How do we ensure our networking is as it should be?

### ISSUE THREAD

**Issue by davidkelliott** [ministryofjustice/modernisation-platform#1036]
## User Story

We have complex networking in the platform, we need to find a way to ensure our networking is as we want it, and that we don't accidentally break it or introduce vulnerabilities.

Things that we should consider:
VPCs
Subnets
Routes
NACLs
????

How could we do this?
Checking for changes in code in PRs
Checking for unexpected changes in the environments
Checking routes/NACLs etc are as we expect in the environments
Checking traffic can flow as we expect
Transit gateway test tool
????

## Value

Increased security in the platform.
Confidence our networking is as it should be.
Confidence that we can make changes and any issues will be identified before they affect end users.

## Questions / Assumptions

There are lots of different things here and ways to achieve them, this spike is to identify which tests/checks would add the most value, and to start looking at options of how to achieve them.  Once these things have been identified tickets should be created for the work to spike the ones we want to move forward and try.

## Definition of done

- [ ] options investigated
- [ ] presented and discussed with team
- [ ] tickets for following work created

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by adeweetman-al** [comment]
Issues created around some potentially applicable tools/approaches
#1055 - IaC Network tester
#1056 - TGW route table analyzer
#1057  - Analysis and feedback from from vpc flow logs

**Comment by davidkelliott** [comment]
Work to be progressed under the above issues
