### ISSUE TITLE
Create AMI repository

### ISSUE THREAD

**Issue by davidkelliott** [ministryofjustice/modernisation-platform#1058]
## Definition of done

- [x] another team member has reviewed
- [x] tests are green

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by pete-j-g** [comment]
https://github.com/ministryofjustice/modernisation-platform/pull/1083
☝️ PR with code to add the repository

**Comment by pete-j-g** [comment]
PR merged and https://github.com/ministryofjustice/modernisation-platform-ami-builds has been created successfully.

**Comment by pete-j-g** [comment]
further PRs to configure access: 
https://github.com/ministryofjustice/modernisation-platform-ami-builds/pull/1
https://github.com/ministryofjustice/modernisation-platform/pull/1085
