### ISSUE TITLE
Networking design for AMI images in shared-services account

### ISSUE THREAD

**Issue by davidkelliott** [ministryofjustice/modernisation-platform#1060]
## User Story

We need a secure area in the shared services account to build ami images.

This should be something like an isolated VPC, this might need to have a public subnet if using github actions or it might be private if using AWS image builder, we should decide the tools we are using before tacking this one.

This issue is to design and draw out what this looks like.

## Definition of done

- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] tests are green

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by adeweetman-al** [comment]
Image builder chosen as basis for solution going forward.
This story is therefore focused on a network design with this in mind.
Specifically, intended outcome is an approved design encompassing
- secure, isolated VPC (with supporting subnets, NACLs, security groups etc) with
- VPC endpoints
- supporting egress to internet
