### ISSUE TITLE
AMI image workflow - create github action and verify workflow

### ISSUE THREAD

**Issue by davidkelliott** [ministryofjustice/modernisation-platform#1062]
## Definition of done

- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] tests are green

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by zuriguardiola** [comment]
https://github.com/aws-samples/amazon-ec2-image-builder-samples

**Comment by davidkelliott** [comment]
Covered in other tickets
