### ISSUE TITLE
Create team documentation on how to log into accounts as superadmin

### ISSUE THREAD

**Issue by davidkelliott** [ministryofjustice/modernisation-platform#1066]
## User Story

As a modernisation platform engineer
I need to know which role / account to use when logging on and accessing accounts as the superadmin
So that I can do my job

## Value

Some accounts such as the core-sandbox-dev account are only accessible via the superadmin role.  Whilst we want to cut down on using this role as much as possible, we should still have documentation on how to use it when needed.

## Definition of done

- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] tests are green

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by dms1981** [comment]
This actually looks like it's been done - https://user-guide.modernisation-platform.service.justice.gov.uk/team-guide/adding-a-new-team-member.html#adding-them-as-a-superadmin-in-our-aws-landing-zone
I'll go through the guidance there and see if it needs any adjustments for clarity then potentially close.

**Comment by dms1981** [comment]
NB - I think I acted before I thought here. I've submitted a very simple PR around the onboarding document with some minor fixes but the goal of this issue is for specific documentation talking about using AWS roles and accounts which I'm not yet familiar enough to answer.

**Comment by dms1981** [comment]
Completed through #1377
