### ISSUE TITLE
Backups Strategy

### ISSUE THREAD

**Issue by davidkelliott** [ministryofjustice/modernisation-platform#1087]
## User Story

We need a strategy of how we handle backups of the platform. Have a session on Backups

## Value

So that we can be confident that we can restore the platform if there is an incident.

## Questions / Assumptions

This ticket is to decide what we want to back up, and potentially how, the outcome should be an ADR and issues raised to complete the work needed.

## Definition of done

- [x] Session on backups
- [x] ask users what they want (previous ticket on back ups was met with silence)
- [x] ADR created
- [x] new backup issues raised
- [x] another team member has reviewed

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by ep-93** [comment]
Is this handling backups ON the platform, as in RDS, EC2 volumes, amazon mq, other amazon offerings etc, or is it about how would we backup the entire platform, hence backups of the platform?

**Comment by davidkelliott** [comment]
Meeting booked in for Friday

**Comment by davidkelliott** [comment]
https://github.com/ministryofjustice/modernisation-platform/issues/2612
And
https://github.com/ministryofjustice/modernisation-platform/issues/2613

**Comment by davidkelliott** [comment]
ADR - [#1087](https://github.com/ministryofjustice/modernisation-platform/issues/1087)
