### ISSUE TITLE
Build out performance hub production

### ISSUE THREAD

**Issue by davidkelliott** [ministryofjustice/modernisation-platform#1099]
## User Story

Build out the performance hub infrastructure in the production environment as the next step of continuing the performance hub migration.

## Value

Infrastructure for production is ready for Jeremy to start using.

## Questions / Assumptions

Should be as simple as uncommenting the production job and deploying the infrastructure.

## Definition of done

- [ ] performance hub infrastructure build for production
- [ ] another team member has reviewed
- [ ] tests are green

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by kcbotsh** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Modernisation-Platform-6155a4fbd2049a001b232e7b/issues/ministryofjustice/modernisation-platform/1099?planning-poker) with ZenHub @seanprivett
