### ISSUE TITLE
Define a networking strategy: VPCs/DNS/CIDR ranges

### ISSUE THREAD

**Issue by jakemulley** [ministryofjustice/modernisation-platform#111]
We should define a networking strategy for VPCs, DNS, and CIDR ranges to ensure we can automate, monitor and configure application VPCs centrally.

**Comment by jakemulley** [comment]
Account modelling and foundations:
- Defining the scope of what we're going to deliver
- ADR and high-level architecture diagrams for a typical account
- What are our requirements?

CIDR ranges, interconnectivity, AWS Transit Gateway, DNS and certificates.

**Comment by jakemulley** [comment]
We should write an ADR and produce a flow diagram for networking.

**Comment by philhorrocks** [comment]
We have defined the network strategy. This needs implemented.
