### ISSUE TITLE
Add CreateSecret permissions to the modernisation platform developer role

### ISSUE THREAD

**Issue by zuriguardiola** [ministryofjustice/modernisation-platform#1117]
## Expected Behavior

As a user of the Modernisation Platform I should have the ability to put secrets through the Secrets Manager console.

## Actual Behavior

modernisation-platform-developer is not authorized to perform: secretsmanager:CreateSecret

**Comment by davidkelliott** [comment]
Closed as secrets should be added via code, and then the value can be updated in the console
