### ISSUE TITLE
Fix bastion bug

### ISSUE THREAD

**Issue by davidkelliott** [ministryofjustice/modernisation-platform#1150]
## User Story

Following on from the previous story of rebuilding bastions daily, this ticket is to fix and verify the bastion is working as expected.

## Definition of done

- [ ] verify that the bastion is deleted daily
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] new bastion version deployed to a mp member

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by gfou-al** [comment]
Issues have come up after trying to update the performance hub environment. A pending issue is that some environments like performance hub are using the private_ip of bastion for CIDR configuration. However, this IP cannot be queried in the same way with the autoscaling group and additionally the IP will be changing on daily basis. We need some analysis to come up with a solution to this.

**Comment by gfou-al** [comment]
Blocked by https://github.com/ministryofjustice/modernisation-platform/issues/1202

**Comment by gfou-al** [comment]
- https://github.com/ministryofjustice/modernisation-platform-terraform-bastion-linux/pull/21
- https://github.com/ministryofjustice/modernisation-platform-environments/pull/160
