### ISSUE TITLE
Implement and test end-to-end image builder workflow in core shared services

### ISSUE THREAD

**Issue by adeweetman-al** [ministryofjustice/modernisation-platform#1152]
## User Story

As a modernisation platform team engineer 
I want to be able to use Image Builder in core-shared-services
So that I can demonstrate the workflow from image builder resource creation to the generation of shared AMIs

As an engineer consuming the modernisation platform for my application
I want to be able to see how Image Builder can be used
To create my AMIs according to agreed design and recommended best practices and conventions

## Value

This story gives us code-driven deployment of Image Builder resources (including components, recipes, pipelines, infrastructure configs and distribution settings) that result in generated and shared AMIs. It allows us to see with good clarity how all the resources fit together and we can utilise them through Terraform to define and build AMIs

## Questions / Assumptions

This story builds on design stories #1059 and #1125 to implement and test the definition and generation of AMIs.
At the time of writing this story, we assume
- we can utilise image builder natively to effectively share generated AMIs
- approaching the management of Image builder resources with Terraform does not throw up any unforeseen blockers from a technical or process point of view

## Definition of done

- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] implemented design showing how image builder resources can be deployed through terraform with surrounding process supporting the creation, management and consumption of AMIs
- [ ] Github action workflows deploying image builder resources into core-shared-services with AMIs shared across required accounts
- [ ] Demo to mod platform team

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by davidkelliott** [comment]
Duplicate this has been done
