### ISSUE TITLE
Terraform Static Code Analysis require_signed_commits

### ISSUE THREAD

**Issue by gfou-al** [ministryofjustice/modernisation-platform#1165]
## User Story

When creating a PR to add the GitHub slug for the Xhibit portal, the TFSEC linting tool (Terraform Static Code Analysis) reported the below issue.

```
Running TFSEC in terraform/github
Excluding the following checks: AWS095,GIT001,AWS050

  Result 1

  [github-repositories-require-signed-commits][HIGH] Resource 'module.terraform-module-trusted-advisor:github_branch_protection.default' does not have require_signed_commits set to true
  /github/workspace/terraform/github/modules/repository/main.tf:45


      42 |   repository_id          = github_repository.default.id
      43 |   pattern                = "main"
      44 |   enforce_admins         = true
      45 |   require_signed_commits = false    bool: false
      46 | 
      47 |   required_status_checks {
      48 |     strict   = true

  Impact:     You cannot guarantee the source of unsigned commits.
  Resolution: Require signed commits for all protected branches.

  More Info:
  - https://tfsec.dev/docs/github/repositories/require-signed-commits#github/repositories 
  - https://registry.terraform.io/providers/hashicorp/github/latest/docs/resources/branch_protection#require_signed_commits 
  - https://docs.github.com/en/authentication/managing-commit-signature-verification/about-commit-signature-verification 
```

For the full log refer to https://github.com/ministryofjustice/modernisation-platform/runs/3813784561?check_suite_focus=true

We need to decide whether to skip the issue or make the required modification.

Interestingly, the issue was not reported in follow up builds, probably because of path matching.

Another concern is that "Terraform Static Code Analysis" last run 22 days ago for the main branch. I am not sure if this is again due to path matching or if there was a decision to disable it for the main branch.

## Definition of done

- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] tests are green

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by davidkelliott** [comment]
Check impact on CI/CD pipeline if signed commits are enforced

**Comment by davidkelliott** [comment]
See this thread here - https://mojdt.slack.com/archives/CFE5ZQAQ7/p1636021657067900

This is going to be looked at at an Organisational level, so for now I think we should add in ignores for these warnings pending the organisational level decision.

**Comment by gfou-al** [comment]
https://github.com/ministryofjustice/modernisation-platform/pull/1242

**Comment by gfou-al** [comment]
Thanks Dave for starting the Slack thread. I added my thoughts into the attached file require-signed-commits.md and shared it in the Slack conversation. Closing this ticket now.

[require-signed-commits.md](https://github.com/ministryofjustice/modernisation-platform/files/7482370/require-signed-commits.md)
