### ISSUE TITLE
Implement AMI build design with Image Builder

### ISSUE THREAD

**Issue by adeweetman-al** [ministryofjustice/modernisation-platform#1169]
## User Story

As a modernisation platform engineer
I want to be able to use IaC and automation workflows to manage Image Builder resources, based on robust guidance
So that I can generate AMIs

## Value

- We can validate, test and gain feedback of our intended use of Image Builder by having another engineer run through the change process for a new or existing AMI
- Clear building blocks (with examples of us) for codifying hardened OS AMIs

## Questions / Assumptions

- The generation of code and workflows, supporting infrastructure and surrounding processes are based on the design (see AMI tab in Mod Plat architecture diagrams)

## Definition of done
- [x] Create starter-for-10 recipes for relevant version(s) of Windows Server and Linux, including relevant components
- [x] Re-formed code on the mainline branch that is consistent with the design choices around the IaC and the structuring of IB resources for different teams
- [x] Image builder resources deployable to core-shared-services account
- [x] Captured documentation/guidance in the README(s)
- [x] Demonstrate an approach to naming conventions
- [x] Another mod platform engineer can read the guidance and can confidently develop and deliver change to new/existing IB resources
- [x] Implement an image sharing mechanism that'd ideally cover all accounts (including newly created ones)
- [ ] another team member has reviewed and tried to build an image
- [x] show and tell handover

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by sobostion** [comment]
We have now covered the majority of the "done" criteria, with the exception of having another engineer to test out creating a pipeline themselves. I have created a separate ticket for that here:

https://github.com/ministryofjustice/modernisation-platform/issues/1254
