### ISSUE TITLE
Bring default security groups under TF and remove ingress/egress rules

### ISSUE THREAD

**Issue by davidkelliott** [ministryofjustice/modernisation-platform#1191]
## User Story

Following on from https://github.com/ministryofjustice/modernisation-platform/issues/1090
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/default_security_group

## Definition of done

- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] tests are green

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by adeweetman-al** [comment]
Workflows run to deploy changes into shared services, network services, security and logging core accounts.
