### ISSUE TITLE
Run static code analysis on a daily schedule

### ISSUE THREAD

**Issue by davidkelliott** [ministryofjustice/modernisation-platform#1194]
## Definition of done

- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] tests are green

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by pete-j-g** [comment]
PRs to resolve across multiple repos
https://github.com/ministryofjustice/modernisation-platform/pull/1231
https://github.com/ministryofjustice/modernisation-platform-terraform-bastion-linux/pull/20
https://github.com/ministryofjustice/modernisation-platform-environments/pull/162
https://github.com/ministryofjustice/modernisation-platform-ami-builds/pull/9
https://github.com/ministryofjustice/modernisation-platform-terraform-ecs/pull/6

**Comment by pete-j-g** [comment]
https://github.com/ministryofjustice/modernisation-platform/pull/1243
https://github.com/ministryofjustice/modernisation-platform-terraform-bastion-linux/pull/22
https://github.com/ministryofjustice/modernisation-platform-environments/pull/171
https://github.com/ministryofjustice/modernisation-platform-ami-builds/pull/14
https://github.com/ministryofjustice/modernisation-platform-terraform-ecs/pull/8
