### ISSUE TITLE
Scheduled baselines doesn't run on schedule

### ISSUE THREAD

**Issue by davidkelliott** [ministryofjustice/modernisation-platform#1239]
## Expected Behavior

This job https://github.com/ministryofjustice/modernisation-platform/actions/workflows/scheduled-baseline.yml

Should run every Saturday

## Actual Behavior

It's not running on Saturday, the job itself runs fine when manually triggered, but for some reason the scheduling isn't working.

## Steps to Reproduce the Problem

  1.
  1.
  1.

**Comment by dms1981** [comment]
Is it possible that this is getting caught by Github scheduler delays as described here: https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows#scheduled-events

Specifically, ```Note: The schedule event can be delayed during periods of high loads of GitHub Actions workflow runs. High load times include the start of every hour. To decrease the chance of delay, schedule your workflow to run at a different time of the hour.```

I can put up a PR to change the time to run a little earlier at, say, 22:30?

**Comment by dms1981** [comment]
Following the merge of #1370 I can see that scheduled runs are taking place once more: https://github.com/ministryofjustice/modernisation-platform/actions/runs/1672383419
