### ISSUE TITLE
Image Builder: Test pipeline creation

### ISSUE THREAD

**Issue by sobostion** [ministryofjustice/modernisation-platform#1254]
## User Story

As a modernisation platform engineer 
I need to test the creation of a new pipeline
So that I can confirm the ami repo functions as intended

## Value

We need to confirm the AMI repo functions as intended, e.g. a new engineer can easily create new pipelines and images using the framework currently in place.

## Questions / Assumptions

Can an engineer follow the Readme and create a working image pipeline as a result?

## Definition of done

- [ ] Image pipeline that can create instances successfully
- [ ] Feedback given on any issues encountered

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by gfou-al** [comment]
Nomis team will need RHEL 6.9 for WebLogic component and the DB uses RHEL 7.x. Reach out to Ewa Stempel from the Nomis team for further information on what they need.

**Comment by jackstockley89** [comment]
Image has now been built, once the default ebs encryption on the account was set to false. this is a issue which needs to be discussed and decided if we like to remove default encryption for the core-share-services account or create a key that can be shared across all accounts that we host

**Comment by dms1981** [comment]
Added this PR to allow access to key from core-shared-services: https://github.com/ministryofjustice/modernisation-platform-environments/pull/317

**Comment by jackstockley89** [comment]
Images in the MP pipeline can be created with a kms key, as after testing if the team account can create there own key and use the mp base image this has been successful. the Team image pipeline is now creating and sharing the sprinkler account

**Comment by dms1981** [comment]
Pipeline created and tested successfully with standard template builds available for teams to work from
