### ISSUE TITLE
Review/fix Protected/TGW Subnets CIDR allocation

### ISSUE THREAD

**Issue by donmasters** [ministryofjustice/modernisation-platform#1259]
## User Story

Review Protected and TGW subnets CIDR allocation with a view to automate allocation and reduce /16 requirement

## Value

At present we have a requiment to reduce the /16 CIDR requirement for Modernisation Platform, We require 7 /16 but need to reduce to as few as possible to 

## Definition of done

- [ ] implement new design for Protected subnet allocation
- [ ] implement new design for TGW subnet allocation
- [ ] readme has been updated
- [ ] user docs have been updated

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by gfou-al** [comment]
Vodafone has allocated the following subnets for the Modernisation Platform:

- 10.20.0.0/16 - MP will use this for networking resources.
- 10.26.0.0/16 - MP will use this for development/test environments.
- 10.27.0.0/16 - MP will use this for preproduction/production environments.
