### ISSUE TITLE
Rebuild remaining core accounts

### ISSUE THREAD

**Issue by davidkelliott** [ministryofjustice/modernisation-platform#1262]
## User Story

Rebuild the remaining core accounts to use the new CIDR ranges.

## Value

Ensure network connectivity and avoid overlapping ranges.

## Definition of done

- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] tests are green

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by donmasters** [comment]
core-security account has now been upgraded with the new cidrs

**Comment by donmasters** [comment]
core-logging account upgraded with new cidrs

**Comment by donmasters** [comment]
core-shared-services account upgraded with new cidrs

**Comment by donmasters** [comment]
these accounts are complete, closing ticket
