### ISSUE TITLE
Support Xhibit-Portal team

### ISSUE THREAD

**Issue by zuriguardiola** [ministryofjustice/modernisation-platform#1267]
## User Story

As an Xhibit-portal team member I need support from the Mod Platform team to develop into production quicker.

Work done in this sprint:

## Definition of done

- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] tests are green

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by dms1981** [comment]
* Built HMCTS preprod & xhibit portal preprod for team
* Provided support on email routing problem
