### ISSUE TITLE
Rebuild core networking account

### ISSUE THREAD

**Issue by davidkelliott** [ministryofjustice/modernisation-platform#1268]
## User Story

Rebuild the core networking to use the new CIDR ranges. This should be done separately from other accounts as it impacts everything and is the most complex.

## Value

Ensure network connectivity and avoid overlapping ranges.

## Definition of done

- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] tests are green

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by donmasters** [comment]
Core networking account has now been migrated to new CIDR ranges.
This change has been tested by ourselves and also using Performance Hub team

PR covering changes has been merged

Closing
