### ISSUE TITLE
Create a new core-vpc-sandbox account and migrate test envs

### ISSUE THREAD

**Issue by gfou-al** [ministryofjustice/modernisation-platform#1279]
## User Story

Create a new core-vpc-sandbox account.
Migrate sprinkler and cooker to it.
CIDR ranges may clash with PTTP, this is not an issue.

## Definition of done

- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] tests are green

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by SteveLinden** [comment]
core-vpc-sandbox was successfully created and made available. Tests showed the connections worked as expected.
