### ISSUE TITLE
Spike: Investigate how we can centrally report on non-tagged resources

### ISSUE THREAD

**Issue by jakemulley** [ministryofjustice/modernisation-platform#128]
We should look at creating something similar to the Cloud Platform's [Orphaned Resources](https://how-out-of-date-are-we.apps.live-1.cloud-platform.service.justice.gov.uk/orphaned_resources) but for non-tagged resources in AWS, so we can find their owner.

Evaluate our resources and member resources vs the guidance - list of non compliant resources.  We can then look at the automation / process for reporting on this regularly as a next step.

Ask Craig
Is there something AWS native that will do the job for us?

**Comment by dms1981** [comment]
@jakemulley  - was this solved by the implementation of AWS Resource Groups / Tag Editor? If so, are we clear to close this issue?

**Comment by davidkelliott** [comment]
https://technical-guidance.service.justice.gov.uk/documentation/standards/documenting-infrastructure-owners.html#documenting-owners-of-infrastructure tagging policy

**Comment by SteveLinden** [comment]
Currently investigating. Looks like it's not a simple process of looking at what we have and what's missing but, based on AWS information, it appears as though we need to look at individual items (e.g. S3, EC2 instance etc.) and then search for the tags on each of these. May be a little more long winded than we would expect.

**Comment by SteveLinden** [comment]
A quick check on one environment (though it was development) indicates the mandatory resources aren't included as tags, although they do exist on the pre-production environment.

**Comment by SteveLinden** [comment]
We discussed the options and there are a couple based on the limitations within terraform. The first is to use the AWS CLI to get all of the tagged items and the tags they contain. This would not be practicable in most cases as it doesn't list items without tags and produces a mountain of results. It also runs for the account connected (in a terminal window) unless you specify another. Examples are shown below:

aws-vault exec mod-platform -- aws resourcegroupstaggingapi get-resources --tags-per-page 100 | jq '.ResourceTagMappingList[] | select(contains({Tags: [{Key: " "} ]}) | not)' 


aws-vault exec test-platform -- aws resourcegroupstaggingapi get-resources --tags-per-page 100 | jq '.ResourceTagMappingList[] | select(contains({Tags: [{Key: "snaphot"} ]}) | not)' 

The first uses the standard mod-platform config which points to the modernisation-platform account and the second (test-platform) points to another (nomis-production) and ignores any tags for snaapshot. Best to run these yourself to see the results.

David Elliott noticed there was an aws config setting called required-tags which is setup on our system under [modernisation-platform-terraform-baselines](https://github.com/ministryofjustice/modernisation-platform-terraform-baselines) resource "aws_config_config_rule" "required-tags" which lists the 4 required tags. This is reported on but not actually sent anywhere other than inside AWS.

**Comment by SteveLinden** [comment]
The plan is to take the data above and report on it in a spreadsheet. This can then be sent to customers asking them to correct their systems to add the 4 required tags as a minimum. Doing so will enable us to ensure the system charges are correctly identified and sent to the correct customers.

We should also ensure that newer customers are aware of the required tags and that they will be added as systems are created.

**Comment by davidkelliott** [comment]
#2729
