### ISSUE TITLE
Ensure logs conform to MoJ security guidance

### ISSUE THREAD

**Issue by davidkelliott** [ministryofjustice/modernisation-platform#1291]
## User Story

As a Modernisation Platform user
I need to know I am following MoJ security guidance

Appropriately storing log data, eg are we storing anything secret in logs

## Value

Make sure we are following data and security guidelines.  Save money by not storing logs we don't have to.

## Questions / Assumptions

[Log retention periods here](https://security-guidance.service.justice.gov.uk/logging-and-monitoring/#maximum-retention-period)](https://security-guidance.service.justice.gov.uk/logging-and-monitoring/#maximum-retention-period)

## Definition of done

- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] tests are green

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by ep-93** [comment]
https://github.com/ministryofjustice/modernisation-platform/pull/2258 Merge for documentation 


https://github.com/ministryofjustice/modernisation-platform/blob/main/terraform/environments/core-logging/s3_logging.tf - Looks like we already meet the requirement.
