### ISSUE TITLE
Finalise VPC changes work - merge working branch to main

### ISSUE THREAD

**Issue by donmasters** [ministryofjustice/modernisation-platform#1314]
## User Story

During CIDR change migration the below branch has been used to apply changes locally, this has prevented unmigrated environments from being impacted.
BRANCH **CIDR-changes-working-branch**

## Definition of done

- [ ] CIDR-changes-working-branch merged to main and all environments tested
- [ ] CICD for all environments has been reactivated

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by gfou-al** [comment]
https://github.com/ministryofjustice/modernisation-platform/pull/1345
