### ISSUE TITLE
IT Heath check preparation - list out infrastructure

### ISSUE THREAD

**Issue by davidkelliott** [ministryofjustice/modernisation-platform#1317]
## User Story

The team performing the IT health check need to know what they are looking at, in a spreadsheet, list out the names/IDs for the following infrastructure listed in the scope document here - https://drive.google.com/file/d/1Nq7jSkl_CjRmmEk-lAj-MsepM7rQJIST/view?usp=sharing

## Value

Enable the testers to quickly find the required resources

## Definition of done

- [x] spreadsheet of infrastructure provided to testers
- [x] another team member has reviewed

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by dms1981** [comment]
First pass has been completed and is available for the team to review here: https://docs.google.com/spreadsheets/d/1R7P_WPz-Qp5q9C36W3ydVhbK68yQHwlo0or1wo5aKB4/edit#gid=0

**Comment by dms1981** [comment]
Spreadsheet provided to assigned testers via email
