### ISSUE TITLE
Investigate automatic rotation of AWS access keys every X days

### ISSUE THREAD

**Issue by jakemulley** [ministryofjustice/modernisation-platform#133]

**Comment by dms1981** [comment]
https://docs.aws.amazon.com/prescriptive-guidance/latest/patterns/automatically-rotate-iam-user-access-keys-at-scale-with-aws-organizations-and-aws-secrets-manager.html?did=pg_card&trk=pg_card

**Comment by davidkelliott** [comment]
I've done something similar in the past, there might be something we can reuse here - https://github.com/ministryofjustice/laa-ccms-shared/blob/master/shared-infrastructure/terraform-shared-services/lambda/key-rotation/main.py

**Comment by dms1981** [comment]
Given that we're progressing with OIDC, I'm going to close this card as it's no longer relevant.
