### ISSUE TITLE
Issue Slack notification upon AWS outage

### ISSUE THREAD

**Issue by gfou-al** [ministryofjustice/modernisation-platform#1331]
## User Story

The AWS status page https://status.aws.amazon.com/ shows general health status with AWS services.

The AWS Personal Health Dashboard: https://phd.aws.amazon.com/phd/home shows health status of AWS services specific to the account.

On Tue 7th Dec 2021 there was an AWS outage that made us to reschedule our planned CIDR migration for production systems.

It would be nice to be notified in Slack when AWS has an outage instead of reactively finding out about it.

In particular, when opening the AWS Personal Health Dashboard https://phd.aws.amazon.com/phd/home, there is the following suggestion: Stay informed quickly and easily. Did you know that you can send AWS Health events to Slack, email lists, or a custom destination of your choice? If you have Business or Enterprise Support, you can set up the AWS Health Aware tool within minutes to send Health events from your account or organization to almost any other destination. Learn more in this AWS blog post.

## Definition of done

- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] tests are green

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by dms1981** [comment]
[AWS Health Aware – Customize AWS Health Alerts for Organizational and Personal AWS Accounts
](https://aws.amazon.com/blogs/mt/aws-health-aware-customize-aws-health-alerts-for-organizational-and-personal-aws-accounts/)
Looks like there's a terraform option available [here](https://github.com/aws-samples/aws-health-aware#terraform) that could be a good starting point.

**Comment by davidkelliott** [comment]
Looks like we can do this with PagerDuty - https://support.pagerduty.com/docs/aws-health-dashboard#integrate-with-a-pagerduty-service

**Comment by davidkelliott** [comment]
We now get emails from AWS health for accounts we manage, and users get them directly. I think this is probably enough as any regional / AZ alerts which would affect user account we would get for our accounts.
