### ISSUE TITLE
User Research: Alerts for member infrastructure

### ISSUE THREAD

**Issue by davidkelliott** [ministryofjustice/modernisation-platform#1332]
## User Story

We have core alerts configured and being sent now to pagerduty - 
https://github.com/ministryofjustice/modernisation-platform/blob/main/architecture-decision-record/0017-monitoring-and-alerting.md

How do we expand on this to enable application teams to receive their own custom alerts to their own slack channels/ emails / oncall teams etc.

## Value

Consistent and easy to use alerting across the platform

## Definition of done

- [x] Carry out UR Canvas session
- [x] User interviews
- [x] UR Analysis

## Outputs / Decisions required

Should we spike AWS version of Insights which is Xray?
Is the Prometheus approach right for us?
Should stick with the CP approach.
Should MP do this or should it be an additional team?
We need to understand the work needed to set this up.
JL could source some existing background docs.
There are two working examples, CP and DSO.

**Comment by ScottSeaward** [comment]
Started interviews, have 5 users booked in. Will link outputs here when analysis completed.
