### ISSUE TITLE
Decide on support hours, oncall rota etc

### ISSUE THREAD

**Issue by davidkelliott** [ministryofjustice/modernisation-platform#1333]
## User Story

Now we have production applications we should consider what our support hours are and what kind of on-call rota we have (if any)

For info Cloud Platform do the following:
https://user-guide.cloud-platform.service.justice.gov.uk/documentation/reference/operational-processes.html#cloud-platform-operational-processes

## Value

Clearly define our support system so that users know what to expect.

## Definition of done

- [ ] team meeting to decide on support hours and on-call rota
- [ ] User guidance updated accordingly
- [ ] ADR documenting the decisions

Possibly break these out into other issues...

- [ ] Any changes needed to PagerDuty made
- [ ] another team member has reviewed

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by davidkelliott** [comment]
https://docs.google.com/document/d/1IXb2Fv-65WbaBQogDKNDcS0iRbo9KUv6oGnCI-_diyg/edit#

**Comment by seanprivett** [comment]
Out of hours agreed.  New ticket to be created for on call rota
