### ISSUE TITLE
Spike: Automate Github Repo Tidy up

### ISSUE THREAD

**Issue by davidkelliott** [ministryofjustice/modernisation-platform#1351]
## User Story

The modernisation-platform-environments repo is starting to get more use, and with that comes stale branches, PRs etc.  We want to be able to automate the closing of PRs and deletion of branches

## Value

Keep the repo tidy without manual intervention

## Definition of done

- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] tests are green

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by jackstockley89** [comment]
There is a go module which could be used to automate this, which then could be ran in an action 
https://github.com/google/go-github

**Comment by davidkelliott** [comment]
https://github.com/ministryofjustice/modernisation-platform/pull/2841
