### ISSUE TITLE
Resize Perf Hub infrastructure - Spike - what's involved?

### ISSUE THREAD

**Issue by seanprivett** [ministryofjustice/modernisation-platform#1353]
## User Story

1 day spike

All environments are sized the same across dev-preprod-prod.
Resize infra according to this thread:  https://mojdt.slack.com/archives/C013RM6MFFW/p1638806074218700

After a meeting between Fasih, GeorgeF and Jeremy Collins on 25 Jan 2022, we decided to re-consider the following change later:

- Database storage_type is gp2. We want to change to gp3. Apply the changes in the maintenance window on Monday evening. Convert this manually from gp2 to gp3, because terraform might time out in 40 min. Converting from gp2 to gp3 theoretically does not need a backup. The larger the data the longer it will take. For our amount of data it will take couple of hours.

Moreover, reducing the RDS instances is not feasible:

- RDS non-production instances cannot be reduced from instance_class db.m5.large to smaller instance_class. We're using SQL Server 2019 engine version sqlserver-se 15.00.4073.23.v1 In https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/CHAP_SQLServer.html under the section "DB instance class support for Microsoft SQL Server", looking at the "Standard Edition", we can see that db.m5.large is the minimal required. For example, to compare db.m5.large with db.t3.xlarge, refer to https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/Concepts.DBInstanceClass.html

## Definition of done

- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] tests are green

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by gfou-al** [comment]
- https://github.com/ministryofjustice/modernisation-platform/pull/1411
- https://github.com/ministryofjustice/modernisation-platform-environments/pull/342

**Comment by gfou-al** [comment]
As a result of this Spike, the following tasks were created:

- https://github.com/ministryofjustice/modernisation-platform/issues/1414
- https://github.com/ministryofjustice/modernisation-platform/issues/1415
- https://github.com/ministryofjustice/modernisation-platform/issues/1416
