### ISSUE TITLE
Config generating API authentication errors

### ISSUE THREAD

**Issue by davidkelliott** [ministryofjustice/modernisation-platform#1356]
Pagerduty alarm - https://moj-digital-tools.pagerduty.com/incidents/Q117AGKJKQUEK1?utm_source=slack&utm_campaign=channel

It looks like the managed policy that we have assigned to our config role - AWS_ConfigRole is missing the ListTaskDefinitionFamilies permission.  This is an AWS manage policy and we've added it in accordance with the config set up guidance.

Ticket raised with AWS support:
https://console.aws.amazon.com/support/home#/case/?displayId=9349392471&language=en

**Comment by dms1981** [comment]
Investigation showed that this was a temporary AWS issue that has since been resolved.
