### ISSUE TITLE
Testing environment for DEX TA work

### ISSUE THREAD

**Issue by Polsonby** [ministryofjustice/modernisation-platform#1360]
### Application Name

dex-ta

### GitHub team slug

dex-ta

### Environments

- [x] Development
- [ ] Test
- [ ] Preproduction
- [ ] Production

### Tags

tag | value
--- | ---
application | dex ta
business-unit | HMPPS
owner | Ian.anderson@digital.justice.gov.uk

#### Subnet sets

- [x] General - this application will use the same subnet as other applications in your business unit
- [ ] Isolated - this application has highly sensitive data which must have its own isolated subnet

#### How do users connect to the application?

- [x] Over the public internet
- [ ] With a purple cabled device (please give details)
- [ ] With a MoJ Official device

## Additional features

- [ ] Additional VPC Endpoints
- [ ] Extended DNS Zones
- [x] Other - bastion access

**Comment by jackstockley89** [comment]
Environment has been created and SSO link passed to Ian Anderson.
