### ISSUE TITLE
Connectivity between PSN and PPUD production environment

### ISSUE THREAD

**Issue by davidkelliott** [ministryofjustice/modernisation-platform#1382]
## User Story

The MP ppud-production account, private subnets, need to be able to access:

www.ppud.gsi.gov.uk
51.247.2.115 port 443 

## Value

Enable PPUD replacement team to get data from PPUD

## Definition of done

- [ ] routing and firewall changes in place
- [ ] another team member has reviewed
- [ ] tests are green

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by dms1981** [comment]
Reopened as corresponding change required in https://github.com/ministryofjustice/deployment-tgw to route traffic back to Modernisation Platform TGW

**Comment by dms1981** [comment]
https://github.com/ministryofjustice/deployment-tgw/pull/27 <- corresponding PR in the deployment-tgw repository

**Comment by dms1981** [comment]
All changes made

**Comment by dms1981** [comment]
Some progress made here: we discovered that although routing was in place to deliver traffic to the PTTP transit gateway it was not being correctly routed from there. We raised a PR - which was completed - to add the necessary routes to the relevant route table.
We then discovered that our traffic was reaching a set of security appliances where it was being accepted but not correctly routed back. We supplied the relevant administrator with our needs and are waiting to hear back from them.

**Comment by dms1981** [comment]
Still waiting on routing change. We have chased, but do not have a date for the change yet.

**Comment by dms1981** [comment]
As a follow-up @dazoakley and I have been in contact via email with the technical services operations manager for networks, and are awaiting a response.

**Comment by dms1981** [comment]
According to @dazoakley the relevant change was scheduled to take place on the evening of the 22nd so I'll check in with him to chase this today.

**Comment by dms1981** [comment]
PSN Palo change was successful; had to work around issues with inspection vpc temporarily pending a support case with AWS / further internal discussion in the team.
#1638 refers to the workaround
