### ISSUE TITLE
ITHC Support - remove temporary testing accounts

### ISSUE THREAD

**Issue by davidkelliott** [ministryofjustice/modernisation-platform#1384]
## User Story

Place holder for work around supporting the ITHC testing taking place from the 17th Jan.

## Definition of done

- [ ] ITHC completed

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by dms1981** [comment]
Requested information from scope document can be found here: https://docs.google.com/spreadsheets/d/1R7P_WPz-Qp5q9C36W3ydVhbK68yQHwlo0or1wo5aKB4/
