### ISSUE TITLE
How to auto update bastions with latest AMI version

### ISSUE THREAD

**Issue by davidkelliott** [ministryofjustice/modernisation-platform#1385]
## User Story

The bastions use an autoscaling group which recreates them daily.  But the autoscaling group pulls the AMI as defined in the launch template, this only gets updated from Terraform when the Terraform is run.

This ticket is to look into a solution that automatically updates the launch template with the latest AMI version.
## Value

Bastions are automatically updated daily to the latest AMI version.

## Definition of done

- [x] solution to automatically update the bastions to the latest AMI version in place
- [x] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] tests are green

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by dms1981** [comment]
Seems like a data call would be ideal here? https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/ami - could be used to return the most recent ami based on a few filters.

**Comment by dms1981** [comment]
I understand this a bit better now; in short, this is to find a way to flag the autoscaling / launch group to use the latest version of the AMI it's set to use, without needing to resort to Terraform updating that AMI when run via data call.

**Comment by dms1981** [comment]
The terraform guidance is here - https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/autoscaling_group#with-latest-version-of-launch-template
However, what that looks like in practice (eg, does it update to a more recent version without a terraform run), I don't know.

**Comment by dms1981** [comment]
Having done a little more thinking on this, I think that the `bastion_linux_template` needs to be decoupled from the code in `main.tf` and then run via github actions on a daily schedule.
The inline reference to the template would need to be replaced by a data call referring to the decomposed template, but this all seems quite achievable.

**Comment by davidkelliott** [comment]
Could we update the bastion Autoscaling groups across the platform with a Lambda?

**Comment by dms1981** [comment]
Having done some more thinking, could we use an SSM parameter (perhaps centrally) and run a GitHub action / terraform nightly to update the parameter? https://docs.aws.amazon.com/autoscaling/ec2/userguide/using-systems-manager-parameters.html

**Comment by mikereiddigital** [comment]
AWS auto-scaling has a feature called "Auto Scaling Scheduled Actions" that allows down & upscaling (to and from zero) of a group's ec2 instances at defined times. This, along with the SSM paramater suggestion above could provide the solution but the test will be whether the updated parameter value is picked up at relaunch or whether a terraform change is required.

**Comment by markgov** [comment]
draft PR created
https://github.com/ministryofjustice/modernisation-platform-terraform-bastion-linux/pull/548

**Comment by markgov** [comment]
Pr moved out of draft and is ready for review

**Comment by markgov** [comment]
Just need user docs updating on this and the PR to be reviewed and this call can be put to bed

**Comment by mikereiddigital** [comment]
I've reviewed this ticket and I'm happy it's been completed.
