### ISSUE TITLE
Create key aliases for KMS keys which are missing them

### ISSUE THREAD

**Issue by davidkelliott** [ministryofjustice/modernisation-platform#1393]
## User Story

Some of our KMS keys are missing aliases, we should create them.

## Value

Makes keys easier to identify and makes it possible to change the key without changing the code.

## Definition of done

- [ ] all KMS keys have aliases
- [ ] another team member has reviewed
- [ ] tests are green

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by SteveLinden** [comment]
It appears these keys do not appear in the terraform code so may be in place from past set ups. 

We discussed this and have decided we will, initially, disable these keys and then delete them in July.

**Comment by SteveLinden** [comment]
Done on core-logging first

**Comment by SteveLinden** [comment]
core-security amended

**Comment by SteveLinden** [comment]
All with no alias were amended to make them disabled in the core accounts. The above and
core-vpc-development
core-vpc-preproduction
core-vpc-sandbox
core-vpc-test
core-vpc-production
core-network-services
core-shared-services

**Comment by SteveLinden** [comment]
As requested, here is a list of the amended ones. Note, core-vpc-sandbox didn't have any keys with no alias.
 **core-logging**
7daed7d8-887d-460b-a686-ba6395640bb5
667c456b-c839-48d3-9cc0-9627cbf37b19

**core-network-services**
685a6485-7d31-4a10-ad96-add96edf84aa
f798f2e4-8d8f-46fb-a3ff-ce14cce3fcb0

**core-security**
629c9db4-c189-4b4e-a12e-dbd125c4a7fd
c1290b62-a99f-4301-916f-d363856de163

**core-shared-services**
8d63b340-d574-44aa-96e3-b2b489aad9e7

**core-vpc-development**
3e3e3f70-2b4e-4c44-927c-ed0965520cd6
d7ae37da-0663-4d40-a62f-ff927d12b7bc

**core-vpc-preproduction**
eebcfbca-eebe-42de-a3ee-61d8e8c7d520
f73e7732-80ad-48bc-9016-abab699638dd

 **core-vpc-production**
1a9dbdc8-8b0a-420c-98fd-1229a449876b
daa66ed4-aac5-460f-b42b-92c8422a7968

**core-vpc-sandbox**
No changes required

**core-vpc-test**
86b61231-baa6-4da1-9691-4c6687e0bebd
cdd2222d-4f63-49aa-bfac-a5ea0ca9abf1
