### ISSUE TITLE
Create guidance on KMS keys and how to use them with code examples for image builder

### ISSUE THREAD

**Issue by jackstockley89** [ministryofjustice/modernisation-platform#1407]
## User Story
Create guidance and code examples for different ways to use kms keys with image builder (a team kms key, business unit key, general key etc) that will allow other teams to setup a key for their own images.

## Value
As EBS encryption is set to enabled by default images are use the default key in the image builder account. This will allow teams to not be dependant on one key that is shared across all account, giving them option to use their own if they choose to.

## Questions / Assumptions

This has been tested in Issue #1254. To make sure that user use the correct permission a template would a good approach to ensure this.

## Definition of done

- [ ] Template added to the a correct repository
- [ ] another team member has reviewed

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by SteveLinden** [comment]
Initial reference put in to how it was set up and links to the associated pull requests so the code can be seen.

Need to add some examples of how it can be used with shared KMS keys such as ebs-hmpps to show how these can be used.

**Comment by SteveLinden** [comment]
Changes completed.
