### ISSUE TITLE
Create module for load balancer with access logs configured

### ISSUE THREAD

**Issue by davidkelliott** [ministryofjustice/modernisation-platform#1409]
## User Story

As a developer
I want to see which IP addresses are accessing my service
So that I can analysis and potential block ips if needed

## Value

Increases the ability to perform analysis on security threats

## Questions / Assumptions

Load balancer access logs are turned off by default, and are fiddly to set up (they go to S3 and need Athena to read)
This ticket suggests creating a module which would create an application load balancer with an option to enable access logs.  It would be good to have an optional on off, then in the code where the module is called you could have conditional expression to only enable for production.

All S3 buckets and logs should be created in line with security logging guidelines.

The new module should have static code analysis and tests

## Definition of done

- [ ] module for ALB with access logs
- [ ] readme has been updated and new module added to main readme
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] tests are create and green
- [ ] static code analysis on module
## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by dms1981** [comment]
Happy to review this one when you're ready for it to be looked at @zuriguardiola
