### ISSUE TITLE
Delete disabled KMS keys

### ISSUE THREAD

**Issue by davidkelliott** [ministryofjustice/modernisation-platform#1417]
## User Story

The following KMS keys have been disabled as they were originally used for cloud trail and security hub logs but are no longer needed.  They are not in code.  We disabled them rather than deleting to ensure nothing of value was encrypted with them.

The keys should now be deleted:
This story should be actioned in July 2022.

Keys:

 core-logging
7daed7d8-887d-460b-a686-ba6395640bb5
667c456b-c839-48d3-9cc0-9627cbf37b19

core-network-services
685a6485-7d31-4a10-ad96-add96edf84aa
f798f2e4-8d8f-46fb-a3ff-ce14cce3fcb0

core-security
629c9db4-c189-4b4e-a12e-dbd125c4a7fd
c1290b62-a99f-4301-916f-d363856de163

core-shared-services
8d63b340-d574-44aa-96e3-b2b489aad9e7

core-vpc-development
3e3e3f70-2b4e-4c44-927c-ed0965520cd6
d7ae37da-0663-4d40-a62f-ff927d12b7bc

core-vpc-preproduction
eebcfbca-eebe-42de-a3ee-61d8e8c7d520
f73e7732-80ad-48bc-9016-abab699638dd

 core-vpc-production
1a9dbdc8-8b0a-420c-98fd-1229a449876b
daa66ed4-aac5-460f-b42b-92c8422a7968

core-vpc-sandbox
No changes required

core-vpc-test
86b61231-baa6-4da1-9691-4c6687e0bebd
cdd2222d-4f63-49aa-bfac-a5ea0ca9abf1

## Definition of done

- [x] keys deleted

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by gfou-al** [comment]
All the above keys have been scheduled for deletion within 7 days from now, by 19 July 2022.
