### ISSUE TITLE
Threat modelling exercise

### ISSUE THREAD

**Issue by davidkelliott** [ministryofjustice/modernisation-platform#1422]
## User Story

As a modernisation platform engineer
I want to understand threats to the platform
So that I can build appropriate security

## Value

what threats are there from within moj to the Mod Platform that NWFW mitigates

Make sure we have security in place that is appropriate and not excessive

## Questions / Assumptions

https://aws.amazon.com/blogs/security/how-to-approach-threat-modeling/
What are the threats?
What do we have in place currently to mitigate these threats?
How can we improve/optimise security?

Note these last 2 questions may be better broken out into further sessions/issues

## Definition of done

- [ ] threats documented
- [ ] another team member has reviewed

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by ScottSeaward** [comment]
Did we cover this in the recent Alerts work #1480  or is this a separate issue

**Comment by davidkelliott** [comment]
https://miro.com/app/board/uXjVO4UACqU=/

**Comment by davidkelliott** [comment]
2nd session complete and all risks transferred to register
