### ISSUE TITLE
Review ITHC findings

### ISSUE THREAD

**Issue by davidkelliott** [ministryofjustice/modernisation-platform#1425]
## User Story

The ITHC is now complete and the findings are here - https://drive.google.com/drive/folders/1jp561wb5wjj7WK0JGU2z-o15mc-e-CCX

This ticket is to review the findings and create issues for and findings that we want to address.  There are 4 low risk issues and 1 medium risk issue to review.

## Value

Increase the security of the platform

## Definition of done

- [ ] risks reviewed
- [ ] issues created for actionable items

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by dms1981** [comment]
Findings reviewed, relevant issues created, spreadsheet updated with references to github issues.
