### ISSUE TITLE
ITHC Network ACL tightening

### ISSUE THREAD

**Issue by dms1981** [ministryofjustice/modernisation-platform#1462]
## User Story

As a modernisation platform engineer
I want to control network traffic entering and exiting my private and data subnets
So that traffic directly to or from the internet is not permitted

## Value

Our IT Healthcheck identified some points of configuration that could be adjusted to improve our security posture. Since our `private` and `data` subnets should not ordinarily need to communicate with internet addresses, we can replace any open network ACL entries with ones referencing private IP addresses instead. This will prevent any unintentional ingress to or egress from the internet.

## Questions / Assumptions

See ITHC report for further details

## Definition of done

- [x] remove any 0.0.0.0/0 entries from data & private ACLS
- [x] add entries for 10.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16
- [x] another team member has reviewed
- [x] tests are green

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by gfou-al** [comment]
https://github.com/ministryofjustice/modernisation-platform/pull/1536
