### ISSUE TITLE
ITHC Secure S3 buckets

### ISSUE THREAD

**Issue by dms1981** [ministryofjustice/modernisation-platform#1464]
## User Story

As a modernisation platform engineer 
I want to apply further security settings to some of my S3 buckets
So that all of our S3 buckets have the same security posture

## Value

Our IT Healthcheck identified some points of configuration that could be adjusted to improve our security posture. Some of our S3 buckets need adjusting to bring their security settings into a consolidated approach. The specific buckets and their requirements are documented in our IT Healtheck report. The only recommendation we are not going to take forward is the requirement for `MFA required for bucket delete`.

## Questions / Assumptions

See ITHC report in google drive for specific buckets related to listed issues

## Definition of done

- [x] Bucket Access Logging implemented where missing
- [x] HTTPS Enforced in bucket policy where missing
- [x] Encryption Enabled where missing
- [x] Bucket versioning enabled where missing
- [x] tests are green

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)
[ITHC Report](https://drive.google.com/drive/folders/1jp561wb5wjj7WK0JGU2z-o15mc-e-CCX)

**Comment by gfou-al** [comment]
The S3 bucket aws-athena-query-results-946070829339-eu-west-2 in the Modernisation Platform account is not managed by terraform. It was manually created and the kind of data it stores do not require encryption. Therefore, we decided to ignore the warning
<img width="1299" alt="Screenshot 2022-03-10 at 15 17 29" src="https://user-images.githubusercontent.com/84845604/157695340-fccfd607-83c9-4f3e-b6f6-5951192c84f2.png">
.

**Comment by gfou-al** [comment]
Same as the above applies for the bucket versioning warning:
<img width="1290" alt="Screenshot 2022-03-10 at 15 30 26" src="https://user-images.githubusercontent.com/84845604/157695688-18a6587b-94b4-47fd-bafe-9cdb081d156f.png">

**Comment by gfou-al** [comment]
Same as the above applies for the HTTPS enforced warning:
<img width="1294" alt="Screenshot 2022-03-10 at 15 32 09" src="https://user-images.githubusercontent.com/84845604/157696223-75c8bfdd-e912-4ca7-b8f0-15d9b0ff850a.png">

**Comment by gfou-al** [comment]
Our S3 bucket module (https://github.com/ministryofjustice/modernisation-platform-terraform-s3-bucket) complies with all the security practices suggested by the above warnings. In particular:

- **Bucket Access Logging implemented where missing**: Refer to log_bucket and log_prefix parameters in https://github.com/ministryofjustice/modernisation-platform-terraform-s3-bucket/blob/main/main.tf#L81
- **HTTPS Enforced in bucket policy where missing**: This warning only occurred for a manually created S3 bucket. None of the S3 buckets created through terraform reported such warning. Therefore, our S3 bucket module enforces HTTPS by default.
- **Encryption Enabled where missing**: Refer to the custom_kms_key and custom_replication_kms_key parameters in https://github.com/ministryofjustice/modernisation-platform-terraform-s3-bucket
- **Bucket versioning enabled where missing**: Refer to versioning_enabled parameter in https://github.com/ministryofjustice/modernisation-platform-terraform-s3-bucket
