### ISSUE TITLE
Upgrade to Terraform AWS Provider 4

### ISSUE THREAD

**Issue by davidkelliott** [ministryofjustice/modernisation-platform#1466]
## User Story

As a Modernisation Platform Engineer
I want to refactor our code to be compliant with V4 of the Hashicorp AWS Terraform Provider
So that we are using the most up-to-date version of the provider, keeping us in line with available bugfixes and enhancements

## Value

Version 4 of the AWS provider is out, our pipelines will start using this version and there are some breaking changes.  We need to refactor for this.

We may also want to document our process for conducting this upgrade.

## Questions / Assumptions

This ticket does not include member accounts

## Definition of done

- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] tests are green

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by dms1981** [comment]
I'll pick this one up (as I've already done some V4 work!)

**Comment by dms1981** [comment]
https://github.com/ministryofjustice/modernisation-platform-terraform-s3-bucket/pull/20 <- PR to upgrade downstream repo

**Comment by dms1981** [comment]
Solved with PR #1494

**Comment by dms1981** [comment]
Came back and added some clarification to the readme for the `modernisation-platform-terraform-s3-bucket` module. Will want to revisit some of this as BAU when resources / data calls become deprecated
