### ISSUE TITLE
Remove external ITHC testers for Xhibit-Portal

### ISSUE THREAD

**Issue by davidkelliott** [ministryofjustice/modernisation-platform#1479]
## User Story

Remove external ITHC testers for Xhibit-Portal ITHC to Xhibit-Portal accounts -

Thomas Marshall
Matthew Smith
Daniel Zielinski

## Value

Keep the platform secure

## Definition of done

- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] tests are green

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by SteveLinden** [comment]
All users with access to xhibit portal removed from collaborators in modernisation-platform

**Comment by SteveLinden** [comment]
Error: error removing IAM User (thomas.boyle) Virtual MFA devices: Error deleting Virtual MFA device arn:aws:iam::946070829339:mfa/thomas.boyle: AccessDenied: User: arn:aws:iam::946070829339:user/ci is not authorized to perform: iam:DeleteVirtualMFADevice on resource: arn:aws:iam::946070829339:mfa/thomas.boyle with an explicit deny
	status code: 403, request id: 80bc30e5-ce21-41b9-ae40-7ea27ae49ad8

+ the same for other users

**Comment by SteveLinden** [comment]
It was a deny on access required for the user ci. This was ported to the main on github and then run manually to delete the accounts
module.collaborators["thomas.marshall"].module.iam_user.aws_iam_user.this[0]: Destruction complete after 1s
module.collaborators["thomas.boyle"].module.iam_user.aws_iam_user.this[0]: Destruction complete after 1s
module.collaborators["matthew.smith"].module.iam_user.aws_iam_user.this[0]: Destruction complete after 1s
module.collaborators["lewis.smith"].module.iam_user.aws_iam_user.this[0]: Destruction complete after 1s
