### ISSUE TITLE
Spike:  core platform alerting - what next

### ISSUE THREAD

**Issue by seanprivett** [ministryofjustice/modernisation-platform#1480]
## User Story

We have set up alerting in the core platform, with a small number of alerts implemented.  What are the critical alerts we should work on next?

**Some starter stories for review and update**

As the Mod plat team
We need to know which alerts we should look at next
So that we are confident with the service provision

As the Mod plat team
We need to know which alerts we should look at next
So that we are aware of any possible issues

As the Mod plat team
We need to know which alerts we should look at next
So that we can plan our approach to alerts

## Value

Improved reliability of the platform, particularly as we now have production services running on it.

## Questions / Assumptions

@ScottSeaward is this something you could facilitate, even though we are the users/customers?

## Definition of done

Agreed set of alerts to work on, in priority order, with tickets created in the backlog.

- [x] Session to decide which alerts to take forward 
- [x] create follow on tickets 
- [x] Session with mod plat team to agree critical alerts

## UR Workshop Outputs 

These were created and voted on by the team

7 votes 
Issue  - What if AWS goes down or something breaks within it?
Possible solution  - Report AWS status to slack in case of outage 

https://github.com/ministryofjustice/modernisation-platform/issues/1331

4 votes
Issue  - DOS or cyber attack 
Possible solution  - Spot any unauthorised access to the platform

4 votes
Issue  - Loss of network access
Possible solution  - Monitor network availability constantly and notify people of issues

3 votes
Best practice 
Alert on unusual traffic in and out of tenant EC2 instances

3 votes
Best practice 
Use latest versions of stuff

3 votes
Best practice 
Review our risk register regularly

1 vote
Supply Chain attack
?

Other best practice noted 

- Don't give admin access to people who don't need it 
- Deploy across multiple regions (in case of AWS outage in London)
- EC2 health?
- IAM changes

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by ScottSeaward** [comment]
@seanprivett absolutely, I'll add a task above, thank you

**Comment by ScottSeaward** [comment]
Created a Miro Board to use for the user research piece with the team. https://miro.com/app/board/uXjVOLRiJGE=/?invite_link_id=416553689997

**Comment by ScottSeaward** [comment]
UR Workshop outputs here https://docs.google.com/document/d/1YR5zlSsin4Ny0LhE6VTnhNP8n70GMOXOifDUdZLiRs4/edit?usp=sharing
