### ISSUE TITLE
Recreate AWS Instance Scheduler in Terraform

### ISSUE THREAD

**Issue by dms1981** [ministryofjustice/modernisation-platform#1483]
## User Story

As a modernisation platform engineer 
I need to recreate the AWS Instance Scheduler CloudFormation Templates in Terraform
So that we can manage the implementation and configuration of AWS Instance Scheduler in line with our chosen IAC approach

## Value

Using CloudFormation stacks to deploy AWS Instance Scheduler allows us to quickly provision the main resources used as well as account credentials in subordinate accounts. However, CF does not allow us to easily detect drift in all resources; for example, DynamoDB entries.

Refactoring to use Terraform allows us to completely manage AWS Instance Scheduler through code, and allows us to offer AWS Instance Scheduler to other users who prefer Terraform to CloudFormation

## Questions / Assumptions

Assumption: the code will be created in a separate repository, eg: `modernisation-platform-terraform-scheduler`
Assumption: any references to AWS-hosted resources (eg, `aws-instance-scheduler/v1.4.0/instance-scheduler.zip`) will continue to point to their AWS-hosted locations.
Assumption: required IAM roles/permissions for remote account are documented in, but not provisioned through this module.
Assumption: Schedules/periods will be defined in the account where the instance scheduler module is called, not the module itself.

## Definition of done

- [ ] external repository created
- [ ] comparable functionality defined in terraform
- [ ] `main` resources successfully deployed through terraform in Modernisation Platform account (eg, `shared-services-dev`)
- [ ] instance scheduling observed to work in `remote` account (eg, `sprinkler-development`)
- [ ] readme created
- [ ] readme reviewed by other team member
- [ ] tests pass 

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)
[AWS Instance Scheduler](https://docs.aws.amazon.com/solutions/latest/instance-scheduler/welcome.html)

**Comment by Papina** [comment]
The current implementation of AWS scheduler uses a custom cloudformation resource that is referenced in the python code using the stack id.  If the idea is to pull the latest AWS python zip code, there will always be at least a cloudformation template to be deployed via tf with the custom resource.  So while not pure TF, it's close enough imho

**Comment by dms1981** [comment]
Looking into this, @Papina is right on the money - the stack ID is constantly referenced in the lambda.
While instance scheduler does some really nice things; logging of shutdown instances, reporting on instance shutdowns, working across accounts, it has a lot that we don't need.

Rather than working to redevelop this, or digging too deep into a self-rolled alternative, AWS SSM documents look to offer much of the functionality we're after.

**Comment by dms1981** [comment]
https://github.com/ministryofjustice/modernisation-platform/issues/1844
