### ISSUE TITLE
Decide on how we'll access EC2 instances

### ISSUE THREAD

**Issue by jakemulley** [ministryofjustice/modernisation-platform#149]
We should have an ADR for accessing EC2 instances:
- ssm
- bastion host
- workspaces

**Comment by jakemulley** [comment]
We'll add a high-level ADR for this.

**Comment by philhorrocks** [comment]
We have a strategy for accessing EC2 bastion hosts via SSM. An ADR document is required.

**Comment by davidkelliott** [comment]
If #408 is ok this would prove we can use SSM and bastions to cover all EC2 access needs that we are currently aware of.
