### ISSUE TITLE
Spike into application team runbook for Xhibit Portal

### ISSUE THREAD

**Issue by davidkelliott** [ministryofjustice/modernisation-platform#1517]
## User Story

As application teams or platform engineers, it is useful to have a run book for common operations, such as starting a service, restoring a service from backup etc.

This ticket is to have a look into what other teams do at the MoJ, is there a common standard?
Would it be beneficial for application teams to keep their run books in a standardised format on the Modernisation Platform?
Would it be beneficial for the platform team to have access to these runbooks?
Could we create a runbook template as part of the files we create when onboarding a new team?

## Value

Understand if there is any value in standardising runbooks for applications running on the Modernisation Platform.

## Questions / Assumptions

Spike - timebox TBC
## Definition of done

- [ ] research done and discussed with the team
- [ ] draft runbook for Xhibit Portal
- [ ] next steps agreed

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by ScottSeaward** [comment]
Canvas session held with team 01/09/22

**Comment by ScottSeaward** [comment]
Requested feedback from users, one so far

FEEDBACK 
User believes having a runbook template is a great idea. With help as to where to store, who the audience is, what languages are used, where hosted, interconnectivity,, how deployments work, backend database info.
Goal - business continuity / risk management / lottery situation
Store - in Github (would MP need a link to this?)
Permissions - dependant on service 
Sensitivity - S3 bucket name are treated as so, open buckets are vulnerable
When to create runbook - many changes throughout onboarding so after migration is better.
