### ISSUE TITLE
AWS terraform provider v4 upgrade (Xhibit Portal)

### ISSUE THREAD

**Issue by davidkelliott** [ministryofjustice/modernisation-platform#1518]
## User Story

As a modernisation platform engineer
I want to create documentation and provide support for teams to use the latest AWS provider version
So that they can upgrade with minimal assistance from the Modernisation Platform team

## Value

Much like #1466 , we want to provide customers of the modernisation platform with the ability to make the same use of Terraform's AWS provider V4. This will ensure that they have access to the most up-to-date features supplied by the provider, as well as bug fixes and other enhancements.

## Questions / Assumptions

We will supply guidance on version constraints and any code refactoring on request
We will need to help them with any terraform imports needed

## Definition of done

- [ ] guidance created
- [ ] providers updated
- [ ] all resources imported

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)
[Terraform AWS Provider Version 4 Upgrade Guide](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/guides/version-4-upgrade)

**Comment by dms1981** [comment]
All customers upgraded besides xhibit-portal. Given their upcoming delivery deadline we've agreed to revisit their upgrade on the week of the 28th of March.

**Comment by dms1981** [comment]
Completed in `xp-dev` and `xp-preprod` branches. Completed in feature branch for production, merged in through https://github.com/ministryofjustice/modernisation-platform-environments/pull/600
