### ISSUE TITLE
SPIKE:  Alert for DOS or Cyber attack

### ISSUE THREAD

**Issue by ScottSeaward** [ministryofjustice/modernisation-platform#1521]
## User Story
 
1) As a Mod Plat Team
I need to know when a DOS or Cyber attack is occurring
So that we can take the appropriate steps to mitigate it

2) As a Mod Plat Team
I need to know when a DOS or Cyber attack has occurred
So that I can gather information to use in an investigation

3) As a Mod Platform team
We need to guard our data from external illegal users
So that our services are not used for malicious purposes

We need to spike what alerting capabilities we have available with AWS Shield, WAF etc.
-->

## Links to 
#1480 

## Hypothesis

If we had a cloud watch alarm that was triggered by a DOS threshold
Then we could get an alert in Slack
Because we would have put processes in place

If we guard against these type of attacks
Then we would be complying with GDPR 
Because we would be upholding our team responsibilities and avoid legal implications

## Definition of done

- [ ] We need to spike what alerting capabilities we have available with AWS Shield, WAF etc.
- [ ] Discuss potential options with the team
- [ ] Raise a ticket on the work decided
- [ ] another team member has reviewed

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by davidkelliott** [comment]
https://docs.aws.amazon.com/whitepapers/latest/aws-best-practices-ddos-resiliency/visibility.html

**Comment by davidkelliott** [comment]
Shield Advanced is being activated soon, we can get DDoS metrics from this

**Comment by davidkelliott** [comment]
Sample alert created here - https://github.com/ministryofjustice/modernisation-platform-environments/pull/516
