### ISSUE TITLE
[SPIKE] Check to see what network Alerting we have and what we still need

### ISSUE THREAD

**Issue by ScottSeaward** [ministryofjustice/modernisation-platform#1522]
## User Story
1) As a Mod Plat Team 
We need to know when a loss of network access has happened
So that we can tell users

2) As a Mod Plat Team
We need to know when a loss of network access has happened
So that we can fix it

3) As a Mod Plat Team
We need to ensure the integrity of our network
So that we guard against reputational damage

## Value

I think there's two strands to this story:
* What alerting is presently in place? We should be able to see this by looking for CloudWatch alarms.
* What alerting is presently missing? Are there components that could be monitored (like Internet Gateways, Route Tables, or Transit Gateway attachments) that we can introduce monitoring for, and if so what would be appropriate to close this gap?

Further, with the monitoring we do have through our status page, what could we do here to make the monitoring more comprehensive? EG; how would we confirm a business unit VPC is "up"?
 
## Hypothesis

If we establish robust monitoring practices
Then we will ensure our network continues to enable MOJ services to work
Because we will react to any issues promptly 

## Definition of done

- [x] Confirm existing monitoring
- [x] Identify any gaps
- [x] Close gaps if possible (or raise new issues for significant gaps)
- [x] Research what tools exist

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by davidkelliott** [comment]
Need to check the state of existing alerts and if there are any more we could add.

**Comment by richgreen-moj** [comment]
Some alerts we already have in place... https://user-guide.modernisation-platform.service.justice.gov.uk/runbooks/cloudwatch-networking-alarms.html#cloudwatch-networking-alarms

**Comment by dms1981** [comment]
I'll refine this - I think it's a spike, but if I spent some time having a think about it I can rewrite this so it's ready for the team to refine / plan

**Comment by markgov** [comment]
https://docs.google.com/document/d/1I3vymZIkvhMDkW1TM56u_GShL-rScczrjHq3zCw2bxU/edit

**Comment by markgov** [comment]
New issue added to backlog
