### ISSUE TITLE
Fix failing SCA checks in modernisation-platform-ami-builds repo

### ISSUE THREAD

**Issue by davidkelliott** [ministryofjustice/modernisation-platform#1534]
## User Story

There are some checks failing here - https://github.com/ministryofjustice/modernisation-platform-ami-builds/runs/5507681918?check_suite_focus=true

## Value

We should fix them so that the check continues to add value and is not just ignored.

## Definition of done

- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] tests are green

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by gfou-al** [comment]
https://github.com/ministryofjustice/github-actions/issues/107

**Comment by gfou-al** [comment]
https://github.com/ministryofjustice/modernisation-platform-ami-builds/pull/32
