### ISSUE TITLE
Clean up security hub / config alerts

### ISSUE THREAD

**Issue by davidkelliott** [ministryofjustice/modernisation-platform#1535]
## User Story

We currently have security hub alerts which go off on pager duty.  We need to look at these alerts and either resolve the underlying issue, or silence them and add a more reasonable alert.

For example security hub requires any failed login attempts to raise an alert.  This happens occasionally and we don't need to know about this.  We have to keep the original alert for security hub compliance, but we could mute that alert on pager duty and create a more useful one, such as 5 failed login attempts in a 1min period.

## Value

Have alerts that when they go off we know we need to do something.

## Definition of done

-
- [ ]  timebox for 1 week maximum
- [x]  review current alerts from security hub
- [x] if alert is not valid, suppress the alert
- [ ] if new ticket required to suppress raise that ticket

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by markgov** [comment]
found two alarms that are going off  the first one is 
sign-in-failures GreaterThanOrEqualToThreshold 1.0 and the second is 
unauthorised-api-calls GreaterThanOrEqualToThreshold 1.0

**Comment by markgov** [comment]
https://github.com/ministryofjustice/modernisation-platform-terraform-baselines/pull/498
PR submitted

**Comment by markgov** [comment]
PR merged and new release created

**Comment by markgov** [comment]
https://github.com/ministryofjustice/modernisation-platform/pull/7376
Pr to update to the latest version

**Comment by markgov** [comment]
created an issue for an error that has been found

**Comment by markgov** [comment]
New Release created with new base count of 10 instances

**Comment by markgov** [comment]
New Cloud watch alarms
[#7450](https://github.com/ministryofjustice/modernisation-platform/issues/7450)
