### ISSUE TITLE
Performance Hub - create a CSR for the custom domains

### ISSUE THREAD

**Issue by zuriguardiola** [ministryofjustice/modernisation-platform#1541]
Create a CSR for the custom domains (domains managed outside of the modernisation platform) in the Performance Hub preprod and prod accounts. One month before certs expire.

DoD
- [x] Sort the certs for performance hub
- [x] Document the process going forward
- [x] Reviewed by another team member

**Comment by gfou-al** [comment]
https://github.com/ministryofjustice/modernisation-platform/pull/1618

**Comment by gfou-al** [comment]
Slack thread: https://mojdt.slack.com/archives/C01BUKJSZD4/p1647959251793639

**Comment by gfou-al** [comment]
https://github.com/ministryofjustice/modernisation-platform-environments/pull/476
