### ISSUE TITLE
New sandbox role for SSO

### ISSUE THREAD

**Issue by davidkelliott** [ministryofjustice/modernisation-platform#1557]
## User Story

This role will have higher permissions for use in development accounts, it will allow users to create and amend some types of infrastructure manually.

As a Mod Plat user
I need ???certain permission levels???
So that I can create and amend some types of infrastructure manually

As a Mod Plat Team
We need to ??? change permission levels ???
So that our users will ??? have more control / be able to...../ test, create, amend???

## User Type(s)
Does this impact specific user types?
Can it link to a persona? 

## Value

Allow developers to use the development accounts more like a sandbox.

## Questions / Assumptions / Hypothesis

If we give more permissions to users in dev accounts
Then they will be able to create and amend infrastructure manually
Because they will have control than they have currently

If something is created in the sandbox that they want to keep, how do they "keep it" so it doesn't get "nuked?

We need to decide what permissions to give users to ensure they can do the things they want but still ensure the safety and security of the platform.

## Definition of done

- [ ] new sandbox SSO role
- [ ] new policy for role
- [ ] UR test the role with a sample user set
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] tests are green

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by gfou-al** [comment]
https://github.com/ministryofjustice/modernisation-platform/pull/1799
