### ISSUE TITLE
Use the core-security account for SecurityHub and GuardDuty main reporting

### ISSUE THREAD

**Issue by jakemulley** [ministryofjustice/modernisation-platform#156]
We should centrally manage SecurityHub and GuardDuty findings in the core-security account.

**Comment by jakemulley** [comment]
Most of this has moved to be part of the wider MOJ effort to [centralise GuardDuty](https://github.com/ministryofjustice/aws-root-account/blob/main/terraform/guardduty.tf) for all members of the AWS Organization.

We should import filtered findings from that source (for Modernisation Platform member accounts only) into an ELK stack or otherwise for our team.

**Comment by dms1981** [comment]
I'm going to close this one as we handle this through the organisation-security account.
