### ISSUE TITLE
Create a runbook for DoS attack

### ISSUE THREAD

**Issue by davidkelliott** [ministryofjustice/modernisation-platform#1561]
## User Story

As a modernisation platform engineer
I need to know what to do when I'm alerted that we are experiencing a DoS attack
So that I can take action to keep the platform running

## Value

Better processes in place so that we know what to do when something happens.

## Questions / Assumptions

How does AWS Shield Advanced notify us/whoever of DOS so that the runbook is invoked
Who else needs to be notified when a DOS attack happens

## Definition of done

- [ ] readme has been updated
- [ ] runbook created
- [ ] another team member has reviewed
- [ ] 
## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by dms1981** [comment]
What alerting are we putting in place for DoS attacks?
What services are we putting alerting in for?
How will we receive the alerts?
Who will be notified?

**Comment by dms1981** [comment]
This ticket is tied to #1521
