### ISSUE TITLE
Add dependabot to repositories

### ISSUE THREAD

**Issue by dms1981** [ministryofjustice/modernisation-platform#1562]
## User Story

As a modernisation platform engineer
I expect to have dependabot enabled in all my terraform repositories
So that my dependencies are managed 

## Value

[Dependabot](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/about-dependabot-version-updates) allows us to receive timely notifications when code that we reference in our own projects is updated. This allows us to keep our dependencies updated without becoming a time-consuming activity

## Questions / Assumptions

* Dependabot is appropriate for all modernisation platform terraform projects

## Definition of done

- [ ] dependabot.yml present and configured in all `modernisation-platform` projects where downstream dependencies are present
- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] tests are green

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by davidkelliott** [comment]
Complete
