### ISSUE TITLE
Spike: automate public certificate renewal process

### ISSUE THREAD

**Issue by gfou-al** [ministryofjustice/modernisation-platform#1619]
## User Story

Applications like performance hub, use domains that are managed by the operations-engineering team:

- staging.hmpps-performance-hub.service.justice.gov.uk
- hmpps-performance-hub.service.justice.gov.uk

The above domains require public certificates, which can be requested from the operations-engineering team, as documented in https://user-guide.modernisation-platform.service.justice.gov.uk/concepts/networking/certificate-services.html#public-certificates (certificate-services.html.md.erb).

Also, periodically the certificates expire and need manual renewal, which can be cumbersome. As suggested by the operations-engineering team in the slack thread https://mojdt.slack.com/archives/C01BUKJSZD4/p1647959251793639, we would like to automate as much of the process as possible, both for the initial certificate request and its renewal.

For relevant context information refer to

- https://github.com/ministryofjustice/modernisation-platform/issues/1541
- The slack thread: https://mojdt.slack.com/archives/C01BUKJSZD4/p1647959251793639
- Runbook on the steps from the operations-engineering team: https://operations-engineering.service.justice.gov.uk/documentation/runbooks/manual-ssl-certificate-processes.html#create-manual-s[…]icate-processes
- Automated certificate renewal: https://security-guidance.service.justice.gov.uk/automated-certificate-renewal/#automated-certificate-renewal

## Definition of done

- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] tests are green

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by davidkelliott** [comment]
This should be covered with ACM see here - https://user-guide.modernisation-platform.service.justice.gov.uk/user-guide/how-to-configure-dns.html#dns-with-acm-certificate
Gandi.net certs will still need to be manual as they have to be purchased and imported.
