### ISSUE TITLE
Create Cloudtrail documentation

### ISSUE THREAD

**Issue by zuriguardiola** [ministryofjustice/modernisation-platform#1623]
## User Story

As an MP engineer I need to know where and how to query Cloudtrail logs in the core-logging account in case of security breaches, debugging, etc...
I need clear documentation explaining the location of the logs and instructions for querying the logs using Athena.

Athena database exists mod_cloudtrail_logs.

Add scenarios
Example athena queries for those scenarios

## Definition of done

- [ ] readme has been updated
- [x] user docs have been updated
- [x] another team member has reviewed
- [x] tests are green

**Comment by SteveLinden** [comment]
Looking at updates and comments that have been provided. I will amend the document, get confirmation and then move it across to the documentation we have in place.
