### ISSUE TITLE
Create usage documentation for the automated README workflow

### ISSUE THREAD

**Issue by zuriguardiola** [ministryofjustice/modernisation-platform#1636]
## User Story

As a MP user I might want to write modules and part of that requires the creation of a README. We have a workflow that automatically creates module READMEs but usage needs to be documented 

https://github.com/ministryofjustice/modernisation-platform-terraform-aws-vm-import/blob/main/.github/workflows/documentation.yml

## Definition of done

- [x] user docs have been updated
- [x] another team member has reviewed

**Comment by davidkelliott** [comment]
👍  I'm also thinking we might want to create a template repo for repositories that already has things like this, SCA, dependabot etc configured.
