### ISSUE TITLE
Module for an EC2 instance

### ISSUE THREAD

**Issue by davidkelliott** [ministryofjustice/modernisation-platform#1641]
## User Story

A user of the platform wants to quickly spin up an EC2 with sensible defaults. Then have the ability to modify this as needed so that it can work in multiple scenarios

Replace example code with whatever is built.

Don't reinvent the wheel, just borrow the Hashicorp wheel and paint it with MOJ colours

Can we re-use / lift the terraform from DSO that they use for their VM module?

The outcome is for people who want to quickly spin up an EC2 to eg test something - should be vanilla

## User Type(s)

MP Platform member user

## Value

Saves users times and helps improve security and coding standards by using sensible defaults.

## Questions / Assumptions / Hypothesis

If we create a module to build an EC2
And give it sensible defaults
And the option to override the defaults
Then we will have an EC2 module that is suitable for both quick usage and for applications

### Proposal

Create an EC2 Terraform Module

## Definition of done

- [ ] Terraform module created
- [ ] Terratest written
- [ ] Tested in example
- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] tests are green
- [ ] UR test OR added to continual research plan

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by dms1981** [comment]
There's a module available in `modernisation-platform-environments` used by the Equip team. I think it's just a fork of a Hashicorp module, though. Is this something that we want to actually build from scratch, or would it be enough to see what MOJ-specific customisations we'd need to make to the Hashicorp module?
https://github.com/terraform-aws-modules/terraform-aws-ec2-instance

**Comment by SteveLinden** [comment]
Very basic version of an ECS build added. Included bits that might not be needed and added a role for access purposes.
