### ISSUE TITLE
Create new role for sharing EBS snapshots

### ISSUE THREAD

**Issue by davidkelliott** [ministryofjustice/modernisation-platform#1671]
## User Story

Question from Julia in the #ask-modernisation-platform slack channel - 

>The images we're building for Nomis have multiple ebs volumes attached which convert to ebs snapshots when the ami is created and shared. When that ami is then used as a source for an aws_instance terraform resource, all is good. However, for our database, the extra volumes need to be managed as separate resources via aws_ebs_volume  and aws_volume_attachment With this we run into difficulties as a account into which the ami is shared doesn't have permission on the underlying ebs snapshots if those need to be directly managed.

copy everything across into the target account using target account IDs
need to add in a role to allow image builder to copy the AMI into that account
account to be created in core baselines so each account can adopt this role

## User Type(s)

Application engineer users

## Value

Enable EBS volumes created as part of the EC2 AMI Image builder pipeline to be shared and managed separately.

### Proposal

Spike in to the best way to do this, I have also raised a support ticket with AWS Case ID 9902640391 in the core-shared-services and have raised with Ross.

## Definition of done

- [ ] Plan on how to move forward with this

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by davidkelliott** [comment]
bit of progress on this from AWS support -
After engaging with internal teams, it appears that this feature should exist in the form of target account IDs within the distribution settings [1]. The two options for sharing AMIs are Launch Permissions and Target Account IDs so it is likely that the former was being used if you are unable to get full permissions to snapshots.
Currently, I think we are using Launch Permissions - https://github.com/ministryofjustice/modernisation-platform-ami-builds/blob/nomis/ami-builder/teams/nomis/rhel7_pipeline.tf
resource "aws_imagebuilder_distribution_configuration" "rhel7" {
  name = local.rhel7_pipeline.distribution.name

  distribution {
    region = local.rhel7_pipeline.distribution.region

    ami_distribution_configuration {

      name = local.rhel7_pipeline.distribution.ami_name

      launch_permission {
        user_ids = local.ami_share_accounts
      }
    }
  }
}
Could you try running with the following please and see if there is any difference?
resource "aws_imagebuilder_distribution_configuration" "rhel7" {
  name = local.rhel7_pipeline.distribution.name

  distribution {
    region = local.rhel7_pipeline.distribution.region

    ami_distribution_configuration {

      name = local.rhel7_pipeline.distribution.ami_name
	  
	  target_account_ids = local.ami_share_accounts
      launch_permission {
        user_ids = local.ami_share_accounts
      }

      }

    }
  }
}

**Comment by davidkelliott** [comment]
See slack thread of error after making the above change, but - 

```
Please make sure your 'EC2ImageBuilderDistributionCrossAccountRole' is setup with correct permission policies.
```
Looks like we need to create the following role in the member accounts with the boot strapping - 
https://docs.aws.amazon.com/imagebuilder/latest/userguide/cross-account-dist.html

**Comment by davidkelliott** [comment]
This role should be created in the delegated access bootstrapping so that it exists in all accounts. Users can then choose if they want launch permissions or account id method of sharing amis

**Comment by dms1981** [comment]
Is it also discussed here?
https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ebs-modifying-snapshot-permissions.html#share-unencrypted-snapshot
This talks through sharing process for encrypted and unencrypted snapshots

**Comment by davidkelliott** [comment]
Julia has create this role here - https://github.com/ministryofjustice/modernisation-platform-environments/blob/main/terraform/environments/nomis/ec2-image-builder-iam.tf move this to sit with the other EC2 image builder code and add guidance on how to use (the different methods of sharing AMIs)
