### ISSUE TITLE
NOMIS Production Environment

### ISSUE THREAD

**Issue by rwhittlemoj** [ministryofjustice/modernisation-platform#1677]
## Environment details

Production

### Application Name

NOMIS

### GitHub team slug

studio-webops

### Environments

- [ ] Development
- [ ] Test
- [ ] Preproduction
- [x ] Production

### Tags

tag | value
--- | ---
application | nomis
business-unit | HMPPS
owner | 

#### Subnet sets

- [ x] General - this application will use the same subnet as other applications in your business unit
- [ ] Isolated - this application has highly sensitive data which must have its own isolated subnet

#### How do users connect to the application?

- [ ] Over the public internet
- [ ] With a purple cabled device (please give details)
- [x ] With a MoJ Official device

#### Connectivity to other applications or external parties

Requires connectivity to Azure fix 'n go for database replication - same as currently have for the test account.

## Additional features

- [ ] Additional VPC Endpoints
- [ ] Extended DNS Zones
- [ ] Other - please specify

**Comment by SteveLinden** [comment]
Nomis production environment created. Will leave this here while we await confirmation

**Comment by SteveLinden** [comment]
Change needed today to put the NACLs in similar to those for test. Completed
