### ISSUE TITLE
SPIKE: how to build Module for DNS and certificates on the platform

### ISSUE THREAD

**Issue by davidkelliott** [ministryofjustice/modernisation-platform#1679]
## User Story

As a user, I want to be able to quickly set up DNS for my services

What is the smallest thing we can build that will be useful?

## User Type(s)

Developer or engineer user

## Value

Make setting up DNS and certificates easier

## Questions / Assumptions / Hypothesis

The way to set up DNS and certificates is documented but requires a few different things to work properly which can easily cause trouble for first time users.
- What trouble is caused?
- Why is it only first time users and what are the different things?
- Does this affect other first time set up processes?

If we create a module, we expect that it will make it easier for first time users to create DNS and certificates and require less input from mp engineers to resolve queries.

## Definition of done

- [ ] module created
- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] Tested in example
- [ ] Terratests written and passing
- [ ] another team member has reviewed
- [ ] tests are green
- [ ] UR test OR added to continual research plan

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by markgov** [comment]
PR Created to create a new repo
https://github.com/ministryofjustice/modernisation-platform/pull/3858

**Comment by markgov** [comment]
initial code pr on new repo
https://github.com/ministryofjustice/modernisation-platform-terraform-dns-certificates/pull/3

**Comment by dms1981** [comment]
Definition of done here is maybe a bit big for a spike.

**Comment by davidkelliott** [comment]
Senarios:

1. Non production uses mp domains and certificates, production uses delegated hosted zone domain and ACM certificates
2. Non production uses mp domains and certificates, production uses delegated hosted zone domain and Gandi certificates
3. Non production uses uses delegated hosted zone, production uses delegated hosted zone domain and ACMs certificates
4. Non production uses uses delegated hosted zone, production uses delegated hosted zone domain and Gandi certificates
