### ISSUE TITLE
Performance hub RDS action AWS recommendations

### ISSUE THREAD

**Issue by davidkelliott** [ministryofjustice/modernisation-platform#1687]
AWS have notified us on the following issue, we should action according to recommendations:

Hello,

We would like to inform you of an important service guidance for Amazon RDS for SQL Server Multi-AZ instances based on Microsoft's recommendation. Microsoft recommends that port 3343 must be open in order to utilize UDP and TCP traffic so that Windows Server Failover Cluster (WSFC) service can continue to communicate across the cluster nodes [1].

TCP and UDP traffic on port 3343, directionally in-bound and out-bound, need to be allowed in Network ACLs of your VPC as well as in the Security Group that is attached to your Amazon RDS for SQL Server Multi-AZ instance(s).

Blocking traffic on port 3343 for TCP and UDP protocols could cause unexpected failures in WSFC service, which can lead to a service outage for Multi-AZ instances.

For information on modifying Network ACL and adding ACL rules, refer to the 'create-network-acl-entry' document [2].

For information on adding inbound or outbound rules to your Security Groups refer to the available documents [3][4].

Please see Amazon RDS for SQL Server FAQ [5] for more details. If you have any questions, please reach out to AWS Support [6].

[1] https://docs.microsoft.com/en-us/troubleshoot/windows-server/networking/service-overview-and-network-port-requirements
[2] https://docs.aws.amazon.com/cli/latest/reference/ec2/create-network-acl-entry.html
[3] https://docs.aws.amazon.com/cli/latest/reference/ec2/authorize-security-group-egress.html
[4] https://docs.aws.amazon.com/cli/latest/reference/ec2/authorize-security-group-ingress.html
[5] https://aws.amazon.com/rds/sqlserver/faqs/
[6] https://aws.amazon.com/support

**Comment by jemnery** [comment]
Thanks for the continuous improvement Edd :slightly_smiling_face: I think I saw this notification about SQL on RDS a few months back via Jake, but at the time I wasn't sure sure it applies to us? I think we only have a single AZ, not a multi-AZ instance. But if you're recommending we apply this change anyway, I can approve the PR.
