### ISSUE TITLE
Guidance on how to view shared accounts

### ISSUE THREAD

**Issue by davidkelliott** [ministryofjustice/modernisation-platform#1714]
## User Story

As a member account developer I need guidance to show me how to change roles to view core/shared resources.

## User Type(s)

Member account developers

## Value

Gives member teams the ability to see core/shared resources without relying on the Mod Platform team.

## Questions / Assumptions / Hypothesis

Create documentation/guidance showing how member account developers can switch roles to view resources created and shared from core accounts. 
The documentation should have explicit mention of the role required to switch roles and the account aliases needed to view each type of resource.

### Proposal
A proposal that is something testable, don't worry whether it works or not, it's a place for ideas. 

## Definition of done

- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] tests are green
- [ ] UR test OR added to continual research plan

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by zuriguardiola** [comment]
roles that people can assume are:

- member-delegation-<core-vpc> for the core vpcs
- modify-dns-records for core-network-services
- member-shared-services for core-shared-services

Account name aliases are the name of the terraform workspace for each account rather than the account name

**Comment by zuriguardiola** [comment]
https://user-guide.modernisation-platform.service.justice.gov.uk/user-guide/member-read-only-core-accounts.html#viewing-core-account-resources-as-a-member-account-developer
