### ISSUE TITLE
SPIKE: Enable Macie on the platform

### ISSUE THREAD

**Issue by davidkelliott** [ministryofjustice/modernisation-platform#1777]
## User Story

https://aws.amazon.com/macie/

Spike to see what the value of enabling Macie on the platform would be.

Timebox at 1-2 days

## Definition of done

- [ ] Timebox of 1 or 2 days
- [ ] Value of adding Macie at org level understood
- [ ] Findings presented to team
- [ ] Discussion on implementation started

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by SteveLinden** [comment]
For info

Pricing (USD)
Preventative control monitoring
Monitor and evaluate S3 buckets for security and access control
Buckets / month
$0.10 per bucket
Object monitoringMonitor and evaluate S3 objects for automated sensitive data discovery
Objects / month
$0.012 per 100k objects
Object analysis for sensitive data discovery
Analyze and report sensitive data in S3 objects by running jobs or performing automated sensitive data discovery
First 50 TB / month
$1.25 per GB
Next 450 TB / month
$0.63 per GB
Over 500 TB / month
$0.31 per GB

**Comment by SteveLinden** [comment]
It seems a little complicated to use but may be useful. 

Costs (on Sprinkler-development with only 6 buckets) may be deemed excessive ($19.71 estimate on the 30 day trial) but that would be up to whoever purchases it to decide.

Currently having some issues on setting up a bucket to send the results to so I have raised a call with AWS to see if they can explain why or offer any insights. I have followed their example for setting everything up as far as I can see.

**Comment by SteveLinden** [comment]
This is a useful youtube video explaining the usage of it.

**Comment by SteveLinden** [comment]
A couple of errors were made in setting up the KMS and the S3 access rights. Contacted AWS support and they quickly spotted these mistakes. Call [171146130901179](https://support.console.aws.amazon.com/support/home?region=eu-west-2#/case/?displayId=171146130901179&language=en) lists these

**Comment by SteveLinden** [comment]
If items are stored in the S3 area it's a long way down to get them. For example on sprinkler the file would be in (as an example) macie-test-results-22032024/AWSLogs/348456244381/Macie/eu-west-2/258e5c3ccb0b28ecbdbc3d63132ba8a3/348456244381/018db474-8f5e-305e-9ea7-5a846b546f60.jsonl.gz

The details aren't exactly clear either but in Macie it is slightly easier to see. Accessing the data is a little more difficult but can be done.

**Comment by SteveLinden** [comment]
Added another job (so 3 now) and the estimated cost has jumped to $ 37.97

**Comment by SteveLinden** [comment]
The "high" results listed (only on Sprinkler) are stored in "macie-sample-finding-bucket" which I can't locate. Not sure if this really exists as a bucket.
**The cost seems quite high**. This is on Sprinkler which has a total bucket size of 1.1Gb. Modernisation Platform has a bucket size of a fraction under 192Gb so the cost would ramp up significantly for this. Sprinkler is currently at $40.70 estimated cost and has only been in place for 5 days. I will update this again when the next job run has completed.

**Finding results is not great**. After looking at the results from jobs there are, currently this many results. Severity:[Low: 2](https://eu-west-2.console.aws.amazon.com/macie/home?region=eu-west-2#findings?search=severity.description%3DLow)[Medium: 51921](https://eu-west-2.console.aws.amazon.com/macie/home?region=eu-west-2#findings?search=severity.description%3DMedium)[High: 9](https://eu-west-2.console.aws.amazon.com/macie/home?region=eu-west-2#findings?search=severity.description%3DHigh)
As mentioned above the high do not appear to relate to our buckets directly. The can be reduced by considering the Suppress Findings option but this does not appear to work. You can reduce the time but, again, this does not appear to show just today's data (as an example).

These are my initial findings. I will update this as more come to light

**Comment by SteveLinden** [comment]
Another quick look at [Macie](https://docs.aws.amazon.com/macie/latest/user/what-is-macie.html) from AWS. It **only** looks at S3 components. This could be an issue if data is stored in these that needs to be kept "invisible" from the world.

I installed a temporary version on Sprinkler which I will remove once this call is closed.

**Comment by SteveLinden** [comment]
New job run following conversations with the team. This increased the cost to $ 51.25

**Comment by SteveLinden** [comment]
Raise a call on AWS but didn't see it appear so I've raised an online one.
At the moment it doesn't look like we can exclude specific items (e.g. name) from being searched. AWS are checking for me

**Comment by SteveLinden** [comment]
Simon has identified one team we can offer this to. I will chase up on this next week when we return from the long weekend.

**Comment by SteveLinden** [comment]
Simon is going to contact the team and let me know who to speak to.

**Comment by SteveLinden** [comment]
Although Macie is expensive it may be

**Comment by SteveLinden** [comment]
Will close the call now

**Comment by davidkelliott** [comment]
Hi @SteveLinden what is the output of this issue?  Are we going to use Macie? Do more issues need to be created? If so could they be linked here please.  Thanks

**Comment by SteveLinden** [comment]
Currently Macie has been set up on the Sprinkler-development account using the 30 day free trial. This will be stopped shortly to prevent charges being incurred on this account, Not needed on an internal development account.

To allow user access it would need to be set up more permanently rather than as a trial. This would simply be a case of enabling Macie using Amazon Macie. 

If an S3 bucket is needed to allow storage of results this needs to be created in S3 and a new KMS key created to give access. The details of the KMS key are shown in AWS documentation but it needs to have the account and details such as this included
     _"Condition": {
                "StringEquals": {
                    "aws:SourceAccount": "348456244381"
                },
                "ArnLike": {
                    "aws:SourceArn": [
                        "arn:aws:macie2:eu-west-2:348456244381:export-configuration:*",
                        "arn:aws:macie2:eu-west-2:348456244381:classification-job/*"
                    ]__
These details are not needed elsewhere but the instructions list REGION:account so not the eu-west-2 and the account number that are listed. The KMS key and bucket names are needed to link the S3 bucket to the account to enable the Macie details to be sent. Using the S3 bucket, although it provides additional data, can prove difficult to access.

The only other thing needed is a job to be set up. This was done manually in Sprinkler but it may be possible to set this up using terraform and I would advise users to do this.

Macie will be disabled in Sprinkler in the next few days to prevent charges being incurred.
