### ISSUE TITLE
Review: security around github actions

### ISSUE THREAD

**Issue by davidkelliott** [ministryofjustice/modernisation-platform#1778]
## User Story

Security review of our github actions to ensure they are still secure.  
Wider conversation with the team to raise any concerns.

## Definition of done

- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] tests are green
- [ ] UR test OR added to continual research plan
- [ ] List of security issues in GHA presented back to the team and discussed for prioritisation

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by dms1981** [comment]
https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions

**Comment by davidkelliott** [comment]
We should add tag protection - https://registry.terraform.io/providers/integrations/github/latest/docs/resources/repository_tag_protection

https://github.com/ministryofjustice/modernisation-platform/issues/2617

**Comment by davidkelliott** [comment]
We should stop using this 3rd party Slack bot - https://github.com/ministryofjustice/modernisation-platform/issues/2217

**Comment by davidkelliott** [comment]
Checked for injection script vulnerabilities in our main repos, none found

**Comment by davidkelliott** [comment]
Preventing GitHub Actions from creating or approving pull requests - not enabling as we have proper PR review oversight

Fork pull request workflows from outside collaborators - changed from first time to all, any users contributing should be in the org or have permissions to push.
