### ISSUE TITLE
[SPIKE] Review how we check and monitor security group access

### ISSUE THREAD

**Issue by davidkelliott** [ministryofjustice/modernisation-platform#1835]
## User Story

As a Modernisation Platform Engineer
I want to investigate methods for auditing AWS Security Group rules
So that we are appropriately using open SG rules

## User Type(s)

Modernisation Platform Customer

## Value

Review how we check and monitor security group access, this is to ensure customers don't configure unprotected access points to the modernisation platform.

Does SecurityHub do enough? Is it just a question of correlating the results so that we can take action?

## Definition of done

- [ ] set appropriate timebox for spike
- [ ] identify AWS-centric ways of auditing security groups
- [ ] investigate other tools that could be integrated with a GitHub action?
- [ ] options identified and presented to team
- [ ] follow-on issues raised

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by dms1981** [comment]
The most obvious tool to use here would be AWS Firewall Manager, as it can be used to audit security groups across, for example, a OU: [How to continuously audit and limit security groups with AWS Firewall Manager](https://aws.amazon.com/blogs/security/how-to-continuously-audit-and-limit-security-groups-with-aws-firewall-manager/)

An alternative option would be something like (https://steampipe.io/), but I think that would require an account-by-account approach.

**Comment by davidkelliott** [comment]
These are also currently raised by security hub

**Comment by SimonPPledger** [comment]
closed as a duplicate
