### ISSUE TITLE
Add protections to Transit gateway

### ISSUE THREAD

**Issue by davidkelliott** [ministryofjustice/modernisation-platform#1836]
## User Story

As a modernisation platform engineer
I want to protect the transit gateway resource and monitor it with more detail
So that unexpected outages are less likely to occur, and reported in a timely fashion.

## User Type(s)

Modernisation Platform Customer

## Value

The transit gateway is a key part of our network infrastructure.  We should add protections and monitoring to know if there are any issues with it.

Add `prevent destroy=true` to terraform to prevent accidental deletion.
Add cloudwatch monitoring alarms linked to pagerduty based on transit gateway metrics.

### Hypothesis 
If we protect our TGW from accidental deletion
Then we remove the risk of isolating our customer VPCs from the wider MOJ network

### Proposal

* Add terraform `prevent destroy` statements
* Add cloudwatch alarms for TGW
* Link cloudwatch alarms to PagerDuty

## Definition of done

- [ ] terraform has been updated
- [ ] any relevant docs have been updated
- [ ] another team member has reviewed
- [ ] tests are green
- [ ] pagerduty integration tested

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by davidkelliott** [comment]
Raised support case to ask about monitoring here - https://us-east-1.console.aws.amazon.com/support/home?region=eu-west-2#/case/?displayId=10267670201&language=en

**Comment by dms1981** [comment]
#1985 adds the `prevent_destroy` to the relevant resources, leaving the cloudwatch alarms, sns topic, and pagerduty integration to be completed.
