### ISSUE TITLE
Create Terratests for Mod Platform Modules

### ISSUE THREAD

**Issue by zuriguardiola** [ministryofjustice/modernisation-platform#1856]
## User Story

As  a Mod Platform developer I need to ensure that our modules are being tested regularly in an automated way. The tests can include naming conventions, IAM policy checks, security group checks, etc..

Modules that require Terratests:

- [x] modernisation-platform-terraform-bastion-linux (GeorgeF, Done)
- [x] modernisation-platform-terraform-ecs (Zuri, Done)
- [x] modernisation-platform-terraform-s3-bucket (Steve,Done)
- [x] modernisation-platform-terraform-s3-bucket-replication-role (Done)
- [x] modernisation-platform-terraform-aws-vm-import (Zuri, Done)
- [x] modernisation-platform-terraform-pagerduty-integration (David, Done)
- [x] modernisation-platform-terraform-loadbalancer  (Steve)

Terratests should be automated - an example can be found here: https://github.com/ministryofjustice/modernisation-platform-terraform-s3-bucket-replication-role

## Definition of done

- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] tests are green
- [ ] Terratests are part of a pipeline

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by gfou-al** [comment]
https://github.com/ministryofjustice/modernisation-platform-terraform-bastion-linux/pull/30
