### ISSUE TITLE
Fix the issue on the SCA warnings for code in Example

### ISSUE THREAD

**Issue by SteveLinden** [ministryofjustice/modernisation-platform#1861]
User Type(s)
MP engineer

Issue
A number of issues are identified in the check which may be found in https://github.com/ministryofjustice/modernisation-platform-environments/runs/6795089720?check_suite_focus=true

These need to be checked and the issue listing them amended.

**Comment by dms1981** [comment]
Brought into current sprint as this should be fairly straightforward

**Comment by dms1981** [comment]
https://github.com/ministryofjustice/modernisation-platform-environments/pull/792
