### ISSUE TITLE
Investigate testing methods for Terraform

### ISSUE THREAD

**Issue by jakemulley** [ministryofjustice/modernisation-platform#189]
We should investigate testing methods for our Terraform, like [kitchen-terraform](https://github.com/newcontext-oss/kitchen-terraform).

**Comment by andy3267** [comment]
Take me of this system. I have nothing to do with the MOJ
    On Monday, 14 December 2020, 08:58:45 GMT, Jake Mulley <notifications@github.com> wrote:  
 
 


We should investigate testing methods for our Terraform, like kitchen-terraform.

**Comment by jakemulley** [comment]
We recently have started investigating [Terratest](https://github.com/gruntwork-io/terratest) and [OPA](https://www.openpolicyagent.org/docs/latest/).
