### ISSUE TITLE
Automation to remove or deactivate unused users from our github team

### ISSUE THREAD

**Issue by davidkelliott** [ministryofjustice/modernisation-platform#1895]
## Definition of done

- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] tests are green
- [ ] UR test OR added to continual research plan

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by seanprivett** [comment]
Is this something that should sit with Operations Engineering, rather than something we'd automate ourselves?

**Comment by davidkelliott** [comment]
Ops eng do this already, can close
