### ISSUE TITLE
Spike: How can we prevent or monitor excessive usage in member AWS accounts

### ISSUE THREAD

**Issue by davidkelliott** [ministryofjustice/modernisation-platform#1897]
## User Story

Eg using up lots of IPs, large instances, lots of resources etc.

Org level alerting so that it can see everything in the OU
Could be a billing thing

## Definition of done

- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] tests are green
- [ ] UR test OR added to continual research plan

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by ewastempel** [comment]
Closing this one, as it's a duplicate of #83
