### ISSUE TITLE
SPIKE: Automation to run TF plan and report to users if their environments are out of sync with their code

### ISSUE THREAD

**Issue by davidkelliott** [ministryofjustice/modernisation-platform#1899]
## Definition of done

- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] tests are green
- [ ] UR test OR added to continual research plan

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by SimonPPledger** [comment]
This is more of an application issue and individual app teams can run account specific plan
