### ISSUE TITLE
SPIKE: Plan how we would rebuild the platform in another region

### ISSUE THREAD

**Issue by davidkelliott** [ministryofjustice/modernisation-platform#1905]
## User Story

In case of a disaster, we want to be confident that we can completely rebuild the platform in another region.

This is more of a test of our ability to rebuild.

We assume we will do this in  EU-west-1 (SP checking with security)

There might be a few items that are region specific, we should record these.
There might be some things that we cannot, or don't want to, include - again these should be recorded including why they were not included.

This is to cover the core and user infrastructure.

It does not include applications

## Definition of done

- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] tests are green
- [ ] UR test OR added to continual research plan

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by SimonPPledger** [comment]
Lets add some more information, including any limitations etc

**Comment by ep-93** [comment]
Tickets Raised 

https://github.com/ministryofjustice/modernisation-platform/issues/5503

https://github.com/ministryofjustice/modernisation-platform/issues/5501

THERE WILL BE MORE but these need to happen first.
