### ISSUE TITLE
Identify key  platform components then we might need to rebuild

### ISSUE THREAD

**Issue by davidkelliott** [ministryofjustice/modernisation-platform#1908]
## User Story

As an MP engineer
I need to know what to do if a component of the platform, eg networking component or AWS account, disappears.
So that I can recreate it

Step 1. identify key components.
Step 2 will be to create tickets for the individual runbooks

## Definition of done

- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] tests are green
- [ ] New tickets raised for the actual runbooks
- [ ] UR test OR added to continual research plan

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by ep-93** [comment]
https://user-guide.modernisation-platform.service.justice.gov.uk/runbooks/dr-process.html#priority-list - Priority List

https://user-guide.modernisation-platform.service.justice.gov.uk/runbooks/dr-process.html#single-account - Single account

**Comment by dms1981** [comment]
I think @ep-93 has covered a lot of this, but I would see the following as *platform* components that would need to be reconstituted in the event of a region loss.

- Ministry of Justice root account
  - AWS Organizations Service Control Policies restricting use of AWS outside of `eu-west-2`
- Modernisation Platform AWS account
  - Contains components necessary to run the platform
  - Some of these are either global, or replicated to different regions
  - KMS keys, S3 buckets, DynamoDB, used for Terraform state
- core-logging-production AWS account
  - S3 buckets used for storing logs & attendant KMS keys already appear to be replicated into `eu-west-1`
- core-network-services-production AWS account
  - Transit Gateway would need to be created in new region
  - `external-inspection` VPC & Network Firewall for communication with internal MOJ networks
  - `non_live_data` / `live_data` VPCs & Network Firewalls for communication between platform & internet
- `core-shared-services-production` AWS account
  - `non_live_data` / `live_data` VPCs used for EC2 Image Builder pipelines, and for some shared customer infrastructure (Active Directory controllers).
  - instance scheduler lambda (not critical, but has region-specific image URI)
- core-vpc-$environment
  - Creates `$environment`-`$business_unit` VPCs (required to share resources out to member accounts)

**Comment by dms1981** [comment]
With regards our KMS keys, the answer here might be to look more deeply into the provision of [kms_replica_key](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/kms_replica_key) resources, as also discussed [here](https://docs.aws.amazon.com/kms/latest/developerguide/multi-region-keys-overview.html).

**Comment by dms1981** [comment]
So I think this gives us the following runbooks in need of creation for platform components:

- [ ] Modernisation Platform account
  - [ ] AWS resources (IAM roles, accounts, secrets)
  - [ ] Resources used by Terraform (s3, dynamoDB)
- [ ] `core-logging-production` account
  - [ ] S3 bucket for logs
- [ ] `core-network-services` account
  - [ ] VPCs w/ Network Firewalls (and NAT gateways for egress)
  - [ ] Transit Gateway (and peering to MOJ TGW)
- [ ] `core-shared-services` account
  - [ ] VPCs for shared infrastructure
  - [ ] AMI builder & resources (eg, S3 bucket)
  - [ ] Instance Scheduler
  - [ ] Shared KMS keys
- [ ] `core-vpc-$environment` accounts
  - [ ] VPCs
  - [ ] RAM shares, VPC endpoints
