### ISSUE TITLE
User Research - Performance Hub feedback on Mod Platform

### ISSUE THREAD

**Issue by squadMoj** [ministryofjustice/modernisation-platform#1915]
**WHAT**
It would be good to know how the current tenants are finding the mod platform. In this ticket - Performance hub.  
Interest to know:
- what they like, 
- what they dislike 
- what they would like to see/have

**WHY**
To help with short term and long term planning of features/work for the roadmap, and prioritise accordingly.

**User Story**
As the MP team
We need to know what needs the Performance Hub have / had
So that we can plan any further work required / update offering

**Hypothesis**
If we.......
The............
Because......

**Definition of Done**
- [x] Canvas session with MP team
- [x] Arrange interviews with users
- [x] Analysis session with MP team
- [x] Synthesis decision with MP team

**Comment by ScottSeaward** [comment]
Miro board here https://miro.com/app/board/uXjVOf1CtEw=/?share_link_id=276377314966
