### ISSUE TITLE
Add collaborator accounts for PPUD Replatform

### ISSUE THREAD

**Issue by dms1981** [ministryofjustice/modernisation-platform#1922]
## User Story

As a PPUD replatforming team 
I need collaborator user accounts created
So that I can explore replatforming my application onto the Modernisation Platform

List of Collaborators:
andrew.larcombe@digital.justice.gov.uk
david.savage@lumen.com
jani.green@lumen.com
luis.martinezarnal@lumen.com
pankaj.pant@lumen.com
umesh.ray@lumen.com

## User Type(s)

Modernisation Platform customer

## Value

The PPUD replatforming team from Lumen will need accounts creating on the Modernisation Platform so that they can begin their work to bring their application across to the Mod Platform.

## Questions / Assumptions / Hypothesis

* We will re-use existing accounts(s) for PPUD
* We will only provision users in the lowest environment at first (development?)

## Definition of done

- [x] new PPUD accounts is created in test
- [x] another team member has reviewed
- [x] tests are green
- [ ] UR test OR added to continual research plan

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by davidkelliott** [comment]
Can we not just reuse the existing PPUD accounts?

**Comment by dms1981** [comment]
Talked about this in standup and refinement; we're good to re-use accounts already created given how lightly they were touched before.
