### ISSUE TITLE
Spike: Use OIDC to access AWS from Github

### ISSUE THREAD

**Issue by davidkelliott** [ministryofjustice/modernisation-platform#1975]
## User Story

https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-amazon-web-services

Instead of using credentials we can use short lived tokens to enable access to AWS from Github.

## Definition of done

- [x] readme has been updated
- [ ] user docs have been updated
- [x] another team member has reviewed
- [x] tests are green
- [x] UR test OR added to continual research plan

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by gfou-al** [comment]
https://github.com/ministryofjustice/modernisation-platform/pull/2021

**Comment by zuriguardiola** [comment]
Follow up tasks after the spike

- Add this OIDC to every member account, delegate access
- And change the member infra role to have this permanently. Using terraform from the main repo.
- Delete the access keys from the actual repos. The github secrets are no longer required.
- Environment repo initially
- Then we can use the same tool for the main repo

**Comment by gfou-al** [comment]
How to use OpenID Connect to access AWS from GitHub actions: [open-id-connect.md](https://github.com/ministryofjustice/modernisation-platform/files/9139968/open-id-connect.md)

**Comment by gfou-al** [comment]
How to use OpenID Connect with terraform to access AWS from GitHub actions:
[open-id-connect-with-terraform.md](https://github.com/ministryofjustice/modernisation-platform/files/9140422/open-id-connect-with-terraform.md)

**Comment by gfou-al** [comment]
Assigning to @zuriguardiola to close this ticket after she completes the diagram and attaches it to this ticket.

**Comment by zuriguardiola** [comment]
![Image](https://user-images.githubusercontent.com/37803183/181451323-d0d52ac7-927e-48f9-b2b6-e72bd8b3a2e6.png)
