### ISSUE TITLE
Low level design and migration plan for new Stateful Network Firewall design

### ISSUE THREAD

**Issue by davidkelliott** [ministryofjustice/modernisation-platform#2012]
## User Story

We currently use Network firewall with stateless rules.  This causes issues for some types of traffic and we have to bypass the firewall.  We have a high level design for a stateful firewall here https://app.diagrams.net/#G1w8dZs5vZOoy0dvCnRr5P6GHc3VQRdwLq on the TGW and NWFW integration tab.

This redesign will have impact on the existing networking and we need to carefully plan the changes so that they do not majorly impact platform users (some downtime may be unavoidable).

This ticket is to complete analysis and create a detailed plan on how to achieve this.

Note there are 2 tickets which will help make this work simpler and should be done in advance of the changes to the firewall:

https://github.com/ministryofjustice/modernisation-platform/issues/1397
https://github.com/ministryofjustice/modernisation-platform/issues/2010

## Definition of done

- [x] detailed plan of migration to new design
- [x] new issues for the work created

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by dms1981** [comment]
Completed pending review of document in team google drive

**Comment by davidkelliott** [comment]
https://docs.google.com/document/d/1tMMCJtsmgLXOhCw9wW9su12IRnqlb7-n2AemIn1zCjg/edit
