### ISSUE TITLE
Test and fix if broken local Terraform plan After OIDC Change

### ISSUE THREAD

**Issue by zuriguardiola** [ministryofjustice/modernisation-platform#2030]
## User Story

Before we can roll out the OIDC changes to all accounts, we need to make sure we haven't broken the way that local plans are run.

## Definition of done

- [ ] readme has been updated
- [x] user docs have been updated
- [x] another team member has reviewed
- [ ] tests are green
- [ ] UR test OR added to continual research plan

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by davidkelliott** [comment]
https://github.com/ministryofjustice/modernisation-platform/issues/1975
