### ISSUE TITLE
Create OIDC Module to create OIDC provider and role in each member account

### ISSUE THREAD

**Issue by davidkelliott** [ministryofjustice/modernisation-platform#2035]
## User Story

Very similar to this - https://github.com/ministryofjustice/aws-root-account/tree/main/modules/github-oidc-provider

We want to create a module that does the following:

- create an OIDC provider for GitHub Actions
- create a github-actions role with read only permissions
- allow for any branches within a repo

Module inputs:
github_repository
additional_permissions (accept aws_iam_policy_document with additional permissions to attach to the github-actions role)

This module should be created in the modernisation-platform repository and should have tests.

## Value

Enables OIDC to be used improving security by removing credentials from Github actions

## Definition of done

- [x] module created
- [x] readme has been updated
- [x] user docs have been updated
- [x] another team member has reviewed
- [x] tests have been created

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by dms1981** [comment]
Could we add some links here to more references? EG, @gfou-al 's readme?

**Comment by dms1981** [comment]
Also we should probably link this to the parent ticket.

**Comment by davidkelliott** [comment]
https://github.com/ministryofjustice/modernisation-platform/issues/1975

**Comment by dms1981** [comment]
Resolved - resource now available through this repo: https://github.com/ministryofjustice/modernisation-platform-github-oidc-provider
