### ISSUE TITLE
Allow github-actions role to assume required roles

### ISSUE THREAD

**Issue by davidkelliott** [ministryofjustice/modernisation-platform#2037]
## User Story

The github-actions role created in #2036 needs to be able to assume the following roles:

same member account - :role/MemberInfrastrucutureAccess role - https://github.com/ministryofjustice/modernisation-platform/blob/main/terraform/environments/bootstrap/delegate-access/iam.tf#L33

core-vpc roles eg - :role/member-delegation-hmpps-test - https://github.com/ministryofjustice/modernisation-platform/blob/main/terraform/environments/core-vpc/vpc.tf#L256

core-network-services roles - :role/modify-dns-records
https://github.com/ministryofjustice/modernisation-platform/blob/main/terraform/environments/core-network-services/iam.tf#L6

## Value

Allows the role to be assumed by the github-actions role

## Definition of done

- [ ] roles have been amended
- [ ] another team member has reviewed
- [ ] tests are green
- [ ] UR test OR added to continual research plan

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by davidkelliott** [comment]
https://github.com/ministryofjustice/modernisation-platform/issues/1975

**Comment by dms1981** [comment]
Requires completion of #2035 to unblock this story
