### ISSUE TITLE
Remove credentials replaced by OIDC from Secrets Manager

### ISSUE THREAD

**Issue by dms1981** [ministryofjustice/modernisation-platform#2041]
## User Story

As a Modernisation Platform Engineer
I want to remove the users & credentials used by our Github terraform actions from AWS Secrets Manager & Github
Because these will be deprecated by our change to OIDC

## User Type(s)

Modernisation Platform Engineer

## Value

By moving to OIDC for authentication of our Github actions, we no longer need to keep related privileged users or credentials in Github or AWS Secrets manager. By deleting them we maintain good security hygeine.

### Hypothesis 
If we delete the user and credentials after switching to use OIDC
Then we won't notice any difference because the user & credentials are unused

### Proposal
We should *deactivate* the deprecated users & credentials prior to deletion.
This will give us confidence that we can delete them without issue, and provide us with an easy back-out point in case of any unintended consequences.

## Definition of done

- [x] MemberCI user deactivated in AWS 
- [x] MemberCI actions tested without issue
- [ ] CI user deactivated in AWS 
- [x] CI actions tested without issue
- [x] User & credentials deleted from AWS
- [x] Credentials removed from Github
- [x] Github actions continue to run without issue

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)
[Change core platform to use OIDC instead of credentials](https://github.com/ministryofjustice/modernisation-platform/issues/2040)

**Comment by julialawrence** [comment]
Dependent on https://github.com/ministryofjustice/modernisation-platform/issues/2400

**Comment by julialawrence** [comment]
`member-ci` deactivated on Dec 9th. Last used on Dec 4th

**Comment by SteveLinden** [comment]
The current version of the ecs module is difficult to get to work so we may need to bring all the code in. Likely to be moved to a post firebreak sprint

**Comment by julialawrence** [comment]
`ci` credentials last used on November 17th.

**Comment by julialawrence** [comment]
https://github.com/ministryofjustice/modernisation-platform/pull/2799

The last time these credentials were used was November 17th. Removing these credentials from github repos with a view of deleting the user next week.

**Comment by julialawrence** [comment]
https://github.com/ministryofjustice/modernisation-platform/pull/2807

Member-ci credentials have not been used since Dec 4th. Removing them from the `modernisation-platform-environments` repo secrets.

As `ci` and `member-ci` locals are not used elsewhere, removing the locals and datacalls from `terraform/github`

**Comment by julialawrence** [comment]
https://github.com/ministryofjustice/modernisation-platform/pull/2810

This PR removes `member-ci` and `ci` users, and associated artifacts now that our repositories have been converted to use github OIDC.

* Removing `member-ci` and `ci` secret manager secrets which stored the AWS keys consumed by other repos.
* Removing the `member-ci` and `ci` groups as well as attached policies.
* Removing `member-ci` and `ci` users and their group memberships.


Additionally,

Removing a deprecated provider argument.

**Comment by julialawrence** [comment]
https://github.com/ministryofjustice/modernisation-platform/pull/2812

This PR removes the placeholders for the org-level secrets in the modernisation-platform repo.

The org keys have not been used since November 18th. 

Note: while the user is managed in code in the `aws-root-account` repo, the keys aren't so I've requested that the keys for the user be manually disabled.
