### ISSUE TITLE
Remove Shakeel from the team

### ISSUE THREAD

**Issue by davidkelliott** [ministryofjustice/modernisation-platform#2048]
## User Story

Now that Shakeel has left we need to remove his access (opposite of this https://user-guide.modernisation-platform.service.justice.gov.uk/runbooks/adding-a-new-team-member.html#adding-a-new-team-member-to-the-modernisation-platform)

## Definition of done

- [x] access removed
- [x] another team member has reviewed

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by dms1981** [comment]
Solved in #2055
