### ISSUE TITLE
Data and Insight Hub AWS Account Creation 

### ISSUE THREAD

**Issue by ionel95** [ministryofjustice/modernisation-platform#2062]
### Application Name
data-and-insight**s**-wepi

### GitHub team slug
data-and-insight**s**-hub

### Environments

- [x] Development
- [ ] Test
- [ ] Preproduction
- [ ] Production

### Tags

tag | value
--- | ---
application | data-and-insight**s**-wepi
business-unit | HQ 
owner | Philip.cooke@justice.gov.uk 

#### Subnet sets

- [x] General - this application will use the same subnet as other applications in your business unit
- [ ] Isolated - this application has highly sensitive data which must have its own isolated subnet

#### How do users connect to the application?

- [x] Over the public internet
- [ ] With a purple cabled device (please give details)
- [x] With a MoJ Official device

## Additional features

[Business Justification for AWS Account Creation.docx](https://github.com/ministryofjustice/modernisation-platform/files/9240466/Business.Justification.for.AWS.Account.Creation.docx)

- [ ] Additional VPC Endpoints
- [ ] Extended DNS Zones
- [ ] Other - please specify

**Comment by ionel95** [comment]
Hi Team - can anyone review the ticket and feedback if any errors or if anything needs updating which has not been correctly filled out?

Thanks

**Comment by dms1981** [comment]
Discussed in planning - we'll cover the account creation in development only in this sprint, as part of our goal to refresh our account creation documentation

**Comment by dms1981** [comment]
Supplied github team slug was incorrect - should be `data-and-insights-hub`
(https://github.com/orgs/ministryofjustice/teams/data-and-insights-hub)

**Comment by ep-93** [comment]
![Image](https://user-images.githubusercontent.com/109581241/184592200-02ed1d24-2a30-49b8-b534-6d32b5fc9f3c.png)
