### ISSUE TITLE
SPIKE:  custom backup timings and retention schedules

### ISSUE THREAD

**Issue by seanprivett** [ministryofjustice/modernisation-platform#2075]
## User Story

As a modernisation platform customer
I want to set custom schedules for AWS Backups
So that I have flexibility on when my backups take place, based on my needs

## User Type(s)

Modernisation Platform Customer

## Value

Our customers are interested in setting flexible backup schedules. As part of this story we will look at how we currently support automated backups and see what work would be involved in allowing a customer to pass in custom schedules.

## Definition of done

- [ ] timeboxed effort
- [ ] understanding gained on how much effort would be required
- [ ] outline produced on how this could be implemented

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by dms1981** [comment]
Moving this one out of sprint until such time as the user research is done.

**Comment by ScottSeaward** [comment]
No availability from some users so have spread the net wider on Slack with the option of a form

**Comment by ScottSeaward** [comment]
Link to form https://forms.gle/XDArZbHNkK9EZGhn6

**Comment by davidkelliott** [comment]
This is now complete users can create their own backup plans
