### ISSUE TITLE
SPIKE to rework centralised roles to reduce permission scope

### ISSUE THREAD

**Issue by zuriguardiola** [ministryofjustice/modernisation-platform#2079]
## User Story

We need to look into reducing the permission scope of the centralised roles to have a more robust security posture in the member accounts. 

The roles are:
MemberInfrastructureAccess
ModernisationPlatformAccess
OrganizationAccountAccessRole

## Definition of done

- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] tests are green
- [ ] UR test OR added to continual research plan

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by davidkelliott** [comment]
MemberInfrastructureAccess is already restricted and OrganizationAccountAccessRole is now only used where it is needed.  The ModernisationPlatformAccess role is used to create things in the member accounts, if we restrict this role then we will end up using the OrganizationAccountAccessRole to add permissions to member account roles.

As such this issue can be closed.
