### ISSUE TITLE
SPIKE:  Fix account creation process

### ISSUE THREAD

**Issue by seanprivett** [ministryofjustice/modernisation-platform#2095]
Account creation steps are no longer correct, we've added additional templates which depend on networking, this is not initially created so it causes issues.

Some steps are in the wrong order

Not enough / correct documentation

**Comment by dms1981** [comment]
This story got shaken out of the Apex account creation woes. What we propose to do here is take a fine-toothed comb to the whole process and re-write the documentation based on this re-evaluation of all the steps that take place, including automated workflow actions.
After that we can trim down the content somewhat, but be confident that we have a refreshed view of what actions are needed and what actions occur when creating a new account.

**Comment by ep-93** [comment]
https://github.com/ministryofjustice/modernisation-platform/pull/2139 - One of the issues fixed, do we close the spike now it seems to work or leave it open?
