### ISSUE TITLE
Create tests for modernisation-platform-terraform-cross-account-access

### ISSUE THREAD

**Issue by dms1981** [ministryofjustice/modernisation-platform#2124]
## User Story

As a modernisation platform engineer 
I expect to have test coverage for my terraform code
So that I protect us from merging in code which does not work

## Value

Terratest coverage through Go is a standard across many of our modules. It is missing here, and the lack of this test functionality has caused the need for a hotfix after a seemingly correct PR was completed. Having tests in place will prevent this kind of situation from occurring again

### Hypothesis 
If we write functioning tests
Then we will never merge in broken code

## Definition of done

- [ ] tests created
- [ ] tests tested
- [ ] documentation updated
- [ ] branch protection settings to include tests

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by ASTRobinson** [comment]
already completed under https://github.com/ministryofjustice/modernisation-platform/issues/6490
