### ISSUE TITLE
Update Performance Hub ECS Module Version

### ISSUE THREAD

**Issue by zuriguardiola** [ministryofjustice/modernisation-platform#2131]
## User Story

I need to update the Performance Hub ECS module to the latest version. The latest version includes dynamic egress security group rules which allows for more flexibility when managing traffic.

The new egress security group rules will rebuild the ECS service so we need to arrange a time to push the change through to production to make sure the service is up.

## Definition of done

- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] tests are green
- [ ] UR test OR added to continual research plan

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by dms1981** [comment]
Given that this will be disruptive, we will need to arrange to do this out of normal hours with the performance hub team

**Comment by davidkelliott** [comment]
https://github.com/ministryofjustice/modernisation-platform-environments/pull/734/files

**Comment by ep-93** [comment]
https://github.com/ministryofjustice/modernisation-platform-environments/pull/734/files

**Comment by ep-93** [comment]
Waiting on a time agreed with the team.
