### ISSUE TITLE
SPIKE: separate environment for each PR

### ISSUE THREAD

**Issue by davidkelliott** [ministryofjustice/modernisation-platform#2162]
## User Story

As a modernisation platform user
I want to raise a PR with my changes and test them
Without affecting another developer who wants to do the same

## Definition of done

- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] tests are green
- [ ] UR test OR added to continual research plan

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by SimonPPledger** [comment]
We think is too complicated due to types of services running in ModP - and we have not had any requests for this
