### ISSUE TITLE
Oasys Dev, Test, Preproduction, Production Environments

### ISSUE THREAD

**Issue by julialawrence** [ministryofjustice/modernisation-platform#2170]
### Application Name

Oasys

### GitHub team slug

https://github.com/orgs/ministryofjustice/teams/studio-webops

### Environments

- [X] Development
- [X] Test
- [X] Preproduction
- [X] Production

### Tags

tag | value
--- | ---
application | oasys
business-unit | HMPPS
owner | digital-studio-operations-team@digital.justice.gov.uk
source-code | https://github.com/ministryofjustice/modernisation-platform-environments/tree/main/terraform/environments/oasys/

#### Subnet sets

- [X] General - this application will use the same subnet as other applications in your business unit
- [ ] Isolated - this application has highly sensitive data which must have its own isolated subnet

#### How do users connect to the application?

- [X] Over the public internet
- [X] With a purple cabled device (please give details)
- [X] With a MoJ Official device

#### Connectivity to other applications or external parties

We haven't yet done a full connectivity analysis on this application but to start with, we'll need the same connectivity is nomis.

For development/test: all nomis-test connectivity plus:

* Cloud Platform
* Ports: 9100, 9172, 443, 1521
* Analytical Platform
* Ports: 1521, 443
* NOMS-Test-DR (10.111.0.0/16), NOMS-Mgmt(10.102.0.0/16), NOMS-Mgmt-DR(10.112.0.0/16), aks-studio-hosting-dev-1 (10.247.0.0/20), nomisapi-t3-root-vnet(10.47.0.0/26) FnG vnets
* Ports: 3872, 22, 1521,9172, 4983, 5556, 7001, 7777, 4903, 7102, 7803

For preproduction/production: all nomis-production connectivity plus:

* Cloud Platform
* Ports: 9100, 9172, 443, 1521
* Analytical Platform
* Ports: 1521, 443
* NOMS-Live-DR(10.40.64.0/18), NOMS-Mgmt-Live-DR(10.40.144.0/20,) aks-studio-hosting-live-1(
10.244.0.0/20), nomisapi-preprod-root-vnet(
10.47.0.64/26), nomisapi-prod-root-vnet (10.47.0.128/26)
* Ports: 3872, 22, 1521,9172, 4983, 5556, 7001, 7777, 4903, 7102, 7803

## Additional features

- [ ] Additional VPC Endpoints
- [X] Extended DNS Zones
- [ ] Other - please specify

## Other information

For the period of migration, a nice-to-have would be an additional private azure.noms.root R53 zone attached to nomis-development and nomis-test and azure.hmpp.root R53 zone attached to nomis-preproduction and nomis-production for resolution of assets still in FixNGo. We currently configure hosts files on VMs to do this.

**Comment by SteveLinden** [comment]
Environment build completed after various issues that will be put into the amended documentation. Will contact them tomorrow before moving to completed.

**Comment by SteveLinden** [comment]
Email sent to the owner address above.
The ports etc. shown above have not been created while changes are being made to the firewall and will be added as part of that work (as per nomis)
