### ISSUE TITLE
Amend routing for live environments as part of NWFW work

### ISSUE THREAD

**Issue by dms1981** [ministryofjustice/modernisation-platform#2200]
## User Story

As a modernisation platform engineer
I want to route live traffic via the AWS Network Firewall
So that I can use the firewall to secure traffic flows 

## Value

As part of the AWS Network Firewall work we're undertaking, once the NWFW has been prepped for traffic we'll need to make some routing table changes to send traffic destined for the live environments via the NWFW, and traffic from the live environments destined for other MOJ endpoints via the NWFW.

Add static route to external route table:  
* `10.27.0.0/16 via inspection VPC attachment. `

Remove VPC propagated routes for production / preproduction VPCs from external route table:  
* eg `10.27.8.0/21 via hmpps-production-attachment. `
* eg `10.27.104.0/21 via platforms-preproduction-attachment. `

Add static route to firewall route table:  
* `0.0.0.0/0 via MP-PTTP peering attachment. `

Add static routes to live_data route table:  
* `10.0.0.0/8 via inspection VPC attachment. `
* `172.16.0.0/12 via inspection VPC attachment. `
* `192.168.0.0/16 via inspection VPC attachment. `

Remove static route from live_data route table:  
* `10.101.0.0/16 via MP-PTTP peering attachment.` 
* `10.40.0.0/16 via MP-PTTP peering attachment.`
* `10.244.0.0/20 via MP-PTTP peering attachment.`
* `10.47.0.64/26 via MP-PTTP peering attachment.`
* `10.47.0.128/26 via MP-PTTP peering attachment.`
* `10.184.0.0/16 via MP-PTTP peering attachment.`
* `172.20.0.0/16 via MP-PTTP peering attachment.`

Test connectivity between AWS & Azure:

Traffic from AWS to Azure should flow as follows:
`member-vpc > MP TGW > firewall > MP TGW > PTTP TGW > Azure`

Traffic from Azure to AWS should flow as follows:
`Azure > PTTP TGW > MP TGW > firewall > MP TGW > member-vpc`

## Definition of done

- [x] routes changed
- [x] tests successful

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by julialawrence** [comment]
PR to amend the routes: https://github.com/ministryofjustice/modernisation-platform/pull/2702
