### ISSUE TITLE
DPR Development Environment Request

### ISSUE THREAD

**Issue by harichintala1** [ministryofjustice/modernisation-platform#2204]
### GitHub team slug

hmpps-digital-prison-reporting 

### Environments

- [x] Development

### Tags

tag | value
--- | ---
application | data-platform
business-unit | HMPPS
owner | digitalprisonreporting@digital.justice.gov.uk

#### Subnet sets

- [x] General - this application will use the same subnet as other applications in your business unit
- [ ] Isolated - this application has highly sensitive data which must have its own isolated subnet

#### How do users connect to the application?

- [ ] Over the public internet
- [x] With a purple cabled device (please give details)
- [ ] With a MoJ Official device

#### Connectivity to other applications or external parties

* Analytical Platform (Oracle)
* Ports: 1521, 443

## Additional features

- [ ] Additional VPC Endpoints
- [ ] Extended DNS Zones
- [ ] Other - please specify

## Other information

We will need access to Legacy Nomis Platform for Data Ingestion

**Comment by dms1981** [comment]
https://github.com/ministryofjustice/modernisation-platform/pull/2231
https://github.com/ministryofjustice/modernisation-platform/pull/2232
^^ first part of the account creation
