### ISSUE TITLE
Add Ewa and Julia to the MP team

### ISSUE THREAD

**Issue by davidkelliott** [ministryofjustice/modernisation-platform#2260]
## User Story

https://user-guide.modernisation-platform.service.justice.gov.uk/runbooks/adding-a-new-team-member.html#adding-a-new-team-member-to-the-modernisation-platform

We need to add Ewa and Julia to the team so that they can work on the platform.

## Value

New team members yay!

## Definition of done

- [ ] Ewa added and enable to access the platform and repositories
- [ ] Julia added and enable to access the platform and repositories
- [ ] another team member has reviewed
- [ ] tests are green

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by ewastempel** [comment]
Added Julia and Ewa to the team page and to the GH team: https://github.com/ministryofjustice/modernisation-platform/pull/2285

**Comment by ewastempel** [comment]
Added Julia to AWS landing zone superadmins: https://github.com/ministryofjustice/modernisation-platform-terraform-iam-superadmins/pull/45
Ewa was already a superadmin.

**Comment by ewastempel** [comment]
Still outstanding: 

> Once their IAM user has been created, log into the [AWS console](https://console.aws.amazon.com/billing/home?region=eu-west-2#/) yourself and:
> 
> switch into the superadmin role in the Modernisation Platform account
> go to their IAM user in [IAM Users](https://console.aws.amazon.com/iam/home?region=eu-west-2#/users)
> go to the Security Credentials tab
> call the user and assign an MFA device with them
> configure console access with an autogenerated password and require a password reset on their next login

**Comment by ewastempel** [comment]
Julia is now set up with the MFA and can log in and switch role to superadmin.

This ticket is done now.
