### ISSUE TITLE
SPIKE: Can we allow PR review for teams when specific files are changed?

### ISSUE THREAD

**Issue by dms1981** [ministryofjustice/modernisation-platform#2267]
## User Story

As a modernisation platform customer
I want to conduct pull-request reviews inside my team for the modernisation-platform-ami-builds repository
So that my team can review changes to ansible playbooks that affect us, and that we are expert in 

## User Type(s)

Modernisation Platform Customer

## Value

Teams writing ansible playbooks are best placed to review the quality of those playbooks

## Questions / Assumptions / Hypothesis

This spike should investigate if it's possible to give a github team - eg `studio-webops` - the ability to review PRs that only change files in a specified directory - eg `teams/nomis` or `ansible`

## Definition of done

- [ ] suitable timebox selected
- [ ] evaluation criteria assessed
- [ ] outcomes to take forward this spike into a story (or not) documented

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by davidkelliott** [comment]
This should be a fairly quick fix by adding the relevant teams/folders to the codeowners file, in the same way we do for the environments repo

**Comment by davidkelliott** [comment]
We've done this for Nomis now, I think this can be managed manually within the codeowners file rather than through automation given that we are looking at very low volumes currently.
