### ISSUE TITLE
Add CODEOWNERS files to all repositories

### ISSUE THREAD

**Issue by jakemulley** [ministryofjustice/modernisation-platform#230]
We should add a `CODEOWNERS` file to all repositories so:

- it's clear who owns the code (Modernisation Platform team)
- the team are automatically assigned to review PRs

**Comment by SteveLinden** [comment]
The CODEOWNERS exists in modernisation-plaatform and modernisation-plaatform-environments. Need to find the other related repos and add it to those.

**Comment by SteveLinden** [comment]
All moved to the masters
