### ISSUE TITLE
We require the vpc in the MLRA-development account peered with LAA Development

### ISSUE THREAD

**Issue by mikereiddigital** [ministryofjustice/modernisation-platform#2316]
## User Story

Although this ticket mentions peering, this should simply be a change in the firewall, and maybe update the route table, although this may already be there.

To enable connectivity between the mlra-development and the LAA Landing Zone development account, can we please have the mlra-dev vpc (vpc-06febffe7b87ab37f in account 890609150221) peered with the environment vpc in LAA Landing Zone's development account - (vpc-86e0dfef in account 411213865113).

This is needed to support trusted connectivity between resources in the above two accounts.

Our ticket is https://dsdmoj.atlassian.net/browse/LAWS-2816 if you want to comment on it.

## Value

In the short term we need to have connectivity between the two VPCs established. Whilst transit gateway will be the long-term solution, using peering extends the approach we use in the LAA LandingZone where restricted connectivity between applications & databases and between databases via sqlnet is in place.

## Questions / Assumptions / Hypothesis

One the peering request is applied, we will accept it at the LAA LZ dev account end.

## Definition of done

VPC peering in place and connection testing completed by the LAA Ops team.

- [ ] readme has been updated
- [ ] user docs have been updated
- [x] another team member has reviewed
- [x] tests are green
- [ ] UR test OR added to continual research plan

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by mikereiddigital** [comment]
Just to add, can we please be kept informed as to when this work will commence & its progress as it's a dependency for standing up the MLRA application on the modernisation platform.

**Comment by davidkelliott** [comment]
@mikereiddigital I've added this to our next sprint, which is starting on Tuesday

**Comment by SteveLinden** [comment]
@mikereiddigital I will need a list of the IP address used by this app to add it. Can you provide that?

**Comment by mikereiddigital** [comment]
There should be absolutely no overlap between the two VPC CIDR ranges and as the MLRA app in MP will be connecting to multiple subnets in LAA LZ dev (as will be the case with the next two moves - MAAT & MAATCD-API) the acceptor & requester CIDRs need to be the full VPC - so for LZ dev that is 10.202.0.0/16 and MLRA-dev it would be 10.26.56.0/21.

**Comment by mikereiddigital** [comment]
Hi there. We've not had any peering requests from our end which would be required for this to be completed. So grateful if you could confirm exactly what's been done. Thank you.

**Comment by mikereiddigital** [comment]
Thanks for confirming that. We'll get the change in question applied at our end & will be in touch to confirm when we're ready to test. It's unfortunate that with TG we will need to add extra monitoring in to keep an eye on the status of this connection. VPC peering has that certainty that configuration changes outside of our view will impact it.
