### ISSUE TITLE
Run terraform plan after upgrading providers

### ISSUE THREAD

**Issue by jakemulley** [ministryofjustice/modernisation-platform#232]
#231 is a simple PR to run `terraform init -upgrade` in each Terraform directory, to update each of the used providers.

We should probably include a second script that goes through all directories and runs Terraform plan to ensure there are no outstanding changes due to the upgraded providers. There's already a [starter script](https://github.com/ministryofjustice/modernisation-platform/blob/main/scripts/internal/loop-through-bootstrap-workspaces-and-plan.sh) that does this for us, but is limited to the `environments/bootstrap` Terraform folder. We should probably expand it out.

**Comment by davidkelliott** [comment]
No longer needed, we've upgraded TF a few times since this date
