### ISSUE TITLE
Create a new repository for a configuration management code.

### ISSUE THREAD

**Issue by ewastempel** [ministryofjustice/modernisation-platform#2332]
There is a need for a central repository to store configuration management code that will be used to manage and maintain EC2 instances/environments in Modernisation Platform (MP).

This repository will be initially used by DSO, hence the team needs full access (being code owners). The idea is, that it will grow into a reusable libraries that can be shared between teams that use MP. DSO uses ansible for config mgmt, but other config mgmt tech can and should also sit here.

Definition of Done:
- [x] repository has been created
- [x] repository name is: modernisation-platform-configuration-management
- [x] initial directories are present (ansible, teams)
- [x] readme has been updated
- [ ] user docs have been updated
- [x] another team member has reviewed
- [x] tests are green

**Comment by ewastempel** [comment]
I have not updated the user docs, shall we mention it in the MP manual?

**Comment by davidkelliott** [comment]
On our main repo page we have a list of other repos, I'll add it there, and we can mention it further in our patching strategy page once we have that done
