### ISSUE TITLE
DRY out environment workflows with GitHub Actions matrices

### ISSUE THREAD

**Issue by davidkelliott** [ministryofjustice/modernisation-platform#2350]
## User Story

See example here - https://github.com/ministryofjustice/modernisation-platform-environments/pull/917

By switching to matrices (https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs) we can dry out our GitHub workflows by combining similar jobs together.

## User Type(s)

MP engineer

## Value

Less code means less code to maintain, easier to maintain and troubleshoot.

## Questions / Assumptions / Hypothesis

As well as the modernisation-platform-environments repo, we need to look at other workflows to see where this could be utilised.

## Definition of done

- [x] modernisation-platform-environments workflows updated
- [ ] any other workflows used in the MP are simplified if possible
- [ ] another team member has reviewed
- [ ] tests are green
- [ ] 
## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by seanprivett** [comment]
This ticket is to be done at the same time as ticket 2039:  https://github.com/ministryofjustice/modernisation-platform/issues/2039

**Comment by julialawrence** [comment]
Sprinkler and Example: https://github.com/ministryofjustice/modernisation-platform-environments/pull/942

**Comment by julialawrence** [comment]
Details of the work in https://github.com/ministryofjustice/modernisation-platform/issues/2039
