### ISSUE TITLE
Add autoscaling group out of hours scaling to ECS module

### ISSUE THREAD

**Issue by davidkelliott** [ministryofjustice/modernisation-platform#2360]
## User Story

Within the ECS module we want non production instances to automatically scale down to zero outside of working hours.

Could potentially pinch this from the bastion where it exists already.

## Value

Save money and the environment

## Definition of done

- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] tests are green
- [ ] UR test OR added to continual research plan

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by ep-93** [comment]
https://github.com/ministryofjustice/modernisation-platform-terraform-ecs/pull/51

**Comment by ep-93** [comment]
New ECS module has been created, this is in progress and the link to the new repo is here.


Once complete, we should check that it scales down out of hours, if not we need to add the functionality. 

https://github.com/ministryofjustice/modernisation-platform-terraform-ecs-cluster - New Repo

**Comment by SimonPPledger** [comment]
@ep-93 is this already in place? - including ooh auto scaling

**Comment by SteveLinden** [comment]
@ep-93 chase this up
