### ISSUE TITLE
Scheduler Lambda deployment with Terraform

### ISSUE THREAD

**Issue by davidkelliott** [ministryofjustice/modernisation-platform#2369]
## User Story

Now we have an instance scheduler - https://github.com/ministryofjustice/modernisation-platform-instance-scheduler
We need to work out how to deploy it with Terraform

See diagram following discussion here - https://jamboard.google.com/d/1DYWJc_S3buWPsnuE3hQRt8e4TeSYKV9giW9nnU3V5tA/viewer

This only covers the running of the lambda in the core-shared-services account. Not scheduling.

## Definition of done

- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] tests are green
- [ ] UR test OR added to continual research plan

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by gfou-al** [comment]
https://github.com/ministryofjustice/modernisation-platform/pull/2445

**Comment by gfou-al** [comment]
https://github.com/ministryofjustice/modernisation-platform/pull/2452

**Comment by gfou-al** [comment]
https://github.com/ministryofjustice/modernisation-platform-instance-scheduler/pull/10

**Comment by gfou-al** [comment]
https://github.com/ministryofjustice/modernisation-platform/pull/2453
