### ISSUE TITLE
Amend Azure FixNGo Attachments

### ISSUE THREAD

**Issue by seanprivett** [ministryofjustice/modernisation-platform#2375]
Mod Platform transit gateway is missing some FixNGo routes (see https://github.com/ministryofjustice/deployment-tgw/blob/master/env/production/eu-west-2.yml).   Only noms-test, noms-live, and noms-mgmt-live are reachable.  The routing should be the same as the tgw-rtb-security route table, e.g. replace the existing mod platform attachments

10.40.0.0/18 # Azure noms-live
10.40.128.0/20 # Azure noms-mgmt-live
With

10.40.0.0/16 # Azure FixNGo

And add

10.102.0.0/16 # Azure noms-mgmt

**Comment by dms1981** [comment]
This one expanded a bit to cover the scope of https://dsdmoj.atlassian.net/browse/DSOS-1513
In short, I added a few more ranges and raised a PR in the `ministryofjustice/deployment-tgw` repo
