### ISSUE TITLE
Ability for HMPPS digital teams to access Nomis application

### ISSUE THREAD

**Issue by Nimphal** [ministryofjustice/modernisation-platform#2396]
## Value

As part of the Nomis migration to MP, this functionality needs to be retained and modified to work with the MP way of managing access.

## Questions / Assumptions / Hypothesis

A lot of these users are not developers who will need to register for GH accounts.

This will likely be a new IAM role attached to a new GH team. Potentially two teams actually, one who has access only to dev and test and one who has access to production. The latter may not be needed.

## Definition of done

- [ ] process for users to access the nomis application has been defined and set up

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by dms1981** [comment]
@Nimphal - Can you help us to understand this request better please? I'm not sure what the story is here (As an X, I need Y, so I can Z).

**Comment by Nimphal** [comment]
Let's try

As an HMPPS service team member
I need to be able to access the nomis remote desktop instance
so I can do data exploration.

Practically, currently there's a studio operations team on GH which has extended permissions on MP when they authenticate. We don't want every dev form HMPPS to have the same, so we need a role/user setup that allows people to use SSM but doesn't give them full admin permissions.

**Comment by SimonPPledger** [comment]
Requestor has left and digital teams must have access
