### ISSUE TITLE
OIDC for 3 more accounts

### ISSUE THREAD

**Issue by seanprivett** [ministryofjustice/modernisation-platform#2398]
After security account, now implement core-logging, core-sandbox, core-shared-services

**Comment by julialawrence** [comment]
Main PR: https://github.com/ministryofjustice/modernisation-platform/pull/2392
Bugfix PR: https://github.com/ministryofjustice/modernisation-platform/pull/2393

**Comment by dms1981** [comment]
#2443 - core-shared-services

**Comment by dms1981** [comment]
core-sandbox is manually run, not subject to a github action, so that marks the completion of this story.
