### ISSUE TITLE
OIDC - Complete current OIDC

### ISSUE THREAD

**Issue by seanprivett** [ministryofjustice/modernisation-platform#2399]
Outstanding OIDC conversions:

Modernisation Platform repo:

 - terraform/
    - [ ] ~~environments (Excluding the files in environments directory as those run off a different set of keys)~~
       - [x] core-vpc - Ewa
       - [x] core-network-services - Ewa
       - [x] bootstrap
          - [ ] ~~delegate-access - Dave~~
          - [x] single-sign-on - Dave
          - [x] secure-baseline - Dave
    - [x] github - Steve
    - [x] pagerduty - Ed
    - [x] modernisation-platform-account - Ewa

**Comment by julialawrence** [comment]
I think terratests in modules should continue using the testing-test ci credentials since adding an OIDC provider in the testing-test account would prevent OIDC module from being tested.

**Comment by julialawrence** [comment]
https://github.com/ministryofjustice/modernisation-platform/issues/2040#issuecomment-1275821857 <-- core-security-production

**Comment by ewastempel** [comment]
picking up the core-vpc account

**Comment by ewastempel** [comment]
OIDC refactor implementation for the core-vpc account: https://github.com/ministryofjustice/modernisation-platform/pull/2551

**Comment by davidkelliott** [comment]
I'm looking at delegate access and the environments as they both run off privileged keys in the root account

**Comment by julialawrence** [comment]
`[Modernisation Platform AMI Builds](https://github.com/ministryofjustice/modernisation-platform-ami-builds)

- [ ] modernisation-platform
- [ ] teams`

Should be split off into a different story.

**Comment by ewastempel** [comment]
OIDC refactor implementation for the core-vpc-test-deployment (I have missed it in the previous PR)
and the core-network-services-deployment workflows: https://github.com/ministryofjustice/modernisation-platform/pull/2560

**Comment by ewastempel** [comment]
OIDC refactor implementation for the modernisation-platform-account: https://github.com/ministryofjustice/modernisation-platform/pull/2567

**Comment by davidkelliott** [comment]
https://github.com/ministryofjustice/modernisation-platform/pull/2571 for single-sign-on and secure-baselines

**Comment by davidkelliott** [comment]
Moved delegate-access and environments out to https://github.com/ministryofjustice/modernisation-platform/issues/2568

**Comment by SteveLinden** [comment]
Moved the github one to [https://github.com/ministryofjustice/modernisation-platform/pull/2570] #2570
