### ISSUE TITLE
Start using SSO creds (not superadmin) for applies in MP-envs repo

### ISSUE THREAD

**Issue by seanprivett** [ministryofjustice/modernisation-platform#2401]
## User Story

The superadmin credentials (AWS access keys) should not be used everyday, we should switch to SSO credentials and delete all superadmin creds, creating them to use as one off only when absolutely necessary. 

## User Type(s)

MP engineer

## Value

Increase the security of the platform

### Hypothesis 
If we use SSO credentials for local development we won't need to have superadmin credentials anymore

### Proposal
Work out how to use SSO credentials with our current Terraform, then once tested and documented remove superadmin credentials.

## Definition of done

- [ ] superadmin credentials deleted
- [ ] readme has been updated
- [ ] user docs have been updated
- [x] another team member has reviewed
- [x] tests are green
- [ ] UR test OR added to continual research plan

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by julialawrence** [comment]
https://github.com/ministryofjustice/modernisation-platform/pull/2424

Allows plan/apply locally using SSO AdministratorAccess role
