### ISSUE TITLE
Request for new Mod Platform Environment - MAATDB

### ISSUE THREAD

**Issue by mikereiddigital** [ministryofjustice/modernisation-platform#2402]
## Environment details

This is required to host the MAAT Database stack that current is hosted in the LAA LandingZone and which is in scope of the move of the MAAT group of applications to MP.

### Application Name

maatdb

### Description of application

This is the MAAT database stack that is currently hosted in the LAA LandingZone. It includes:
- An Oracle 19c RDS database, parameter & option groups.
- Security Groups.
- S3 bucket for FTP integration
- IAM account, role & policy that supports integration between directories in the Oracle database & S3
- IAM policies that enable access to the S3 by lambda functions that support the transfer of files from the bucket to 3rd parties.

Note that the applications that use the database (MLRA, MAAT & MAAT API) will be hosted in separate MP accounts.

### Environments

| Environment 		| Access level |
| --- 				| --- |
|<ul><li>[x] Development</li></ul>	| <ul><li>[ ] view-only</li><li>[x] developer</li><li>[ ] sandbox</li></ul> |
|<ul><li>[ ] Test</li></ul>			| <ul><li>[ ] view-only</li><li>[ ] developer</li></ul> |
|<ul><li>[ ] Preproduction</li></ul>| <ul><li>[ ] view-only</li><li>[ ] developer</li></ul> |
|<ul><li>[ ] Production</li></ul>	| <ul><li>[ ] view-only</li><li>[ ] developer</li></ul> |

### Tags

tag | value
--- | ---
application | maatdb
business-unit | LAA
owner | LAA

### Subnet sets

- [ x] General - this application will use the same subnet as other applications in your business unit
- [ ] Isolated - this application has highly sensitive data which must have its own isolated subnet with no network connectivity

### How do users connect to the application?

User connections will ingress via the LAA LandingZone & to MP using the Transit Gateway

- [ ] Over the public internet
- [ ] With a purple cabled device (please give details)
- [ ] With a MoJ Official device

## Additional features

- [ ] Additional VPC Endpoints
- [ ] Extended DNS Zones
- [ ] Other - please specify

## Definition of done

- [x] account created
- [x] customer informed

**Comment by dms1981** [comment]
Account created, customer informed via Slack
