### ISSUE TITLE
SPIKE: Create Hardened AMIs

### ISSUE THREAD

**Issue by davidkelliott** [ministryofjustice/modernisation-platform#2414]
## User Story

Look in to creating hardened base AMIs which are maintained at a platform level, users can then use these AMIs to build their own images.

## Definition of done

- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] tests are green
- [ ] UR test OR added to continual research plan

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by SimonPPledger** [comment]
is this a copy of what DSO has already done?

**Comment by richgreen-moj** [comment]
https://aws.amazon.com/about-aws/whats-new/2023/01/ec2-image-builder-cis-benchmarks-security-hardening-amis/

**Comment by SimonPPledger** [comment]
Application teams manage their own AMIs
