### ISSUE TITLE
SPIKE: Monitor that SSM instances are installed on platform EC2s

### ISSUE THREAD

**Issue by davidkelliott** [ministryofjustice/modernisation-platform#2415]
## User Story

To apply patching we will need the SSM agent installed on user instances. This spike to find out how to monitor and alert for this if instances do not have SSM agent installed.  And to identify any blockers which could prevent SSM agent being installed on all EC2 instances.

Time boxed to 1 week.

## Value

Visibility of instances and understanding which instances can be patched when needed.

## Questions / Assumptions / Hypothesis

Can we use AWS native tools for that?

## Definition of done

- [x] List of EC2 instances in member accounts where the agent is running and where it is not running.
- [x] Follow on issue created to push these data onto Observability Platform

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by richgreen-moj** [comment]
Here's an example of how it could be achieved at single account level with the AWS CLI...
https://stackoverflow.com/questions/60084104/aws-ssm-agent-using-the-aws-cli-is-there-a-way-to-list-all-the-aws-instances

**Comment by richgreen-moj** [comment]
I've written a script that runs some cli commands to check which instances are managed by SSM and have a workflow that triggers the script in each account on the Mod Platform. This then outputs the results in a csv file and uploads it to the run.

Here is a work in progress: https://github.com/ministryofjustice/modernisation-platform/actions/runs/9081286758

**Comment by richgreen-moj** [comment]
After discussion at stand-up we agreed we should write a ticket for:

- Finding out which Operating Systems the instances are using which haven't got the SSM agents installed so we can focus our attention on who to contact 
- A ticket to get this information via the Observability Platform vs. running scripts/workflows.

**Comment by richgreen-moj** [comment]
This PR https://github.com/ministryofjustice/modernisation-platform-security/pull/8 adds ability to scan MP instances to see which don't have the SSM agent installed. The result contains information on the platform of the instance so we can start to see if the SSM agent is viable or if there are no details we would need to contact the customers directly to see if there are any blockers to them installing SSM.

**Comment by richgreen-moj** [comment]
https://github.com/ministryofjustice/modernisation-platform/issues/7088 issue raised to contact customers based on results from the script.
