### ISSUE TITLE
New development environment for LAA CCMS EBS migration

### ISSUE THREAD

**Issue by rajindersinghsandhu** [ministryofjustice/modernisation-platform#2431]
### Application Name

ccms-ebs

### Description of application
CCMS is a system that manages certified civil legal aid applications, amendments and bills, it is our general ledger, chart of accounts and payment system and manages accounts receivable.

### GitHub team slug
[laa-ccms-migration-team](https://github.com/orgs/ministryofjustice/teams/laa-ccms-migration-team)

### Environments

| Environment 		| Access level |
| --- 				| --- |
|<ul><li>[x] Development</li></ul>	| <ul><li>[ ] view-only</li><li>[x] developer</li><li>[ ] sandbox</li></ul> |
|<ul><li>[ ] Test</li></ul>			| <ul><li>[ ] view-only</li><li>[ ] developer</li></ul> |
|<ul><li>[ ] Preproduction</li></ul>| <ul><li>[ ] view-only</li><li>[ ] developer</li></ul> |
|<ul><li>[ ] Production</li></ul>	| <ul><li>[ ] view-only</li><li>[ ] developer</li></ul> |

### Tags

tag | value
--- | ---
application |  ccms-ebs
business-unit |  LAA
owner | [donovan.artz@digital.justice.gov.uk](mailto:donovan.artz@digital.justice.gov.uk)

### Subnet sets

- [x] General - this application will use the same subnet as other applications in your business unit
- [ ] Isolated - this application has highly sensitive data which must have its own isolated subnet with no network connectivity

### How do users connect to the application?

- [x] Over the public internet
- [x] With a purple cabled device (please give details)
- [ ] With a MoJ Official device

### Connectivity to other applications or external parties

VPN to 6dg 3rd party hosting

## Additional features

- [ ] Additional VPC Endpoints
- [ ] Extended DNS Zones
- [ ] Other - please specify

## Definition of done

- [ ] account created
- [ ] customer informed

**Comment by dms1981** [comment]
@ewastempel - this one might be good for you?

**Comment by dms1981** [comment]
Account creation PR: https://github.com/ministryofjustice/modernisation-platform/pull/2456

**Comment by dms1981** [comment]
Adding the migration team to the github teams PR: https://github.com/ministryofjustice/modernisation-platform/pull/2457

**Comment by dms1981** [comment]
PR for new files in modernisation-platform-environments: https://github.com/ministryofjustice/modernisation-platform-environments/pull/1001
PR for new files in modernisation-platform: https://github.com/ministryofjustice/modernisation-platform/pull/2459

**Comment by dms1981** [comment]
PR to share resources in `laa-development` with `ccms-ebs-development` account: https://github.com/ministryofjustice/modernisation-platform/pull/2461

**Comment by dms1981** [comment]
PR to correctly associate new account with laa-development in modernisation-platform-environments: https://github.com/ministryofjustice/modernisation-platform-environments/pull/1003

**Comment by dms1981** [comment]
PR to correctly associate new account with laa-development in modernisation-platform: https://github.com/ministryofjustice/modernisation-platform/pull/2462
