### ISSUE TITLE
Create VPNs from 6dg <-> MP

### ISSUE THREAD

**Issue by davidkelliott** [ministryofjustice/modernisation-platform#2448]
## User Story

The LAA are migrating the CCMS EBS component of EBS directly from 3rd party hosting with 6dg to the Modernisation Platform.

The following VPNs are required:

| 6dg Range | 6dg Env | MP VPC |
|---|---|---|
|10.221.0.0/16 |dev | laa-development |
|10.222.0.0/16 |uat|laa-test
|10.223.0.0/16| stage|laa-preproduction
|10.225.0.0/16 |prod|laa-prodduction

Configuration of these should mirror the existing VPN configuration from 6dg to LAA LZ here - https://github.com/ministryofjustice/laa-ccms-shared/blob/master/shared-infrastructure/terraform-all-envs/vpn.tf

These VPNs are temporary for migration purposes only, as such should be created to our TGW rather than the PTTP TGW
## Definition of done

- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] tests are green
- [ ] UR test OR added to continual research plan

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by davidkelliott** [comment]
https://github.com/ministryofjustice/modernisation-platform/pull/2505

**Comment by davidkelliott** [comment]
Initial code created, awaiting further details from 6dg

**Comment by dms1981** [comment]
Closing this as an alternative approach for traffic between MP and 6DG is being explored. The VPNs have been created on our side.
