### ISSUE TITLE
Investigate Xhibit Portal WAF blocking and re-enable

### ISSUE THREAD

**Issue by davidkelliott** [ministryofjustice/modernisation-platform#2454]
## User Story

See thread here - https://mojdt.slack.com/archives/C01A7QK5VM1/p1666260688515569

Some users were being blocked, this ticket is to investigate why and re enable the auto remediation from count to block

## Definition of done

- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] tests are green
- [ ] UR test OR added to continual research plan

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by davidkelliott** [comment]
The rate limit is currently set to 100, going to increase this to 1000

**Comment by dms1981** [comment]
From investigation it appeared that blocked users were coming from behind the same public IP address which was triggering our rate limiting. After increasing this limit, switching the action from `block` to `count` and leaving for a month to assess the impact, we no longer see any hits against the action.

As such we have returned the action to `block`.
