### ISSUE TITLE
Implement terraform state locking in S3 backends

### ISSUE THREAD

**Issue by dms1981** [ministryofjustice/modernisation-platform#2467]
## User Story

As a Modernisation Platform Engineer 
I need to implement backend locking of the terraform statefile
So that only one agent can modify the statefile at any given time

## Value

Without state file locking, it's possible for two jobs to access the statefile at the same time, leading to the creation of terraform statefile versions which are not in agreement with each other. In the case of a new account creation, this can lead to a state where terraform jobs cannot successfully run due to missing information.

Also, given our approach to work where many hands can be busy at one time, state file locking is an ideal solution to prevent any problems with clashing workflows.

### Proposal
We should implement a DynamoDB table and the necessary configuration elements specified by Hashicorp in the [S3 backend type documentation](https://developer.hashicorp.com/terraform/language/settings/backends/s3)

##Environments

- [x] apex
- [x] ccms-ebs
- [x] cooker
- [x] core-logging
- [x] core-security
- [x] core-vpc
- [x] data-and-insights-wepi
- [x] delius-iaps
- [x] digital-prison-reporting
- [x] equip
- [x] example
- [x] maatdb
- [x] main.tf
- [x] mlra
- [x] nomis
- [x] oasys
- [x] performance-hub
- [x] ppud
- [x] refer-monitor
- [x] sprinkler
- [x] testing
- [x] threat-and-vulnerability-mgmt
- [x] xhibit-portal

## Definition of done

- [x] State file locking has been implemented across our backend.tf files
- [x] another team member has reviewed

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)
[Backend type: S3](https://developer.hashicorp.com/terraform/language/settings/backends/s3)

**Comment by SteveLinden** [comment]
Initial PR put in place for review

**Comment by SteveLinden** [comment]
I think this is now in place for the core-vpc code and needs to be tested. The above has been edited to list all the environments that have a backend.tf which probably need to be amended.

**Comment by SteveLinden** [comment]
core-vpc and core-security completed (individual PRs) (e.g. #2552)
Others will be done in one PR

**Comment by SteveLinden** [comment]
Changes made for the above but I am now going through them to see which do not work. bichard7 is the first culprit, and I will remove them from the list above and try to take them out of the PR

**Comment by SteveLinden** [comment]
Non-working items to remove from PR

bichard7 - storage class issues
analytical-platform-data - storage class issues
analytical-platform-management - storage class issues
Bootstrap/delegate-access
Bootstrap/secure-baselines
Core-network-services - S3 issues
Core-sandbox - S3 issues
core-shared-services - S3 issues
Mi-platform - S3 issues
Remote-supervision - storage class issues


Sprinkler has been left in place but it indicates it will destroy 9 items

**Comment by SteveLinden** [comment]
plan on core-sandbox indicates it will destroy 10 items so this is being left out.
Added core-network-services and core-shared-services
