### ISSUE TITLE
Implement terraform plans on PRs for create-environment step

### ISSUE THREAD

**Issue by julialawrence** [ministryofjustice/modernisation-platform#2468]
## User Story

As a Modernisation Platform Engineer I need to implement the ability to run `terraform plan` on create-environment step in `Terraform: New Accounts` workflow.

## Value

Without the ability to run `terraform plan` prior to PR merges, we have no way to spot issues in critical code and prevent an apply when the plans are not what we expect. Ability to plan will provide an additional quality gate in situations when PR reviews don't spot mistakes. 

### Proposal

A separate workflow file that triggers on a raised PR which makes changes to files that trigger `Terraform: New environment` workflows which runs a `terraform plan` on `terraform/environment` directory.

## Definition of done

- [ ] ability to run `terraform plan` implemented 
- [ ] readme has been updated
- [ ] another team member has reviewed

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by davidkelliott** [comment]
I think this is already there, see here - https://github.com/ministryofjustice/modernisation-platform/actions/runs/3731313330/jobs/6329398148
There are 2 requests for new accounts in the todo column so I will double check this when doing them

**Comment by davidkelliott** [comment]
Confirmed this happens already - https://github.com/ministryofjustice/modernisation-platform/actions/runs/3806263296/jobs/6474909088
