### ISSUE TITLE
Remove references to hashicorp/template in our example environment

### ISSUE THREAD

**Issue by julialawrence** [ministryofjustice/modernisation-platform#2506]
## User Story

As a modernisation platform engineer I would like to remove references in our code to the deprecated `hashicorp/template` provider. 

## User Type(s)

MP engineers

## Value

Keeping the platform up to date with provider changes improves our security posture and allows us to take advantage of new features. Additionally, since the deprecation of the template provider, we are unable to run terraform locally on M1 laptops without compiling a binary since the binary isn't being distributed. This is highly undesirable: we should be striving to keep the experience uniform across developer devices. 

## Questions / Assumptions / Hypothesis

Identify any references to [these](https://registry.terraform.io/providers/hashicorp/template/latest/docs) resources in example folder in `modernisation-platform-environment` repo and convert them to built-in `template` function or the [new provider](https://registry.terraform.io/modules/hashicorp/dir/template).

## Definition of done

- [x] example environment converted
- [x] readme has been updated
- [x] user docs have been updated
- [x] another team member has reviewed
- [ ] tests are green

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by ewastempel** [comment]
Temp solution (using hashicorp/dri/template):
https://github.com/ministryofjustice/modernisation-platform-terraform-bastion-linux/pull/49 
https://github.com/ministryofjustice/modernisation-platform-terraform-bastion-linux/pull/50

**Comment by ewastempel** [comment]
Final solution (using `templatefile` terraform function):
https://github.com/ministryofjustice/modernisation-platform-terraform-bastion-linux/pull/52

**Comment by ewastempel** [comment]
This is done.
