### ISSUE TITLE
Connect Mod Platform to Analytical Platform

### ISSUE THREAD

**Issue by seanprivett** [ministryofjustice/modernisation-platform#2524]
The Analytical Platform will need to connect to databases within Mod Platform. This will be required by the NOMIS standby database before it can go fully live, so that data can be extracted to AP

Determine path and add relevant routing

Ask Analytical Platform to make the relevant change (e.g. existing[https://github.com/ministryofjustice/data-engineering-airflow/blob/main/Pulumi.prod.yaml - Connect to preview](https://github.com/ministryofjustice/data-engineering-airflow/blob/main/Pulumi.prod.yaml)routes shown here).  Include the entire Mod Platform range in the cidr blocks 10.26.0.0/16 (nonlive) and 10.27.0.0/16 (live)

Add return path routing to Mod platform (e.g. [modernisation-platform/transit_gateway_connections.tf at main · ministryofjustice/modernisation-platform](https://github.com/ministryofjustice/modernisation-platform/blob/main/terraform/environments/core-network-services/transit_gateway_connections.tf)) 
DoD:

Routing is agreed

Analytical Platform have ticket to implement their end

Routing tested

**Comment by dms1981** [comment]
This should be covered (for us) by #2199 and #2200 but in case we need something in advance of those, the routes should be:
```172.24.0.0/16
172.25.0.0/16
```

**Comment by dms1981** [comment]
See https://mojdt.slack.com/archives/C013RM6MFFW/p1667293760328399 for context.

**Comment by dms1981** [comment]
Raised PR in airflow repository: https://github.com/ministryofjustice/data-engineering-airflow/pull/91/files

**Comment by dms1981** [comment]
Placed in `blocked` until PR merged in for airflow

**Comment by dms1981** [comment]
https://asdslack.slack.com/archives/C8X3PP1TN/p1667553580234069 <- referring conversation that shows the PR is due to be completed on Monday

**Comment by dms1981** [comment]
https://github.com/ministryofjustice/data-engineering-airflow/pull/91 <- PR has been merged in!
