### ISSUE TITLE
SMTP relay routing between MP and MOJO TGW

### ISSUE THREAD

**Issue by seanprivett** [ministryofjustice/modernisation-platform#2526]
Replacing comms which currently go to the Azure fix n go environment, but will need to move to MP

Uses tcp/25

from MP side:

add route for 10.180.0.0/16 via the MoJ transit gateway

from MoJo side (Cloud Ops):

Raise PR with Cloud Ops team in x repo to add all MP ranges (not just requested ranges from tenant alter any allowlists/ACLs to allow SMTP access from 10.27/16 + 10.26/16)

## Definition of Done

- [x] Routes in place in Transit Gateway route tables
- [x] Customer has completed necessary security group changes
- [x] Customer has confirmed that SMTP traffic reaches relay

**Comment by dms1981** [comment]
This doesn't look too complicated; if we approach this on it's own then it's some simple addition of routes.
Alternatively, this will be covered by the work in #2199 & #2200

**Comment by dms1981** [comment]
One point of clarification - how are they sending email? SMTP traffic maybe rate limited, not sure about TLS secured SMTP.

**Comment by seanprivett** [comment]
Additional context here: https://mojdt.slack.com/archives/C966L8ZFY/p1668507069948719

**Comment by SteveLinden** [comment]
Putting into blocked while we wait to see if the change has worked as expected.

**Comment by SteveLinden** [comment]
Raised a request on the #ask-nvvs-devops channel to try to get the traffic connection set up.....

Hi
We’ve made am amendment to our modernisation-platform code to allow access to an SMTP service. Can you arrange for traffic from 10.26.0.0/16 or 10.27.0.0/16 hit 10.180.0.0/16 on tcp/25? I was told the CloudOps team could do this.
Thanks

**Comment by SteveLinden** [comment]
Connection is covered by 10.0.0.0/8, from cloud ops team

**Comment by SteveLinden** [comment]
It has been tested and it is not working from either prod or dev

**Comment by dms1981** [comment]
Pull requests completed in the deployment-tgw repository. Waiting on automation run to implement them

**Comment by SteveLinden** [comment]
The run was completed.
It was tested and now appears to be working (slack message below)
Dominic Robinson
  [10:18](https://mojdt.slack.com/archives/D04CVPMEREX/p1669717089585109)
Looks good - I’ve got a connection rom both nomis-test and nomis-production against the SMTP server 10.180.104.100  on port 25.
