### ISSUE TITLE
Enable Application teams to contribute to modules in our module repositories

### ISSUE THREAD

**Issue by ewastempel** [ministryofjustice/modernisation-platform#2549]
## User Story

As a modernisation platform user I want to be able to write terraform modules to keep the code dry.

## User Type(s)

Application/infrastructures users who host their infrastructure in MP.

## Value

Keeping the code dry and sharing the modules across the teams. Additionally, it is less work for the MP team, if the modules can be implemented through the community efforts.

## Questions / Assumptions / Hypothesis

Users should be able to write to all MP module repositories. 

Timebox implementation to 2 days for for/each loop - manual if it goes beyond this

### Proposal

See the code here, where the write access to repositories is done per repository basis (for all app teams in the local list of app teams): https://github.com/ministryofjustice/modernisation-platform/blob/main/terraform/github/main.tf#L351

Refactor the code so that it can iterate through the list of all module repositories and set the write access for all app teams in the list programatically.
e.g. the repo list could be a json file to be read as a local variable of the repo list

## Definition of done

- [ ] readme has been updated
- [ ] contributor guidelines added to docs - indicating generic vs specific
- [ ] linked to github workflow for contributors
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] tests are green
- [ ] UR test OR added to continual research plan

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by dms1981** [comment]
Solved by https://github.com/ministryofjustice/modernisation-platform/pull/2670
