### ISSUE TITLE
Spike: Can we use Terragrunt on MP?

### ISSUE THREAD

**Issue by davidkelliott** [ministryofjustice/modernisation-platform#2556]
## User Story

We have had several requests to use Terragrunt on the Modernisation Platform.  This spike is to look into:

What benefits does Terragrunt offer?
What complexity does it add?
How stable is the Terragrunt offering?
How secure is the Terragrunt offering?
How much extra learning/knowledge is required to use it?

## Definition of done

- [x] research into Terragrunt
- [x] team discussion on findings
- [ ] ADR of decision

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by ewastempel** [comment]
The research has been done and the conversation with the team has happened.

The outcome was to use terragrunt in the ami build repository, but to have another spike (during the firebreak sprint) to evaluate if we want to roll it out in all of the MP repos.

Therefore the ADR write-up and decision has been postponed until the next spike outcome. The ADR will be documented in this [branch](https://github.com/ministryofjustice/modernisation-platform/tree/docs/terragrunt-adr) and another ticket will be created for the firebreak spike.

This ticket is done.
