### ISSUE TITLE
OIDC: AMI-builds repo

### ISSUE THREAD

**Issue by julialawrence** [ministryofjustice/modernisation-platform#2563]
## User Story

As a modernisation platform developer, I would like to convert modernisation-platform-ami-builds repo to use OIDC

### Proposal
Amend the OIDC module to take additional repos/roles. 

Two potential ways forward: 

* Reuse the github-actions role defined as part of the core-shared-services provider in the ami-builds repo (this would require adding additional permissions to the role.)

* Refine the OIDC provider module to take additional repo/roles and define a new role with a new set of permissions that is usable only in ami-builds repo and has enough permissions for ImageBuilder.

The second approach will need some analysis as we've made assumptions that OIDC roles are going to be called github-actions and deviating from this will need some impact assessment. 

## Definition of done

Convert the following workflows in [Modernisation Platform AMI Builds](https://github.com/ministryofjustice/modernisation-platform-ami-builds) repo

- [x] modernisation-platform
- [x] example
- [x] nomis
- [ ] base -- @ewastempel 

Additionally ...

- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] tests are green
- [ ] UR test OR added to continual research plan

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by julialawrence** [comment]
Another potential approach would be to reuse the MP OIDC provider and role and add ami-builds as an allowed repo. That could potentially be a quicker win as only would require a small change in the OIDC module to accept a list of allowed repos.

**Comment by julialawrence** [comment]
At the moment, the ami workflows run with the modernisation platform ci user. If these files were in the modernisation-platform repo, converting to OIDC would be trivial, very similar to https://github.com/ministryofjustice/modernisation-platform/pull/2560.

However, since it's a separate repo, the github-actions permissions need to be modified to allow this repo. Converting the OIDC module to take a list of repos would resolve this.

**Comment by julialawrence** [comment]
Using the new version of the module to add the ami repo to the trust policy of the default github-actions role: https://github.com/ministryofjustice/modernisation-platform/pull/2650

**Comment by julialawrence** [comment]
Adding the required secret and fixing a repo-naming bug: https://github.com/ministryofjustice/modernisation-platform/pull/2652

**Comment by julialawrence** [comment]
PR for the conversion of one of the workflows: https://github.com/ministryofjustice/modernisation-platform-ami-builds/pull/125

**Comment by ewastempel** [comment]
Base workflow has been implemented with the following PR:
https://github.com/ministryofjustice/modernisation-platform-ami-builds/pull/135

This is done now.
