### ISSUE TITLE
Investigate management of collaborator and SSO role policies in one place.

### ISSUE THREAD

**Issue by julialawrence** [ministryofjustice/modernisation-platform#2565]
## User Story

As a modernisation platform developer, I would like to explore ways we can manage permissions for external collaborators and members of our github organisation in one place. 

## User Type(s)

Internal MOJ github org members
External collaborators
Modernisation Platform engineers

## Value

This would reduce the overhead of managing role permissions and keep permissions of internal and external users aligned.

### Proposal

Currently, SSO permission sets are managed via `aws_ssoadmin_permission_set_inline_policy` resource which adds an `SSO Inline Policy` to the SSO roles in every account.

If switching out to `aws_ssoadmin_customer_managed_policy_attachment` creates a named policy in member accounts, that policy can subsequently be looked up via a terraform datasource and attached to the locally created developer user. 

This might require some changes to order of operations as single-sign-on will need to run before delegate-access.

## Definition of done

- [ ] Feasibility of this approach tested using a local admin user. 
- [ ] If feasible, implemented for the collaborator developer role.
- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] tests are green
- [ ] UR test OR added to continual research plan

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by davidkelliott** [comment]
https://github.com/ministryofjustice/aws-root-account/pull/677
https://github.com/ministryofjustice/aws-root-account/pull/674
https://github.com/ministryofjustice/modernisation-platform/pull/2881
https://github.com/ministryofjustice/aws-root-account/pull/673
https://github.com/ministryofjustice/modernisation-platform/pull/2879
