### ISSUE TITLE
OIDC: Environments and delegate-access

### ISSUE THREAD

**Issue by davidkelliott** [ministryofjustice/modernisation-platform#2568]
## User Story

Complete OIDC work for the environments terraform and delegate-access.

This will need to have changes to the OIDC provider in the root account, see conversation here - https://mojdt.slack.com/archives/C013RM6MFFW/p1667824037263999

## Definition of done

- [x] delegate-access converted
- [x] environments converted
- [ ] readme has been updated
- [ ] user docs have been updated
- [x] another team member has reviewed
- [x] tests are green
- [ ] UR test OR added to continual research plan

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by julialawrence** [comment]
Related Issues:
https://github.com/ministryofjustice/modernisation-platform/issues/2568
https://github.com/ministryofjustice/modernisation-platform/issues/2593

Context:
We would like to convert workflows that currently run with organisation [master account iam user credentials](https://github.com/ministryofjustice/modernisation-platform/blob/main/.github/workflows/new-environment.yml#L40) to use OIDC. Organisation master account already has an [OIDC provider](https://github.com/ministryofjustice/aws-root-account/blob/954b7ae8482d601968a3cb7a0383675001b1ad08/management-account/terraform/iam.tf#L23) so the change only requires a github web identity assumable role in the master account which has permissions to assume [these roles](https://github.com/ministryofjustice/modernisation-platform/blob/main/terraform/environments/bootstrap/delegate-access/providers.tf).

Prerequisite PRs:
Module that creates a Github Web Identity Assumable Role here: https://github.com/ministryofjustice/modernisation-platform-github-oidc-role
PRs that creates/fixes this role in the org master account here: https://github.com/ministryofjustice/aws-root-account/pull/628 & https://github.com/ministryofjustice/aws-root-account/pull/629

https://github.com/ministryofjustice/modernisation-platform/pull/2686:
* Gives the new role permissions on the state bucket
* Converts new-environments/delegate-access workflow job to OIDC
* Converts scheduled-baseline/delegate-access workflow job to OIDC

https://github.com/ministryofjustice/modernisation-platform/pull/2694:
* Converts remaining jobs to OIDC.
