### ISSUE TITLE
Replace depreciated set-output in our GitHub Actions

### ISSUE THREAD

**Issue by davidkelliott** [ministryofjustice/modernisation-platform#2572]
## User Story

See here - https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

> Starting 1st June 2023 workflows using save-state or set-output commands via stdout will fail with an error.

The occurrences of set-output in code need to be examined and a determination made to see if they need to be amended following the Terraform changes. All modernisation-platform repos will need to be examined to make sure every version of this setting is checked.

## Definition of done

- [x] jobs with deprecated `set-output` identified
- [x] jobs updated so they no longer rely on `set-output`
- [ ] jobs tested
- [ ] UR test OR added to continual research plan

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by SimonPPledger** [comment]
only impacts 1 area

**Comment by SteveLinden** [comment]
Checked all the modernisation-platform* repositories and only 2 have the code in there:

- modernisation-platform
- modernisation-platform-incident-response.

In both cases the code is in a yml file

**Comment by SteveLinden** [comment]
A good example/explanation is [here](https://github.com/orgs/community/discussions/35994)

**Comment by SteveLinden** [comment]
Added 
">> $GITHUB_OUTPUT" to the end of each of the 4 lines in modernisation-platform repo.

It has not been done on the modernisation-platform-incident-response as the lines are commented out in there and may not be used.

**Comment by SteveLinden** [comment]
PR  (#4450) raised for the change. Want as many reviews as possible before it gets pushed onto main. It could possibly impact building new environments. We don't want to test because of the effort of removing environments that are built.

**Comment by SteveLinden** [comment]
#4450  merged

**Comment by SteveLinden** [comment]
After discussion decided to close as we don't know when a new release will come in.
