### ISSUE TITLE
Introduce custom scheduling of instances

### ISSUE THREAD

**Issue by gfou-al** [ministryofjustice/modernisation-platform#2579]
## User Story

We would like to enhance the Instance Scheduler so that it can stop/start instances before other instances in a specific order. This is an important feature worthy some analysis and agreement with the team.

Each application might have its own requirements for ordering of instances. 

users want to be able to stop and start instances at specific times, this is to add that functionality

See also:

- https://user-guide.modernisation-platform.service.justice.gov.uk/concepts/environments/instance-scheduling.html

## Definition of done

- [ ] Update documentation
- [ ] Implement this change
- [ ] Unit test completed successfully - in terraform and go?

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by SimonPPledger** [comment]
we will close this if Nick Buckingham raises his similar, but more useful, ticket

**Comment by SimonPPledger** [comment]
replaced by another ticket
