### ISSUE TITLE
Create IAPS production account

### ISSUE THREAD

**Issue by seanprivett** [ministryofjustice/modernisation-platform#2590]
### Application Name

delius-integrated-accredited-programmes-system

### GitHub team slug

https://github.com/orgs/ministryofjustice/teams/hmpps-migration

### Environments

| Environment 		| Access level |
| --- 				| --- |
|<ul><li>[x] Production</li></ul>	| <ul><li>[ ] view-only</li><li>[x] developer</li><li>[ ] sandbox</li></ul> |

### Tags

tag | value
--- | ---
application | delius-integrated-accredited-programmes-system
business-unit | HMPPS
owner | probation-webops@digital.justice.gov.uk

#### Subnet sets

- [ ] General - this application will use the same subnet as other applications in your business unit
- [ ] Isolated - this application has highly sensitive data which must have its own isolated subnet with no network connectivity

#### How do users connect to the application?

- [ ] Over the public internet
- [ ] With a purple cabled device
- [x] With a MoJ Official device

#### Connectivity to other applications or external parties

- [x] Delius (delius-core-dev-vpc - 10.161.20.0/22)

## Additional features

- [ ] Additional VPC Endpoints
- [x] Extended DNS Zones (We do not expect to need them permanently)
- [ ] Other - please specify

## Other information

Application users currently access the application by tunnelling through a bastion using Windows laptops with PuTTY. 

## Definition of done

- [ ] account created
- [ ] customer informed

**Comment by dms1981** [comment]
NB - Connectivity to `delius-core-dev-vpc` is configured through this PR: https://github.com/ministryofjustice/modernisation-platform/pull/2702/files

**Comment by dms1981** [comment]
Placed in blocked pending the completion of the above PR, and on finding a contact for delius-iaps who I can inform about the account creation
