### ISSUE TITLE
ECS working example

### ISSUE THREAD

**Issue by seanprivett** [ministryofjustice/modernisation-platform#2591]
Using LAA implementation as an example, use the MP module and additional terraform resources to create an ECS cluster with resource monitoring/alerting and autoscaling based on resource metrics in our `example` environment. This will help customers looking to implement an flexible ECS cluster in their own environment.

The example should use the outputs of the MP ECS module to create a node scaling and service scaling policies based on cloudwatch resource metrics/alerts.

DOD:

- [x] ECS cluster created
- [ ] Documentation updated

**Comment by julialawrence** [comment]
https://github.com/ministryofjustice/modernisation-platform-environments/tree/main/terraform/environments/mlra/modules/ecs

**Comment by dms1981** [comment]
https://github.com/ministryofjustice/modernisation-platform-environments/tree/main/terraform/environments/example

**Comment by SteveLinden** [comment]
I had issues with my "M1" macbook failing to init on the example code. This has now been resolved so I can start to work on this again. Initial plan was to run the current code to setup the EC2 that should be in place.

**Comment by SteveLinden** [comment]
The current version of the ecs module is difficult to get to work so we may need to bring all the code in. Likely to be moved to a post firebreak sprint

**Comment by ewastempel** [comment]
Implemented with this PR: https://github.com/ministryofjustice/modernisation-platform-environments/pull/1303

The deployment of infra was successful, however the deployment of app was not. 
The follow on task will be created to investigate it.

**Comment by ewastempel** [comment]
this is the error when a task definition is being deployed:
`service [example-app-ecs-service](https://eu-west-2.console.aws.amazon.com/ecs/v2/clusters/example-app/services/example-app-ecs-service?region=eu-west-2) was unable to place a task because no container instance met all of its requirements. Reason: No Container Instances were found in your cluster. For more information, see the Troubleshooting section of the Amazon ECS Developer Guide.`

**Comment by ewastempel** [comment]
follow on tickets: https://github.com/ministryofjustice/modernisation-platform/issues/3019
