### ISSUE TITLE
Runbook for CW Networking Alarms

### ISSUE THREAD

**Issue by julialawrence** [ministryofjustice/modernisation-platform#2635]
## User Story

As a modernisation platform engineer
I would like to have a runbook explaining how to investigate, remediate and potentially tune cloud watch networking alarms
So that we have a standard practice we can refer to

## User Type(s)

Modernisation platform engineers
On-call engineers

## Value

The runbook itself and the process of writing it is a good opportunity to increase and share the knowledge of MP networking.

### Hypotheses

If the runbook is available and useful, more people will feel comfortable being on-call and more confident they will be able to handle the alarms without needing escalation.

### Proposal

An experienced engineer pairs with a less experienced engineer to walk through the process of resolving the networking alarms.

The walkthrough is used as a basis for the runbook

## Definition of done

- [ ] Runbook has been created and published on the MP docs site
- [ ] user docs have been updated
- [ ] another team member has reviewed

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by davidkelliott** [comment]
https://user-guide.modernisation-platform.service.justice.gov.uk/runbooks/cloudwatch-networking-alarms.html#a-summary-of-current-alarms
