### ISSUE TITLE
Rework module unit tests to either remove the backend or select a workspace prior to applying

### ISSUE THREAD

**Issue by julialawrence** [ministryofjustice/modernisation-platform#2647]
## Expected Behavior

Unit tests in modules should point at the state file in /environments/members/testing/testing-test S3 folder because the terraform is configured to expect to be run in the testing-test workspace.

## Actual Behavior

There's nothing in the go code that selects the correct workspace, so some unit tests run against the correct state and some run against the main terraform.tfstate file in the top level of main state bucket.

When terraform uses the main terraform.tfstate file, it modifies the permissions on it in such a way that roles/users outside the modernisation platform account lose access to it, breaking modernisation-platform-environments workflows as well as others like delegate-access.

## Steps to Reproduce the Problem

  1. Create a new module
  2. Write some unit test terraform
  3. Load testing-test credentials into the environment
  4. Run the go test -v command.
  5. Because testing-test workspace hasn't been created, terraform will update the main terraform.tfstate file in the top level of the state bucket.

## Proposed solution
Either add an explicit command to select/create a workspace in the go test code or remove backend.tf configuration from the unit test terraform.

**Comment by julialawrence** [comment]
A number of PRs raised at the same time on all our modules highlighted the issue with using the same state for all terratest runs. Between managing different persistent states or dispensing with persistent states altogether, it's better to move to local states that don't persist between runs. 

Any issues arising out of that should be mitigated by the the weekly runs of autonuke.

**Comment by dms1981** [comment]
I've raised a range of PRs that should resolve this and checked that the tests run - the ECS module tests appear to still have a few issues, but those aren't related to the backend removal and will be investigated separately.
