### ISSUE TITLE
Request for mlra-test, mlra-preprod and mlra-prod

### ISSUE THREAD

**Issue by mikereiddigital** [ministryofjustice/modernisation-platform#2655]
### Application Name

MLRA

### Description of application

This is for the remaining environments of the LAA's "MLRA" application that we will be migrating from other AWS accounts to MP.

### GitHub team slug

laa-aws-infrastructure

### Environments

| Environment 		| Access level |
| --- 				| --- |
|<ul><li>[ ] Development</li></ul>	| <ul><li>[ ] view-only</li><li>[ ] developer</li><li>[ ] sandbox</li></ul> |
|<ul><li>[x] Test</li></ul>			| <ul><li>[ ] view-only</li><li>[x] developer</li></ul> |
|<ul><li>[x] Preproduction</li></ul>| <ul><li>[ ] view-only</li><li>[x] developer</li></ul> |
|<ul><li>[x] Production</li></ul>	| <ul><li>[ ] view-only</li><li>[x] developer</li></ul> |

### Tags

tag | value
--- | ---
application | MLRA
business-unit | LAA
owner | LAA

### Subnet sets

- [x] General - this application will use the same subnet as other applications in your business unit
- [ ] Isolated - this application has highly sensitive data which must have its own isolated subnet with no network connectivity

### How do users connect to the application?

- [ ] Over the public internet
- [ ] With a purple cabled device (please give details)
- [ ] With a MoJ Official device
- [x] Via other existing AWS account

### Connectivity to other applications or external parties

These vpcs used by accounts will need to be hooked up to the MoJ's Transit Gateway as per laa-development.

## Additional features

- [ ] Additional VPC Endpoints
- [ ] Extended DNS Zones
- [ ] Other - please specify

## Definition of done

- [ x] account created
- [ x] customer informed

**Comment by SteveLinden** [comment]
Code to create the new environments is created #2734

**Comment by SteveLinden** [comment]
Added the access requirements via #2734 (pull request 2736)

**Comment by SteveLinden** [comment]
Sent a slack message to @mikereiddigital to let him know the accounts have been created. Said to raise anything on the ask channel if there are issues.
