### ISSUE TITLE
New IAPS environment

### ISSUE THREAD

**Issue by seanprivett** [ministryofjustice/modernisation-platform#2720]
## Environment details
Preproduction environment for the IAPS system being migrated from legacy AWS accounts

### Application Name
delius-integrated-accredited-programmes-system

### GitHub team slug
https://github.com/orgs/ministryofjustice/teams/hmpps-migration

### Environments

| Environment 		| Access level |
| --- 				| --- |
|<ul><li>[ ] Development</li></ul>	| <ul><li>[ ] view-only</li><li>[ ] developer</li><li>[ ] sandbox</li></ul> |
|<ul><li>[ ] Test</li></ul>			| <ul><li>[ ] view-only</li><li>[ ] developer</li></ul> |
|<ul><li>[x] Preproduction</li></ul>| <ul><li>[ ] view-only</li><li>[ ] developer</li></ul> |
|<ul><li>[ ] Production</li></ul>	| <ul><li>[ ] view-only</li><li>[ ] developer</li></ul> |

### Tags

tag | value
--- | ---
application | delius-integrated-accredited-programmes-system
business-unit | HMPPS
owner | probation-webops@digital.justice.gov.uk

HMPPS
### Subnet sets

- [ ] General - this application will use the same subnet as other applications in your business unit
- [ ] Isolated - this application has highly sensitive data which must have its own isolated subnet with no network connectivity

### How do users connect to the application?

- [ ] Over the public internet
- [ ] With a purple cabled device (please give details)
- [x] With a MoJ Official device

### Connectivity to other applications or external parties

- [x] Delius (delius-core-dev-vpc - 10.161.20.0/22)
## Additional features

- [ ] Additional VPC Endpoints
- [ ] Extended DNS Zones
- [ ] Other - please specify

## Other information

Application users currently access the application by tunnelling through a bastion using Windows laptops with PuTTY. 
## Definition of done

- [ ] account created
- [ ] customer informed

**Comment by SteveLinden** [comment]
Put in a pull for this - looks quite simple #2733

**Comment by SteveLinden** [comment]
Completed. I can access it and I'm waiting for confirmation that the customer is OK with it.
