### ISSUE TITLE
Create new accounts for Jitbit

### ISSUE THREAD

**Issue by seanprivett** [ministryofjustice/modernisation-platform#2721]
### Application Name
jitbit

### Description of application
Jitbit is a ticketing system that probation staff use to log incidents in frontline operations

### GitHub team slug

https://github.com/orgs/ministryofjustice/teams/hmpps-migration
### Environments

| Environment 		| Access level |
| --- 				| --- |
|<ul><li>[x] Development</li></ul>	| <ul><li>[ ] view-only</li><li>[ ] developer</li><li>[x] sandbox</li></ul> |
|<ul><li>[ ] Test</li></ul>			| <ul><li>[ ] view-only</li><li>[ ] developer</li></ul> |
|<ul><li>[x] Preproduction</li></ul>| <ul><li>[ ] view-only</li><li>[x] developer</li></ul> |
|<ul><li>[x] Production</li></ul>	| <ul><li>[ ] view-only</li><li>[x] developer</li></ul> |

### Tags

tag | value
--- | ---
application | delius-jitbit
business-unit | HMPPS
owner | probation-webops@digital.justice.gov.uk

HMPPS
### Subnet sets

- [ ] General - this application will use the same subnet as other applications in your business unit
- [ ] Isolated - this application has highly sensitive data which must have its own isolated subnet with no network connectivity

### How do users connect to the application?

- [ ] Over the public internet
- [ ] With a purple cabled device (please give details)
- [x] With a MoJ Official device

## Additional features

- [ ] Additional VPC Endpoints
- [ ] Extended DNS Zones
- [ ] Other - please specify

## Definition of done

- [ ] account created
- [ ] customer informed

**Comment by sobostion** [comment]
General subnet set should apply here
For additional features we will need connectivity to workmail

**Comment by ewastempel** [comment]
Original PR: https://github.com/ministryofjustice/modernisation-platform/pull/2745
Auto-generated and updated PRs:
https://github.com/ministryofjustice/modernisation-platform/pull/2746
https://github.com/ministryofjustice/modernisation-platform-environments/pull/1126

**Comment by ewastempel** [comment]
Documentation improvements:
https://github.com/ministryofjustice/modernisation-platform/pull/2747

**Comment by ewastempel** [comment]
Manually run the RAM share (due to issue we had in the pipeline worfklow):
```aws-vault exec mp-admin -- scripts/member-account-ram-association.sh delius-jitbit development
aws-vault exec mp-admin -- scripts/member-account-ram-association.sh delius-jitbit preproduction
aws-vault exec mp-admin -- scripts/member-account-ram-association.sh delius-jitbit production```

**Comment by ewastempel** [comment]
Verified that the accounts have been created and that the subnets exist inside those accounts.

**Comment by ewastempel** [comment]
Re-opening, as must inform the customer first.

**Comment by ewastempel** [comment]
I informed the Delius Threelius gang, but no news, which I treat as a good news. Closing this ticket.
