### ISSUE TITLE
Move ECS module to Perf Hub repository

### ISSUE THREAD

**Issue by dms1981** [ministryofjustice/modernisation-platform#2723]
## Expected Behavior

Migrate module from existing repo into perf hub folder in envs repo
This then becomes a non mod platform module

## Actual Behavior

Ensure there are no changes to the module as this would need downtime for perf hub. Coordinate closely with Perf Hub team and Jeremey.
```

## Other information

**Comment by dms1981** [comment]
https://developer.hashicorp.com/terraform/tutorials/configuration-language/move-config <- might be useful / relevant to this

**Comment by markgov** [comment]
PR Created tested on dev
https://github.com/ministryofjustice/modernisation-platform-environments/pull/1754

**Comment by markgov** [comment]
pre prod apply was applied with no errors
