### ISSUE TITLE
Create Customer Gateway & attach with VPN through Transit Gateway for PPUD

### ISSUE THREAD

**Issue by dms1981** [ministryofjustice/modernisation-platform#2728]
## User Story

As a Modernisation Platform Customer 
I want to connect my external environment to the Modernisation Platform via a site-to-site VPN
So that I can migrate data from my old environment to my new environment

## User Type(s)

Modernisation Platform Engineer
Modernisation Platform Customer

## Value

For the PPUD team to migrate their application into the Modernisation Platform, they also need to migrate the data from their old environments into their new environments. This requires connectivity to be establish between old and new. The team has requested that the Modernisation Platform team configure the AWS part of a site-to-site VPN with the following provided configuration:

```
Customer Gateway public IP: 212.124.224.214
Remote IPv4 Network CIDRs:
192.168.173.0/28
192.168.177.208/28
192.168.174.152/29
192.168.173.216/29

192.168.200.80/28
192.168.200.128/28
192.168.200.112/28
192.168.200.224/28

Local IPv4 Network CIDRs:
10.26.24.0/21
10.27.8.0/21

## Questions / Assumptions / Hypothesis

Do we need to use the `enable_acceleration` flag for the VPN connection?
_My first instinct here is no, but it would be worth reading up on this_

## Definition of done

- [ ] Customer Gateway created
- [ ] Site to site VPN created from appropriate endpoint (presume Transit Gateway)
- [ ] Any necessary routes added
- [ ] Configuration passed to customer
- [ ] VPN tunnel phase 1 & 2 establishment confirmed

## Reference

* [How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)
* https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/vpn_connection
* https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/customer_gateway
* https://mojdt.slack.com/archives/C03GRLUA42W/p1669373077419749

**Comment by davidkelliott** [comment]
Putting this in blocked until after PPUD meeting as I think this might not be needed.

**Comment by davidkelliott** [comment]
Not needed as using AWS application migration service
