### ISSUE TITLE
Create OAS accounts in MP for Ops team

### ISSUE THREAD

**Issue by tmahmood72** [ministryofjustice/modernisation-platform#2787]
### Application Name

oas

### Description of application
This is for the remaining environments of the LAA's "OAS" application that we will be migrating from other AWS accounts to MP.

Oracle Analytic Services that replaced OBIEE. The components are:
EC2 running the Oracle software
RDS database
There are hooks back to portal for user authorisation plus dblinks to apex, cis etc.

Current infra - https://github.com/ministryofjustice/laa-oas-upgrade

### GitHub team slug
laa-aws-infrastructure

### Environments

| Environment 		| Access level |
| --- 				| --- |
|<ul><li>[x] Development</li></ul>	| <ul><li>[ ] view-only</li><li>[x] developer</li><li>[ ] sandbox</li></ul> |
|<ul><li>[x] Test</li></ul>			| <ul><li>[ ] view-only</li><li>[x] developer</li></ul> |
|<ul><li>[x] Preproduction</li></ul>| <ul><li>[ ] view-only</li><li>[x] developer</li></ul> |
|<ul><li>[x] Production</li></ul>	| <ul><li>[ ] view-only</li><li>[x] developer</li></ul> |

### Tags

tag | value
--- | ---
application |  OAS
business-unit |  LAA
owner |  LAA

### Subnet sets

- [x] General - this application will use the same subnet as other applications in your business unit
- [ ] Isolated - this application has highly sensitive data which must have its own isolated subnet with no network connectivity

### How do users connect to the application?

- [ ] Over the public internet
- [ ] With a purple cabled device (please give details)
- [ ] With a MoJ Official device
- [x] Via other existing AWS account

## Additional features

- [ ] Additional VPC Endpoints
- [ ] Extended DNS Zones
- [ ] Other - please specify

## Other information

[
](https://dsdmoj.atlassian.net/jira/software/c/projects/LAWS/boards/262?modal=detail&selectedIssue=LAWS-2961&quickFilter=626)

## Definition of done

- [ ] account created
- [ ] customer informed

**Comment by dms1981** [comment]
Hi @tmahmood72 - what access level do you need for your development account?

**Comment by tmahmood72** [comment]
For Development we need 'developer' access - thanks

**Comment by davidkelliott** [comment]
Created developer account for now, other environments can be build out later
