### ISSUE TITLE
Investigate database patching possibilities using SSM

### ISSUE THREAD

**Issue by ep-93** [ministryofjustice/modernisation-platform#2813]
## User Story

As a member account user 
I want to be able to patch databases on ec2 
So that when they are migrated, a process in in place for auto-patching

## User Type(s)

Database admins for nomis and other teams.

## Value

Migrating databases will be ever so tempting when we have a patching process in place.

## Definition of done

- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] tests are green
- [ ] UR test OR added to continual research plan

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by SteveLinden** [comment]
It's possible through SSM but would need a DBA to create scripts for this. Application team responsibility rather than MODERNISATION PLATFORM
