### ISSUE TITLE
SPIKE: Investigate improvements to the patching module

### ISSUE THREAD

**Issue by ep-93** [ministryofjustice/modernisation-platform#2816]
Investigate with customers and the team what could be improved on in the module, and carry it out. 

## Improvements

- Alerting
- Custom script possibly
- More options for manually running
- More customisable 
- Check any new AWS patching scripts available. 

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by SimonPPledger** [comment]
We cannot do any further work on this, closing
