### ISSUE TITLE
Fix checkov failure

### ISSUE THREAD

**Issue by davidkelliott** [ministryofjustice/modernisation-platform#2831]
## Expected Behavior

Checkov check passes

## Actual Behavior

Failing with error 139

```
Running Checkov in terraform/environments
Excluding the following checks: CKV_GIT_1,CKV_AWS_126,CKV2_AWS_38,CKV2_AWS_39
checkov_exitcode=139
```

## Steps to Reproduce the Problem

  1.Run static code analysis

## Other information

Link to failed run - https://github.com/ministryofjustice/modernisation-platform/actions/runs/3871489057/jobs/6599333471#step:4:2089

Link to relevant repository with action - https://github.com/ministryofjustice/github-actions

**Comment by dms1981** [comment]
An exploratory look at the problem seems to show the problem being down to having a local version of `pyston`.
On removing it, checkov and pip both work locally:
```
root@84ff50712b9b:/# checkov -v
Segmentation fault
root@84ff50712b9b:/# rm -rf /usr/local/lib/python3.7/dist-packages/pyston*
root@84ff50712b9b:/# checkov -v
2.2.254
root@84ff50712b9b:/# pip3 --version
pip 22.3.1 from /usr/local/lib/python3.7/dist-packages/pip (python 3.7)
```

**Comment by dms1981** [comment]
https://github.com/ministryofjustice/github-actions/pull/174

**Comment by dms1981** [comment]
Released a new tagged version into the actions repository:
https://github.com/ministryofjustice/github-actions/releases/tag/v10

**Comment by dms1981** [comment]
New version works!
