### ISSUE TITLE
Fix implicit trust in Cloudtrail logging

### ISSUE THREAD

**Issue by seanprivett** [ministryofjustice/modernisation-platform#2883]
## User Story

The following email was received from amazon regarding our cloudtrail:

We contacted you recently regarding an AWS Identity and Access Management (IAM) change delivered on September 21, 2022 that updates an aspect of how role trust policy evaluation behaves when a role assumes itself. With this change, role assumption always requires an explicit role trust policy grant. At that time, we identified one or more roles in this account relying on implicit trust when the role assumes itself. These roles were placed on an allow list to prevent AssumeRole calls from being denied due to the new trust policy evaluation behavior. We are providing time for you to make any necessary changes to your existing processes, code, or configurations to prepare for removal of the implicit trust behavior. For more information about this behavior change in your account, please review additional details in the blog post "Announcing an Update to IAM Role Trust Policy Behavior" [1].

We are contacting you again to announce that we are delivering the capability that indicates whether your role trust policy explicitly grants trust to itself under the conditions specified in the role trust policy. This helps distinguish between role self-assumption calls that succeed because the role trust policy explicitly allows it or because the role is allow listed. Starting December 20, 2022, we are adjusting AWS CloudTrail logging for your sts:AssumeRole calls. While your role remains on the allow list, this adjustment provides insight into how IAM would evaluate your role assumption calls when the role assumes itself. Now, AWS CloudTrail log entries for your sts:AssumeRole call may be annotated with the “explicitTrustGrant” flag that appears in the “AdditionalEventData” field.

{
    "eventVersion": "1.08",
    "userIdentity": {
        "type": "AWSService",
        "invokedBy": "[myAWSService.amazonaws.com](http://myawsservice.amazonaws.com/)"
    },
    "eventTime": "2022-12-20T20:31:53Z",
    "eventSource": "[sts.amazonaws.com](http://sts.amazonaws.com/)",
    "eventName": "AssumeRole",
    "awsRegion": "us-west-2",
    "sourceIPAddress": "[myAWSService.amazonaws.com](http://myawsservice.amazonaws.com/)",
    "userAgent": "[myAWSService.amazonaws.com](http://myawsservice.amazonaws.com/)",
    "AdditionalEventData": {
        "explicitTrustGrant": "true"
    }
    ... additional entries ...
}

If the value of this flag is “true”, then this role assumption call would have succeeded in creating new role session credentials were it not on the allow list. If the value of this flag is “false”, then this role assumption call would have failed with an “AccessDenied” error were it not on the allow list. If the “explicitTrustGrant” flag does not appear in your AssumeRole Cloud Trail log entry, then this role assumption call is not allow listed. The change to Cloud Trail logging will become visible over several weeks as it deploys across all AWS regions. Allow listed roles will not show the “explicitTrustGrant” flag until deployment completes in the region in which the role is used.

Once your code and role configuration result in CloudTrail log entries that meet the expectations of your use case, you are ready to request that the role be removed from the allow list. For assistance with removing existing roles from the allow list, please contact AWS Support [2].

[1] https://aws.amazon.com/blogs/security/announcing-an-update-to-iam-role-trust-policy-behavior/
[2] https://aws.amazon.com/support

## User Type(s)

MP engineers

## Value

AWS have updated behaviour relating to how roles assume themselves. They have introduced an allow list to allow certain of our processes to continue, but these need to be updated, then a request put in via support to remove these from the allow list.

## Definition of done

- [ ] update policy
- [ ] support request to alter allow list
- [ ] another team member has reviewed
- [ ] tests are green

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by dms1981** [comment]
Having looked at the emails we receive from AWS, the only MP account I could see listed was `analytical-platform-management-production` so I'll focus my efforts there.

**Comment by dms1981** [comment]
After querying the CloudTrail logs for the `analytical-platform-management-production` account I couldn't see any roles which were taking advantage of implicit trust. I'll raise a support request to ask AWS support to check, too.

For reference, I searched the logs through `CloudWatch > Log groups > Cloudtrail` then searched all events with the following filter pattern:

```
{ ($.eventSource = "sts.amazonaws.com") && ($.additionalEventData.explicitTrustGrant= "false") }
```

**Comment by dms1981** [comment]
Waiting on a response from AWS Support at present, but given how long it's been (~48 hours) I'll ask AWS Support to chase their internal team.

**Comment by dms1981** [comment]
I had a response from AWS Support in the `analytical-platform-management-production` account. From what I read we should expect a further communication from them to tell us which roles are currently allowlisted at which point we can take corrective action.

**Comment by dms1981** [comment]
Putting this back onto the backlog until such time as we get a response (or I chase it up again in a few weeks!)

**Comment by dms1981** [comment]
As we've had no further communication from AWS this one is safe to close.
