### ISSUE TITLE
Windows updates on port 80 don't work

### ISSUE THREAD

**Issue by seanprivett** [ministryofjustice/modernisation-platform#2890]
## Expected Behavior

Customers have requested the ability to send HTTP requests to the internet.
This would allow the following scenarios to execute successfully:
* Windows WSUS servers would be able to receive patches/updates
* DotNET2.0/3.5 framework features would work

The tenants concerned are the IAPS and Equip accounts

## Actual Behavior

Outbound traffic on HTTP is not permitted through our network ACLs at present.
We don't necessarily want to allow unrestricted HTTP access to the internet, but this is something we ought to discuss as a team to avoid making disconnected tactical changes.

## Other information
We may want to consider allowing HTTP traffic, but only to specified FQDNs, through our AWS Network Firewall.
If we do this, we may also want to consider how we will manage this on an ongoing basis, and what kind of impediment this may present to our customers.

**Comment by dms1981** [comment]
This one might be down to the network ACLs in the customer VPCs, and the ports they allow out.

**Comment by dms1981** [comment]
https://github.com/ministryofjustice/modernisation-platform/pull/2916 <- this PR would solve the immediate issue

**Comment by dms1981** [comment]
Pulled this one out of sprint until I can rewrite it. In general, we need to revisit how we control *http* traffic leaving the modernisation platform and apply some FQDN filtering. This is a big bigger than one sentence though.
