### ISSUE TITLE
Create shared S3 bucket for AMI builds

### ISSUE THREAD

**Issue by davidkelliott** [ministryofjustice/modernisation-platform#2922]
## User Story

See the user request here - https://mojdt.slack.com/archives/C01A7QK5VM1/p1672842566496289

>Hi team, we're looking at setting up a bucket to hold application artefacts for use in AMI building. We were thinking of the existence of such a bucket in core-shared-services-production. What do you think of this from a platform design point of view? Naturally, we'd want to go with a pattern that is repeatable by other users too.

## User Type(s)

MP users

## Value

Installers all held in one place and reused by other teams, no need for teams to create their own S3 buckets

### Proposal

Create an S3 bucket in the core-shared-services account with permissions to allow any MP account access.

## Definition of done

- [x] bucket created
- [x] user docs have been updated
- [x] another team member has reviewed
- [x] tests are green

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by ep-93** [comment]
Done, but needs to be tested.
