### ISSUE TITLE
Create remaining CCMS EBS environments

### ISSUE THREAD

**Issue by davidkelliott** [ministryofjustice/modernisation-platform#2933]
### Application Name

ccms-ebs

### Description of application
CCMS is a system that manages certified civil legal aid applications, amendments and bills, it is our general ledger, chart of accounts and payment system and manages accounts receivable.

### GitHub team slug
[laa-ccms-migration-team](https://github.com/orgs/ministryofjustice/teams/laa-ccms-migration-team)

### Environments

| Environment 		| Access level |
| --- 				| --- |
|<ul><li>[ ] Development</li></ul>	| <ul><li>[ ] view-only</li><li>[ ] developer</li><li>[ ] sandbox</li></ul> |
|<ul><li>[x] Test</li></ul>			| <ul><li>[ ] view-only</li><li>[x] developer</li></ul> |
|<ul><li>[x] Preproduction</li></ul>| <ul><li>[ ] view-only</li><li>[x] developer</li></ul> |
|<ul><li>[x] Production</li></ul>	| <ul><li>[ ] view-only</li><li>[x] developer</li></ul> |

### Tags

tag | value
--- | ---
application |  ccms-ebs
business-unit |  LAA
owner | [donovan.artz@digital.justice.gov.uk](mailto:donovan.artz@digital.justice.gov.uk)

### Subnet sets

- [x] General - this application will use the same subnet as other applications in your business unit
- [ ] Isolated - this application has highly sensitive data which must have its own isolated subnet with no network connectivity

### How do users connect to the application?

- [x] Over the public internet
- [x] With a purple cabled device (please give details)
- [ ] With a MoJ Official device

### Connectivity to other applications or external parties

VPN to 6dg 3rd party hosting

## Additional features

- [ ] Additional VPC Endpoints
- [ ] Extended DNS Zones
- [ ] Other - please specify

## Definition of done

- [ ] account created
- [ ] customer informed

**Comment by markgov** [comment]
creating pr

**Comment by markgov** [comment]
PR Created

**Comment by markgov** [comment]
pr merged just need to create pr for the ram share

**Comment by markgov** [comment]
all pr confirmed and merged
