### ISSUE TITLE
New access level for DBAs/Oracle/Windows admins

### ISSUE THREAD

**Issue by davidkelliott** [ministryofjustice/modernisation-platform#2941]
## User Story

As a DBA/Oracle/Windows admin
I need to be able to access instances and databases
So that I can do my job

## User Type(s)

MP Users, 3rd Parties

## Value

The current developer role gives SSM permissions, but also gives access to other things such as secrets which teams may not want to give DBAs.

### Hypothesis 
If we create an "instance-admin" role with SSM, AD and other relevant permissions
Then we can securely allow people to do their job whilst following the principle of least priviledge.

### Proposal
Create an access level with the following permissions:
Read only plus:

```
      "aws-marketplace:ViewSubscriptions",
      "ds:*Tags*",
      "ds:*Snapshot*",
      "ds:ResetUserPassword",
      "ec2:StartInstances",
      "ec2:StopInstances",
      "ec2:RebootInstances",
      "ec2:ModifyImageAttribute",
      "ec2:ModifySnapshotAttribute",
      "ec2:CopyImage",
      "ec2:CreateImage",
      "ec2:CopySnapshot",
      "ec2:CreateSnapshot",
      "ec2:CreateSnapshots",
      "ec2:CreateTags",
      "ec2:DescribeVolumes",
      "ec2:DescribeInstances",
      "ec2:DescribeInstanceTypes",
      "identitystore:DescribeUser",
      "kms:Decrypt*",
      "kms:Encrypt",
      "kms:ReEncrypt*",
      "kms:GenerateDataKey*",
      "kms:DescribeKey",
      "rds:CopyDBSnapshot",
      "rds:CopyDBClusterSnapshot",
      "rds:CreateDBSnapshot",
      "rds:CreateDBClusterSnapshot",
      "rds:RebootDB*",
      "rhelkb:GetRhelURL",
      "ssm:*",
      "ssm-guiconnect:*",
      "sso:ListDirectoryAssociations",
      "support:*"
```

## Definition of done

- [ ] new access level created
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] tests are green

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by adeweetman-al** [comment]
Thanks for creating this. Our use case is even more simpler than the above permissions, as our 3rd party really just requires access to the ec2 instance and currently AD instance permission to reset a user password (ds:ResetUserPassword, plus maybe a few other list/get permissions to see the instance). But appreciate there's a balance to be struck between simplicity and exact least privilege.
We will probably look at using Fleet Manager to allow our 3rd party to initiate RDP connections. If this works fine, this could negate any need for AD which would be good.

**Comment by ep-93** [comment]
https://github.com/ministryofjustice/modernisation-platform/pull/3087
