### ISSUE TITLE
SPIKE: Find opportunities for code consolidation

### ISSUE THREAD

**Issue by dms1981** [ministryofjustice/modernisation-platform#2942]
## User Story

As a modernisation platform engineer 
I want to identify opportunities to refactor and reduce our code estate
So that we have more concise, more comprehensible code, that is easier for engineers to understand and update 

## User Type(s)

Modernisation Platform Engineer

## Value

Over time we add new features and change our code to support customer needs, or implement new features and ideas. This can lead to our code becoming overly verbose, or overly complicated.

By finding opportunities to refactor our code we can consolidate the amount of code we have, and standardise approaches to solving problems in code. This should result in us having less code, that is hopefully less complicated, and easier for engineers to understand.

### Hypothesis 
If we invest time looking for code consolidation opportunities
Then we can update our code and save time and effort in future

## Definition of done

- [ ] opportunities for consolidation identified
- [ ] new issues raised covering these opportunities
- [ ] another team member has reviewed

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by dms1981** [comment]
There's a disconnect in how we create VPCs for the platform, and for member accounts.

For member VPCs we reference the [modernisation-platform-terraform-member-vpc module](https://github.com/ministryofjustice/modernisation-platform-terraform-member-vpc).

For core VPCs we reference a [local module](https://github.com/ministryofjustice/modernisation-platform/tree/main/terraform/modules/vpc-hub).

Bringing these two modules closer into harmony would make it easier to port changes between the two. For starters, a card exists to align the network ACLs better (#2403).

Beyond this, the construction of the VPCs is complicated, relying on some complicated local values and containing references to routing strategies prior to the implementation of the Modernisation Platform Transit Gateway. Finding ways to reduce to complexity and increase the commonality between the two approaches will make it easier to support how these resources are provisioned through code, but will need to be done cautiously.

**Comment by dms1981** [comment]
In the [modernisation-platform-ami-builds repository](https://github.com/ministryofjustice/modernisation-platform-ami-builds/tree/main/modernisation-platform) there are multiple pipeline.tf files that appear to be very similar retreads of each other. Could these be modularised and supplied with a common format input like json?

**Comment by davidkelliott** [comment]
Couple of things I can think of off the top of my head -

 - repeating code in the environments repo, eg providers.tf backend.tf
 - repeating code in github actions, eg application workflow files
 - repeating code in bash scripts between the environments repo and the main repo
