### ISSUE TITLE
Update environments repo provider files so that users don't need to modify them to run local plans

### ISSUE THREAD

**Issue by davidkelliott** [ministryofjustice/modernisation-platform#2943]
## User Story

Do this to all provider files in the environments repo - https://user-guide.modernisation-platform.service.justice.gov.uk/user-guide/running-terraform-plan-locally.html#running-local-plans-without-file-modifications

conditional - there is an example in the documentation. check that this works for all users, SSO and collaborators.

## Definition of done

- [x] readme has been updated
- [x] user docs have been updated
- [ ] another team member has reviewed
- [ ] tests are green
- [ ] UR test OR added to continual research plan

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by davidkelliott** [comment]
Note we discussed this as something to do when we refactor to use terragrunt to save updating everything in multiple places

**Comment by davidkelliott** [comment]
Template changes in sprinkler here - https://github.com/ministryofjustice/modernisation-platform-environments/pull/1350

**Comment by seanprivett** [comment]
@davidkelliott to review after assessing new roles that have been created since ticket drafted
