### ISSUE TITLE
UR - Alternative roles for user access to the platform. 

### ISSUE THREAD

**Issue by ep-93** [ministryofjustice/modernisation-platform#2944]
## User Story

As a MP user
I need/want/expect to be able to possibly manage, or have created for me, varying levels of access for external and internal members
So that they can perform tasks on the platform. 

## User Type(s)

All teams may required different access levels at some point.

## Value

This could allow a varying level of people to access what is needed on the platform ,without giving them too much power. Etc, DB admins, third parties. 

## Questions / Assumptions / Hypothesis

Who will manage these roles?
Will there be a limit?

## Definition of done

- [x] Hold UR Canvas with MP team
- [x] Hold workshop with users to further discussion

Workshop outputs https://docs.google.com/document/d/1f-Vly6AUljnzSYCeBefYFXLgSMeHZW2cSFNlLn_oVrM/edit?usp=sharing 

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by ScottSeaward** [comment]
Arranged a UR Canvas for weds 11th Jan with team
