### ISSUE TITLE
Refactor modernisation-platform-terraform-bastion-linux to remove template provider

### ISSUE THREAD

**Issue by dms1981** [ministryofjustice/modernisation-platform#2954]
## User Story

As a modernisation platform engineer 
I want to remove the references to the `templatefile` provider from this module
So that customers with M1 macbooks are not impeded from using our code

## User Type(s)

Modernisation Platform Customer (eg, developers)

## Value

The value here is twofold:

First, the `template` provider was [archived over two years ago](https://github.com/hashicorp/terraform-provider-template/issues/85). It cannot be assumed to be continually compatible with future versions of Terraform, and should be replaced by native Terraform functions

Secondly, customers who make use of this module run into issues when running the code locally if they try to do so with an M1 MacBook. Since we want our customers to continue to use our code, we need to ensure that they can do so.

## Questions / Assumptions / Hypothesis

A previous attempt to remove the `template` provider ran into issues with GitHub actions. What were these issues? They will need to be understood and mitigated as part of this story.

## Definition of done

- [ ] template provider removed
- [ ] tests are green
- [ ] m1 macbook user has tested locally without issue

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by ewastempel** [comment]
This is now resolved with this release: https://github.com/ministryofjustice/modernisation-platform-terraform-bastion-linux/releases/tag/v3.0.7
