### ISSUE TITLE
Split out MP managed TF code in to separate files and protect with codeowners

### ISSUE THREAD

**Issue by davidkelliott** [ministryofjustice/modernisation-platform#2956]
## User Story

There are some files such as locals.tf and data.tf that we generate from a template.  Users have added to these files, which means if we want to update them we can't just copy and past over the whole file in a bulk operation, we need to go in individually to each file and update the changed parts, increasing the time and complexity of the activity.

This task is to split these files out into their own file and rename them so it's clear this is for platform use only, eg:

platform_data.tf
platform_locals.tf

(note there may be more files the above 2 are just and example)

Then protect these files from changes with codeowners

Potentially we could dry these out with terragrunt but that would be another card

## Definition of done

- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] tests are green
- [ ] UR test OR added to continual research plan

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by dms1981** [comment]
Closing this one because so far as I can tell it was a duplicate of https://github.com/ministryofjustice/modernisation-platform/issues/2521 - this card is a bit less specific, but the goal of separating MP managed code and protecting with `codeowners` has been achieved.
