### ISSUE TITLE
Enable DNS logs

### ISSUE THREAD

**Issue by davidkelliott** [ministryofjustice/modernisation-platform#2972]
## User Story

As a security team
I want to view DNS logs
So that I can identify abnormal or malicious activity

## User Type(s)

Security team

## Value

Be able to identify abnormal or malicious activity in DNS and therefore improve our security posture and become aware of security incidents earlier.

### Hypothesis 
If we enable DNS logs
Then a security team will be able to analyse and detect issues

Talk with security team/Steve to agree what exactly we need to implement

Check MOJ guidelines for DNS logging

### Proposal

In order to implement Route53 Resolver Query Logging we will need to do the following:
* Create one of more CloudWatch Log Groups to hold the logs in `core-logging` (potentially one for `live_data` and one for `non_live_data`)
* Create a reusable module that can take in a variable for the log group ARN and the ID of a VPC
* Call this reusable module with a for_each expression in each terraform directory that creates per-business-unit VPCs and supply it with the relevant VPC ID and log group ARN

## Definition of done

- [x] CloudWatch log group(s) created
- [x] Reusable module created
- [x] Module implemented to add logging wherever we create a VPC
- [x] DNS logging enabled
- [x] user docs have been updated
- [x] another team member has reviewed
- [x] tests are green

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by SteveLinden** [comment]
The DNS definitions appear to all be under modernisation platform account. To add we need to create a profile (see below) and create a log group. Note, some of the route 53 environments do not, currently, have the option of adding query logging as an option so these may require additional changes/settings.

Required profile is here ...
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Sid": "Route53LogsToCloudWatchLogs",
      "Effect": "Allow",
      "Principal": {
        "Service": [
          "route53.amazonaws.com"
        ]
      },
      "Action": [
        "logs:CreateLogStream",
        "logs:PutLogEvents"
      ],
      "Resource": "arn:aws:logs:us-east-1:278663825216:log-group:*"
    }
  ]
}

**Comment by SteveLinden** [comment]
If the comment I have seen is true this might not be possible on eu-west-2

"There are restrictions on the configuration of query logging. Notably, the CloudWatch log group must be in the us-east-1 region"

**Comment by dms1981** [comment]
Speaking with @SteveLinden this story is a bit unclear so I'm going to update the description to cover what's required.

**Comment by SteveLinden** [comment]
PR for module and the log/profile build https://github.com/ministryofjustice/modernisation-platform/pull/3049

**Comment by dms1981** [comment]
I've sorted the code for this and built all but two of the log query associations - `laa-test` and `hmcts-preproduction`.
I can't see anything that would have caused those two to have failed, so I've raised a support request with AWS.

**Comment by dms1981** [comment]
Moved this into blocked while the support case with AWS is resolved.

**Comment by dms1981** [comment]
Have chased this with our TAM

**Comment by dms1981** [comment]
Tracked the problem down with AWS Support to a CloudWatch policy - `"AWSLogDeliveryWrite20150319"` - that was missing a VPC statement in each affected account.
