### ISSUE TITLE
Add apply step to aws-root-account workflow

### ISSUE THREAD

**Issue by davidkelliott** [ministryofjustice/modernisation-platform#2973]
## User Story

As an MP engineer
I expect to not have to rely on a person to deploy root account infrastructure
So that I can deploy approved infrastructure

## User Type(s)

MP engineers, Ops eng engineers

## Value

Removes the single point of failure of requiring a person to deploy to the root account infrastructure.

## Definition of done

- [ ] apply step added to aws-root-account workflow
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] tests are green
- [ ] UR test OR added to continual research plan

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by SimonPPledger** [comment]
@davidkelliott is this already done?

**Comment by ep-93** [comment]
https://github.com/ministryofjustice/aws-root-account/ - This repo

**Comment by ep-93** [comment]
https://github.com/ministryofjustice/aws-root-account/commits/main/.github/workflows/management-account-apply.yml 


Well done everyone.

**Comment by dms1981** [comment]
Looks like it was solved in this commit: https://github.com/ministryofjustice/aws-root-account/pull/724?
