### ISSUE TITLE
Tasks to recreate VPN to Azure in UK West

### ISSUE THREAD

**Issue by seanprivett** [ministryofjustice/modernisation-platform#2997]
A VPN has been set up from the NOMIS production account to Azure UK South for the purposes of testing. The DSO team now need a VPN setting up to UK West, where all of the actual production stuff sits.

I think this is a switchover from UK South.

There will be an outage to production services - NOMIS Audit database and NOMIS Operational Reporting. This switch needs to be coordinated with those teams and will need to be done out of hours. I'm not sure if this affects the MP team.

## Definition of done
- [x] VPN between MP and Azure created
- [x] Static routes to Azure ranges added to MP Transit Gateway route table
- [x] Traffic flow tested

**Comment by dms1981** [comment]
I think for us there are two tasks, neither of which ought to be too challenging because they're retreads of things we've done before..
1. Set up VPN between `MP TGW` and `UK West VPN GW`
2. Add manual routes to `UK West` via VPN in `MP TGW

**Comment by dms1981** [comment]
I've approached the DSO webops team to get this one started. We'll need to be aligned as when the VPN comes up we'll be advertising routes to them, and will need to configure our own routing to minimise any possible outage.

**Comment by dms1981** [comment]
Raise https://github.com/ministryofjustice/modernisation-platform/pull/3012 to cover the creation of the VPN

**Comment by dms1981** [comment]
VPN creation has been completed from the MP side, but is awaiting completion from the Azure side.
Checked with @drobinson-moj that sufficiently long static routes are in place on the Azure side so that the routes propagated by BGP from AWS do not interrupt the flow of traffic

**Comment by dms1981** [comment]
All done! Routes are in, VPN is up, traffic flow has been tested successfully.
