### ISSUE TITLE
Support FQDN-based allow listing on AWS Network Firewall

### ISSUE THREAD

**Issue by dms1981** [ministryofjustice/modernisation-platform#2998]
## User Story

As a modernisation platform engineer
I need to implement a way to allow HTTP traffic to selected FQDNs
So that I can allow customers to access update servers, without compromising security of the platform

## User Type(s)

Modernisation Platform Engineer
Modernisation Platform Customer

## Value

[This issue](https://github.com/ministryofjustice/modernisation-platform/issues/2890) discusses the need for customers to be able to conduct Windows updates via WSUS servers. The WSUS servers need to start their communication with the remote update servers over HTTP before switching to HTTPS according to our customers. Therefore, we need to allow traffic to these destinations only.

Implementing an fqdn-based rule that allows us to permit traffic to determined addresses will allow us to open up our network ACLs with confidence that traffic will only be flowing out to secure destinations.

Ideally we will look at how we add rules to our rule groups, and create a rule allowing HTTP traffic out to hosts that match a static list of domain names that we will curate.

## Definition of done

- [x] readme has been updated
- [x] fqdn-based rule implemented
- [x] user docs have been updated if appropriate
- [x] another team member has reviewed

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)
[Domain filtering example](https://docs.aws.amazon.com/network-firewall/latest/developerguide/suricata-examples.html#:~:text=sid%3A1%3B)%22%0A%20%20%20%7D%0A%7D-,Domain%20filtering,-Note)

**Comment by markgov** [comment]
Code tested locally and one rule group gets created need a list of dns name that we want to allow access to as well as adding all the vpc cidr ranges as well

**Comment by markgov** [comment]
Draft PR updated

**Comment by markgov** [comment]
FQDN Rules now in place

**Comment by markgov** [comment]
Need to do documentation update and readme update
