### ISSUE TITLE
Amend NACLs to allow non-public subnets to send traffic on tcp/80

### ISSUE THREAD

**Issue by dms1981** [ministryofjustice/modernisation-platform#2999]
## User Story

As a Modernisation Platform Customer
I need to send traffic out to destinations on tcp port 80 for HTTP
So that I can leverage my WSUS servers to supply updates to my hosted servers on MP 

## User Type(s)

Modernisation Platform Customer

## Value

[This issue](https://github.com/ministryofjustice/modernisation-platform/issues/2890) discusses the need for customers to be able to conduct Windows updates via WSUS servers. The WSUS servers need to start their communication with the remote update servers over HTTP before switching to HTTPS according to our customers. Therefore, we need to allow traffic to these destinations only.

Our network ACLs do not currently allow traffic to leave MP on a destination port of tcp/80 to a public destination. We will need to amend the NACLs to allow this. An example PR can be seen [here](https://github.com/ministryofjustice/modernisation-platform/pull/2916).

## Definition of done

- [ ] FQDN filtering already in place before doing this
- [ ] Network ACLS updated
- [ ] User docs have been updated if appropriate
- [ ] another team member has reviewed

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)
[Allow HTTP out from customer VPCs](https://github.com/ministryofjustice/modernisation-platform/pull/2916)

**Comment by markgov** [comment]
PR Merged
