### ISSUE TITLE
Implement Network Firewall rules

### ISSUE THREAD

**Issue by davidkelliott** [ministryofjustice/modernisation-platform#3005]
## User Story

The network firewall rules are currently set to log only, we need to turn these on to block unwanted traffic, and document how to add new firewall rules.

Before turning to block, check logs and add any rules which are required.

## User Type(s)

MP engineers

## Value

Ensure traffic from the wider MoJ network only goes where user want it to go.

## Definition of done

- [x] firewall rules set to block
- [x] user docs have been updated - how to add new rules
- [x] another team member has reviewed
- [x] tests are green

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by markgov** [comment]
started to look at the log for the firewall to determine what to allow through

**Comment by markgov** [comment]
pr raised and approved/merged for new firewall rules

**Comment by markgov** [comment]
documentation completed

**Comment by markgov** [comment]
https://github.com/ministryofjustice/modernisation-platform/pull/3115 PR for blocking network traffic

**Comment by markgov** [comment]
PR updated to remove strict order

**Comment by markgov** [comment]
block implemented on dev only

**Comment by markgov** [comment]
New PR for changing the lifecycle and resource name
https://github.com/ministryofjustice/modernisation-platform/pull/3177

**Comment by markgov** [comment]
New PR pushed to repo
https://github.com/ministryofjustice/modernisation-platform/pull/3196

**Comment by markgov** [comment]
final pr complete
https://github.com/ministryofjustice/modernisation-platform/pull/3257

new rules in place for dev environment

**Comment by markgov** [comment]
PR for prod and pre-prod traffic blocking
https://github.com/ministryofjustice/modernisation-platform/pull/3266

**Comment by markgov** [comment]
Firewall network blocking in place
