### ISSUE TITLE
EC2 instances/ASG are not registered as ECS container instances when using ECS module

### ISSUE THREAD

**Issue by ewastempel** [ministryofjustice/modernisation-platform#3019]
## Expected Behavior

The EC2/ASG should be registered as an ECS containers.

## Actual Behavior

When standing up an ECS environment using the[ ECS module](https://github.com/ministryofjustice/modernisation-platform-terraform-ecs), the EC2instances/ASG do not get registered as ECS container instances. This means there are no container instances to run containers on (and therefore the application deployment fails).

## Steps to Reproduce the Problem

  1. Run terraform apply in the [example directory of the environments repo](https://github.com/ministryofjustice/modernisation-platform-environments/tree/main/terraform/environments/example).
  2. Log on to the `example-development` account and navigate to [Amazon Elastic Container Service](https://eu-west-2.console.aws.amazon.com/ecs/v2/home?region=eu-west-2)
[Clusters](https://eu-west-2.console.aws.amazon.com/ecs/v2/clusters?region=eu-west-2)
[example-app](https://eu-west-2.console.aws.amazon.com/ecs/v2/clusters/example-app?region=eu-west-2)
Infrastructure
  3. Note, no Capacity Providers, nor Container Instances are listed.

## Other information

If you navigate to: [Amazon Elastic Container Service](https://eu-west-2.console.aws.amazon.com/ecs/v2/home?region=eu-west-2)
[Clusters](https://eu-west-2.console.aws.amazon.com/ecs/v2/clusters?region=eu-west-2)
[example-app](https://eu-west-2.console.aws.amazon.com/ecs/v2/clusters/example-app?region=eu-west-2)
[Services](https://eu-west-2.console.aws.amazon.com/ecs/v2/clusters/example-app/services?region=eu-west-2)
[example-app-ecs-service](https://eu-west-2.console.aws.amazon.com/ecs/v2/clusters/example-app/services/example-app-ecs-service?region=eu-west-2)
Deployments

you will see the error why the task failed to deploy (no instances).

Deploy and test in example with terratests written and passing

**Comment by SteveLinden** [comment]
This module has now been archived
