### ISSUE TITLE
terraform plan in the example directory is not idempotent

### ISSUE THREAD

**Issue by ewastempel** [ministryofjustice/modernisation-platform#3027]
## Expected Behaviour

When running `terraform plan` then applying changes with `terraform apply` and re-running `terraform plan` in the [example directory of the env repo](https://github.com/ministryofjustice/modernisation-platform-environments/tree/main/terraform/environments/example) there should be no changes detected (as they have been applied with `terraform apply`). 

## Actual Behaviour

When running `terraform plan` after applying changes with `terraform apply`  in the [example directory of the env repo](https://github.com/ministryofjustice/modernisation-platform-environments/tree/main/terraform/environments/example) the plan output  suggests changes to the environment. This is most likely because there are some default values that have not been captured with code.

## Steps to Reproduce the Problem

  1. Run `terraform plan` in the  [example directory of the env repo](https://github.com/ministryofjustice/modernisation-platform-environments/tree/main/terraform/environments/example).
  2.  Then run `terraform apply` and apply changes.
  1. Re-run `terraform plan` and note the changes in the plan output.

## Other information

  - Repository/Directory: https://github.com/ministryofjustice/modernisation-platform-environments/tree/main/terraform/environments/example
  - Account: example-development

**Comment by ep-93** [comment]
So this module is the problem. 

source = "github.com/ministryofjustice/modernisation-platform-terraform-loadbalancer?ref=v2.1.1"

If we pass it empty ingress and egress rules, it works fine and doesn't need to rebuild, will try and work out why.
