### ISSUE TITLE
Move things out of delegated access that don't need higher credentials

### ISSUE THREAD

**Issue by davidkelliott** [ministryofjustice/modernisation-platform#3053]
## User Story

Move everything that doesn't need the root account access from delegate access to member bootstrap

Everything apart from this - 
https://github.com/ministryofjustice/modernisation-platform/blob/main/terraform/environments/bootstrap/delegate-access/iam.tf#L12
Things relating to this and also this:
https://github.com/ministryofjustice/modernisation-platform/blob/main/terraform/environments/bootstrap/delegate-access/policies.tf

Everything else should be able to be moved.
## Definition of done

- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] tests are green
- [ ] UR test OR added to continual research plan

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by SimonPPledger** [comment]
what can be taken out - need this information to consider it 'refined'

**Comment by davidkelliott** [comment]
Everything apart from this - 
https://github.com/ministryofjustice/modernisation-platform/blob/main/terraform/environments/bootstrap/delegate-access/iam.tf#L12
Things relating to this and also this:
https://github.com/ministryofjustice/modernisation-platform/blob/main/terraform/environments/bootstrap/delegate-access/policies.tf

Everything else should be able to be moved.

**Comment by ep-93** [comment]
Needs to be tested, most stuff can be deleted and recreated, some things might need to import..

**Comment by sukeshreddyg** [comment]
1. Migrated following resources from **delegate access** to **member bootstrap**

	* **Collaborators roles** 
 	* **GitHub-oidc role**
 	* **AWSRTSSupport role**
 	* **iam account alias resource**
 	* **SSM Parameters**
 	
2. Migrated **All policies** from delegate access to single-sign-on

#6144 
#6156 
#6244 
#6254
