### ISSUE TITLE
Replace GitHub classic Personal Access Tokens with fine-grained tokens

### ISSUE THREAD

**Issue by dms1981** [ministryofjustice/modernisation-platform#3058]
## User Story

As a Modernisation Platform Engineer
I want to replace our Classic PATs with fine-grained PATs
So that I can continue to adhere to a principle of least privilege

## User Type(s)

Modernisation Platform Engineer

## Value

In October 2022, GitHub released an update to how Personal Access Tokens can have their permissions controlled. In replacing our existing classic PATs with fine-grained PATs we can restrict their privileges so that only necessary actions they were created to accomplish are achievable using the new permission options.

### Hypothesis 
If we replace our classic PATs with fine-grained PATs
Then we will reduce the risk from a compromised PAT

## Definition of done

- [x] use cases for each classic PAT understood
- [x] fine grained PATs generated to replace classic PATs
- [x] GitHub actions referring to PATs updated
- [x] GitHub actions tested successfully

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)
[Introducing fine-grained personal access tokens for GitHub](https://github.blog/2022-10-18-introducing-fine-grained-personal-access-tokens-for-github/)

**Comment by dms1981** [comment]
The tokens in scope for this are the following:

| Token | Description |
| -- | -- |
| github_ci_user_pat | Used to create PRs etc in GitHub actions and deploy GitHub resources via Terraform |
| github_ci_user_environments_repo_pat | Used in reusable pipelines of the modernisation-platform-environments repository. This is so that the CI user can post comments in PRs, e.g. tf plan/apply output. |

From a quick look at the tokens available to the CI user one has already been converted to a fine-grained token, so hopefully only `github_ci_user_pat` will need updating

**Comment by richgreen-moj** [comment]
The `github_ci_user_pat` token is used to populate the `TERRAFORM_GITHUB_TOKEN` secret in the Modernisation Platform repository. This is then referenced in the following jobs:  
- `collaborator-inactivity-monitoring.yml`
- `modernisation-platform-account.yml`
- `new-environment.yml`
- `new-environment-files.yml`
- `new-member-environment-files.yml`
- `secrets-retrieval.yml`
- `secrets-rotation-reminder.yml`
- `terraform-github.yml`
- `terraform-pagerduty.yml`
- `terraform-single-sign-on.yml`
- `generate-dependabot-file.yml`

It currently has the following permissions:

- **repo**
Full control of private repositories
- **workflow**
Update GitHub Action workflows
- **admin:org**
Full control of orgs and teams, read and write org projects
- **user:email** 
Access user email addresses (read-only) 
- **project**
Full control of projects

Next steps are to try creating a dummy fine-grained token that has the necessary permissions required to perform all the actions.

I might create a dummy token with minimal permissions and then on a branch try running all of these workflows and see what it complains about.

**Comment by richgreen-moj** [comment]
I've tested each workflow listed in the comment above by creating a new fine-grained token and giving it virtually no access and then referencing it in a branch in all the jobs and running them to see what fails. Then I have gradually enabled more permissions as required.

In particular, the `terraform-github.yml` workflow which runs the [Terraform](https://github.com/ministryofjustice/modernisation-platform/tree/main/terraform/github) to manage all of our github resources (e.g. creating new repos etc.) requires the widest scope as it needed me to open up permissions to "All repositories" rather than "Only select repositories" where you can limit it to just the MP repo for example.

I'm thinking of writing a follow-up to consider creating another token that has less privileged access for those jobs.

**Comment by richgreen-moj** [comment]
A new fine-grained GitHub token has been created, updated in aws secrets manager and [applied here](https://github.com/ministryofjustice/modernisation-platform/actions/runs/11814725018/job/32914365423#step:12:2183)

Permissions granted:

**Organization permissions**

-  Read and Write access to members and organization projects

**Repository permissions**

-  Read access to metadata
-  Read and Write access to administration, code, pull requests, and secrets

**Comment by richgreen-moj** [comment]
Follow on story created to consider creating a separate token with less privileges for certain workflows - https://github.com/ministryofjustice/modernisation-platform/issues/8476

**Comment by mikereiddigital** [comment]
I've reviewed this & moving to done.
