### ISSUE TITLE
SCA failing in module repositories

### ISSUE THREAD

**Issue by ewastempel** [ministryofjustice/modernisation-platform#3060]
## Expected Behavior

Code runs clean in GH actions.
Output of this ticket is list of things to fix from where SCA is failing

## Actual Behavior

Sec vulnerabilities are highlighted by the SCA action.

## Steps to Reproduce the Problem

  1.Create a PR for the example account and see the failing actions

## Other information

The SCA fails for code in modules that are used in the example account.
This ticket is to address all of the modules where the SCA is failing.
Get the list of modules where the SCA is failing, once this https://github.com/ministryofjustice/modernisation-platform/issues/3061 is implemented

A/C a list of repositories and number of issues in each so we can then prioritise which repos to tackle first

**Comment by ewastempel** [comment]
get the list of modules where the SCA is failing, once this [ticket](https://github.com/ministryofjustice/modernisation-platform/issues/3061) is implemented

**Comment by SimonPPledger** [comment]
this should be resolved as part of the workflow failure ticket

**Comment by SteveLinden** [comment]
The referenced item above is listed as a new issue but there's a note stating it has been completed.

**Comment by dms1981** [comment]
I discussed this ticket with @ewastempel who asked that we :
> "treat this like an extra check to go through all of the module repos and check if the SCA is not failing"
So I've been going through the repositories looking for failing workflows and finding things to fix such as this PR:
https://github.com/ministryofjustice/modernisation-platform-ami-builds/pull/618/files (which also involved some manual terraform state manipulation to refresh to `data.terraform_remote_state` contents).

**Comment by ASTRobinson** [comment]
modules identified in Example enviroment:

module "ec2_test_autoscaling_group” - source = "github.com/ministryofjustice/modernisation-platform-terraform-ec2-autoscaling-group?ref=v2.1.1"
module "bastion_linux" - source = "github.com/ministryofjustice/modernisation-platform-terraform-bastion-linux?ref=v4.0.0"
module "ec2_test_instance" - source = "github.com/ministryofjustice/modernisation-platform-terraform-ec2-instance?ref=v2.2.0"
module "ecs-cluster" - source = "github.com/ministryofjustice/modernisation-platform-terraform-ecs-cluster//cluster?ref=v3.0.0"
module "service" - source = "git::https://github.com/ministryofjustice/modernisation-platform-terraform-ecs-cluster//service?ref=v3.0.0"
module "ecs_lb_access_logs_enabled" - source = "github.com/ministryofjustice/modernisation-platform-terraform-loadbalancer?ref=v3.1.2"
module "lb_access_logs_enabled" - source = "github.com/ministryofjustice/modernisation-platform-terraform-loadbalancer?ref=v3.1.2"
module "s3-bucket-lb" - source = "github.com/ministryofjustice/modernisation-platform-terraform-s3-bucket?ref=v7.1.0"
module "s3-bucket" - source = "github.com/ministryofjustice/modernisation-platform-terraform-s3-bucket?ref=v7.1.0"

i will work through the modules one by one and check for any SCA failures.

**Comment by ASTRobinson** [comment]
[ec2_test_autoscaling_group](github.com/ministryofjustice/modernisation-platform-terraform-ec2-autoscaling-group) All green, no failures seen within run [/actions/runs/6792715578](https://github.com/ministryofjustice/modernisation-platform-terraform-ec2-autoscaling-group/actions/runs/6792715578)

[bastion_linux](github.com/ministryofjustice/modernisation-platform-terraform-bastion-linux) All green, no failures seen within run [/actions/runs/6792726581](https://github.com/ministryofjustice/modernisation-platform-terraform-bastion-linux/actions/runs/6792726581)

[ec2_instance](github.com/ministryofjustice/modernisation-platform-terraform-ec2-instance) All green, no failures seen within run [/actions/runs/6792734263](https://github.com/ministryofjustice/modernisation-platform-terraform-ec2-instance/actions/runs/6792734263)

[ecs-cluster]([github.com/ministryofjustice/modernisation-platform-terraform-ecs-cluster](http://github.com/ministryofjustice/modernisation-platform-terraform-ecs-cluster)) All green, no failures seen within run [/actions/runs/6819752344](https://github.com/ministryofjustice/modernisation-platform-terraform-ecs-cluster/actions/runs/6819752344)

[loadbalancer]([github.com/ministryofjustice/modernisation-platform-terraform-loadbalancer](http://github.com/ministryofjustice/modernisation-platform-terraform-loadbalancer)) All green, no failures seen within run [/actions/runs/6819775380](https://github.com/ministryofjustice/modernisation-platform-terraform-loadbalancer/actions/runs/6819775380)

[s3-bucket](github.com/ministryofjustice/modernisation-platform-terraform-s3-bucket) All green, no failures seen within run [/actions/runs/6819767093](https://github.com/ministryofjustice/modernisation-platform-terraform-s3-bucket/actions/runs/6819767093)
