### ISSUE TITLE
Get AWS Health issues directly to users

### ISSUE THREAD

**Issue by davidkelliott** [ministryofjustice/modernisation-platform#3069]
## User Story

We often get health emails from AWS such as this:

Hello,

Athena engine auto-upgrade will begin in 60 days on March 9, 2023 for the EU-WEST-2 Region. Before upgrading a workgroup we perform a set of validation tests to confirm that its queries perform correctly and efficiently on engine version 3. Since our validation is performed on a best-effort basis, we recommend that all customers perform their own validation testing and follow the following practices to ensure all queries are executing as expected:

We then send these on to the user.

We need a better way of:
1. Getting these directly to the user
2. Get an overview of all of these on MP so that we can see which issues are not being actioned
3. A process to ensure these get addressed

## User Type(s)

MP engineer, MP user

## Value

Prevent SPOF with health notifications

## Definition of done

- [ ] users directly informed
- [ ] method of viewing across the platform implemented
- [ ] process in place for reviewing
- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] tests are green
- [ ] UR test OR added to continual research plan

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by jakemulley** [comment]
A way to ensure users get these, as MP splits by account, is to take a user's `infrastructure-support` email and set the `OPERATIONS` contact using the [aws_account_alternate_contact](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/account_alternate_contact) resource.
