### ISSUE TITLE
Enable teams to review PRs that are within their team directory

### ISSUE THREAD

**Issue by ewastempel** [ministryofjustice/modernisation-platform#3083]
## User Story

As a webops and a MP user
I want to be able to review PRs that are scoped to my team's directory in the https://github.com/ministryofjustice/modernisation-platform-ami-builds repo
So that I am not blocked.

## User Type(s)

MP users

## Value

Faster delivery of team's AMI infrastructure.
Fewer requests in the ask channel
PR gets reviewed by the engineers that have the context.

### Proposal

Add other MP users/teams to the [codeowners](https://github.com/ministryofjustice/modernisation-platform-ami-builds/blob/main/.github/CODEOWNERS) of the AMI builds repository.

## Definition of done

- [x] readme has been updated
- [x] user docs have been updated
- [x] another team member has reviewed
- [x] tests are green
- [x] UR test OR added to continual research plan

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by SteveLinden** [comment]
Need a list of teams that require this access.
