### ISSUE TITLE
Review bastion shutdown and startup routines

### ISSUE THREAD

**Issue by SteveLinden** [ministryofjustice/modernisation-platform#3084]
A call was raised to ask for a bastion to be started up and when I checked (just after 20:00) it was in a terminated state. It was needed because there was an issue which required bastion access to resolve.

After checking the terraform code (running a plan etc) I found the service had been rebuilt and would be available within a few minutes.

We need to check the stop/start process to ensure the stop only takes place overnight (not at 20:00) and make sure the user community is aware of when this will take place.

**Comment by davidkelliott** [comment]
Guidance has now been added which explains how to restart instances at night so closing this - https://user-guide.modernisation-platform.service.justice.gov.uk/concepts/networking/instance-access-and-bastions.html#accessing-instances
