### ISSUE TITLE
Environment Request for Tipstaff

### ISSUE THREAD

**Issue by matt-k1998** [ministryofjustice/modernisation-platform#3096]
### Application Name

tipstaff

### Description of application

The Tipstaff office is responsible for acting on arrest warrants and child abduction orders. The office is responsible for executing orders for the removal of children from parents in domestic child abduction cases, including cases with an international element under the Hague convention and other provisions. In addition, the office is also responsible for the execution of High Court Warrants of Arrest and Warrants of Committal.

It is an .NET MVC solution hosted on SSG servers and is only accessible within the DOM1 domain.

The website allows the Tipstaff Office to record cases and generate standard letters.

### GitHub team slug

dts-heritage-services

### Environments

| Environment 		| Access level |
| --- 				| --- |
|<ul><li>[X] Development</li></ul>	| <ul><li>[ ] view-only</li><li>[ ] developer</li><li>[X] sandbox</li></ul> |
|<ul><li>[ ] Test</li></ul>			| <ul><li>[ ] view-only</li><li>[ ] developer</li></ul> |
|<ul><li>[ ] Preproduction</li></ul>| <ul><li>[ ] view-only</li><li>[ ] developer</li></ul> |
|<ul><li>[X] Production</li></ul>	| <ul><li>[ ] view-only</li><li>[X] developer</li></ul> |

### Tags

tag | value
--- | ---
application | Tipstaff
business-unit | HMCTS
owner | dts-legacy-applications:dts-legacy-apps-support-team@hmcts.net

### Subnet sets

- [X] General - this application will use the same subnet as other applications in your business unit
- [ ] Isolated - this application has highly sensitive data which must have its own isolated subnet with no network connectivity

### How do users connect to the application?

- [x] Over the public internet
- [ ] With a purple cabled device (please give details)
- [X] With a MoJ Official device

## Additional features

- [ ] Additional VPC Endpoints
- [ ] Extended DNS Zones
- [ ] Other - please specify

## Definition of done

- [ ] account created
- [ ] customer informed

**Comment by SteveLinden** [comment]
Attempted to create but the github slug I entered doesn't exist so need to contact the person who raised the call to check what one I should use. There are two listed [terraform-tipstaff-admin-team](https://github.com/orgs/ministryofjustice/teams/terraform-tipstaff-admin-team)
Automated generated team to grant users access to this repository
Jefex7
1 member	0 teams 
[terraform-tipstaff-write-team](https://github.com/orgs/ministryofjustice/teams/terraform-tipstaff-write-team)
Automated generated team to grant users access to this repository

Both of these only have one user which is a little unusual

**Comment by SteveLinden** [comment]
No mention of the "Additional features" listed so they have not been created. The user will be informed using the email ([dts-legacy-apps-support-team@hmcts.net](mailto:dts-legacy-apps-support-team@hmcts.net) listed above.

**Comment by SteveLinden** [comment]
@matt-k1998 Hi Matt. I tried using the address in the call but that appears to go to a helpdesk/service desk rather than a person. The accounts are created. If you need any more info please contact us. Best location is #ask-modernisation-platform on slack
