### ISSUE TITLE
Create PPUD preproduction environment

### ISSUE THREAD

**Issue by davidkelliott** [ministryofjustice/modernisation-platform#3097]
### Application Name
ppud

### Description of application

PPUD migration already in progress and application json present, this issue is to add a preproduction environment with migration access so that MGN can be used to lift and shift existing servers.

### GitHub team slug
See existing application json

### Environments

| Environment 		| Access level |
| --- 				| --- |
|<ul><li>[ ] Development</li></ul>	| <ul><li>[ ] view-only</li><li>[ ] developer</li><li>[ ] sandbox</li></ul> |
|<ul><li>[ ] Test</li></ul>			| <ul><li>[ ] view-only</li><li>[ ] developer</li></ul> |
|<ul><li>[x] Preproduction</li></ul>| <ul><li>[ ] view-only</li><li>[ ] developer</li><li>[x] migration</li></ul> |
|<ul><li>[ ] Production</li></ul>	| <ul><li>[ ] view-only</li><li>[ ] developer</li></ul> |

### Tags

tag | value
--- | ---
application | 
business-unit | 
owner | 

### Subnet sets

- [x] General - this application will use the same subnet as other applications in your business unit
- [ ] Isolated - this application has highly sensitive data which must have its own isolated subnet with no network connectivity

### How do users connect to the application?

- [ ] Over the public internet
- [ ] With a purple cabled device (please give details)
- [ ] With a MoJ Official device

## Additional features

- [ ] Additional VPC Endpoints
- [ ] Extended DNS Zones
- [ ] Other - please specify

## Definition of done

- [ ] account created
- [ ] customer informed

**Comment by markgov** [comment]
PR Raised https://github.com/ministryofjustice/modernisation-platform/pull/3133

**Comment by markgov** [comment]
Networking pprod update
https://github.com/ministryofjustice/modernisation-platform/pull/3138
