### ISSUE TITLE
Investigate AWS Transit Gateway Network Manager to monitor our network

### ISSUE THREAD

**Issue by jakemulley** [ministryofjustice/modernisation-platform#313]
We should look at using something like AWS Transit Gateway Network Manager to provide us with network visibility across our Transit Gateway, so we can monitor our network more easily.

**Comment by davidkelliott** [comment]
This is enabled for the transit gateway.  Monitoring for TGW is covered in [#1836](https://github.com/ministryofjustice/modernisation-platform/issues/1836)
