### ISSUE TITLE
nomis-data-hub

### ISSUE THREAD

**Issue by crvgilbertson** [ministryofjustice/modernisation-platform#3132]
### Application Name

nomis-data-hub

### Description of application

Nomis-data-hub is the legacy interface solution to facilitate data exchange between nomis, oasys and ndelius. Also produces critical data extracts (ie offloc) for internal (ie mercury) and external consumers (ie police)

### GitHub team slug

studio-webops

### Environments

Development | Sandbox

Test | Developer

PreProduction | Developer

Production | Developer

### Tags

tag | value
--- | ---
application | nomis-data-hub
business-unit | HMPPS
owner | digital-studio-operations-team@digital.justice.gov.uk

### Subnet sets

- [X] General - this application will use the same subnet as other applications in your business unit
- [ ] Isolated - this application has highly sensitive data which must have its own isolated subnet with no network connectivity

### How do users connect to the application?

- [ ] Over the public internet
- [ ] With a purple cabled device (please give details)
- [X] With a MoJ Official device

## Additional features

- [ ] Additional VPC Endpoints
- [ ] Extended DNS Zones
- [ ] Other - please specify

## Definition of done

- [x] account created
- [x] customer informed

**Comment by SteveLinden** [comment]
Email sent to the above address stating the environments have been created. Asked them to raise any calls or issues on the ask channel
