### ISSUE TITLE
Implement new linter across Modernisation Platform repositories

### ISSUE THREAD

**Issue by dms1981** [ministryofjustice/modernisation-platform#3147]
## User Story

As a Modernisation Platform Engineer 
I want to implement the new code formatting approach across our repositories
So that our linting standards are applied across all of our code consistently. 

## Value

As part of https://github.com/ministryofjustice/modernisation-platform/issues/2259 we replaced the code-formatter job that ran when pull requests were raised with a nightly job that ran a linter against our code and provided a pull request if/when changes were found following a run of the linter.

This card will cover the addition of this task into our other repositories

## Questions / Assumptions / Hypothesis

Do we want to supplement the code formatter with this new action, or replace it?

## Definition of done

- [ ] new code formatter applied across mp repositories

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

[https://github.com/ministryofjustice/modernisation-platform/issues/2259](https://github.com/ministryofjustice/modernisation-platform/issues/2259)

**Comment by SimonPPledger** [comment]
@davidkelliott do you agree that we need this for all repositories, too?

**Comment by SimonPPledger** [comment]
Not required for other repositories
