### ISSUE TITLE
Add a GitHub action to automatically complete Dependabot PRs

### ISSUE THREAD

**Issue by dms1981** [ministryofjustice/modernisation-platform#3176]
## User Story

As a Modernisation Platform Engineer 
I want to reduce the amount of Dependabot PRs we need to approve
So that we can focus on the Dependabot PRs that are important 

## User Type(s)

Modernisation Platform Engineer

## Value

The value of this story is twofold. First, we have an increasing number of Dependabot PRs being raised that will only increase now that we are including code scanning as part of our standard workflow. Second, with large numbers of Dependabot PRs we reduce the amount of scrutiny each PR gets.

By automatically approving simple Dependabot PRs - such as updates to `checkov` / `tfsec` / `tflint` - we can more quickly keep our dependencies up to date without engaging engineer time. Assuming that our existing checks on a pull request being raised are sufficient, then there are cases where we can trust a Dependabot PR to be merged in with minimal impact even if it later needs to be reverted.

### Hypothesis 
If we automate the approval of chores
Then we can focus on the things that matter

## Definition of done

- [ ] decision made on which PRs to include
- [ ] GitHub action written and tested
- [ ] GitHub action rolled out across MP repositories
- [ ] tests are green

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)
[Auto-merge Dependabot PR](https://remarkablemark.org/blog/2022/11/18/dependabot-auto-merge-pull-request/)

**Comment by SimonPPledger** [comment]
no longer required now we have the merger tooling
