### ISSUE TITLE
New EBS Development Sandbox environment For Testing EBS SSO Authentication

### ISSUE THREAD

**Issue by keith-h** [ministryofjustice/modernisation-platform#3180]
### Application Name
laa-ccms-infra-azure-ad-sso

### Description of application
We require this account so that we can spin up a test EBS instance in order to test the [laa-ccms-ebs-azure-ad] app which is hosted on Cloud Platform 

### GitHub team slug
[LAA CCMS Devs](https://github.com/orgs/ministryofjustice/teams/laa-ccms-devs)

### Environments

| Environment 		| Access level |
| --- 				| --- |
|<ul><li>[x] Development</li></ul>	| <ul><li>[ ] view-only</li><li>[ ] developer</li><li>[x] sandbox</li></ul> |
|<ul><li>[ ] Test</li></ul>			| <ul><li>[ ] view-only</li><li>[ ] developer</li></ul> |
|<ul><li>[ ] Preproduction</li></ul>| <ul><li>[ ] view-only</li><li>[ ] developer</li></ul> |
|<ul><li>[ ] Production</li></ul>	| <ul><li>[ ] view-only</li><li>[ ] developer</li></ul> |

### Tags

tag | value
--- | ---
application | laa-ccms-infra-azure-ad-sso
business-unit | LAA
owner | donovan.artz@digital.justice.gov.uk

### Subnet sets

- [x] General - this application will use the same subnet as other applications in your business unit
- [ ] Isolated - this application has highly sensitive data which must have its own isolated subnet with no network connectivity

### How do users connect to the application?

- [x] Over the public internet
- [x] With a purple cabled device (please give details)
- [x] With a MoJ Official device

## Additional features

- [ ] Additional VPC Endpoints
- [ ] Extended DNS Zones
- [ ] Other - please specify

## Definition of done

- [ ] account created
- [ ] customer informed

**Comment by davidkelliott** [comment]
Hi @keith-h do you have some more information about this application please, I had a quick look at the repo and it looks like it's hosted in Docker so would be a better fit for the Cloud Platform

**Comment by keith-h** [comment]
Hi @davidkelliott I'll get a diagram for you so you can see why we want to build it in MP.

**Comment by keith-h** [comment]
I've been discussing this with @rajindersinghsandhu and we agree that the app itself would be a better fit for the Cloud Platform.  However, we do need an account on MP in which we will be deploying a vanilla instance of EBS in order to create spikes and test cross-platform connectivity between the app and EBS
