### ISSUE TITLE
New development/test environments for LAA CCMS OEM migration

### ISSUE THREAD

**Issue by rajindersinghsandhu** [ministryofjustice/modernisation-platform#3187]
### Application Name
laa-oem

### Description of application
All the LAA Oracle products such as Database, Weblogic , SOA,PUI, EBS,  are monitored using OEM

### GitHub team slug
[laa-ccms-migration-team](https://github.com/orgs/ministryofjustice/teams/laa-ccms-migration-team)

### Environments

| Environment 		| Access level |
| --- 				| --- |
|<ul><li>[X] Development</li></ul>	| <ul><li>[ ] view-only</li><li>[ ] developer</li><li>[X] sandbox</li></ul> |
|<ul><li>[X] Test</li></ul>			| <ul><li>[ ] view-only</li><li>[X] developer</li></ul> |
|<ul><li>[ ] Preproduction</li></ul>| <ul><li>[ ] view-only</li><li>[ ] developer</li></ul> |
|<ul><li>[ ] Production</li></ul>	| <ul><li>[ ] view-only</li><li>[ ] developer</li></ul> |

### Tags

tag | value
--- | ---
application | laa-oem
business-unit | LAA
infrastructure-support | donovan.artz@digital.justice.gov.uk
owner | [donovan.artz@digital.justice.gov.uk](mailto:donovan.artz@digital.justice.gov.uk)

### Subnet sets

- [X] General - this application will use the same subnet as other applications in your business unit
- [ ] Isolated - this application has highly sensitive data which must have its own isolated subnet with no network connectivity

### How do users connect to the application?

- [x] Over the public internet
- [ ] With a purple cabled device (please give details)
- [X] With a MoJ Official device

## Additional features

- [ ] Additional VPC Endpoints
- [ ] Extended DNS Zones
- [X] Other - Connectivity to existing Landing zone and MP ccms-ebs , dev and test accounts

## Definition of done

- [ ] account created
- [ ] customer informed

**Comment by SteveLinden** [comment]
Completed. Checked and the subnets are all in place.
