### ISSUE TITLE
DPR TEST Environment Request

### ISSUE THREAD

**Issue by harichintala1** [ministryofjustice/modernisation-platform#3252]
### GitHub team slug

hmpps-digital-prison-reporting 
https://github.com/ministryofjustice/modernisation-platform-environments/tree/main/terraform/environments/digital-prison-reporting

### Environments

- [x] TEST

### Tags

tag | value
--- | ---
application | digital-prison-reporting
business-unit | HMPPS
owner | digitalprisonreporting@digital.justice.gov.uk

#### Subnet sets

- [x] General - this application will use the same subnet as other applications in your business unit
- [ ] Isolated - this application has highly sensitive data which must have its own isolated subnet

#### How do users connect to the application?

- [ ] Over the public internet
- [x] With a purple cabled device (please give details)
- [ ] With a MoJ Official device

#### Connectivity to other applications or external parties

* Analytical Platform (Oracle)
* Ports: 1521, 443, 5432

## Additional features

- [ ] Additional VPC Endpoints
- [ ] Extended DNS Zones
- [ ] Other - please specify

## Other information

We will need access to Legacy Nomis Platform for Data Ingestion

**Comment by markgov** [comment]
PR for the new account https://github.com/ministryofjustice/modernisation-platform/pull/3315
