### ISSUE TITLE
Find out where the timeout is located that affected AP extract

### ISSUE THREAD

**Issue by seanprivett** [ministryofjustice/modernisation-platform#3269]
All details are provided in this thread: https://mojdt.slack.com/archives/C01A7QK5VM1/p1677238956382549

The NOMIS team have put in a workaround, but this is likely to trip up future customers

Likelihood is that this is baked in to AWS and we may not be able to configure it. If so, verify and produce some documentation.

**Comment by dms1981** [comment]
This was traced back to how AWS expects TCP connections to be utilised, and how the database differed in its expectations of long-running TCP connections. A way to configure keepalives was provided and implemented as there was no AWS option we could configure.
