### ISSUE TITLE
Complete production ready checklist for PPUD

### ISSUE THREAD

**Issue by davidkelliott** [ministryofjustice/modernisation-platform#3272]
## User Story

Prior to PPUD going live in production complete the following checklist:

https://user-guide.modernisation-platform.service.justice.gov.uk/user-guide/production-ready-checklist.html

## User Type(s)

MP engineers

## Value

Ensure code quality and security of the platform

## Definition of done

- [x] checklist complete
- [ ] another team member has reviewed

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by ep-93** [comment]
1. For public facing interfaces - [Create DDoS alarms, enable SRT access, enable Layer 7 Mitigation for ELBs](https://user-guide.modernisation-platform.service.justice.gov.uk/runbooks/enabling-shield-advanced.html).
2. All EC2 instances have the AWS Systems Manage Session Manager [SSM Agent](https://docs.aws.amazon.com/systems-manager/latest/userguide/ssm-agent.html) installed.
3. Infrastructure code has been reviewed and signed off by a Modernisation Platform engineer.
4. The application runbook (README.md` in the application folder in the [modernisation-platform-environments repository](https://github.com/ministryofjustice/modernisation-platform-environments/tree/main/terraform/environments)) has been completed.
5. The application conforms to the [MoJ Technical Guidance](https://technical-guidance.service.justice.gov.uk/) and [MoJ Security Guidance](https://security-guidance.service.justice.gov.uk/)
6. The application has been tested.
7. Appropriate application monitoring and logging is in place.
8. There is an application support team in place and their contact details are in the application runbook.
9. The Modernisation Platform team are aware of any cutover/migration dates/times and have agreed additional cover if required.

**Comment by ep-93** [comment]
**_Outstanding Work_**

- Remove Jump Server before go live date.
- Update README with contact details as well as other parts.
- Confirm go live date does not change. 
- Runbook creation is in process for Lumen support guys, however I have requested it be shared with Mod Platform also. This needs to be there for support.
- Naming convention isn’t for me. Not sure this is anything to change, what do the team think?
- Service support documentation to be created following https://technical-guidance.service.justice.gov.uk/ 
- Need to run through this a few weeks after go live - https://github.com/ministryofjustice/modernisation-platform/issues/3690

**Comment by ep-93** [comment]
Go live date moved to end of month.

**Comment by SimonPPledger** [comment]
Asked Mark Hardy to update read.me

**Comment by dms1981** [comment]
I'll take over on this from @ep-93
