### ISSUE TITLE
Add firewall rule requirements to new environment template

### ISSUE THREAD

**Issue by seanprivett** [ministryofjustice/modernisation-platform#3274]
When customers use our [New Modernisation Platform Environment](https://github.com/ministryofjustice/modernisation-platform/blob/main/.github/ISSUE_TEMPLATE/new-environment.md) template, we would like them to supply any firewall rules necessary to allow communication with other internal MoJ applications.

These rules should not allow customers to circumvent good practice on the Modernisation Platform (eg, unneccesarily opening up SSH access to manage instances where a bastion or SSM access should be used), but should prevent us from having to go back-and-forth to get all the rules needed for internal connectivity.

**Comment by ewastempel** [comment]
This has been implemented with https://github.com/ministryofjustice/modernisation-platform/pull/3354

This is done now.
