### ISSUE TITLE
SPIKE: X11 forwarding over SSM Session Manager to EC2s

### ISSUE THREAD

**Issue by davidkelliott** [ministryofjustice/modernisation-platform#3275]
## User Story

As a user of MP
I want to use X11 forwarding
To run GUI installers on EC2s

## User Type(s)

MP Users

## Value

Establish a pattern for users doing legacy installs.

### Proposal

Spike to find out if this is possible, if it is then document how to do it.

## Definition of done

- [ ] establish if X11 forwarding is possible
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] tests are green
- [ ] UR test OR added to continual research plan

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by dms1981** [comment]
https://aws.amazon.com/blogs/compute/how-to-enable-x11-forwarding-from-red-hat-enterprise-linux-rhel-amazon-linux-suse-linux-ubuntu-server-to-support-gui-based-installations-from-amazon-ec2/

**Comment by dms1981** [comment]
Further to this, it looks like it's quite possible to forward X11 over SSH through SSM - https://github.com/aws/session-manager-plugin/issues/66

**Comment by SimonPPledger** [comment]
see the above link explaining how to do this
