### ISSUE TITLE
Rename data "aws_subnets" "private-public" in platform_data.tf

### ISSUE THREAD

**Issue by davidkelliott** [ministryofjustice/modernisation-platform#3276]
## User Story

Rename data "aws_subnets" "private-public" in platform_data.tf

https://github.com/ministryofjustice/modernisation-platform/blob/main/terraform/templates/platform_data.tf#L23

This is currently - 

`data "aws_subnets" "private-public"`

It should be:

`data "aws_subnets" "shared-private`

This needs to be changed in the templates files and then refactored throughout all the repos and where it is referenced.

## Value

Accurate naming of things reduces the chances of errors

## Definition of done

- [x] rename data source
- [x] refactor mp repo
- [x] refactor environments repo
- [x] another team member has reviewed
- [x] tests are green

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by SteveLinden** [comment]
Code amended in PR https://github.com/ministryofjustice/modernisation-platform-environments/pull/2120 got modernisation-platform-environments and https://github.com/ministryofjustice/modernisation-platform/pull/3777 got modernisation-platform. Not the latter of these only has one file change.
