### ISSUE TITLE
Create further OAS environments

### ISSUE THREAD

**Issue by dms1981** [ministryofjustice/modernisation-platform#3279]
### Application Name

oas

### Description of application

This is for the remaining environments of the LAA's "OAS" application that we will be migrating from other AWS accounts to MP.

Oracle Analytic Services that replaced OBIEE. The components are:
EC2 running the Oracle software
RDS database
There are hooks back to portal for user authorisation plus dblinks to apex, cis etc.

Current infra - https://github.com/ministryofjustice/laa-oas-upgrade

### GitHub team slug

laa-aws-infrastructure

### Environments

| Environment   | Access level |
| ---     | --- |
|<ul><li>[ ] Development</li></ul> | <ul><li>[ ] view-only</li><li>[ ] developer</li><li>[ ] sandbox</li></ul> |
|<ul><li>[x] Test</li></ul>   | <ul><li>[ ] view-only</li><li>[ ] developer</li></ul> |
|<ul><li>[x] Preproduction</li></ul>| <ul><li>[ ] view-only</li><li>[ ] developer</li></ul> |
|<ul><li>[x] Production</li></ul> | <ul><li>[ ] view-only</li><li>[ ] developer</li></ul> |

### Tags

tag | value
--- | ---
application | OAS
business-unit |  LAA
infrastructure-support | aws-webops-laa@digital.justice.gov.uk
owner | get-acccess-service-improvement@digital.justice.gov.uk

### Subnet sets

- [x] General - this application will use the same subnet as other applications in your business unit
- [ ] Isolated - this application has highly sensitive data which must have its own isolated subnet with no network connectivity

### How do users connect to the application?

- [ ] Over the public internet
- [ ] With a purple cabled device (please give details)
- [ ] With a MoJ Official device
- [x] Via other existing AWS account

## Additional features

- [ ] Additional VPC Endpoints
- [ ] Extended DNS Zones
- [ ] Other - please specify

## Definition of done

- [ ] account created
- [ ] customer informed

**Comment by dms1981** [comment]
Original development request here - https://github.com/ministryofjustice/modernisation-platform/issues/2787

Looks like this was amended after the development environment was created?

**Comment by SteveLinden** [comment]
Emailed the above addresses.
