### ISSUE TITLE
Portal AWS accounts in MP for Ops team

### ISSUE THREAD

**Issue by alanrana7** [ministryofjustice/modernisation-platform#3287]
### Application Name

portal

### Description of application

The LAA Online Portal (Portal) is the Identity and Access Management (IDAM) solution for the LAA. Portal is the gateway to most LAA applications for external and internal users. 

Some key components for the portal application includes:

- Few EC2 instances running oracle softwares 
- RDS (Oracle)
- Front end Java applications
- WAF/Cloudfront (Have to be connected to the MoJ VPN to access Portal login page in the non-prod evnvironments)

Current Infrastructure Repo in LAA Landing Zone: https://github.com/ministryofjustice/laa-portal 

### GitHub team slug
laa-aws-infrastructure

### Environments

| Environment   | Access level |
| ---     | --- |
|<ul><li>[x] Development</li></ul> | <ul><li>[ ] view-only</li><li>[x] developer</li><li>[ ] sandbox</li></ul> |
|<ul><li>[x] Test</li></ul>   | <ul><li>[ ] view-only</li><li>[x] developer</li></ul> |
|<ul><li>[x] Preproduction</li></ul>| <ul><li>[ ] view-only</li><li>[x] developer</li></ul> |
|<ul><li>[x] Production</li></ul> | <ul><li>[ ] view-only</li><li>[x] developer</li></ul> |

### Tags

tag | value
--- | ---
application | Portal
business-unit | LAA
owner | LAA

### Subnet sets

- [x] General - this application will use the same subnet as other applications in your business unit
- [ ] Isolated - this application has highly sensitive data which must have its own isolated subnet with no network connectivity

### How do users connect to the application?

- [x] Over the public internet (For production)
- [ ] With a purple cabled device (please give details)
- [x] With a MoJ Official device
- [x] Via other existing AWS account

### Connectivity to other applications or external parties

Portal is the gateway to other applications, so majority of the applications will need to be connected. Currently in the MP we have MLRA and OAS infrastructure deployed in the development environment. Those will need to have relevant connectivity to Portal. 

Will need to be connected to the Transit Gateway for connectivity with LAA LandingZone.

(Unsure about external parties for now)

## Additional features

- [ ] Additional VPC Endpoints
- [ ] Extended DNS Zones
- [ ] Other - please specify

## Definition of done

- [x] account created
- [x] customer informed

**Comment by SteveLinden** [comment]
Email sent the the address above
