### ISSUE TITLE
Use terraform-docs to generate module documentation

### ISSUE THREAD

**Issue by jakemulley** [ministryofjustice/modernisation-platform#329]
We should use [terraform-docs](https://github.com/terraform-docs/terraform-docs) to generate our module documentation so we can define it in code and create a human-readable version from that, to reduce duplication in copying information from code to markdown.

**Comment by jakemulley** [comment]
See the [sample output](https://github.com/ministryofjustice/modernisation-platform/pull/380/files) of terraform-docs for the VPC Hub module.

**Comment by davidkelliott** [comment]
Need to document the process plus add the documentation to the existing core and member modules.
