### ISSUE TITLE
SPIKE: Create collaborator users as SSO users

### ISSUE THREAD

**Issue by davidkelliott** [ministryofjustice/modernisation-platform#3305]
## User Story

We current have IAM users (collaborators) and SSO users (moj github users).  What if instead of using IAM users, we created SSO users directly in Terraform (rather than the GitHub sync which happens for normal users).  This would simplify our policies and provide a more consistent user experience between collaborators and MoJ users. This would also help for some things which rely on SSO such as fleet manager.  (see original slack thread where this issue can up https://mojdt.slack.com/archives/C01A7QK5VM1/p1678114589293019)

## User Type(s)

MP collaborators

## Value

More consistent user experience.

## Assumptions / Hypothesis / Questions / Unknowns

Do not know if this is possible or sensible, the spike will determine this.

## Definition of done

- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] tests are green
- [ ] UR test OR added to continual research plan

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by SimonPPledger** [comment]
Will need Dave to provide some pointers

**Comment by SimonPPledger** [comment]
We don't see how this is possible - without anything to authenticate this
