### ISSUE TITLE
Bastion tidy-up after XP incident

### ISSUE THREAD

**Issue by seanprivett** [ministryofjustice/modernisation-platform#3307]
Ensure that users can alter ASGs so that if a bastion is scaled down, they can scale it back to 1 out of hours

A/C 

tested in one of our MP test accounts 
documented in our user guidance
communicated to XP and wider users
tested by XP that they can do this

**Comment by SteveLinden** [comment]
Amended the documentation to indicate what needs to be changed.
Need to test to make sure it's available to users.

**Comment by SteveLinden** [comment]
Amended instructions change approved and applied. Also sent a slack message to the update channel.

**Comment by SteveLinden** [comment]
Still waiting for confirmation that users can do this themselves. Out developer account might be slightly different to the one users have. Once I have confirmation I will close this call.

**Comment by SteveLinden** [comment]
Had confirmation that it works.
