### ISSUE TITLE
Move from tfsec to trivy

### ISSUE THREAD

**Issue by davidkelliott** [ministryofjustice/modernisation-platform#3336]
## User Story

As a Modernisation Platform Engineer
I want to migrate from tfsec to trivy
So that we continue to benefit from up-to-date secure code analysis

trivy is now being favoured over tfsec, they are still using the same base rules so this isn't urgent but we should still change at some point.
https://github.com/aquasecurity/tfsec/blob/master/docs/guides/trivy.md

## User Type(s)

Modernisation Platform Engineer

## Value

The migration from tfsec to trivy is discussed [here](https://github.com/aquasecurity/tfsec/discussions/1994).
Trivy is now being favoured over tfsec. While they are still using the same base rules this isn't urgent but we should change to ensure we stay in line with the most up-to-date tooling, and prevent the need to urgently change should tfsec be fully deprecated.

## Definition of done

- [x] references to tfsec actions in `Modernisation Platform` repositories updated
- [x] `ministryofjustice/github-actions/terraform-static-analysis` tool updated
- [x] another team member has reviewed
- [x] tests are green
- [ ] create issues to replicate in other MP environments

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)
[Moving towards configuration scanning with Trivy](https://github.com/aquasecurity/tfsec/blob/master/docs/guides/trivy.md)

**Comment by SimonPPledger** [comment]
currently not urgent, but this might change. Though only for code formatting

**Comment by markgov** [comment]
created code for trivy and tested it on a personl repo and found to be working going to add code to the modernisation platform repo via a pr shortly

**Comment by markgov** [comment]
https://github.com/ministryofjustice/modernisation-platform/pull/5938

**Comment by markgov** [comment]
https://github.com/ministryofjustice/modernisation-platform/pull/5978

**Comment by markgov** [comment]
This is now complete new issue raised to do all other mod platform repos
