### ISSUE TITLE
Change to new code formatting workflow in environments repo

### ISSUE THREAD

**Issue by davidkelliott** [ministryofjustice/modernisation-platform#3396]
## User Story

Change to new code formatting workflow in environments repo

Implement this action from the modernisation-platform repository: https://github.com/ministryofjustice/modernisation-platform/blob/main/.github/workflows/format-code.yml

This change in approach was the agreed fix from this issue in the environments repo https://github.com/ministryofjustice/modernisation-platform/issues/2259

## Definition of done

- [x] replace format-code.yml workflow
- [ ] confirm successful run
- [ ] another team member has reviewed

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by dms1981** [comment]
Raised https://github.com/ministryofjustice/modernisation-platform-environments/pull/1814 to cover this

**Comment by davidkelliott** [comment]
Need to remove megalinter reports

**Comment by davidkelliott** [comment]
https://github.com/ministryofjustice/modernisation-platform-environments/pull/1845
https://github.com/ministryofjustice/modernisation-platform/pull/3549
