### ISSUE TITLE
Sort out S3 bucket breaking changes

### ISSUE THREAD

**Issue by davidkelliott** [ministryofjustice/modernisation-platform#3397]
## User Story

There were breaking changes in the S3 buckets latest release, we need to either document this and let users know what to do and create a new breaking changes release, or update users code ourselves and amend so that the buckets work.

## Definition of done

- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] tests are green
- [ ] UR test OR added to continual research plan

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by dms1981** [comment]
This one needs refining; it's not clear where these breaking changes were observed, or which release of the s3 bucket module introduced these breaking changes. Also the definition of done needs updating to reflect the requirements for completion of this ticket.

**Comment by davidkelliott** [comment]
Introduction of the breaking change:
https://github.com/ministryofjustice/modernisation-platform-terraform-s3-bucket/compare/v6.2.0...v6.3.0
Broke for users here:
https://github.com/ministryofjustice/modernisation-platform-terraform-s3-bucket/pull/42/files

**Comment by dms1981** [comment]
I remember this one now! It was the removal of the `versioning_enabled_on_replication_bucket` that caused the break.
