### ISSUE TITLE
New IAM role for running Ansible in a Github Action via SSM.

### ISSUE THREAD

**Issue by ep-93** [ministryofjustice/modernisation-platform#3407]
Request - https://mojdt.slack.com/archives/C01A7QK5VM1/p1678789323337849 

## User Story

As a mod platform user i want to be able to run ansible in a github action runner via SSM so that we can apply configuration changes after instances are provisioned and throughout their lifecycle.

## Value

Requested so that that the same process can be used for windows and linux instances.

### Unknowns

The full list of permissions are not known, but definitely 

ec2:DescribeInstances
ssm:StartSession

and some s3 permissions 

## Definition of done

- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] tests are green
- [ ] UR test OR added to continual research plan

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by seanprivett** [comment]
Arrange follow up with Jon to understand this process more @seanprivett

**Comment by SimonPPledger** [comment]
@davidkelliott is this solved by your ADR on ???

**Comment by SimonPPledger** [comment]
do we still need this?

**Comment by ep-93** [comment]
I'll chase this up to see if it is still required, also https://github.com/ministryofjustice/modernisation-platform/issues/3935
