### ISSUE TITLE
Automate deployment of core-network-services

### ISSUE THREAD

**Issue by donmasters** [ministryofjustice/modernisation-platform#342]
**Task**
Configure automation of Terraform task using GitHub Actions for deployment of core-network-services. Ensure the task has manually checked gates to verify the Terraform Apply actions.

**Reason**
Automation of core system builds is required to ensure builds are both centrally managed and repeatable.

**DOD**
- Automation of core-network-services using Github actions
- Manual checks have been implemented to verify actions to be carried out

**Comment by donmasters** [comment]
Update:
- terraform plan summary has now been exported to PR

**Comment by donmasters** [comment]
This task has been completed using automated Terratest testing that is triggered from raising a PR.
After a PR has been commited, comments are added to the PR giving the results of the TerraTest and Terraform Plan outcome

**Comment by jakemulley** [comment]
🎉
