### ISSUE TITLE
Automation to provide info for new onboarders

### ISSUE THREAD

**Issue by davidkelliott** [ministryofjustice/modernisation-platform#3451]
## User Story

When a new environment issue has been closed, I want the person raising the issue to be tagged and provided with the following information:

> Welcome to the Modernisation Platform! Your new accounts have now been created.  Please see the user guidance for details on how to build and access infrastructure in the Modernisation Platform - https://user-guide.modernisation-platform.service.justice.gov.uk/#getting-started
>
> If you need any help or assistance please contact us in the [#ask-modernisation-platform](https://mojdt.slack.com/archives/C01A7QK5VM1)

## Value

Provide essential information to users in an automated fashion
## Definition of done

- [x] automation added
- [x] another team member has reviewed
- [x] tests are green
- [ ] UR test OR added to continual research plan

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by SimonPPledger** [comment]
where does this get raised? Which github repo?

**Comment by SteveLinden** [comment]
Discussed with Dave Elliott and this will be set up so it runs once the issue is closed.

**Comment by SteveLinden** [comment]
Sample yaml code created. Testing will require a temporary call that we can close to ensure it works

**Comment by SteveLinden** [comment]
Failed lots of times with a useless message. Appears to be part of the code where it can't find details. Working on it

**Comment by SteveLinden** [comment]
The code now sends a note to the call (see #5640 for details). No email is sent but we are limited in what we can get from github to progress this

**Comment by SteveLinden** [comment]
Result is approved. If needed we can manually email the details to the customer
