### ISSUE TITLE
Switch to shared workflows

### ISSUE THREAD

**Issue by davidkelliott** [ministryofjustice/modernisation-platform#3452]
## User Story

Nomis have been trialing reusable workflows - https://github.com/ministryofjustice/modernisation-platform-environments/pull/1482, test these new workflows on MP applications and if there are no issues switch all applications to these.

## User Type(s)

MP users

## Value

Cleans up workflow code, dries it out and adds new features

## Definition of done

- [x] switch MP apps to new workflows and test
- [x] switch user apps to new workflows
- [x] let users know about the changes
- [x] user docs have been updated
- [x] another team member has reviewed

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by ewastempel** [comment]
This has been implemented and documented with the PR links attached.
The update channel received a post on the changes.

This is done now.
