### ISSUE TITLE
New "open" kms key for the modernisation-platform-software bucket

### ISSUE THREAD

**Issue by SteveLinden** [ministryofjustice/modernisation-platform#3468]
New more open KMS key needed for the software bucket. User Vincent Cheung was getting an error stating it did not exist or he wasn't allowed access

**Comment by SteveLinden** [comment]
Error user received was 

[root@ip-10-26-57-175 bin]# aws s3 cp s3://modernisation-platform-software20230224000709766100000001/laa-platform/cloudwatch-agent-config/config.json /opt/aws/amazon-cloudwatch-agent/bin/.
download failed: s3://modernisation-platform-software20230224000709766100000001/laa-platform/cloudwatch-agent-config/config.json to ../../opt/aws/amazon-cloudwatch-agent/bin/config.json An error occurred (AccessDenied) when calling the GetObject operation: The ciphertext refers to a customer master key that does not exist, does not exist in this region, or you are not allowed to access.

**Comment by davidkelliott** [comment]
Can be closed as they can use an existing shared key
