### ISSUE TITLE
BUG: Some Modernisation Platform customers cannot send emails to on-call inbox

### ISSUE THREAD

**Issue by dms1981** [ministryofjustice/modernisation-platform#3513]
## Expected Behavior

Modernisation Platform customers who need on-call support should be able to send emails to our on-call inbox (contact-on-call-modernisation-platform@digital.justice.gov.uk)

## Actual Behavior

External parties without `digital.justice.gov.uk` email addresses receive an `email cannot be delivered` response when sending emails to this inbox. Specifically customers from ROC Technologies, although it is likely that other 3rd party customers may be affected.

This behaviour was witnessed with a recent on-call event, when a customer was not able to start an EC2 instance successfully and was unable to escalate this to us through our documented process.

## Steps to Reproduce the Problem

  1. Attempt to send email to contact-on-call-modernisation-platform@digital.justice.gov.uk from a non-digital email
  2. Observe `failed delivery` email response

**Comment by davidkelliott** [comment]
Group settings changed to allow emails from external users.  There isn't an option for filtering though so we will have to reassess if too much spam comes through.
