### ISSUE TITLE
Request for New Mod Platform Accounts for LAA MoJ Finance Database Migration

### ISSUE THREAD

**Issue by mikereiddigital** [ministryofjustice/modernisation-platform#3537]
## Environment details

This request covers all four accounts required for the migration of the LAA's MOJ Finance database.

### Application Name

MOJFIN

### Description of application

This is an Oracle RDS database that contains data pulled from CCMS, CIS etc that is used for reporting purposes by the MoJ Finance team.

### GitHub team slug

LAA AWS infrastructure

### Environments

| Environment   | Access level |
| ---     | --- |
|<ul><li>[x] Development</li></ul> | <ul><li>[ ] view-only</li><li>[x] developer</li><li>[ ] sandbox</li></ul> |
|<ul><li>[x] Test</li></ul>   | <ul><li>[ ] view-only</li><li>[x] developer</li></ul> |
|<ul><li>[ ] Preproduction</li></ul>| <ul><li>[ ] view-only</li><li>[ ] developer</li></ul> |
|<ul><li>[x] Production</li></ul> | <ul><li>[ ] view-only</li><li>[x] developer</li></ul> |

### Tags

tag | value
--- | ---
application | mojfin
business-unit | LAA
infrastructure-support | aws-webops-laa@digital.justice.gov.uk
owner | william.moran@justice.gov.uk

### Subnet sets

- [x] General - this application will use the same subnet as other applications in your business unit
- [ ] Isolated - this application has highly sensitive data which must have its own isolated subnet with no network connectivity

### Firewall rules

    # e.g.
    "cp_to_mp_hmpps_test": {"
      "action": "PASS",
      "source_ip": "172.20.0.0/16",
      "destination_ip": "10.26.8.0/21",
      "destination_port": "443",
      "protocol": "TCP"
    },

### How do users connect to the application?

- [ ] Over the public internet
- [x] With a purple cabled device (please give details)
- [x] With a MoJ Official device

## Additional features

- [ ] Additional VPC Endpoints
- [ ] Extended DNS Zones
- [ ] Other - please specify

## Definition of done

- [x] account created
- [x] customer informed

**Comment by SteveLinden** [comment]
Environments are built. Were some issues due to changes in file locations due to another change that had been applied but this was resolved.

**Comment by SteveLinden** [comment]
Informed Will through email with access to the modernisation platform documentation and a link to the ask channel. The firewall rules are the same as we have for other LAA environments so I have suggested if more are needed he can ask us.

Also mentioned about using RDS and having to build those with the latest version of Oracle. If this isn't possible we may need to advise him (or LAA could) on building Oracle in an EC2.
