### ISSUE TITLE
Prevent users from creating OIDC providers in the environments repo

### ISSUE THREAD

**Issue by davidkelliott** [ministryofjustice/modernisation-platform#3542]
## User Story

As a mp user
I should not be allowed to create OIDC providers via the member pipeline
Because this would allow access via uncontrolled means

## Value

Improved security

## Definition of done

- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] tests are green
- [ ] UR test OR added to continual research plan

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by SimonPPledger** [comment]
@davidkelliott can you provide a bit more detail - and whether you know how to do this

**Comment by davidkelliott** [comment]
Just checked, this has already been done
