### ISSUE TITLE
Retire ECS module repository

### ISSUE THREAD

**Issue by seanprivett** [ministryofjustice/modernisation-platform#3543]
## User Story

The Mod Platform has an old ECS module. The only users of this module are the Performance Hub and our Example account. The module ECS code has already been moved to Perf Hub, so they now own that. This ticket is to remove the [ECS module](https://github.com/ministryofjustice/modernisation-platform-terraform-ecs) repo. This will break example, but there is another ticket to sort that.

## Definition of done

- [ ] archive in code? If not remove from state and archive manually
- [ ] readme has been updated to remove this as an available module
- [ ] another team member has reviewed
- [ ] module is no longer available on the platform
- [ ] UR test OR added to continual research plan

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by ewastempel** [comment]
The description has been updated to point to the repo that needs retiring (https://github.com/ministryofjustice/modernisation-platform-terraform-ecs)

**Comment by SteveLinden** [comment]
Need to confirm this. The code was run but failed. @davidkelliott did this run when you re-ran the workflow. There was a job that failed elsewhere that seemed to indicate it had been deleted.

**Comment by SteveLinden** [comment]
The PR @https://github.com/ministryofjustice/modernisation-platform/pull/3619 failed but it the workflow was manually run by Dave Elliott
