### ISSUE TITLE
Switch ECS module in example to new module

### ISSUE THREAD

**Issue by seanprivett** [ministryofjustice/modernisation-platform#3544]
## User Story

Review new ECS module
Deploy to example, which will involve removing the previous module
Test in example

https://github.com/ministryofjustice/modernisation-platform-terraform-ecs-cluster

## Definition of done

- [x] update example code to use the new module
- [ ] readme has been updated
- [x] user docs have been updated
- [ ] another team member has reviewed
- [ ] tests are green
- [ ] UR test OR added to continual research plan

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by markgov** [comment]
New Branch Created and started work on moving to the new ecs module

**Comment by markgov** [comment]
PR for New ECS
https://github.com/ministryofjustice/modernisation-platform-environments/pull/1910

**Comment by markgov** [comment]
PR Updated with working plan and apply

**Comment by markgov** [comment]
after looking at this a bit more it could be that there is nothing running on port 80 and that is why the status is unhealthily
