### ISSUE TITLE
SPIKE: Can users be given permissions to revoke KMS grants?

### ISSUE THREAD

**Issue by dms1981** [ministryofjustice/modernisation-platform#3550]
## User Story

As a Modernisation Platform Cutomer
I need to have the ability to revoke KMS grants
So that when I delete infrastructure I can do so successfully.

## Value

Following on from a [discussion in slack](https://mojdt.slack.com/archives/C01A7QK5VM1/p1680189455196879), can we look at how to potentially allow developers to revoke grants - or otherwise allow our CI/CD pipeline role to do so?

## Definition of done

- [x] spike has been timeboxed
- [ ] alternatives explored
- [ ] if time allows, solution implemented
- [x] otherwise, spike outcome documented

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by SteveLinden** [comment]
I have had a look through the documentation for AWS KMS keys and it appears that if we add the following to a KMS it will stop anyone, other than the owner, from being able to revoke grant options.

"Condition": {
    "Bool": {
      "kms:GrantIsForAWSResource": true
    }
  }

**Comment by SteveLinden** [comment]
I have, so far, been unable to test this but page suggests that this is the correct approach
https://docs.aws.amazon.com/kms/latest/developerguide/conditions-kms.html

**Comment by SteveLinden** [comment]
Finally, I have managed to get a snapshot copied from sprinkler to cooker. 
The KMS used on sprinkler was "sprinkler_ebs-encryption-key". On cooker it was available and copied to cooker using "ec2-key" which is set up in cooker and allows access for sprinkler. The one I created with the "ebs" KMS key on sprinkler will not copy using the "ec2-key" on cooker.

This is being slightly complicated by the fact that sprinkler and cooker have their own kms keys and are not using those created in core-shared-services.

Anyway, I still haven't been able to test the above but I am fairly sure that the code above will allow users to revoke grants on KMS that are only inside their environment/ID

**Comment by SteveLinden** [comment]
Just attempting a little more to see if I can revoke grants or adding the above prevents that

**Comment by SteveLinden** [comment]
We can add the revoke option but to prevent non-owning accounts from revoking all we would need the code above. I have been unable to test this with our current accounts so we may need to test it elsewhere.

**Comment by SteveLinden** [comment]
Example code to list grants
aws-vault exec core-shared-services -- aws kms list-grants --key-id arn:aws:kms:eu-west-2:374269020027:key/12984197-3371-4c21-8e43-a88a1581e691

**Comment by SteveLinden** [comment]
New request created {https://github.com/ministryofjustice/modernisation-platform/issues/3875)
