### ISSUE TITLE
Restrict firewall ranges to VPCs

### ISSUE THREAD

**Issue by davidkelliott** [ministryofjustice/modernisation-platform#3652]
## User Story

Some of our firewall cidr allow ranges are allow access to the whole of an environment, whilst this is fine for things like Global protect vpn, it shouldn't be the case for Azure or other department specific things.

For example - https://github.com/ministryofjustice/modernisation-platform/blob/main/terraform/environments/core-network-services/production_rules.json#L100

Also to rename the entries to ensure they meet our standard naming conventions

This is the list of DSO IPs
https://github.com/ministryofjustice/modernisation-platform-environments/tree/main/terraform/modules/ip_addresses

This is a list of MP CIDR ranges:
https://github.com/ministryofjustice/modernisation-platform/blob/main/cidr-allocation.md

## User Type(s)

MP users

## Value

Increased security preventing things accessing things it shouldn't

## Definition of done

- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] tests are green
- [ ] UR test OR added to continual research plan

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by markgov** [comment]
Made a start on amending the rules

**Comment by markgov** [comment]
https://github.com/ministryofjustice/modernisation-platform/pull/3688/
pr rasied

**Comment by markgov** [comment]
New PR created as base firewall change have been apply to main
https://github.com/ministryofjustice/modernisation-platform/pull/3720

**Comment by markgov** [comment]
PR Approved and applied
