### ISSUE TITLE
Amend DDoS load balancer settings for PPUD

### ISSUE THREAD

**Issue by SteveLinden** [ministryofjustice/modernisation-platform#3690]
For PPUD settings were created for DDoS on 21st April 2023. These were set to count but, assuming all is OK, they should be amended to block after 1-2 weeks as per 

_Once the configuration is complete, monitor the WAF metrics and Shield events for 1-2 weeks to ensure that there are no false positives with the new rules. Then return to the configuration, and change the “Count” to “Block” for the rate limit rule and for the automatic mitigation.
_
Follow the instruction in [here](https://user-guide.modernisation-platform.service.justice.gov.uk/runbooks/enabling-shield-advanced.html#enable-srt-access)

### Application Name
ppud

### Environments
development, 
preproduction
production

### How do users connect to the application?

- [ ] Over the public internet
- [ ] With a purple cabled device (please give details)
- [ ] With a MoJ Official device

## Definition of done

- [ ] account amended 
- [ ] customer informed

**Comment by SimonPPledger** [comment]
Will wait until PPUD goes live - and then runs for around 4 weeks to validate traffic

**Comment by SimonPPledger** [comment]
plan to go live 10th June - so go this is required for mid July-ish

**Comment by ep-93** [comment]
Done in prod.
