### ISSUE TITLE
Add the pre-production enmvironment to Tipstaff

### ISSUE THREAD

**Issue by matt-k1998** [ministryofjustice/modernisation-platform#3694]
### Application Name

Tipstaff

### Description of application

The Tipstaff office is responsible for acting on arrest warrants and child abduction orders. The office is responsible for executing orders for the removal of children from parents in domestic child abduction cases, including cases with an international element under the Hague convention and other provisions. In addition, the office is also responsible for the execution of High Court Warrants of Arrest and Warrants of Committal.

It is an .NET MVC solution hosted on SSG servers and is only accessible within the DOM1 domain.

The website allows the Tipstaff Office to record cases and generate standard letters.

### GitHub team slug

dts-heritage-services

### Environments

The Tipstaff environment already exsits in the modernisation platform and has a development and a production environment. I am creating this request to add a pre-production environment.

| Environment   | Access level |
| ---     | --- |
|<ul><li>[ ] Development</li></ul> | <ul><li>[ ] view-only</li><li>[ ] developer</li><li>[ ] sandbox</li></ul> |
|<ul><li>[ ] Test</li></ul>   | <ul><li>[ ] view-only</li><li>[ ] developer</li></ul> |
|<ul><li>[X] Preproduction</li></ul>| <ul><li>[ ] view-only</li><li>[X] developer</li></ul> |
|<ul><li>[ ] Production</li></ul> | <ul><li>[ ] view-only</li><li>[ ] developer</li></ul> |

### Tags

tag | value
--- | ---
application | Tipstaff
business-unit | HMCTS
infrastructure-support | dts-legacy-apps-support-team@hmcts.net
owner | dts-legacy-applications:dts-legacy-apps-support-team@hmcts.net

### Subnet sets

- [X] General - this application will use the same subnet as other applications in your business unit
- [ ] Isolated - this application has highly sensitive data which must have its own isolated subnet with no network connectivity

### How do users connect to the application?

- [X] Over the public internet
- [ ] With a purple cabled device (please give details)
- [X] With a MoJ Official device

## Additional features

- [ ] Additional VPC Endpoints
- [ ] Extended DNS Zones
- [ ] Other - please specify

## Definition of done

- [ ] account created
- [X] customer informed

**Comment by markgov** [comment]
New Environment PR created an merged

**Comment by markgov** [comment]
Ramshare PR raised
https://github.com/ministryofjustice/modernisation-platform/pull/3770
