### ISSUE TITLE
Documentation on how to contribute to the platform

### ISSUE THREAD

**Issue by davidkelliott** [ministryofjustice/modernisation-platform#3725]
## User Story

We need some documentation on how to contribute to the platform and our modules, best practices, testing etc.

## User Type(s)

MP Users and engineers

## Value

Allow people to contribute and add value to the platform.

## Assumptions / Hypothesis / Questions / Unknowns

[Setting guidelines for repository contributors](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/setting-guidelines-for-repository-contributors)

* We'll use `CONTRIBUTING.md` as the location to store this information
* We'll add a page to our user-guide to briefly detail this approach

## Definition of done

- [x] readme has been updated
- [x] user docs have been updated
- [x] another team member has reviewed
- [x] tests are green
- [ ] UR test OR added to continual research plan

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by SteveLinden** [comment]
@davidkelliott should the file be contributors.md or contributing.md (as suggested in the github documentation)? I've named it contributors,md but it can easily be changed.

**Comment by dms1981** [comment]
Go with `CONTRIBUTING.md` - I'll update the story.

**Comment by SteveLinden** [comment]
Most of the documentation I've written appears to relate to how people should code etc. rather than specifically relating to contributors. I need to look at it again and, maybe, rewrite it so it's just contributor related rather than aimed at general coders. Will be looking at this with David S today.
May be a major update later today.

**Comment by dms1981** [comment]
Steve and I rewrote the document. I raised a new PR here: https://github.com/ministryofjustice/modernisation-platform/pull/4125

**Comment by SteveLinden** [comment]
After many discussions a rewrite was suggested as the documentation I had written was too "everyday" user based not specifically related to contributors. This has now been approved in https://github.com/ministryofjustice/modernisation-platform/pull/4125 and merged into main. Complete!
