### ISSUE TITLE
Configure and publish external status page

### ISSUE THREAD

**Issue by davidkelliott** [ministryofjustice/modernisation-platform#3784]
## User Story

Once the external status page add on has been purchased, configure the external status page for MP use.

This should include a custom modernisation platform domain.

Let our users know about this page and add to documentation, pin to channels etc.

## Value

Give users access to live updates from incidents and the ability to subscribe to them without needing pagerduty accounts.

## Definition of done

- [x] configure pagerduty external status
- [x] create and configure custom domain
- [x] publicise the new page
- [x] readme has been updated
- [x] user docs have been updated
- [x] another team member has reviewed
- [x] tests are green
- [x] UR test OR added to continual research plan

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by markgov** [comment]
custom URL created and cnames added to core-network services

**Comment by markgov** [comment]
slack integration added to our ask channel and the mod platform channel

**Comment by markgov** [comment]
documentation completed
