### ISSUE TITLE
Complete production ready checklist for CCMS

### ISSUE THREAD

**Issue by SimonPPledger** [ministryofjustice/modernisation-platform#3801]
User Story
Prior to CCMS going live in production complete the following checklist:

https://user-guide.modernisation-platform.service.justice.gov.uk/user-guide/production-ready-checklist.html

User Type(s)
MP engineers

Value
Ensure code quality and security of the platform

Questions / Assumptions / Hypothesis
Definition of done
 checklist complete
 another team member has reviewed

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by davidkelliott** [comment]
https://mojdt.slack.com/archives/C0592BG1BMY/p1687163816906379
