### ISSUE TITLE
Establish latency between CP and MP by enabling ICMP connectivity

### ISSUE THREAD

**Issue by davidkelliott** [ministryofjustice/modernisation-platform#3822]
## User Story

As a Modernisation Platform Engineer
I want to establish ICMP connectivity between the Modernisation Platform and the Cloud Platform
So that I can measure latency between the two platforms

## User Type(s)

Modernisation Platform Engineer

## Value

There have been reports of latency between MP and CP, to establish this we need to enable ICMP connectivity between the 2 platforms so that we can use proper latency tools rather than timing TCP tools.

This story will cover any changes required to get ICMP traffic to & from the Cloud Platform which may involve the following:
* network ACLs
* firewall rules
* security group entries from example?

## Definition of done

- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] tests are green
- [ ] UR test OR added to continual research plan

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by kcbotsh** [comment]
@davidkelliott team would like more info/ refinement before accepting this story. We have 2 interpretations of what is required and need clarification
