### ISSUE TITLE
Allow developers to delete account-local ECR images.

### ISSUE THREAD

**Issue by dms1981** [ministryofjustice/modernisation-platform#3883]
## User Story

As a Modernisation Platform developer
I want to be able to manually delete ECR images in my account
So that I don't need to rely on MP engineers to do this for me
https://mojdt.slack.com/archives/C01A7QK5VM1/p1684324129674539
## User Type(s)

Modernisation Platform Customer

## Value

Customers who maintain ECR repositories in **their** accounts sometimes need to delete those images (specifically, `MLRA`). If we add the permission to delete ECR images to the `developer` role, customers will be able to delete images before tearing down a development account.

## Definition of done

- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] tests are green
- [ ] UR test OR added to continual research plan

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by ASTRobinson** [comment]
https://github.com/ministryofjustice/modernisation-platform/pull/4608
