### ISSUE TITLE
New hmpps-oem accounts

### ISSUE THREAD

**Issue by seanprivett** [ministryofjustice/modernisation-platform#3892]
## Environment details

DSO and Probation WebOps are combining their OEM (Oracle Enterprise Manager) setups so we have only 1 which monitors all Oracle databases across HMPPS. We'd like a separate account for this so it doesn't sit in, for example, the NOMIS account.

### Application Name

hmpps-oem

### Description of application
Oracle Enterprise Manager setup for monitoring and alerting of Oracle databases

### GitHub team slug
https://github.com/orgs/ministryofjustice/teams/studio-webops
https://github.com/orgs/ministryofjustice/teams/hmpps-migration

### Environments

| Environment   | Access level |
| ---     | --- |
|<ul><li>[x] Development</li></ul> | <ul><li>[ ] view-only</li><li>[ ] developer</li><li>[x] sandbox</li></ul> |
|<ul><li>[x] Test</li></ul>   | <ul><li>[ ] view-only</li><li>[x] developer</li></ul> |
|<ul><li>[x] Preproduction</li></ul>| <ul><li>[ ] view-only</li><li>[x] developer</li></ul> |
|<ul><li>[x] Production</li></ul> | <ul><li>[ ] view-only</li><li>[x] developer</li></ul> |

### Tags

tag | value
--- | ---
application | hmpps-oem
business-unit | HMPPS
infrastructure-support | digital-studio-operations-team@digital.justice.gov.uk
owner | digital-studio-operations-team@digital.justice.gov.uk, probation-webops@digital.justice.gov.uk

### Subnet sets

- [x] General - this application will use the same subnet as other applications in your business unit
- [ ] Isolated - this application has highly sensitive data which must have its own isolated subnet with no network connectivity

### Firewall rules

    # e.g.
    "cp_to_mp_hmpps_test": {"
      "action": "PASS",
      "source_ip": "172.20.0.0/16",
      "destination_ip": "10.26.8.0/21",
      "destination_port": "443",
      "protocol": "TCP"
    },

### How do users connect to the application?

- [ ] Over the public internet
- [x] With a purple cabled device (please give details)
- [ ] With a MoJ Official device

## Additional features

- [ ] Additional VPC Endpoints
- [ ] Extended DNS Zones
- [ ] Other - please specify

## Definition of done

- [x] account created
- [x] customer informed

**Comment by SimonPPledger** [comment]
Need clarification re infrastructure-support mail address - we only can have 1

**Comment by markgov** [comment]
Pr created for environments
https://github.com/ministryofjustice/modernisation-platform/pull/4114

**Comment by markgov** [comment]
New accounts created
