### ISSUE TITLE
New PlanetFME Accounts

### ISSUE THREAD

**Issue by drobinson-moj** [ministryofjustice/modernisation-platform#3908]
## Environment details

New accounts to support migration of PlanetFME from Azure to AWS

### Application Name

planetfme

### Description of application

Facilities management system for prisons.

### GitHub team slug

https://github.com/orgs/ministryofjustice/teams/studio-webops

### Environments

| Environment   | Access level |
| ---     | --- |
|<ul><li>[x] Development</li></ul> | <ul><li>[ ] view-only</li><li>[ ] developer</li><li>[x] sandbox</li></ul> |
|<ul><li>[x] Test</li></ul>   | <ul><li>[ ] view-only</li><li>[x] developer</li></ul> |
|<ul><li>[x] Preproduction</li></ul>| <ul><li>[ ] view-only</li><li>[x] developer</li></ul> |
|<ul><li>[x] Production</li></ul> | <ul><li>[ ] view-only</li><li>[x] developer</li></ul> |

### Tags

tag | value
--- | ---
application | planetfme
business-unit | HMPPS
infrastructure-support | digital-studio-operations-team@digital.justice.gov.uk
owner | david.forshaw@digital.justice.gov.uk

### Subnet sets

- [x] General - this application will use the same subnet as other applications in your business unit
- [ ] Isolated - this application has highly sensitive data which must have its own isolated subnet with no network connectivity

### Firewall rules

    # e.g.
    "cp_to_mp_hmpps_test": {"
      "action": "PASS",
      "source_ip": "172.20.0.0/16",
      "destination_ip": "10.26.8.0/21",
      "destination_port": "443",
      "protocol": "TCP"
    },

### How do users connect to the application?

- [ ] Over the public internet
- [ ] With a purple cabled device (please give details)
- [x] With a MoJ Official device

## Additional features

- [ ] Additional VPC Endpoints
- [ ] Extended DNS Zones
- [ ] Other - please specify

## Definition of done

- [x] account created
- [x] customer informed

**Comment by SimonPPledger** [comment]
@drobinson-moj should this be planetfme or planetfm? Also is there a group email address for owner, rather than an individual

**Comment by ewastempel** [comment]
Addressing comments in this [slack thread](https://mojdt.slack.com/archives/C966L8ZFY/p1685444568474099),
application name will be set to: planetfm
owner will be set to: digital-studio-operations-team@digital.justice.gov.uk
and nuke will be skipped

**Comment by ewastempel** [comment]
this is implemented now; awaiting confirmation by DSO that it is looking good

**Comment by ewastempel** [comment]
@jnq from DSO confirmed that it looks good


This is done now
