### ISSUE TITLE
DPR "PreProduction" Environment Request

### ISSUE THREAD

**Issue by harichintala1** [ministryofjustice/modernisation-platform#3911]
### GitHub team slug

hmpps-digital-prison-reporting 
https://github.com/ministryofjustice/modernisation-platform-environments/tree/main/terraform/environments/digital-prison-reporting

### Environments

- [x] **preproduction**

### Tags

tag | value
--- | ---
application | digital-prison-reporting
business-unit | HMPPS
owner | digitalprisonreporting@digital.justice.gov.uk

#### Subnet sets

- [x] General - this application will use the same subnet as other applications in your business unit
- [ ] Isolated - this application has highly sensitive data which must have its own isolated subnet

#### How do users connect to the application?

- [ ] Over the public internet
- [x] With a purple cabled device (please give details)
- [ ] With a MoJ Official device

#### Connectivity to other applications or external parties

* Analytical Platform (Oracle)
* Ports: 1521, 443, 5432

## Additional features

- [ ] Additional VPC Endpoints
- [ ] Extended DNS Zones
- [ ] Other - please specify

## Other information

We will need access to Legacy Nomis Platform for Data Ingestion

**Comment by ewastempel** [comment]
Implemented with:
https://github.com/ministryofjustice/modernisation-platform/pull/4059
https://github.com/ministryofjustice/modernisation-platform/pull/4062

The connectivity to NOMIS in azure and AP already exists:
https://github.com/ministryofjustice/modernisation-platform/blob/9b52129217b2ad28dc6c2c2239bdf68ac808605e/terraform/environments/core-network-services/firewall-rules/preproduction_rules.json#LL86C2-L86C2
[https://github.com/ministryofjustice/modernisation-platform/blob/9b52129217b2ad28d[…]s/core-network-services/firewall-rules/preproduction_rules.json](https://github.com/ministryofjustice/modernisation-platform/blob/9b52129217b2ad28dc6c2c2239bdf68ac808605e/terraform/environments/core-network-services/firewall-rules/preproduction_rules.json#L135)

@harichintala1 was informed about the account creation completion.

**Comment by ewastempel** [comment]
This is now done.
