### ISSUE TITLE
Allow Route53 query logging in cloudwatch

### ISSUE THREAD

**Issue by drobinson-moj** [ministryofjustice/modernisation-platform#3926]
## User Story

As a webops engineer
I need to capture Route53 query logs
So I can investigate Route53 queries when diagnosing incidents / security incidents.

## User Type(s)

WebOps Engineers

## Value

Security best practice.  Resolves checkov recommendation CKV2_AWS_39

## Assumptions / Hypothesis / Questions / Unknowns

See https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/query-logs.html
Attempting to create using us-east-1 provider results in following error 
```
Error: creating CloudWatch Logs Log Group (route53/development.nomis.service.justice.gov.uk): 
AccessDeniedException: User: arn:aws:sts::***:assumed-role/MemberInfrastructureAccessUSEast/aws-go-sdk-1684769053606027923 is not authorized to perform: logs:CreateLogGroup on resource: arn:aws:logs:us-east-1:***:log-group:route53/development.nomis.service.justice.gov.uk:log-stream: because no identity-based policy allows the logs:CreateLogGroup action
```
Allow `logs:*` or `CreateLogGroup,DeleteLogGroup,DescribeLogGroup,ListTagsLogGroups,TagLogGroup` in us-east-1 

## Definition of done

- [x] another team member has reviewed
- [x] tested route53 query logs can be created in us-east-1 using terraform us-east-1 member provider

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by markgov** [comment]
https://github.com/ministryofjustice/modernisation-platform/pull/4162

**Comment by markgov** [comment]
informed Dominic of the change and he is going to test
