### ISSUE TITLE
Restrict NACLs in VPC hub

### ISSUE THREAD

**Issue by davidkelliott** [ministryofjustice/modernisation-platform#3951]
## User Story

As a Modernisation Platform Engineer
I want to restrict the open NACL ports in the `vpc-hub` module
So that we reduce our potential attack surface

## User Type(s)

MP engineer

## Value

The NACLs in the VPC hub are overly permissive and we could restrict them further. Potentially to only 80, 443 and ephemeral port ranges.

Increase security of the platform

### Unknowns
There's a limit to the number of rules that can be applied to a NACL. Can we restrict traffic but allow sufficient space for unknowns? Will we run the risk of returning to our status quo?

## Definition of done

- [ ] NACLs restricted
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] tests are green
- [ ] UR test OR added to continual research plan

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by ewastempel** [comment]
Looking at the AWS and terraform documentations, only CIDR ranges are allowed for IP ranges (no sets, e.g. [10.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16]) and only from-to port ranges (no sets, e.g. `[80, 442, 1024-65535]`). This make it much trickier to group.

**Comment by ewastempel** [comment]
so far there are 10 rules in private and data nacls and 4 rules in public and transit nacls

**Comment by ewastempel** [comment]
PR created, but not convinced it adds much value: https://github.com/ministryofjustice/modernisation-platform/pull/4176

Asked @davidkelliott the question whether we want to go ahead with it, which can be tracked in this [slack thread.](https://mojdt.slack.com/archives/C013RM6MFFW/p1686227024001509)

**Comment by ewastempel** [comment]
The PR was merged and there is another [ticket](https://github.com/ministryofjustice/modernisation-platform/issues/3008) that is to consolidate two modules into one.

This is done now.
