### ISSUE TITLE
SPIKE: Can GitHub Actions handle a timed-out Terraform run?

### ISSUE THREAD

**Issue by dms1981** [ministryofjustice/modernisation-platform#4070]
## User Story

As a Modernisation Platform Engineer 
I want to investigate conditional handling for GitHub Actions
So that I can push an `errored.tfstate` file into S3 when a GitHub Actions Terraform run times out.

## User Type(s)

Modernisation Platform Engineer
Modernisation Platform Customer

## Value

Terraform runs in GitHub Actions occasionally run for so long that Action reaches a timeout threshold. This leads to a failure to push changes back into the statefile in S3 and a drift between created resources in AWS, and those in the remote statefile.

Is it possible that we can better handle these events? Perhaps with some GitHub conditional steps based on the presence of an `errored.tfstate` file?

Here's an example of the output from a failed run:
```
│ Error: Failed to save state
│ 
│ Error saving state: failed to upload state: ExpiredToken: The provided
│ token has expired.
│ 	status code: 400, request id: XXXXXXXXXXXXXXXX, host id:
│ AAAAAAAAAAAAAA/BBBBBBBBBBBBBB/CCCCCCCCCCCCCC/DDDDDDDDDDDD=
╵
╷
│ Error: Failed to persist state to backend
│ 
│ The error shown above has prevented Terraform from writing the updated
│ state to the configured backend. To allow for recovery, the state has been
│ written to the file "errored.tfstate" in the current working directory.
│ 
│ Running "terraform apply" again at this point will create a forked state,
│ making it harder to recover.
│ 
│ To retry writing this state, use the following command:
│     terraform state push errored.tfstate
│ 
╵
```

### Hypothesis 
If we can account for the presence of `errored.tfstate`
Then we can prevent drift between the resources in AWS and those in the statefile

### Proposal
Look into GitHub Actions conditionals to see if we can use some combination of the `cache` or artifact action to persist a tfstate within a job after the terraform step, and push it into S3 if a step times out.

## Definition of done

- [ ] Spike is timeboxed
- [ ] Options explored
- [ ] Findings documented (comments on this issue will suffice)
- [ ] Options discussed with team
- [ ] Story raised if appropriate

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by markgov** [comment]
so the first option that i came up with was the following 

[Setting a failure exit code in a Docker container action](https://docs.github.com/en/actions/creating-actions/setting-exit-codes-for-actions#setting-a-failure-exit-code-in-a-docker-container-action)
If you are creating a Docker container action, you can set a failure exit code in your entrypoint.sh script. For example:
if <condition> ; then
  echo "Game over!"
  exit 1
fi
but after the then we do
 terraform state push errored.tfstate

but since then i have done a bit more digging into cache and am looking at that at present

**Comment by markgov** [comment]
we can define the cache as follows
- name: Cache Terraform state
        uses: actions/cache@v2
        with:
          path: terraform.tfstate.d
          key: terraform-state-${{ hashFiles('**/*.tf') }}
          restore-keys: |
            terraform-state-

**Comment by markgov** [comment]
and then try and capture the error like this 

- name: Capture Errored State
        if: failure()  # Only capture if previous steps failed
        run: mv errored.tfstate terraform.tfstate.d/
which would move the errored state file to the cache

**Comment by markgov** [comment]
then push the errored state file from the cache to the s3 bucket
- name: Push Errored State to S3
        if: failure()  # Only push if previous steps failed
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws s3 cp terraform.tfstate.d/errored.tfstate s3://your-s3-bucket/path/to/store/errored.tfstate

**Comment by markgov** [comment]
we can just have a section in the workflow that just captures the failer state and runs terraform state push errored.tfstate which should just upload the errored state to the s3 bucket

**Comment by markgov** [comment]
new issue created GitHub Actions handle a timed-out Terraform run #5212
