### ISSUE TITLE
Allow controlled egress to SMTP ports from private subnets

### ISSUE THREAD

**Issue by davidkelliott** [ministryofjustice/modernisation-platform#4094]
## User Story

PPUD application needs to send emails to CJSM SMTP relay.  In order to do this we need to open up the NACLs for the required ports and create an allow to the domain in the firewall.

## User Type(s)

MP users

## Value

Allow main to be securely sent to SMTP relays

### Proposal

Open the egress NACLs in private subnets to port 587
Open the egress firewall port 587 to [cjsm.net](http://cjsm.net/)

### Unknowns
PPUD currently use port 25, trying to use a more secure port which supports TLS in the first instance.

## Definition of done

- [x] NACLS opened
- [x] Firewall rule created
- [ ] Mail tested
- [x] another team member has reviewed
- [x] tests are green

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by dms1981** [comment]
Resolved via https://github.com/ministryofjustice/modernisation-platform/pull/4147 - as we don't have the ability to generate & send mail to `cjsm.net` I've not completed the email test, but will leave this to the PPUD team to confirm.

**Comment by dms1981** [comment]
This ended up being rolled back after discussion with the PPUD team. We better understand their needs, they better understand the infrastructure of the Modernisation Platform, and the application specifics around email relaying have been discussed.
