### ISSUE TITLE
Implement merge queues for the modernisation platform repo workflows

### ISSUE THREAD

**Issue by davidkelliott** [ministryofjustice/modernisation-platform#4116]
## User Story

See thread here - https://mojdt.slack.com/archives/C013RM6MFFW/p1685702249538789

As an MP engineer
I need to be able to merge my PRs
Without worrying that the workflow is going to clash with another.

## User Type(s)

MP Engineer

## Value

Prevent errors of workflows trying to access the same state/infra at the same time

### Hypothesis 
If we enable merge queues and reduce workflow concurrency to 1
Then workflows will queue when multiple PRs are merged at the same time.

### Proposal
Implement merge queues for the main mp repo.

### Unknowns
Merge queues have not been used on the platform before, it would be work experimenting in a personal repo as to how they work in reality.

## Definition of done

- [ ] merge queues and single concurrency implemented
- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] tests are green

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by markgov** [comment]
https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue

**Comment by markgov** [comment]
I have created a few PR's to implement merge queue code into workflows but all have failed going to revert this code and create multiple Pr to how merge queues work

**Comment by markgov** [comment]
i have now got merge group working on workflows but not sure it's doing what we want it to do here is a document i have found on it and this the only document i have found on the webhook
https://github.blog/changelog/2022-08-18-merge-group-webhook-event-and-github-actions-workflow-trigger/

**Comment by markgov** [comment]
dicustion with github
https://github.com/orgs/community/discussions/60124
https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#merge_group
https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue#triggering-merge-group-checks-with-github-actions
https://github.blog/changelog/2022-08-18-merge-group-webhook-event-and-github-actions-workflow-trigger/
https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/merging-a-pull-request-with-a-merge-queue
https://github.blog/changelog/2023-02-08-pull-request-merge-queue-public-beta/

**Comment by markgov** [comment]
closing for now as more testing needs to be done on more complex workflows also testing on what happen on editing the same line moving this to more 10% time and implementing after the feature is out of public beta
