### ISSUE TITLE
Define pagerduty slack integrations in code

### ISSUE THREAD

**Issue by davidkelliott** [ministryofjustice/modernisation-platform#4154]
## User Story

As an MP engineer or user
I want to define integrations from pagerduty services or teams to slack in code
So that I have better visibility and control of my monitoring infrastructure

https://registry.terraform.io/providers/PagerDuty/pagerduty/latest/docs/resources/slack_connection

## User Type(s)

MP engineers and users

## Value

Currently this is a manual step here - https://user-guide.modernisation-platform.service.justice.gov.uk/user-guide/integrating-alarms-with-pagerduty-with-slack.html#4-link-the-pagerduty-service-to-your-slack-channel

This would move this into code and remove the need for a manual step.

### Proposal
Create code for existing integrations and import them.  Update the code example in the repo to have this code per service.

### Unknowns
This has not been tested yet.

## Definition of done

- [x] code created
- [x] imports done
- [x] user docs have been updated
- [x] another team member has reviewed
- [x] tests are green

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by markgov** [comment]
Code created and added to repo for testing
https://github.com/ministryofjustice/modernisation-platform/pull/4245

**Comment by markgov** [comment]
The current issue is that when we run the terraform apply we are getting the following error
╷
│ Error: 
│ 
│ No valid credentials found for PagerDuty provider.
│ Please see https://www.terraform.io/docs/providers/pagerduty/index.html
│ for more information on providing credentials for this provider.
│ 
│ 
│   with pagerduty_slack_connection.example_connection,
│   on member-services-integrations.tf line 355, in resource "pagerduty_slack_connection" "example_connection":
│  355: resource "pagerduty_slack_connection" "example_connection" {
│ 
╵
and this is even with the creation of a new provider and a new token.

**Comment by markgov** [comment]
This error has now been resolved we have a working example of the code which we can update the rest of the teams with and remove the need for manual intervention when doing pager duty creation

**Comment by markgov** [comment]
i have now imported the current resources listed in the terraform file and working on the plan as it states there are currently 23 to change

**Comment by markgov** [comment]
all pr's have been merged and all that is left is for the documentation to update

**Comment by markgov** [comment]
documentation pr 
https://github.com/ministryofjustice/modernisation-platform/pull/4361
