### ISSUE TITLE
New Preprod environment to replicate existing MOJ Official (Network Operations Centre) #208632142291

### ISSUE THREAD

**Issue by RonakDalalMoJ** [ministryofjustice/modernisation-platform#4160]
## Environment details
Preprod environment for testing and development before releasing to prod NOC. Below name is chosen to keep it as close to current prod environment as possible (thus not conforming the naming requirement of lowercase and char limit)

### Application Name
moj-network-operations-centre

Account type: member-unrestricted

### Description of application
The environment will run various applications for monitoring and managing the network infrastructure. Current deployment on Prod has various tools installed - SolarWinds, ServiceNOW MID server, Azure application proxy server and Netbox application

### GitHub team slug

moj-official-techops

### Environments
AWS Preproduction (Prod environment already exists)
preproduction

| Environment   | Access level |
| ---     | --- |
|<ul><li>[x] Preproduction</li></ul>| <ul><li>[x] administrator</li></ul> |

### Tags

tag | value
--- | ---
application |   moj-network-operations-centre
business-unit | HQ
infrastructure-support | [MOJNOC@justice.gov.uk](mailto:MOJNOC@justice.gov.uk)
owner | chinyere.onuoha@justice.gov.uk

### Subnet sets

- [ ] General - this application will use the same subnet as other applications in your business unit
- [ ] Isolated - this application has highly sensitive data which must have its own isolated subnet with no network connectivity

### How do users connect to the application?

- [ ] Over the public internet
- [ ] With a purple cabled device (please give details)
- [ ] With a MoJ Official device

## Additional features

- [ ] Additional VPC Endpoints
- [ ] Extended DNS Zones
- [ ] Other - please specify

## Definition of done

- [ ] account created
- [ ] customer informed

**Comment by SteveLinden** [comment]
Email sent to both addresses to inform them of our contact point (on slack) and the documentation location.

**Comment by SteveLinden** [comment]
Application name amended to  moj-network-operations-centre after the team decided that moj-official was not suitable. Took a while to remove the old one. New one is in the process of being created.

**Comment by SteveLinden** [comment]
Emailed with the new environment (moj-network-operations-centre-preproduction) details.
