### ISSUE TITLE
Review of DNS on the platform

### ISSUE THREAD

**Issue by davidkelliott** [ministryofjustice/modernisation-platform#4169]
## User Story

As an MP user and Engineer
I need to understand how to do DNS on the platform
So that I have repeatable easy patterns to follow

## User Type(s)

MP users
MP Engineers

## Value

Understand how we do DNS, where should domains be created, where should hosted zones be created.
Once created, how should hosted zones be shared with accounts?

### Proposal

Run through our current DNS set up, identify areas where we are lacking, create issues to resolve those areas.

## Definition of done

- [x] review complete
- [x] results presented to the team
- [x] consensus reached on approach
- [x] new issues created
- [x] another team member has reviewed
- [x] ADR created

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by SimonPPledger** [comment]
@davidkelliott to re-write to cover what we want to do with DNS

**Comment by dms1981** [comment]
https://aws.amazon.com/blogs/architecture/using-route-53-private-hosted-zones-for-cross-account-multi-region-architectures/

**Comment by dms1981** [comment]
Moving to blocked until the outcome of Tuesday's catch-up is clear

**Comment by dms1981** [comment]
Stories to be raised:
[ ] - Creating private zones in core-network-services and associating them with relevant customer vpc.
[ ] - Review documentation and make it clearer - eg, with examples
[ ] - Spike that covers securing what can be done to zones hosted in core-network-services from a customers' application code.

**Comment by dms1981** [comment]
ADR here - https://github.com/ministryofjustice/modernisation-platform/pull/4480

**Comment by dms1981** [comment]
Spike for securing Route53: https://github.com/ministryofjustice/modernisation-platform/issues/4476

Story for refreshing documentation: https://github.com/ministryofjustice/modernisation-platform/issues/4475

Story for creating module: https://github.com/ministryofjustice/modernisation-platform/issues/4474
