### ISSUE TITLE
Upgrade to AWS Terraform provider 5.0.0 - to cover MP modules only

### ISSUE THREAD

**Issue by davidkelliott** [ministryofjustice/modernisation-platform#4173]
## User Story

The latest version of the AWS Terraform provider is out. https://github.com/hashicorp/terraform-provider-aws/releases/tag/v5.0.0
There are breaking changes so we should assess and update as appropriate in a controlled manner.
We should provide guidance to users on how to update.

Note we need to verify that the upgraded modules work with the environments repo that has not yet been upgraded, otherwise we need to issue guidance advising people not to upgrade to the latest release of the module until the environments repo has been upgraded.

## User Type(s)

MP Engineers
MP Users

## Value

Keeping the platform up to date and secure

## Definition of done

- [x] update to mp modules repos completed
- [x] another team member has reviewed
- [x] tests are green

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by dms1981** [comment]
I've moved this back to `in-progress` because there's one thing left to do (so far as I can see):
> We should provide guidance to users on how to update.

**Comment by dms1981** [comment]
https://github.com/ministryofjustice/modernisation-platform-environments/pull/2585

So far as guidance goes, I don't think there's much to be said beyond a message in #modernisation-platform-updates that we can forward to #ask-modernisation-platform for awareness. We'll need to approve changes to `platform_versions.tf`, but none of the module updates involved any user-side changes beyond the release reference and the provider version so there's not a log to say here.
