### ISSUE TITLE
Upgrade to AWS Terraform provider 5.0.0 - to cover environments repository

### ISSUE THREAD

**Issue by davidkelliott** [ministryofjustice/modernisation-platform#4174]
## User Story

The latest version of the AWS Terraform provider is out. https://github.com/hashicorp/terraform-provider-aws/releases/tag/v5.0.0
There are breaking changes so we should assess and update as appropriate in a controlled manner.
We should provide guidance to users on how to update.

## User Type(s)

MP Engineers
MP Users

## Value

Keeping the platform up to date and secure

## Definition of done

- [ ] update to environments repo completed
- [ ] another team member has reviewed
- [ ] tests are green

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by ep-93** [comment]
https://github.com/ministryofjustice/modernisation-platform-environments/pull/2664/files - HMPPS

https://github.com/ministryofjustice/modernisation-platform-environments/pull/2685 - LAA

**Comment by davidkelliott** [comment]
All PRs now merged
