### ISSUE TITLE
Review current access levels

### ISSUE THREAD

**Issue by davidkelliott** [ministryofjustice/modernisation-platform#4184]
## User Story

As an MP user
I want access levels which meet my needs
So that I can do my job

As an MP security engineer
I want access levels which meet the principal of least privilege
So that I can keep the plat form secure

See thread here - https://mojdt.slack.com/archives/C01A7QK5VM1/p1685615497407569

## User Type(s)

MP user, MP security engineer

## Value

Ensure that the access levels are fit for purpose and secure

### Hypothesis 
If we do some analysis of what we have vs what users want
Then we can address any gaps or inconsistencies

### Proposal
The access levels have grown organically from user requests over time.  This may been some levels no longer suit the need or have grown too large.  Could we do access in a different way?  Are some roles too permissive?  Do we understand what any wildcards really mean?

Conduct initial analysis on the current roles and any overlap and common things.
Do user research on what is lacking from the current roles.

Create issues to then do:
Refactor to move common permissions centrally.
Add in additional permissions or access levels needed.
Remove permissions or access levels that are now.

## Definition of done

- [ ] analysis of current access levels
- [ ] review existing user research
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] tests are green
- [ ] UR test OR added to continual research plan

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by ep-93** [comment]
https://github.com/ministryofjustice/modernisation-platform/issues/4541

Maybe related.

**Comment by ep-93** [comment]
https://docs.google.com/presentation/d/1rdDIH0su0YImwUK6kmKd00xHxXzCDSXhYA_IVjRd4_0/edit?usp=sharing
