### ISSUE TITLE
SPIKE: Manage secrets in one place

### ISSUE THREAD

**Issue by davidkelliott** [ministryofjustice/modernisation-platform#4312]
## User Story

Currently we are managing secrets for workflows in 2 places, in secrets manager, then we are putting in them into Github repository secrets via our Github terraform code.

If the environments TF fails we can end up with no secrets in Github as seen here - https://mojdt.slack.com/archives/C013RM6MFFW/p1686913462629909?thread_ts=1686911210.327769&cid=C013RM6MFFW

This spike is to see if we could get them directly from secrets manager instead, since we already authenticate via OIDC so we don't use creds for that.

Timebox for 3 days but for 1 workflow - create a test workflow and  running the plan 

## User Type(s)

MP engineers

## Value

More resilient platform

### Proposal
At the beginning of a job, get the secrets from secrets manager

### Unknowns
Not been tried before

## Definition of done

- [ ] spike completed
- [ ] presented to team
- [ ] another team member has reviewed

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by SimonPPledger** [comment]
https://docs.aws.amazon.com/secretsmanager/latest/userguide/retrieving-secrets_github.html

**Comment by richgreen-moj** [comment]
The issue of the secret not being updated in GitHub has happened once more where an account deletion was involved.... https://mojdt.slack.com/archives/C013RM6MFFW/p1710181133706049?thread_ts=1710158699.597139&cid=C013RM6MFFW
Could be worth investing time in this ticket to avoid more occurrences

**Comment by sukeshreddyg** [comment]
Completed spike for fetching secrets from Secrets Manager. Confirmed feasibility for scheduled baseline workflow. Initiating ticket #6627 for testing integration. Next steps: test retrieval, update docs, ensure seamless integration for enhanced security
