### ISSUE TITLE
Upgrade to Terraform 1.5 - check if we need to do anything

### ISSUE THREAD

**Issue by davidkelliott** [ministryofjustice/modernisation-platform#4315]
## User Story

This story is just to double check that we do allow minor version upgrades as we think we do.

https://github.com/hashicorp/terraform/releases/tag/v1.5.0

As part of this story we should have a consistent approach to how we version our use of Terraform.
EG. Instead of having instances where we use `>= 1.0.1` and `~> 1.3` we should choose a consistent approach and apply it.
(There have been enhancements in 1.3 that for some module necessitate that version as a floor.)

## User Type(s)

MP engineers
MP users

## Value

Keep up to date with the latest features and security patches

## Definition of done

- [x] mp repo updated to 1.5
- [x] ensure we have a consistent approach to terraform versioning across our code
- [ ] another team member has reviewed
- [ ] tests are green
- [ ] UR test OR added to continual research plan

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by dms1981** [comment]
In https://github.com/ministryofjustice/modernisation-platform-environments/ the reusable `[plan_and_apply](https://github.com/ministryofjustice/modernisation-platform-environments/blob/main/.github/workflows/reusable_terraform_plan_apply.yml#L110)` uses `[1.3.9](https://github.com/ministryofjustice/modernisation-platform-environments/blob/main/.github/workflows/reusable_terraform_plan_apply.yml#L40)` by default.

**Comment by dms1981** [comment]
In [modernisation-platform](https://github.com/ministryofjustice/modernisation-platform) the actions all consistently use `"~1"` in their syntax.
In the terraform code in this repository there's a mix of `required_versions`. Most jobs specify `"~> 1.0"` but some specify `"~> 1.0.1"` so I'll bring those into line in a PR.

**Comment by dms1981** [comment]
Following https://github.com/ministryofjustice/modernisation-platform/pull/4460, the terraform required version is consistently set through code. This will use the most up-to-date version in the `1.x` release train.
