### ISSUE TITLE
Implement workflows to automatically apply changes in terraform/environments/<application>

### ISSUE THREAD

**Issue by dms1981** [ministryofjustice/modernisation-platform#4365]
## User Story

As a Modernisation Platform engineer
I want to automate any changes or additions to files in `terraform/environments/<application>`
So that bespoke additions to customer environments are automatically applied

## User Type(s)

Modernisation Platform Engineer
Modernisation Platform Customer

## Value

At present, changes to add bespoke additions such as IAM users for SES or supplemental VPCs for SaaS products require manual intervention by a Modernisation Platform engineer. Creating an appropriate workflow action or trigger will remove this manual element.

## Definition of done

- [ ] check existing workflows
- [ ] create new workflow if required
- [ ] another team member has reviewed
- [ ] tests are green
- [ ] UR test OR added to continual research plan

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by davidkelliott** [comment]
In an ideal world it would be good if this was in one workflow which does the following:

On PR:
Gets the lists of application folders
Checks if there are any changes to the folders
If there are run the plan for all environments
Trigger a deploy for development and test (skip if no changes)

On Merge:
Gets the lists of application folders
Checks if there are any changes to the folders
If there are then trigger deploy to all environments (skip if no changes)

Bonus points for being able to run it via workflow dispatch and pass in an application folder name

The aim of this is trying to avoid having another 30 workflow files in this repo.

NOTE: We do not currently use github environments in the MP repo so this will also need to be set up.

**Comment by dms1981** [comment]
Moved to blocked awaiting a review of https://github.com/ministryofjustice/modernisation-platform/pull/4590
