### ISSUE TITLE
New LAA Ops Environment - MAAT

### ISSUE THREAD

**Issue by mikereiddigital** [ministryofjustice/modernisation-platform#4374]
### Application Name

maat

### Description of application

This is the LAA's Means Assessment Administration Tool. It is a dockerised java application that runs on ecs. It connects to the MAAT database that is hosted in the LAA Landing Zone.

### GitHub team slug

@ministryofjustice/laa-aws-infrastructure 

### Environments

| Environment   | Access level |
| ---     | --- |
|<ul><li>[x] Development</li></ul> | <ul><li>[ ] view-only</li><li>[ ] developer</li><li>[ ] sandbox</li></ul> |
|<ul><li>[x] Test</li></ul>   | <ul><li>[ ] view-only</li><li>[ ] developer</li></ul> |
|<ul><li>[x] Preproduction</li></ul>| <ul><li>[ ] view-only</li><li>[ ] developer</li></ul> |
|<ul><li>[x] Production</li></ul> | <ul><li>[ ] view-only</li><li>[ ] developer</li></ul> |

### Tags

tag | value
--- | ---
application | "Means Assessment Administration Tool - MAAT"
business-unit | LAA
infrastructure-support | laa-role-sre@digital.justice.gov.uk
owner | laa-crime-apps@digital.justice.gov.uk

### Subnet sets

- [x] General - this application will use the same subnet as other applications in your business unit
- [ ] Isolated - this application has highly sensitive data which must have its own isolated subnet with no network connectivity

### How do users connect to the application?

- [x] Over the public internet
- [ ] With a purple cabled device (please give details)
- [ ] With a MoJ Official device

Note that whilst most users access the application from DOM1, current access is via the internet.

## Additional features

- [ ] Additional VPC Endpoints
- [ ] Extended DNS Zones
- [ ] Other - please specify

## Definition of done

- [ ] account created
- [x] customer informed

**Comment by SimonPPledger** [comment]
Just checking that we can't just use the maat db accounts, rather than create a new one

**Comment by mikereiddigital** [comment]
> Just checking that we can't just use the maat db accounts, rather than create a new one

We'd like to keep MAATDB as it is as that will be a separate migration.

**Comment by ASTRobinson** [comment]
I have informed @mikereiddigital that the new environments have now been successfully created.
