### ISSUE TITLE
Enabling access for ITHC testers

### ISSUE THREAD

**Issue by SimonPPledger** [ministryofjustice/modernisation-platform#4436]
## User Story
Raised on behalf of Michael Clarke
As an application manager I need to be able to arrange IT Health Checks. And these checkers will need to be able to access components to carry out these tests.
This request is to provide them with an EC2 with kali linux installed accessible SSM. (there might be a requirement for multiple boxes).

This will need to be available externally to MoJ.

## User Type(s)
3rd party ITHC testers

## Value
This will enable the application team to understand any security issues with the application

## Assumptions / Hypothesis / Questions / Unknowns
This is likely to be a frequent requirement in the future, so ideally we would codify this, but this might not be possible for this request. If not, then we need to raise a subsequent ticket

## Definition of done

- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] access confirmed
- [ ] tests are green
- [ ] new ticket raised
## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by markgov** [comment]
Joe Beauchamp <Joe.Beauchamp@bsigroup.com>
Shaun Dundavan <Shaun.Dundavan@bsigroup.com>

collaborator accounts needed

**Comment by SimonPPledger** [comment]
We have confirmation that they can access the console
