### ISSUE TITLE
Move data platform OIDC over to MP OIDC

### ISSUE THREAD

**Issue by davidkelliott** [ministryofjustice/modernisation-platform#4455]
## User Story

data platform are using oidc currently as MP offering isn't yet in place - https://github.com/ministryofjustice/modernisation-platform-environments/pull/2691

This should be switched over once MP OIDC is in place.

## User Type(s)

data-platform users

## Value

Keep consistent OIDC usage on the platform

## Definition of done

- [ ] OIDC switched to MP OIDC
- [ ] another team member has reviewed
- [ ] tests are green
- [ ] UR test OR added to continual research plan

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by ep-93** [comment]
https://github.com/ministryofjustice/data-platform/pull/1313

Done
