### ISSUE TITLE
Duplicate Backup

### ISSUE THREAD

**Issue by ASTRobinson** [ministryofjustice/modernisation-platform#4466]
## Expected Behavior

One complete backup is taken nightly. 

## Actual Behavior

Reported by Dominic Robinson:- "An observation re AWS Backup jobs.   While doing a backup/restore test this afternoon, I noticed there are duplicate backups for EBS volumes each night.  One taken when the EC2 instance is backed up (since all attached EBS volumes are backed up), and one for the EBS volume itself (since it also happens to have a `is-production` true flag). So EBS:SnapshotUsage cost is basically twice what it needs to be.  We could fix by removing the `is-production` flag from the EBS volumes, but on the other hand, they are production."

## Steps to Reproduce the Problem

  1. Create a backup for an EC2 instance with EBS volumes attached tagged with `is-production`

## Other information

Reported on nomis-test account, resource id: t3-nomis-db-1

**Comment by drobinson-moj** [comment]
It would be great if we could opt out of the default backup jobs as well, because we also don't need our Auto Scaling Group servers backed up.   And also are likely to create a custom backup job for our DBs.

**Comment by drobinson-moj** [comment]
For NOMIS we have worked around by create custom policy (daily backups for 7 days, weekly backups for 4 weeks) and select this by using a "backup-plan" tag.  We've removed the "backup" tag to avoid backups in non-production accounts but to avoid the default production backups, we've had to change the is-production tag, .e.g. is-production = "true-no-default-backup-workaround"
If there is a nicer way of opting out of production backups as a result of this ticket, please do let me know.

**Comment by markgov** [comment]
after looking into this issue i have found that there is two ways to resolve this one way is to turn off ether ec2 backups from aws backup or EBS volumes from aws backups or we need to amend the way the ec2 module is written to allow for separate tags for the ebs volumes to be passed through

**Comment by markgov** [comment]
Hello!

Thank you for contacting AWS Support. My name is Tommy and I will be assisting you with your case.

From the case notes, I understand you have EC2 and EBS backups enabled on AWS Backup and are getting duplicate backups. You would like to know if this is normal and what is the difference between EC2 backups and EBS backups. Please correct me if I have misunderstood.

I would like to inform you that when backing up an Amazon EC2 instance, AWS Backup takes a snapshot of the root Amazon EBS storage volume, and all associated EBS volumes.

When you take backup of EC2 instance using resource type as EC2 via AWS Backup, it creates Amazon Machine Images (AMI) and as the AMI is the metadata of the EC2 instance, snapshots are created a part of the AMI's. AWS Backup takes a snapshot of the root Amazon EBS storage volume, the launch configurations, and all associated EBS volumes. AWS Backup stores certain configuration parameters of the EC2 instance, including instance type, security groups, Amazon VPC, monitoring configuration, and tags with an exclusion of Ephemeral storage. The backup data is stored as an Amazon EBS volume-backed Amazon Machine Image (AMI)[1]. 

And, if you want to individually back up just the EBS volumes alone without backing up the EC2 instance as a whole, it's also possible as you had mentioned by taking EBS backup separately for individual volumes.. More information on taking EBS backup separately is mentioned in the following AWS documentation with a following third party article which might provide more clarity on how backup works with an EC2 instance or EBS volume:
[https://docs.aws.amazon.com/prescriptive-guidance/latest/backup-recovery/new-ebs-volume-backups.html ](https://docs.aws.amazon.com/prescriptive-guidance/latest/backup-recovery/new-ebs-volume-backups.html) 

In summary, it is normal behavior that you are seeing duplicate backups. EBS volume snapshots are included when backing up of a EC2 instance. It is not necessary to do EBS volume backups as it is included in the EC2 backups, but could be useful if you have multiple EBS volumes attached to an instance and you want to restore for example one ebs volume and not all of them.

I hope you find the above information useful. If you have any questions or concern, please feel free to contact me and I'll be happy to assist. 

References
[1]How AWS Backup works with Amazon EC2 - [https://docs.aws.amazon.com/aws-backup/latest/devguide/working-with-other-services.html#working-with-ec2 ](https://docs.aws.amazon.com/aws-backup/latest/devguide/working-with-other-services.html#working-with-ec2)   
[2][https://docs.aws.amazon.com/prescriptive-guidance/latest/backup-recovery/new-ebs-volume-backups.html ](https://docs.aws.amazon.com/prescriptive-guidance/latest/backup-recovery/new-ebs-volume-backups.html) 

We value your feedback. Please share your experience by rating this and other correspondences in the AWS Support Center. You can rate a correspondence by selecting the stars in the top right corner of the correspondence.

Best regards,
Tommy T.
Amazon Web Services

**Comment by markgov** [comment]
yeah ok that's good but still based on tags so the ec2 baseline module will still need to be changed to allow fo the extra tag for the ebs volumes separate from the ec2 resource


Mark Roberts
  [9 minutes ago](https://mojdt.slack.com/archives/C013RM6MFFW/p1692176908285739?thread_ts=1692027606.927229&cid=C013RM6MFFW)
it's all about the tagging


David Sibley
:baby:  [6 minutes ago](https://mojdt.slack.com/archives/C013RM6MFFW/p1692177094146119?thread_ts=1692027606.927229&cid=C013RM6MFFW)
Should be as simple as adding the condition, releasing and referencing the changed module, and putting a note in the documents for customers in need of that exclusion :slightly_smiling_face:


Dave Elliott
  [5 minutes ago](https://mojdt.slack.com/archives/C013RM6MFFW/p1692177147893899?thread_ts=1692027606.927229&cid=C013RM6MFFW)
I know what Mark means the tags get passed in to our EC2 instance module as a block so it will be all or nothing.  You could add an input to the module something like backup  with values of ec2, ebs, all , defaulting to all, and then add the skip tag where needed according to the input logic (edited) 


Dave Elliott
  [3 minutes ago](https://mojdt.slack.com/archives/C013RM6MFFW/p1692177216831739?thread_ts=1692027606.927229&cid=C013RM6MFFW)
So 2 changes needed the change to the backup plan in the baselines and change to our EC2 module

**Comment by markgov** [comment]
New issue raised
AWS Backup exclusion tags #4802
