### ISSUE TITLE
Create module for private hosted zones

### ISSUE THREAD

**Issue by dms1981** [ministryofjustice/modernisation-platform#4474]
## User Story

As a Modernisation Platform Customer 
I want to create AWS Route53 Private hosted zones
So that I can migrate my application to the Modernisation Platform 

## User Type(s)

Modernisation Platform Customers

## Value

Customers who need access to AWS Route53 Private hosted zones don't currently have a way to provision them.
In order to maintain some sensible segregation between how we use AWS accounts, we should write the necessary terraform to allow them to make use of private hosted zones.

We should create new zones on request in our `core-network-services` account, associated with the `live-data` VPC.
From there we should also create the necessary association authorization for the customer VPC.
Then, we should create the association in the customer VPC for this private hosted zone.

What I anticipate is the use of a `local` value and a resource statement in the `core-network-services` account that handles the new zone creation, and a module that handles the authorization/association which can be used by customers.

## Definition of done

- [x] code written to create new zones in core-network-services
- [x] code written to authorise the association and the associate a member VPC with the new zone
- [x] another team member has reviewed
- [x] new documentation created

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)
[Using AWS Route53 Private Hosted Zones for cross-account multi-region architectures](https://aws.amazon.com/blogs/architecture/using-route-53-private-hosted-zones-for-cross-account-multi-region-architectures/)

**Comment by markgov** [comment]
Added new private dns section to core-network-services and this plans without any errors

**Comment by markgov** [comment]
working on authorisation module

**Comment by markgov** [comment]
https://github.com/ministryofjustice/modernisation-platform/pull/4604

**Comment by markgov** [comment]
took some of the advice from david and amended the module it looks good but i have push my code to the pr for others to take a look and surgest any changes

**Comment by markgov** [comment]
i believe i have a working module the only issue i see is that the route53 part in the core network is taking longer to finish than the module takes to run on the vpc so the module is not picking up any changes as the DNS is still being created

**Comment by markgov** [comment]
Module completed and up for review

**Comment by markgov** [comment]
module PR merged

**Comment by markgov** [comment]
Re-oppend as user has just used the module and i checked the pr and the plan and terraform is stating no changes

**Comment by dms1981** [comment]
Raised this PR to rework the private hosted zones module: https://github.com/ministryofjustice/modernisation-platform/pull/4694

**Comment by dms1981** [comment]
Closed following successful association of private zone with VPC in separate account
