### ISSUE TITLE
SPIKE: Review our ability to secure DNS zones

### ISSUE THREAD

**Issue by dms1981** [ministryofjustice/modernisation-platform#4476]
## User Story

As a Modernisation Platform Customer
I want to investigate ways to control changes to AWS Route53 zones
So that we can assess the available security controls for future use

## User Type(s)

Modernisation Platform Engineer

## Value

Given the possibility of one Modernisation Platform customer to add or change records in a Route53 zone used by another Modernisation Platform customer, we should assess what we can do to prevent accidental changes to Route53 zones using the `aws.core-network-services` provider.

## Definition of done

- [ ] spike timeboxed
- [ ] options investigated
- [ ] new stories raised based on outcome of spike

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by ep-93** [comment]
https://github.com/ministryofjustice/modernisation-platform/blob/main/terraform/environments/core-network-services/route53.tf

It makes sense how our zones are managed, I'm strugging to come up with options.

**Comment by ep-93** [comment]
So, this ticket is less about the DNS zones we manage in the modernisation platform account, and more about adding records to zones.


_**Records should be added to new zones by the requestor in code through the [Modernisation Platform Environments](https://github.com/ministryofjustice/modernisation-platform-environments/tree/main/terraform/environments) repository.**_

**Comment by ep-93** [comment]
https://docs.google.com/document/d/1EEmWeA2J9OWAx8tNt-MdUw5l2V_m46f58S5QVwsBLt0/edit?usp=sharing
