### ISSUE TITLE
Create NOLASA accounts in MP for Ops team

### ISSUE THREAD

**Issue by alanrana7** [ministryofjustice/modernisation-platform#4489]
### Application Name

nolasa

### Description of application

Not On Libra Auto-Search Application (NOLASA) is a micro-service that reads cases that have been marked as 'not-on-libra' from the MLRA database once a day (8pm). It then auto-searches the HMCTS Libra system via the LAA's Infox message broker service. The message protocol used is SOAP.

If NOLASA finds that there are results returned for a case it updates its status in MLRA to say 'RESULTS FOUND'. This means that caseworkers can filter 'not on libra' cases to ones that they know they will have results for. They can then prioritize their case searching and linking more effectively.

NOLASA (“not on libra autosearch) is a batch scheduler java application that is dockerised & runs on ecs. It has connections with MAATDB and Infox

### GitHub team slug

laa-aws-infrastructure

### Environments

| Environment   | Access level |
| ---     | --- |
|<ul><li>[x] Development</li></ul> | <ul><li>[ ] view-only</li><li>[x] developer</li><li>[ ] sandbox</li></ul> |
|<ul><li>[x] Test</li></ul>   | <ul><li>[ ] view-only</li><li>[x] developer</li></ul> |
|<ul><li>[x] Preproduction</li></ul>| <ul><li>[ ] view-only</li><li>[x] developer</li></ul> |
|<ul><li>[x] Production</li></ul> | <ul><li>[ ] view-only</li><li>[x] developer</li></ul> |

### Tags

tag | value
--- | ---
application | nolasa
business-unit | LAA
owner | LAA

### Subnet sets

- [x] General - this application will use the same subnet as other applications in your business unit
- [ ] Isolated - this application has highly sensitive data which must have its own isolated subnet with no network connectivity

### How do users connect to the application?

- [ ] Over the public internet
- [ ] With a purple cabled device (please give details)
- [ ] With a MoJ Official device
- [x] Via other existing AWS account

## Additional features

- [ ] Additional VPC Endpoints
- [ ] Extended DNS Zones
- [ ] Other - please specify

## Definition of done

- [ ] account created
- [ ] customer informed

**Comment by SimonPPledger** [comment]
@alanrana7 can this move to CP instead, which would be cheaper

**Comment by alanrana7** [comment]
Hi @SimonPPledger - I'll discuss this with my team and get back to you

**Comment by mikereiddigital** [comment]
@SimonPPledger - that would be a follow up exercise and one that the product team could do themselves at a future date.

**Comment by SimonPPledger** [comment]
Update from LAA Ops:

**Comment by SimonPPledger** [comment]
decision to leave for now and ask the LAA Dev team to move to CP
