### ISSUE TITLE
Environment Request for Wardship

### ISSUE THREAD

**Issue by matthewsearle01** [ministryofjustice/modernisation-platform#4509]
### Application Name

wardship

### Description of application

The Wardship Registers is a non-critical business application that allows Royal Courts of Justice High Court authorised staff to view wardship entries previously created within the application. Wardship applications can still be issued by the High Court, however there is no longer any requirement to record and process Wardship applications. There are occasional requests for searches on the Wardship Registers application for historic applications.

### GitHub team slug

dts-legacy

### Environments

| Environment   | Access level |
| ---     | --- |
|<ul><li>[X] Development</li></ul> | <ul><li>[ ] view-only</li><li>[ ] developer</li><li>[X] sandbox</li></ul> |
|<ul><li>[ ] Test</li></ul>   | <ul><li>[ ] view-only</li><li>[ ] developer</li></ul> |
|<ul><li>[X] Preproduction</li></ul>| <ul><li>[ ] view-only</li><li>[X] developer</li></ul> |
|<ul><li>[X] Production</li></ul> | <ul><li>[ ] view-only</li><li>[X] developer</li></ul> |

### Tags

tag | value
--- | ---
application | Wardship
business-unit | HMCTS
infrastructure-support | dts-legacy-apps-support-team@hmcts.net
owner | dts-legacy-applications:dts-legacy-apps-support-team@hmcts.net

### Subnet sets

- [X] General - this application will use the same subnet as other applications in your business unit
- [ ] Isolated - this application has highly sensitive data which must have its own isolated subnet with no network connectivity

### How do users connect to the application?

- [X] Over the public internet
- [ ] With a purple cabled device (please give details)
- [X] With a MoJ Official device

## Additional features

- [ ] Additional VPC Endpoints
- [ ] Extended DNS Zones
- [ ] Other - please specify

## Definition of done

- [ ] account created
- [X] customer informed

**Comment by SteveLinden** [comment]
PR #4549

**Comment by SteveLinden** [comment]
Account created
