### ISSUE TITLE
Environment Request for DACP

### ISSUE THREAD

**Issue by matt-k1998** [ministryofjustice/modernisation-platform#4510]
### Application Name

DACP

### Description of application

The Divorce Section Search Service (DACP) application is a business critical application that allows HMCTS Central Family court staff to maintain an internal searchable register of all decree absolutes applications, dissolutions of civil partnerships and same sex marriages applications Records searched for are for divorce decree absolutes (DA) only.

Divorce decree absolutes (DA) certificates are held by the issuing local court within the UK.

Key capabilities for staff users are:

    Create a public user application request record (DA request application) > via the 'Work Allocation’ feature
    View all open work allocations by month/year
    Quick Search > search results for previous searches carried out, using basic search criteria. Returns basic search results
    Ability to view selected case details > via the ‘Proceeding Details’ feature
    Search results > previous search results using multiple search criteria. Returns search results
    Ability to view selected previous search result and letter issued for that search result > via ‘Previous Search’ feature

### GitHub team slug

dts-legacy

### Environments

| Environment   | Access level |
| ---     | --- |
|<ul><li>[X] Development</li></ul> | <ul><li>[ ] view-only</li><li>[ ] developer</li><li>[X] sandbox</li></ul> |
|<ul><li>[ ] Test</li></ul>   | <ul><li>[ ] view-only</li><li>[ ] developer</li></ul> |
|<ul><li>[X] Preproduction</li></ul>| <ul><li>[ ] view-only</li><li>[X] developer</li></ul> |
|<ul><li>[X] Production</li></ul> | <ul><li>[ ] view-only</li><li>[X] developer</li></ul> |

### Tags

tag | value
--- | ---
application | DACP
business-unit | HMCTS
infrastructure-support | dts-legacy-apps-support-team@hmcts.net
owner | dts-legacy-applications:dts-legacy-apps-support-team@hmcts.net

### Subnet sets

- [X] General - this application will use the same subnet as other applications in your business unit
- [ ] Isolated - this application has highly sensitive data which must have its own isolated subnet with no network connectivity

### How do users connect to the application?

- [X] Over the public internet
- [ ] With a purple cabled device (please give details)
- [X] With a MoJ Official device

## Additional features

- [ ] Additional VPC Endpoints
- [ ] Extended DNS Zones
- [ ] Other - please specify

## Definition of done

- [ ] account created
- [X] customer informed

**Comment by SteveLinden** [comment]
Account created and the customer has been sent an email with a copy of our documentation and a link to the ask channel
