### ISSUE TITLE
Environment Request for pra-register

### ISSUE THREAD

**Issue by matthewsearle01** [ministryofjustice/modernisation-platform#4511]
## Environment details

pra-register

### Description of application

The Parental Responsibility Agreement Register (PRA) application is a business critical application that allows HMCTS Central Family court staff to register all Parental Responsibility Agreements (PRAs)  submitted to Central Family Court. Staff users can also view submitted PRAs within the lifecycle of the Agreement and search for agreements using selected criteria.

### GitHub team slug

dts-legacy

### Environments

| Environment   | Access level |
| ---     | --- |
|<ul><li>[X] Development</li></ul> | <ul><li>[ ] view-only</li><li>[ ] developer</li><li>[X] sandbox</li></ul> |
|<ul><li>[ ] Test</li></ul>   | <ul><li>[ ] view-only</li><li>[ ] developer</li></ul> |
|<ul><li>[X] Preproduction</li></ul>| <ul><li>[ ] view-only</li><li>[X] developer</li></ul> |
|<ul><li>[X] Production</li></ul> | <ul><li>[ ] view-only</li><li>[X] developer</li></ul> |

### Tags

tag | value
--- | ---
application | pra-register
business-unit | HMCTS
infrastructure-support | dts-legacy-apps-support-team@hmcts.net
owner | dts-legacy-applications:dts-legacy-apps-support-team@hmcts.net

### Subnet sets

- [X] General - this application will use the same subnet as other applications in your business unit
- [ ] Isolated - this application has highly sensitive data which must have its own isolated subnet with no network connectivity

### How do users connect to the application?

- [X] Over the public internet
- [ ] With a purple cabled device (please give details)
- [X] With a MoJ Official device

## Additional features

- [ ] Additional VPC Endpoints
- [ ] Extended DNS Zones
- [ ] Other - please specify

## Definition of done

- [ ] account created
- [X] customer informed

**Comment by markgov** [comment]
https://github.com/ministryofjustice/modernisation-platform/pull/4524

**Comment by markgov** [comment]
environment complete
