### ISSUE TITLE
Delete Xhibit portal snapshots older than 28 days old

### ISSUE THREAD

**Issue by davidkelliott** [ministryofjustice/modernisation-platform#4522]
## User Story

As a Modernisation Platform Engineer
I want to remove snapshots greater than 28 days old from the Xhibit Portal accounts
So that ongoing costs are reduced

## User Type(s)

MP user

## Value
Delete snapshots taken as backups in the xhibit-portal-production account older than 28 days old.
See thread here - https://mojdt.slack.com/archives/C01A7QK5VM1/p1685712004261419

The Xhibit portal team don't have the permissions to do this, and snapshots managed through AWS Backup are retired after 28 days so this will be mostly an admin task / chore that we undertake for them.

This ought to be easy to do manually with a little bash scripting, and can be done relatively quickly.

Save money and carbon

## Definition of done

- [ ] snapshots greater than 28 days old deleted
- [ ] xhibit portal team have reviewed

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by dms1981** [comment]
You can retrieve the snapshots with something like this:
`aws ec2 describe-snapshots --query "Snapshots[?StartTime<='$(date -u -v-28d '+%Y-%m-%dT%H:%M:%S')']"`

**Comment by dms1981** [comment]
Given the discrepancy between what I can see with the describe command, and the expectation of the XP team that around 11K snapshots need deleting, I've asked them to confirm how they filtered to get that result. Once we understand what they're after we can then remove the snapshots.

**Comment by dms1981** [comment]
As discussed on Slack [here](https://mojdt.slack.com/archives/C01B17VU6RY/p1691510974300889), the Xhibit Portal team have confirmed that anything over 28 days is in scope.

**Comment by ep-93** [comment]
So I removed 5k with a script, however the rest are protected via aws backup, in the vault called everything. 

we're down to 7250 recovery points to remove, a lot of them snapshots.

```
{
    "BackupVaultName": "everything",
    "BackupVaultArn": "REDACTED",
    "EncryptionKeyArn": "REDACTED",
    "CreationDate": "2021-10-06T14:25:58.471000+01:00",
    "NumberOfRecoveryPoints": 7250,
    "Locked": false
}
```

I have a command to do them one by one, but I'm trying to make a list of the arns and then loop through.

**Comment by ep-93** [comment]
Deleted all snapshots up to July 2023. Just over 28 days. 

`aws backup list-recovery-points-by-backup-vault --backup-vault-name everything | grep -B 15 2023-06 | sed -n 's/RecoveryPointArn//p' | grep snapshot/ | sed 's/^.*arn/arn/' |  sed 's/,//g' | sed 's/"//g'`

Used this and put it into a file, then read the file in with a delete command. 3700 snapshots down from the 15000 originally seems good.
