### ISSUE TITLE
Investigate and implement routing to use both NOMS VPN connections

### ISSUE THREAD

**Issue by dms1981** [ministryofjustice/modernisation-platform#4523]
## User Story

As a Modernisation Platform Customer 
I want to have a backup route to Azure Fix N' Go
So that if the primary route fails I have a backup route and my services do not suffer an outage

## User Type(s)

Modernisation Platform Customer

## Value

On Thursday July 6th, at 21:16 UTC, the primary live VPN connection between the Modernisation Platform and Azure Fix N' Go failed.
When this connection lost both tunnels, there was no route back to Azure Fix N' Go from the Modernisation Platform, leading to an application outage for approximately 30 minutes.

In order to prevent this we would like to investigate adding a static routes back to Azure Fix N' Go via the secondary live & secondary DR VPN connections between the Modernisation Platform and Azure Fix N' Go.

Doing so is fairly simple through code, but requires us to work with the probation webops team to apply configuration & test it without causing an outage to services.

## Definition of done

- [x] extra static routes for testing identified
- [x] static routes applied on MP TGW and tested
- [ ] static routes applied through code
- [ ] tests are green

## Reference

[Slack conversation detailing the outage](https://mojdt.slack.com/archives/C01A7QK5VM1/p1689063417350269)
[Log messages in core-network-services showing the outage in NOMS Live tunnel 1](https://eu-west-2.console.aws.amazon.com/cloudwatch/home?region=eu-west-2#logsV2:log-groups/log-group/NOMS-Transit-Live-VPN-VNG-1-vpn-attachment-logs/log-events/vpn-096d9fee372422221-3.11.198.152-IKE.log$3Fstart$3D1688678040000$26end$3D1688680800000$26filterPattern$3DDELETE) 
[Log messages in core-network-services showing the outage in NOMS Live tunnel 2](https://eu-west-2.console.aws.amazon.com/cloudwatch/home?region=eu-west-2#logsV2:log-groups/log-group/NOMS-Transit-Live-VPN-VNG-1-vpn-attachment-logs/log-events/vpn-096d9fee372422221-3.9.193.141-IKE.log$3Fstart$3D1688678040000$26end$3D1688680800000$26filterPattern$3DDELETE)
[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by SteveLinden** [comment]
Messaged [#ask-probation-webops](https://mojdt.slack.com/archives/C032BQQHJE5) to get a route set up we can use on development or test and asked for a contact.

**Comment by SteveLinden** [comment]
Had a reply and sent it to [#ask-digital-studio-ops ](https://mojdt.slack.com/archives/C6D94J81E/p1692021568966549) and I have had a response. Will discuss it with @dms1981 tomorrow


Dominic Robinson  [3:34 PM]
Hiya, for devtest, you can use
10.102.1.79
Port 22 should be reachable.  It’s our SSH bastion in Azure but it doesn’t matter if you break connectivity to it from Mod Platform
Dominic Robinson  [3:39 PM]
If you want to test from prod accounts, you can use
10.40.129.79
Again, port 22 should be reachable and nothing will break it connectivity is lost to that specific IP

**Comment by dms1981** [comment]
From investigation, this isn't possible. Adding duplicate static routes results in an error message.
