### ISSUE TITLE
Connectivity from MoJ Official devices to DIH Redshift

### ISSUE THREAD

**Issue by davidkelliott** [ministryofjustice/modernisation-platform#4538]
## User Story

Member request from Stephen Jobling direct via slack
Use Power BI on an MoJ Official device to access data in the Redshift cluster in data-and-insights-hub-wepi accounts

I believe the following is required - 

- firewall rule allowing traffic from global protect to hq-<environment> on port 5439
- VPC endpoint for Redshift

Routing from moj official devices to MP TGW should already be in place.

## User Type(s)

MP user

## Value

Allow users to securely access Redshift clusters locally.

## Definition of done

- [x] connectivity established
- [ ] Stephen Jobling has tested and able to access as required
- [x] another team member has reviewed
- [x] tests are green

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by SimonPPledger** [comment]
@davidkelliott to add requestor details

**Comment by dms1981** [comment]
Raised https://github.com/ministryofjustice/modernisation-platform/pull/4630, but this requires further discussion.

**Comment by dms1981** [comment]
Raised https://github.com/ministryofjustice/modernisation-platform/pull/4635 which should create the necessary endpoints and allow access from within the HQ VPCs (will need a further update to the VPC module to update the VPC endpoint security groups).

**Comment by dms1981** [comment]
Suggested customer use something like this to get traffic from AWS LB to Redshift VPC endpoints:
```
data "aws_vpc_endpoint" "redshift-data" {
  vpc_id       = data.aws_vpc.shared.id
  service_name = "com.amazonaws.eu-west-2.redshift-data"
}

data "aws_network_interface" "redshift-data" {
  for_each = data.aws_vpc_endpoint.redshift-data.network_interface_ids
  id       = each.value
}

resource "aws_lb" "redshift-data" {}
resource "aws_lb_target_group "redshift-data" {}
resource "aws_lb_target_group_attachment" "redshift data" {
  for_each         = data.aws_network_interface.redshift-data
  target_group_arn = aws_lb_target_group.redshift-data.arn
  target_id        = each.value.private_ip
  port             = 5439
}
```

**Comment by dms1981** [comment]
We're applied the necessary network firewall rules, updated the VPC nacls, the security group applied to the VPC endpoints, and created the `redshift-data` endpoints. When the `data-and-insights-hub` team have built a load balancer that uses the endpoints as targets, we'll be able to ask for confirmation that this has been sufficient.
