### ISSUE TITLE
New Role.

### ISSUE THREAD

**Issue by ep-93** [ministryofjustice/modernisation-platform#4541]
## User Story

https://mojdt.slack.com/archives/C01A7QK5VM1/p1689153385536339

As a Mod Platform user
I need to assign a github team and select number of permissions
So that they can perform their job.

## Value

They have too many permissions currently.

### Proposal

A similar bunch of permissions to instance-management however, with no sudo permissions via SSM. To find the exact permissions please contact Robert Sweetman.

### Unknowns

Not sure how we could share this amongst teams, which we need to think about when creating, as well as if it can be avoided by having something that removes team members from the wheel group once created? 

## Definition of done

- [ ] Decide on a new role or way to remove people from wheel group.
- [ ] Create new role if needed
- [ ] Add to role page in docs
- [ ] tests are green

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by SimonPPledger** [comment]
We don't want to create new roles
