### ISSUE TITLE
SPIKE: Can we post AWS Health messages to Slack?

### ISSUE THREAD

**Issue by dms1981** [ministryofjustice/modernisation-platform#4553]
## User Story

As a Modernisation Platform Engineer 
I want to be proactively notified of AWS Health Alerts
So that I don't have to check my emails to see Health Alerts

## User Type(s)

Modernisation Platform Customer

## Value

First, is it possible to set up something that publishes an AWS Health message to something like an SNS topic that then puts a message into Slack?

Second, what would be involved in getting AWS Health messages from all of the accounts in the Modernisation Platform?

### Hypothesis 
If we have Slack messages for AWS Health Alerts
Then we will be more likely to see those alerts

### Proposal
If we get the right signal-to-noise ratio then we can have AWS Health Alerts show up that we will see in a timely fashion, allowing us to respond to alerts faster 

### Unknowns
If we did do this, could we do it through Terraform? Where would we do this? In the `member-bootstrap`?

## Definition of done

- [ ] spike has been appropriately timeboxed
- [ ] method to send health alerts to slack identified
- [ ] consider ways to get alerts from all modernisation platform accounts
- [ ] document outcomes in comments
- [ ] raise following stories as appropriate

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by ASTRobinson** [comment]
```hcl
provider "aws" {
  region = "us-east-1"  # Update with your desired region
}

resource "aws_cloudwatch_event_rule" "aws_health_events" {
  name = "aws_health_events"
  description = "Rule to trigger on AWS Health events"
  
  event_pattern = <<EOF
{
  "source": ["aws.health"],
  "detail-type": ["AWS Health Event"],
  "resources": ["arn:aws:health:*:*:event/*"],
  "detail": {
    "service": ["EC2", "RDS"]  # Update with desired services
  }
}
EOF
}

resource "aws_lambda_function" "send_to_slack" {
  filename      = "send_to_slack.zip"
  function_name = "send_to_slack"
  role          = aws_iam_role.lambda.arn
  handler       = "index.handler"
  runtime       = "nodejs14.x"

  source_code_hash = filebase64sha256("send_to_slack.zip")
}

resource "aws_iam_role" "lambda" {
  name = "lambda_role"

  assume_role_policy = jsonencode({
    Version = "2012-10-17",
    Statement = [{
      Action = "sts:AssumeRole",
      Effect = "Allow",
      Principal = {
        Service = "lambda.amazonaws.com"
      }
    }]
  })
}

resource "aws_iam_policy" "lambda" {
  name        = "lambda_policy"
  description = "Policy for sending messages to Slack"

  policy = jsonencode({
    Version = "2012-10-17",
    Statement = [{
      Action = "logs:CreateLogGroup",
      Effect = "Allow",
      Resource = "*"
    }, {
      Action = ["logs:CreateLogStream", "logs:PutLogEvents"],
      Effect = "Allow",
      Resource = "arn:aws:logs:*:*:*"
    }, {
      Action = "health:DescribeEvents",
      Effect = "Allow",
      Resource = "*"
    }]
  })
}

resource "aws_iam_policy_attachment" "lambda" {
  name = "lambda_policy_attachment"
  policy_arn = aws_iam_policy.lambda.arn
  roles      = [aws_iam_role.lambda.name]
}

resource "aws_lambda_permission" "allow_cloudwatch" {
  statement_id  = "AllowExecutionFromCloudWatch"
  action        = "lambda:InvokeFunction"
  function_name = aws_lambda_function.send_to_slack.arn
  principal     = "events.amazonaws.com"

  source_arn = aws_cloudwatch_event_rule.aws_health_events.arn
}

# Create a ZIP file containing your Lambda code (index.js and any other dependencies)
# Deploy the ZIP file to AWS Lambda and configure necessary environment variables
# Include Slack webhook URL as an environment variable
# Implement the Lambda code to parse AWS Health events and send messages to Slack

```

**Comment by ASTRobinson** [comment]
above is an Terraform example for sending AWS Health Messages to Slack.

**Comment by ASTRobinson** [comment]
Ideally [AWS Health Aware](https://aws.amazon.com/blogs/mt/aws-health-aware-customize-aws-health-alerts-for-organizational-and-personal-aws-accounts/) can be setup and configured using the terraform examples on there GitHub page https://github.com/aws-samples/aws-health-aware/

**Comment by ASTRobinson** [comment]
Story created for implementation https://github.com/ministryofjustice/modernisation-platform/issues/4787
