### ISSUE TITLE
Create dedicated page for roles.

### ISSUE THREAD

**Issue by ep-93** [ministryofjustice/modernisation-platform#4587]
## User Story

Confusion about the roles that the platform has and what they do occurs often, so by defining each role and also the process a user needs to take in requesting a new one, we will hopefully reduce any role duplication.

We have agreed on sticking to the current method, however creating a page for roles, and having role creation and links to our roles is a minimum. 

## Value

Having defined roles and a process on our docs will help users understand it. 

## Definition of done

- [x] Page has been created
- [x] Role creation process has been defined 
- [x] Each role is defined with links to code

## Reference

https://github.com/ministryofjustice/modernisation-platform/issues/4184

**Comment by davidkelliott** [comment]
We have documentation on this here - https://user-guide.modernisation-platform.service.justice.gov.uk/user-guide/creating-environments.html#access but it is within the creating envs docs

**Comment by dms1981** [comment]
NB. Although each role is defined, there's no direct mapping of role-to-policy because as we make changes to the policies.tf document those links will quickly become outdated.
