### ISSUE TITLE
Add RDS instances to instance scheduler

### ISSUE THREAD

**Issue by davidkelliott** [ministryofjustice/modernisation-platform#4673]
## User Story

As a platform user
I want RDS instances to be shutdown by the instance scheduler as well
So that I can save money and carbon

## User Type(s)

MP users

## Value

Save money and carbon

## Definition of done

- [x] RDS instances added to instance scheduler
- [x] Tests updated
- [x] user docs have been updated
- [ ] another team member has reviewed
- [x] tests are green

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by markgov** [comment]
Code created but not tested yet

**Comment by markgov** [comment]
https://github.com/ministryofjustice/modernisation-platform-instance-scheduler/pull/478

**Comment by markgov** [comment]
code updated

**Comment by markgov** [comment]
Mock ing of the rds side has been completed and starting to implement testing functions of the main code

**Comment by markgov** [comment]
Code has now been merged and should start shutting down RDS instances as of tonight
