### ISSUE TITLE
Investigate DNS failover

### ISSUE THREAD

**Issue by jakemulley** [ministryofjustice/modernisation-platform#476]
## User Story

As a person who uses a service on the Modernisation Platform
I want the service to be highly available, even if Route53 is disrupted
So that I can continue using the service if it is an isolated incident

## Value

[Operations Engineering](https://github.com/ministryofjustice/operations-engineering/issues/30) have an item on their backlog for DNS failover for most justice.gov.uk domains. We should look at also supporting a similar mitigation on the Modernisation Platform, so we can quickly switch DNS providers if required.

## Questions / Assumptions

- Is it viable?
- What tools are out there to help us with this?

## Definition of done

- [ ] documentation about our findings are public
- [ ] another team member has reviewed

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by dms1981** [comment]
This one is likely to be quite complicated to implement. If we're talking about a situation where Route53 goes down, the impact of that to other AWS services would be such that even if we were able to direct users to applications hosted on the modernisation platform, there's a high likelihood that they'd be experiencing issues internally.
If we're talking about a separate way of publishing DNS records then that brings up a question of how we'd handle orchestration - where would we publish records, how would we decide which DNS provider is authoritative, and what would we do to trigger a failover / failback?
CDDO *do* discuss having multiple suppliers, however, so it may be worth an ask in that direction to ask what they've seen done successfully? https://www.gov.uk/service-manual/technology/get-a-domain-name#choose-where-youll-host-your-dns

**Comment by SimonPPledger** [comment]
we will not progress this work
