### ISSUE TITLE
Manage Collaborators Deployment Reviewers in code

### ISSUE THREAD

**Issue by ASTRobinson** [ministryofjustice/modernisation-platform#4761]
## User Story

As a user of the Modernisation Platform
I want to be able to manage deployment reviewers in code.
So that we reduce the number of queries in the ask channel from users who have been manually added and then automatically overwritten from a deployment. 

## User Type(s)
Manually added (click-ops) Deployment Reviewers.

## Value
Helping to maintain our goals and principles of Infrastructure as Code (IaC) wherever possible and also reducing queries in the ask channel requesting users to be added and/or approving deployments. 

## Definition of done

- [x] Have a collaborator review deployments via code (not just terraform, maybe a script, whatever is possible)
- [x] Update docs on collaborators
- [x] another team member has reviewed
- [x] tests are green

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by dms1981** [comment]
A few thoughts on this one: can we add the collaborator slugs to the `environments/$application.json` and then use some `jq` to retrieve them and patch them in through the `git-create-environments.sh` script?
I know it's a second place to add collaborators, but I think it's a better approach to keep application-specific options in the app json.

**Comment by ASTRobinson** [comment]
reference for previous unmerged issue / pr to amend deployment reviewers https://github.com/ministryofjustice/modernisation-platform/issues/4516

**Comment by ASTRobinson** [comment]
Created a branch containing the wip for the new function to add additional reviewers ( https://github.com/ministryofjustice/modernisation-platform/compare/main...feature/additional-reviewers )

**Comment by ASTRobinson** [comment]
PR merged in containing the new add_additional_reviewers function https://github.com/ministryofjustice/modernisation-platform/pull/4945

**Comment by ASTRobinson** [comment]
https://github.com/ministryofjustice/modernisation-platform/pull/4950 merged in following some issues with the script. however, this still does not update GitHub correctly and nothing obvious in the logs to explain why. I will need to add the debug flag (set -x) back in and then update an environment to hopefully catch the error. or try and get https://github.com/nektos/act running locally to test.

**Comment by ASTRobinson** [comment]
PR Ready for review: https://github.com/ministryofjustice/modernisation-platform/pull/5014

**Comment by ASTRobinson** [comment]
another documentation update (https://github.com/ministryofjustice/modernisation-platform/pull/5026) and removal of additional debugging flags (https://github.com/ministryofjustice/modernisation-platform/pull/5024). All completed and working as expected, I am therefore closing this ticket.
