### ISSUE TITLE
Create permission set for users to access MWAA

### ISSUE THREAD

**Issue by jacobwoffenden** [ministryofjustice/modernisation-platform#4791]
## User Story

As a platform engineer,
I want to create a permission set
So data engineering/science team members can access MWAA, and only MWAA

## User Type(s)

platform engineering and data engineering

## Value

Analytical and Data Platforms are consolidating our MWAA infrastructure and migrating it to Modernisation Platform. In doing so, we lose the ability to offer fine grained permissions using our Alpha identity system. The data engineering role offered by MP currently is too broad and we would prefer a role that is scoped specifically to accessing MWAA

## Proposal
Relevant resources are created that ultimately map to the following policy, where `${MWAA_ENVIRONMENT}` will probably be `*`

```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": "airflow:CreateWebLoginToken",
            "Resource": [
                "arn:aws:airflow:${AWS_REGION}:${AWS_ACCOUNT}:role/${MWAA_ENVIRONMENT}/User"
            ]
        }
    ]
}
```

## Definition of done

- [ ] permission set created
- [ ] can access MWAA as `User` using assumed role

## Reference

I did start creating these, but less generic https://github.com/ministryofjustice/data-platform/issues/791#issuecomment-1634297755

https://docs.aws.amazon.com/mwaa/latest/userguide/access-policies.html#web-ui-access

**Comment by dms1981** [comment]
https://docs.aws.amazon.com/mwaa/latest/userguide/access-policies.html

**Comment by dms1981** [comment]
This one has been solved via this PR: https://github.com/ministryofjustice/aws-root-account/pull/765
You should now have the access level of `data-platform-mwaa-user` available to assign github slugs to via `terraform/environments/$application.json`.

Moving this one to closed, but will reopen if @jacobwoffenden finds that it's unsuitable or something is missing.
