### ISSUE TITLE
New MP accounts for Data Platform

### ISSUE THREAD

**Issue by murdo-moj** [ministryofjustice/modernisation-platform#4794]
### Application Name

data-platform

### GitHub team slug

data-platform-labs

### Environments

We currently have a development account, but we would like accounts and workflows for Test, Preprod, and Prod. 

| Environment   | Access level |
| ---     | --- |
|<ul><li>[ ] Development</li></ul> | <ul><li>[ ] view-only</li><li>[ ] developer</li><li>[ ] sandbox</li></ul> |
|<ul><li>[x] Test</li></ul>   | <ul><li>[x] view-only</li><li>[X] developer</li></ul> |
|<ul><li>[x] Preproduction</li></ul>| <ul><li>[x] view-only</li><li>[X] developer</li></ul> |
|<ul><li>[x] Production</li></ul> | <ul><li>[x] view-only</li><li>[X] developer</li></ul> |

### Tags

tag | value
--- | ---
application | data-platform
business-unit | Platforms
infrastructure-support | dataplatform@digital.justice.gov.uk
owner | dataplatform@digital.justice.gov.uk

### Subnet sets

- [x] General - this application will use the same subnet as other applications in your business unit
- [ ] Isolated - this application has highly sensitive data which must have its own isolated subnet with no network connectivity

### How do users connect to the application?

- [x] Over the public internet
- [ ] With a purple cabled device (please give details)
- [x] With a MoJ Official device

## Additional features

- [ ] Additional VPC Endpoints
- [ ] Extended DNS Zones
- [ ] Other - please specify

## Definition of done

- [ ] account created
- [ ] customer informed

**Comment by dms1981** [comment]
https://github.com/ministryofjustice/modernisation-platform/pull/4785/files << This PR shows an example of what I think @murdo-moj is after, only for a different application.

**Comment by SteveLinden** [comment]
Request states they only want view-only so I will email to get confirmation. Not sure view only is really what they want/need

**Comment by SteveLinden** [comment]
Clarified the requirements. Read only and developer are required.

**Comment by SteveLinden** [comment]
Initial PR - #4871

**Comment by SteveLinden** [comment]
We had a number of issues so there were a few other PRs #4873 #4876 #4877

**Comment by SteveLinden** [comment]
Looks complete now
