### ISSUE TITLE
Refactor EC2 module

### ISSUE THREAD

**Issue by markgov** [ministryofjustice/modernisation-platform#4803]
## User Story

As a modernisation platform engineer
I want to allow a new variable to be passed
so that i can exclude items from being included in the aws backup routine 

## Value

we need to amend the current EC2 module in the following repo https://github.com/ministryofjustice/modernisation-platform-terraform-ec2-instance?ref=v2.1.0 to allow the passing of a  new backup input that has been created as part of [AWS Backup exclusion tags #4802](https://github.com/ministryofjustice/modernisation-platform/issues/4802) this ticket can not be done without that ticket being completed

this modification is needed so that new elements can be passed into the module that can exclude ebs volumes from being backed up as part of the standard backup this is a continuation of issue [Duplicate Backup#4466](https://github.com/ministryofjustice/modernisation-platform/issues/4466)

This should help eliminate duplicate backups from being created

## Definition of done

- [ ] Module updated
- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] tests are green

**Comment by ewastempel** [comment]
The functionality is there already and it's using the backup tags being set in general or on EC2 or EBS.
Tests were implemented to test the logic and the README was updated to provide guidance when setting the tags in code.
