### ISSUE TITLE
New account hmpps-domain-services

### ISSUE THREAD

**Issue by drobinson-moj** [ministryofjustice/modernisation-platform#4845]
### Application Name

hmpps-domain-services

### Description of application

Provides domain services to other HMPPS applications.  For example, provides azure.hmpp.root and azure.noms.root NTLM to corporate-staff-rostering and planetfm applications.

### GitHub team slug

@ministryofjustice/studio-webops

### Environments

| Environment   | Access level |
| ---     | --- |
|<ul><li>[ ] Development</li></ul> | <ul><li>[ ] view-only</li><li>[ ] developer</li><li>[x] sandbox</li></ul> |
|<ul><li>[ ] Test</li></ul>   | <ul><li>[ ] view-only</li><li>[x] developer</li></ul> |
|<ul><li>[ ] Preproduction</li></ul>| <ul><li>[ ] view-only</li><li>[x] developer</li></ul> |
|<ul><li>[ ] Production</li></ul> | <ul><li>[ ] view-only</li><li>[x] developer</li></ul> |

### Tags

tag | value
--- | ---
application | hmpps-domain-services
business-unit | HMPPS
infrastructure-support | digital-studio-operations-team@digital.justice.gov.uk
owner | sean.privett@digital.justice.gov.uk

### Subnet sets

- [x] General - this application will use the same subnet as other applications in your business unit
- [ ] Isolated - this application has highly sensitive data which must have its own isolated subnet with no network connectivity

### How do users connect to the application?

- [ ] Over the public internet
- [ ] With a purple cabled device (please give details)
- [x] With a MoJ Official device

### Connectivity to other applications or external parties

Connectivity to Azure FixNGo and other applications within HMPPS VPC.  Note this is already in place)

## Additional features

- [ ] Additional VPC Endpoints
- [ ] Extended DNS Zones
- [ ] Other - please specify

## Definition of done

- [ ] account created
- [ ] customer informed

**Comment by connormaglynn** [comment]
The [environment has been created](https://github.com/ministryofjustice/modernisation-platform-environments/tree/main/terraform/environments/hmpps-domain-services) and [pipelines are working](https://github.com/ministryofjustice/modernisation-platform-environments/actions/runs/5941107467).

Customers informed via [email](https://groups.google.com/a/digital.justice.gov.uk/g/modernisation-platform/c/4k74rGc1BAs).
