### ISSUE TITLE
Oracle 10g Module build

### ISSUE THREAD

**Issue by zuriguardiola** [ministryofjustice/modernisation-platform#486]
## User Story
Create Oracle 10g TF module to use in legacy migrations. 

## Value

Create modules for Oracle 10g installs which will be useful during LAA (possibly others) migrations on to Mod Platform.

## Definition of done

- [ ] Create TF module
- [ ] Test by provisioning ec2 instance
- [ ] Document any findings

**Comment by davidkelliott** [comment]
Most likely these type of builds will be done via the AMI builder now
