### ISSUE TITLE
Investigate regularly failing workflows

### ISSUE THREAD

**Issue by davidkelliott** [ministryofjustice/modernisation-platform#4872]
## User Story

As an MP engineer
I want to reduce the amount of workflow failures
So that we have more successful deployments

## User Type(s)

MP engineers

## Value

Less deployment failures
More consistent deployments

### Hypothesis 
If we search for failed workflows on main branches in our repositories (excluding environments repo)
Then we can see which ones are regularly failing and try to improve them

### Proposal
Search github for failed workflows on main:

https://github.com/ministryofjustice/modernisation-platform/actions?query=is%3Afailure+branch%3Amain+

Go through them and see which ones can be fixed, if they are failing regularly and not being addressed do we need a slack alert for them?

### Unknowns
We have data from DORA metrics which indicates around 50% of our workflows fail.  We don't know where these are now, if there is a lot of work to be done we may need to split this out into smaller issues.

## Definition of done

- [ ] workflows across all repos excluding the environments repo analysed:
  - [x] modernisation-platform
  - [x] modernisation-platform-terraform-ec2-autoscaling-group
  - [x] modernisation-platform-ami-builds
  - [x] modernisation-platform-terraform-ec2-instance
  - [x] modernisation-platform-configuration-management
  - [x] modernisation-platform-terraform-ecs
  - [x] modernisation-platform-cp-network-test
  - [x] modernisation-platform-terraform-ecs-cluster
  - [x] modernisation-platform-terraform-environments
  - [x] modernisation-platform-github-oidc-provider
  - [x] modernisation-platform-terraform-iam-superadmins
  - [x] modernisation-platform-github-oidc-role
  - [x] modernisation-platform-terraform-lambda-function
  - [x] modernisation-platform-terraform-loadbalancer
  - [x] modernisation-platform-terraform-member-vpc
  - [x] modernisation-platform-infrastructure-test
  - [x] modernisation-platform-instance-scheduler
  - [x] modernisation-platform-terraform-pagerduty-integration
  - [x] modernisation-platform-terraform-aws-vm-import
  - [x] modernisation-platform-terraform-s3-bucket
  - [x] modernisation-platform-terraform-baselines
  - [x] modernisation-platform-terraform-s3-bucket-replication-role
  - [x] modernisation-platform-terraform-bastion-linux
  - [x] modernisation-platform-terraform-ssm-patching
  - [x] modernisation-platform-terraform-cross-account-access
  - [x] modernisation-platform-terraform-trusted-advisor 
- [ ] workflows to fix identified
- [ ] workflows fixed or issues created to fix
- [ ] another team member has reviewed
- [ ] tests are green

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by ewastempel** [comment]
@ewastempel is working on the `modernisation-platform`

**Comment by SteveLinden** [comment]
@SteveLinden picked up the modernisation-platform-terraform-baselines code

**Comment by connormaglynn** [comment]
@connormaglynn looking at `modernisation-platform-instance-scheduler` 👀

**Comment by SteveLinden** [comment]
Search incorrect. I will look again.

**Comment by SteveLinden** [comment]
Added some chatbot ignores to modernisation platform terraform-baselines

**Comment by SteveLinden** [comment]
Repeated the same for the s3-bucket one.

**Comment by SteveLinden** [comment]
Waiting for the above releases to be approved so I will look at modernisation-platform-terraform-trusted-advisor

**Comment by connormaglynn** [comment]
`modernisation-platform-instance-scheduler` integration tests fixed and [this ticket](https://github.com/orgs/ministryofjustice/projects/17/views/1?sortedBy%5Bdirection%5D=asc&sortedBy%5BcolumnId%5D=1564443&pane=issue&itemId=38266976) has been created to remedy potential future issues

**Comment by ewastempel** [comment]
Analysis from `modernisation-platform` repository workflows:
```
Repo: https://github.com/ministryofjustice/modernisation-platform
Workflows: failed in main (search: "is:failure branch:main")
Workflow Name                         | Failure number  |               Comments            |    Action
______________________________________|_________________|___________________________________|________________
format-code.yml                       | 51              | no logs available                 | none
add-issues-to-project.yml             | 8               | no logs available                 | none
bootstrap-sprinkler.yml               | 0               | -                                 | none
close-stale-prs.yml                   | 0               | -                                 | none
core-logging-deployment.yml           | 6               | no logs available                 | none
core-network-services-deployment.yml  | 34              | run #1351 - timeout issue         | rerun and fixed 
                                      |                 | run #1338 - unknown               | fixed forward
                                      |                 | run #1312 - bad code              | fixed forward
                                      |                 | run #1309 - unknown               | fixed forward
                                      |                 | other runs have no logs           | none
core-security-deployment.yml          | 2               | no logs available                 | none
core-shared-services-deployment.yml   | 38              | state lock issue                  | none
core-vpc-development-deployment.yml   | 26              | run #994 - bad code               | fixed forward
                                      |                 | run #991 - bad code               | fixed forward
                                      |                 | run #986 - bad code               | fixed forward
                                      |                 | run #978 - bad code               | fixed forward
                                      |                 | run #976 - bad code               | fixed forward
                                      |                 | other runs have no logs           | none
core-vpc-preproduction-deployment.yml | 26              | bad code - same PRs as in dev     | fixed forward
core-vpc-production-deployment.yml    | 23              | bad code - same PRs as in dev     | fixed forward
core-vpc-test-deployment.yml          | 24              | bad code - same PRs as in dev     | fixed forward
generate-dependabot-file.yml          | 0               | -                                 | none
documentation.yml                     | 0               | -                                 | none
new-environment-files.yml             | 0               | -                                 | none
opa-policies.yml                      | 0               | -                                 | none
pages-build-deployment                | 0               | -                                 | none
publish-gh-pages.yml                  | 4               | run #160 - bad code               | fixed forward
labeler.yml                           | 0               | -                                 | none
scorecards.yml                        | 31              | mostly timeout issue when uploadi | 
                                      |                 | ng the artifact SARIF file from   |
                                      |                 | 2 months ago;                     |
                                      |                 | ScoreCards found 3 HIGH vulnerabil| create a ticket
                                      |                 | ities: https://github.com/ministr | to fix vulnerabilities
                                      |                 | yofjustice/modernisation-platform |
                                      |                 | /security/code-scanning           |
code-scanning.yml                     | 112             | all fixed/suppressed, mostly for: | create a ticket
                                      |                 | # checkov:skip=CKV2_AWS_57        | to revisit fixing CKV_AWS_149
                                      |                 | # checkov:skip=CKV_AWS_149        | to use customer-managed KMS 
SonarCloud analysis                   | 0               | workflow no longer exists         | none
terraform-static-analysis.yml         | 233             | all fixed/suppressed, mostly for: | same ticket as for
                                      |                 | # checkov:skip=CKV2_AWS_57        | code-scanning.yml
                                      |                 | # checkov:skip=CKV_AWS_149        | 
terraform-github.yml                  | 14              | run #1250 - actions secrets rate  |
                                      |                 | limit exceeded                    | none
terraform-member-environment.yml      | 4               | bad code mostly, no longer issue  | fixed forward
terraform-pagerduty.yml               | 4               | bad code mostly, no longer issue  | fixed forward
scheduled-baseline.yml                | 91              | noticed some pipelines were never | should aim to rerun failed
                                      |                 | rerun, but scheduled runs take ca | deployments when merging
                                      |                 | of it; latest run passes          |
Testing slack message                 | 0               | the workflow no longer exists     | none
Testing SSO assumption                | 0               | the workflow no longer exists     | none
```

Summarising, three tickets to be created:
1. SonarCloud vulnerability issues: https://github.com/ministryofjustice/modernisation-platform/security/code-scanning
2. Chekov issue:
terraform-static-analysis.yml : https://github.com/ministryofjustice/modernisation-platform/actions/runs/5923065434/job/16058039084
code-scanning.yml: https://github.com/ministryofjustice/modernisation-platform/actions/runs/5921047939/job/16053081949
3. Additionally add a ticket to update all pipelines to use slack notifications when a pipeline fails.

**Comment by SteveLinden** [comment]
New issue for the s3-bucket created with Ewa's comment in there. #4996

**Comment by connormaglynn** [comment]
Looked at [modernisation-platform-cp-network-test](https://github.com/ministryofjustice/modernisation-platform-cp-network-test). Only failing pipeline on main was the [Secure Code Analysis](https://github.com/ministryofjustice/modernisation-platform-cp-network-test/actions/workflows/code-scanning.yml) from over 5 months ago, though they've been running fine since

GitHub had disabled the scheduled actions due to inactivity, which I've now re-enabled. This feature is probably something to be mindful of if we're depending on scheduled checks for inactive repos🤔

**Comment by SteveLinden** [comment]
modernisation-platform-terraform-ssm-patching - checkov errors relate to calling the test area. I have commented out (#checkov:skip=) the offending items as they do not appear to be related to what we want to do

**Comment by ewastempel** [comment]
@ewastempel is picking up `[modernisation-platform-terraform-ecs-cluster](https://github.com/ministryofjustice/modernisation-platform-terraform-ecs-cluster)`

**Comment by SteveLinden** [comment]
Changes to modernisation-platform-terraform-ssm-patching have been pushed through. I will check the results tomorrow to see if that fixes the checkov issues.

**Comment by ewastempel** [comment]
@ewastempel is picking up  [`modernisation-platform-terraform-iam-superadmins`](https://github.com/ministryofjustice/modernisation-platform-terraform-iam-superadmins)

**Comment by SteveLinden** [comment]
Still trying to fix the tfsec error. Changing the scan_type to changed so, in theory, it should ignore other bits. Bit of a desperate change more in hope than anticipation. The error doesn't cause an issue but shows up as a fail on the actions list.
This is for modernisation-platform-terraform-trusted-advisor initially. If it does fix it I will do it for modernisation-platform-terraform-ssm-patching too.

**Comment by SteveLinden** [comment]
modernisation-platform-terraform-cross-account-access had been failing on the tfsec part of the routine. This has been working for the past 3 weeks so it appears to be fixed,

**Comment by dms1981** [comment]
Applied fixes / addressed security code analysis alerts for the following repositories :
* modernisation-platform-infrastructure-test
* modernisation-platform-terraform-aws-vm-import
* modernisation-platform-terraform-bastion-linux
* modernisation-platform-terraform-pagerduty-integration
* modernisation-platform-terraform-s3-bucket-replication-role

**Comment by SteveLinden** [comment]
I've checked  modernisation-platform-github-oidc-role and there are no errors showing other than dependabot issues.

Also checked  modernisation-platform-incident-response which had lots of errors but I have been informed that this should not be on the list and the git should have been archived.

**Comment by SteveLinden** [comment]
The version of  modernisation-platform-terraform-ecs in the library is archived so this has not been looked at - last run was 6 months ago.

**Comment by SteveLinden** [comment]
modernisation-platform-configuration-management - only failures are undertaken by user groups so this does not need any changes at the moment.

**Comment by SteveLinden** [comment]
Lookin at modernisation-platform-terraform-iam-superadmins

**Comment by dms1981** [comment]
modernisation-platform-terraform-member-vpc - this one passes security checks now

**Comment by SteveLinden** [comment]
modernisation-platform-terraform-lambda-function has not general failures but there are issues go tests such as being unable to find credentials ( Error: No valid credential sources found) or invalid count (Error: Invalid count argument) but they are infrequent

**Comment by SteveLinden** [comment]
Looking at **modernisation-platform-github-oidc-provider** which has one checkov failure that should be cured with the addition of another condition (CKV_AWS_358: "Ensure GitHub Actions OIDC trust policies only allows actions from a specific known organization") and should be relatively easy to fix.

**Comment by SteveLinden** [comment]
PR for the above has been posted. It's [here](https://github.com/ministryofjustice/modernisation-platform-github-oidc-provider/pull/228)

**Comment by markgov** [comment]
PR added for documentation workflow error on  modernisation-platform-terraform-ec2-instance

**Comment by markgov** [comment]
PR added for documentation workflow error on modernisation-platform-terraform-ec2-autoscaling-group
https://github.com/ministryofjustice/modernisation-platform-terraform-ec2-autoscaling-group/pull/191

**Comment by davidkelliott** [comment]
https://github.com/ministryofjustice/modernisation-platform-terraform-s3-bucket/actions/runs/6705525744/job/18220159561

**Comment by dms1981** [comment]
I'll pick up the S3 bucket checks today
