### ISSUE TITLE
Update `tflint` references

### ISSUE THREAD

**Issue by dms1981** [ministryofjustice/modernisation-platform#4916]
## User Story

As a Modernisation Platform Engineer
I want to update our `tflint` workflows
So that we can actively use `tflint` as part of our secure code analysis

## User Type(s)

Modernisation Platform Engineer

## Value

In a recent update the `tflint` tool used in our `code-scanning.yml` workflows has updated to a version which reports errors with our configured usage:
```
Running tflint in .
Command line arguments support was dropped in v0.47. Use --chdir or --filter instead.
tflint_exitcode=1
```
We should update our `code-scanning.yml` workflows across repositories to fix this error.
From a quick check of my local copies of modernisation platform repositories I could see around 83 separate uses of this action in yaml files.

You can see the release where the command line arguments were deprecated here: https://github.com/terraform-linters/tflint/releases/tag/v0.47.0

The pull request that shows the deprecations being implemented is available here: https://github.com/terraform-linters/tflint/pull/1687

## Definition of done

- [ ] solution found and applied for one repository
- [ ] solution applied consistently across team repositories via scripting
- [ ] another team member has reviewed
- [ ] tflint / secure code analysis checks pass without deprecation error

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by ASTRobinson** [comment]
after investigating the issue I have discovered that this was resolved under PR https://github.com/ministryofjustice/github-actions/pull/202 and am therefore closing this issue.
