### ISSUE TITLE
modernisation-platform-terraform-trusted-advisor upgrade nodejs to 18

### ISSUE THREAD

**Issue by ep-93** [ministryofjustice/modernisation-platform#4965]
## Expected Behavior

It should work.

## Actual Behavior

It does not.

## Steps to Reproduce the Problem

Deploy v18 of nodejs to the module and test it, it errors.

## Other information

This might be why - https://aws.amazon.com/blogs/developer/why-and-how-you-should-use-aws-sdk-for-javascript-v3-on-node-js-18/

**Comment by ewastempel** [comment]
Implemented with: 
https://github.com/ministryofjustice/modernisation-platform-terraform-trusted-advisor/pull/196
 https://github.com/ministryofjustice/modernisation-platform/pull/4966
