### ISSUE TITLE
Add manual static routes for VPN to Azure

### ISSUE THREAD

**Issue by seanprivett** [ministryofjustice/modernisation-platform#4974]
## User Story

The VPN to Azure goes down whenever Microsoft do regular security patches. MP team understands why this is - there is an issue with BGP. Suggestion from David Sibley is "add manual static routes that matched the advertised networks and pointed them via the PTTP TGW"

## Value

This becomes more critical and valuable as more services go into production from Azure to MP. The value is in providing a stable VPN.
## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by SimonPPledger** [comment]
we cannot do this directly, as Azure has too many IPs - this would impact other traffic. so we might need to add some other static routes

**Comment by dms1981** [comment]
As I see this, the path to introducing routes propagated via BGP into the inspection route table looks like this:
* Add manual static routes matching those being advertised to ensure a consistent flow of traffic to Azure via the MOJ TGW (https://github.com/ministryofjustice/modernisation-platform/pull/5111)
* Activate propagation from the NOMS VPN connections to the inspection route table
* Remove NOMS static routes from the inspection route table and confirm that propagated routes are installed to replace them

**Comment by dms1981** [comment]
https://github.com/ministryofjustice/modernisation-platform/pull/5120
^^ This PR configures the propagation as discussed in my last comment

**Comment by dms1981** [comment]
https://github.com/ministryofjustice/modernisation-platform/pull/5122
^^ This PR removes the now-unneccesary static routes
