### ISSUE TITLE
Spike: Explore how we can enable AWS Chatbot

### ISSUE THREAD

**Issue by ewastempel** [ministryofjustice/modernisation-platform#4987]
## User Story

As a platform user
I want to receive event messages in slack orchestrated by AWS Chatbox
So that I know when a resource configuration changes

## User Type(s)

MP platform users.
MP engineers.

## Value

Notifications that are not necessary incidents/alerts can get posted to slack without a need for PagerDuty configuration.

### Proposal
Rather than adding `chatbox` permissions to the developer role, we want to enable provide it as a module.
A couple of options were discussed in this [thread](https://mojdt.slack.com/archives/C013RM6MFFW/p1694422939680059), where the [AWS cloud control](https://registry.terraform.io/providers/hashicorp/awscc/latest/docs/resources/chatbot_slack_channel_configuration) looked like the best candidate. 

## Definition of done
- [ ] working example of using Chatbox with slack
- [ ] ticket for creating a chatbox tf module repo that is based on the outcome of this spike
- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] tests are green

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by SteveLinden** [comment]
Attempted to play around with this to see if I can get it sending something to slack (new channel modernisation-platform-chatbot-test) but I am continuingly getting an error. It could be it's my ID and it's using a default but the error is 

AWS Chatbot can't create the Slack channel configuration.
User: arn:aws:sts::348456244381:assumed-role/AWSReservedSSO_AdministratorAccess_a7491ea25c15715b/stevelinden@digital.justice.gov.uk is not authorized to perform: iam:PassRole on resource: arn:aws:iam::348456244381:role/aws-reserved/sso.amazonaws.com/eu-west-2/AWSReservedSSO_AdministratorAccess_a7491ea25c15715b with an explicit deny

This is on sprinkler but I was getting the same repeatedly on Modernisation Platform too. This was in spite of me adding addiotnal access rights to iam:PassRole

**Comment by SteveLinden** [comment]
May return to this once the checkov change has been completed.

**Comment by SimonPPledger** [comment]
This has been enabled as part of the work Rich has been doing ....
