### ISSUE TITLE
Give members access to firewall logs and core networking

### ISSUE THREAD

**Issue by davidkelliott** [ministryofjustice/modernisation-platform#5001]
## User Story

As an MP user
I want to inspect firewall logs and core networking VPCs and firewall rules
So that I can troubleshoot network connectivity.

Need to check there is not one already

## User Type(s)

MP users

## Value

Enable users to solve their own problems

### Proposal
Create new role (or expand and rename the read-dns-role) to allow users to view firewall, firewall logs and VPC flow logs. 
Is there an issue with renaming read-dns-role?

## Definition of done

- [x] role created or amended
- [x] readme has been updated
- [x] user docs have been updated
- [x] another team member has reviewed
- [x] tests are green

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by dms1981** [comment]
Created role, confirmed can assume it and view specified CloudWatch Log Groups, Streams, and events for firewalls, as well as firewall policies and rule groups

**Comment by dms1981** [comment]
There turned out to be a few complications with the replacement of `read-dns` with `read-logs`.
https://github.com/ministryofjustice/modernisation-platform/pull/5152 >> this PR replaced the `read-dns` role.
https://github.com/ministryofjustice/modernisation-platform/pull/5157 >> this PR amended the IAM permissions for the new ReadFirewallRecords policy.

**Comment by dms1981** [comment]
We found that there were other references outside of the Modernisation Platform repository, particularly in Modernisation Platform Environments, that made use of the `read-dns` role and also needed refactoring. As an interim measure I raised this PR to recreate the role while we find out why `read-logs` cannot be assumed.
https://github.com/ministryofjustice/modernisation-platform/pull/5158

**Comment by dms1981** [comment]
`member-delegation-read-only` role can now read VPC flow logs.
`read-log-records` role can read VPC flow logs in `core-network-services` as well as firewall configuration

**Comment by dms1981** [comment]
TODO: remove permission to assume `read-dns-records`
TODO: remove `read-dns-records` role

**Comment by dms1981** [comment]
Removed the trust relationship and role - all done!
