### ISSUE TITLE
Block public access to AMIs as default

### ISSUE THREAD

**Issue by davidkelliott** [ministryofjustice/modernisation-platform#5012]
## User Story

Block public access to AMIs as default
https://aws.amazon.com/about-aws/whats-new/2023/09/amazon-ec2-block-public-access-machine-images/

This does not include making changes to block AMIs that already exist - this will be done via a separate ticket

## User Type(s)

MP users

## Value

Increased security as images can't accidentally be made public.

### Proposal
Using the member bootstrapping enable the block public access setting for each MP account.
### Unknowns
Double check the image can still be shared to other AWS accounts if needed
## Definition of done

- [ ] add blocking to each MP account
- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] tests are green
- [ ] ticket raised to check that pre-existing AMIs are not publicly available (and amend if they are)

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by dms1981** [comment]
Do we want to pick up / wait for this issue on the Terraform AWS provider backlog?
https://github.com/hashicorp/terraform-provider-aws/issues/33473

**Comment by mikereiddigital** [comment]
I'm going to start this by looking at the member bootstrap source to get an understanding of how that works.

**Comment by mikereiddigital** [comment]
Having gone through the source & spoken to both David & Ewa the changes I'm looking at are:

- core-shared-services - in the https://github.com/ministryofjustice/modernisation-platform-ami-builds/blob/main/modules/imagebuilde module add a "aws_ec2_image_block_public_access" resource. This should then apply to those AMIs generated by IB and still held in that account.

- https://github.com/ministryofjustice/modernisation-platform-terraform-baselines/blob/main/modules/iam/main.tf - add the "aws_ec2_image_block_public_access" resource and create a new version of it. Then update the references to that module with the new version and so roll out to member accounts and protect AMIs held there.

**Comment by mikereiddigital** [comment]
Doing some more reading, the "block-public-access" setting is enabled by default in accounts that have no publicly shared AMIs. So for core-shared-services, this has already been applied and as such the first of the two changes listed is not required.

**Comment by mikereiddigital** [comment]
Created new release https://github.com/ministryofjustice/modernisation-platform-terraform-baselines/tree/v6.22. Next week I will update the references to this module in Modernisation Platform.

**Comment by mikereiddigital** [comment]
PR - https://github.com/ministryofjustice/modernisation-platform/pull/6072 covers the changes in modernisation-platform to use the new module release.

**Comment by mikereiddigital** [comment]
A number of the memberbootstrap jobs failed with the failed to save state error. Will talk to Ewa tomorrow morning if she's in.

**Comment by mikereiddigital** [comment]
Re-running the failed member-bootstrap jobs now.

**Comment by mikereiddigital** [comment]
All jobs ran. This ticket is now done.
