### ISSUE TITLE
Permissions for DPR Sandbox Development Role to create VPC Endpoints

### ISSUE THREAD

**Issue by harichintala1** [ministryofjustice/modernisation-platform#5016]
## User Story

Help us provision rights to able to setup VPC Endpoints on Digital-Prision-Reporting Sandbox ENV, this is required for us to validate DMS 3.4.7 upgrade
-->

## User Type(s)

Acceptance Criteria: DPR developers able to create VPC Endpoints on AWS Sandbox/Development Environment 

## Reference

[AWS DMS Upgrade Document for reference](https://aws.amazon.com/blogs/database/new-features-in-aws-dms-3-4-7/)

**Comment by dms1981** [comment]
VPC endpoints can be created by adding them to the relevant `environments-networks/$business_unit-$environment.json` file through the `additional_endpoints` field. They will need to be approved by a Modernisation Platform engineer however, as they will be available to all accounts with access to the relevant VPC.
