### ISSUE TITLE
New issue templates improvements

### ISSUE THREAD

**Issue by ewastempel** [ministryofjustice/modernisation-platform#5038]
## User Story

As a mod platform engineer 
we want to have a better way of logging new issues
So that it is easier to raise new issues

## User Type(s)

This will affect all users logging new issues to the platform

## Value

This Change will simplify the way new issues are raised, requests for new accounts and reporting new bugs

### Proposal
The proposal is to use the information in the bellow thread to create new yml based forms. 
See this slack [thread](https://mojdt.slack.com/archives/C013RM6MFFW/p1692718430865629) for details.

## Definition of done 

- [x] create new issue form
- [x] create new form for other elements like new environments and bugs
- [x] another team member has reviewed
- [x] tests are green
- [x] delete old forms once new forms agreed

**Comment by markgov** [comment]
PR created with new template
https://github.com/ministryofjustice/modernisation-platform/pull/5050

**Comment by markgov** [comment]
https://github.com/ministryofjustice/modernisation-platform/pull/5094

**Comment by markgov** [comment]
All forms have been changed to yml forms and have been implemented
