### ISSUE TITLE
Modify ALB access log module so that you don't need to create Athena tables

### ISSUE THREAD

**Issue by davidkelliott** [ministryofjustice/modernisation-platform#5046]
## User Story
In the load balancer with logs module - https://github.com/ministryofjustice/modernisation-platform-terraform-loadbalancer

See thread here - https://mojdt.slack.com/archives/C01A7QK5VM1/p1695117211518099
Currently you need to run the Athena query to create the table, but the developer role doesn't have this permission.

Ideally this table should be created when the module runs or soon after, potentially a Glue crawler could be use, similar to here - 
https://github.com/ministryofjustice/aws-root-account/blob/main/organisation-security/terraform/license-manager.tf#L137

## User Type(s)

MP users

## Value

Easier for users to view the logs

## Definition of done

- [ ] module updated
- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] tests are green

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by markgov** [comment]
created a new branch and started writing out the code found that in the module we are already creating an Athena database so reusing that instead of creating a new one. the only section i am unsure of at the moment is the s3 target section of the following code block

```
resource "aws_glue_crawler" "ssm_resource_sync" {
  database_name = aws_athena_database.lb-access-logs.name
  name          = "ssm_resource_sync"
  role          = aws_iam_role.lb_glue_crawler.arn
  schedule      = "cron(15 1 ? * MON *)"

  s3_target {
    path = "s3://${module.ssm_resource_sync_s3_bucket.bucket_name}"
  }
}
```

**Comment by markgov** [comment]
https://github.com/ministryofjustice/modernisation-platform-terraform-loadbalancer/pull/259

**Comment by markgov** [comment]
pr deployed and release made bumped to release 3.2 user informed
