### ISSUE TITLE
new aws account request for ERIC

### ISSUE THREAD

**Issue by tajewole-moj** [ministryofjustice/modernisation-platform#5070]
Hello Team,

As part of migrating LAA application to MP can you create an aws account for application called eric for test and production environment please. We want to start moving the ec2 instance across to the MP account 

Regards
Tunde

### Application Name
ERIC

### Description of application
LAA use this application for sharing Management Information with Legal Aid providers, currently only one report has been released. Effectively this is the frontend of the MI service

### Environments

| Environment   | Access level |
| ---     | --- |
|<ul><li>[ ] Development</li></ul> | <ul><li>[ ] view-only</li><li>[ ] developer</li><li>[ ] sandbox</li></ul> |
|<ul><li>[ &#10003;] Test</li></ul>   | <ul><li>[ ] view-only</li><li>[ &#10003;] developer</li></ul> |
|<ul><li>[ ] Preproduction</li></ul>| <ul><li>[ ] view-only</li><li>[ ] developer</li></ul> |
|<ul><li>[&#10003; ] Production</li></ul> | <ul><li>[ &#10003;] view-only</li><li>[ ] developer</li></ul> |

### Tags

tag | value
--- | ---
application | eric
business-unit | LAA
infrastructure-support |
owner |

### Subnet sets

- [ ] General - this application will use the same subnet as other applications in your business unit
- [ ] Isolated - this application has highly sensitive data which must have its own isolated subnet with no network connectivity

### How do users connect to the application?

- [ ] Over the public internet
- [ ] With a purple cabled device (please give details)
- [ ] With a MoJ Official device

## Additional features

- [ ] Additional VPC Endpoints
- [ ] Extended DNS Zones
- [ ] Other - please specify

## Definition of done

- [ ] account created
- [ ] customer informed

**Comment by markgov** [comment]
https://github.com/ministryofjustice/modernisation-platform/pull/5137

**Comment by markgov** [comment]
Network PR https://github.com/ministryofjustice/modernisation-platform/pull/5142

**Comment by markgov** [comment]
New Environment is now complete
