### ISSUE TITLE
New development environment for LAA CCMS EBS upgrade

### ISSUE THREAD

**Issue by rajindersinghsandhu** [ministryofjustice/modernisation-platform#5096]
### Environment details

CCMS is a system that manages certified civil legal aid applications, amendments and bills, it is our general ledger, chart of accounts and payment system and manages accounts receivable.

The version of EBS which is currently being used is very old and out of support.We want to update our DB servers to a new supported versions. Due to other high priority work we don't want to make any changes to our envs in ccms-ebs acccount and will use this account to do the spike work

### Application Name

ccms-ebs-upgrade

### Description of application

CCMS is a system that manages certified civil legal aid applications, amendments and bills, it is our general ledger, chart of accounts and payment system and manages accounts receivable.

The version of EBS which is currently being used is very old and out of support.We want to update our DB servers to a new supported versions

### GitHub team slug

laa-ccms-migration-team

### Environments

- [X] Development
- [ ] test
- [ ] Preproduction
- [ ] Production

### Environment access level Development

sandbox

### application

ccms-ebs-upgrade

### business-unit

LAA

### infrastructure-support

laa-ccms-platform-tea-aaaaeti4e5egi736k6a4k46qtm@moj.org.slack.com

### owner

donovan.artz@digital.justice.gov.uk

### Subnet sets

- [X] General
- [ ] Isolated

### How do users connect to the application

Over the public internet

### Additional features

Please check any additional features required
- [ ] Additional VPC Endpoints
- [ ] Extended DNS Zones
- [ ] Other - please specify

### Definition of Done

Definition of Done
- [x] account created
- [x] customer informed

**Comment by SteveLinden** [comment]
Not stated what account level should be given so I have added sandbox. Also left the nuke exclude as per the current ccms-ebs-development account.

**Comment by SteveLinden** [comment]
Emailed Donovan with the details. The account is ccms-ebs-upgrade-development. I kept the development part just in case they ask to have additional parts in future.
