### ISSUE TITLE
Create further Apex Environments 

### ISSUE THREAD

**Issue by alanrana7** [ministryofjustice/modernisation-platform#5105]
### Environment details

Apex development environment was previously created. This ticket is to create the remaining environments for Apex

### Application Name

laa-apex

### Description of application

LAA Apex is an Oracle Application Express environment, which hosts several internal LAA applications. APEX applications are Tender Verification System (TV) Provider Information (PIMS) which are used by central commissioning as enablers in the process of tendering contracts.

### GitHub team slug

laa-aws-infrastructure

### Environments

- [ ] Development
- [X] test
- [X] Preproduction
- [X] Production

### Environment access level Development

developer

### Environment access level Test

developer

### Environment access level Preproduction

developer

### Environment access level Production

developer

### application

laa-apex

### business-unit

LAA

### infrastructure-support

aws-webops-laa@digital.justice.gov.uk

### owner

LAA

### Subnet sets

- [X] General
- [ ] Isolated

### How do users connect to the application

Over the public internet

### Additional features

Please check any additional features required
- [ ] Additional VPC Endpoints
- [ ] Extended DNS Zones
- [ ] Other - please specify

### Definition of Done

Definition of Done
- [x] account created
- [x] customer informed

**Comment by SteveLinden** [comment]
Slight delay with this - an issue showed up on the Eric account build so this cannot be undertaken until that error is corrected.

**Comment by SteveLinden** [comment]
After a few issues the environments have been created. Onto the RAM change section

**Comment by SteveLinden** [comment]
Apex environments created
