### ISSUE TITLE
Stop checkov "300" error through code

### ISSUE THREAD

**Issue by SteveLinden** [ministryofjustice/modernisation-platform#5133]
### Expected Behavior

At present we have the following in place on the modernisation-platform-terraform-s3-bucket in two places #checkov:skip=CKV_AWS_300: "Ensure S3 lifecycle configuration sets period for aborting failed uploads"

We want to add the code to remove this skip

### Actual Behavior

At present an error for the top section
"Check: CKV_AWS_300: “Ensure S3 lifecycle configuration sets period for aborting failed uploads”
	FAILED for resource: aws_s3_bucket_lifecycle_configuration.default
	File: /main.tf:49-113"
appears. A similar one appears for the lower section. 

With the skip in place this stops the check being undertaken and the error does not appear.

There is code in place on the "top" section (line 67 -76) but it does not appear to work currently. This needs to be fixed or replaced.

### Steps to Reproduce the Problem

To reproduce the error the skips would need to be reviewed and a PR raised. It's not advisable to do this!

**Comment by dms1981** [comment]
This doesn't need to be fixed does it? It looks like a known issue in Checkov: https://github.com/bridgecrewio/checkov/issues/5363

You can see it being handled in code like so:
```
      abort_incomplete_multipart_upload {
        days_after_initiation = lookup(rule.value, "abort_incomplete_multipart_upload_days", "7")
      }
```
https://github.com/ministryofjustice/modernisation-platform-terraform-s3-bucket/blob/main/main.tf#L52

**Comment by dms1981** [comment]
That being the case I'd say this just needs a skip statement. Maybe with a comment to review it later.

**Comment by SteveLinden** [comment]
Did not make the above changes as the current fix requirement cannot be satisfied. We should maybe review this when a fix is implemented on checkov for this feature.

**Comment by SteveLinden** [comment]
Moved into backlog

**Comment by SimonPPledger** [comment]
Looks like this has now been resolved, so we can remove the 'skip'

**Comment by dms1981** [comment]
Agreed @SimonPPledger - I've checked the Chekov issue and it's resolved, so any future failures may be legit. I'll close this issue.
