### ISSUE TITLE
SPIKE: Investigate action required for NCSC Active Cyber Defence (ACD) services

### ISSUE THREAD

**Issue by davidkelliott** [ministryofjustice/modernisation-platform#5149]
### User Story

As an MP engineer
I want to make use of ACD
So that the platform and its applications are more secure

### Value / Purpose

Help to prevent against cyber attacks.

### Useful Contacts

MoJ TVMSOC

### Additional Information

The ACD services that must be used are:
− Protective DNS (pDNS) – to protect devices from accessing known-bad internet
services. https://www.ncsc.gov.uk/information/pdns
− WebCheck – which identifies common security problems in websites https://www.ncsc.gov.uk/information/web-check
− MailCheck – validates that email anti-spoofing controls and confidentiality protections
are working correctly. https://www.ncsc.gov.uk/information/mailcheck

[INC2079321  - SA003 - Active Cyber Defence Measures.pdf](https://github.com/ministryofjustice/modernisation-platform/files/13206779/INC2079321.-.SA003.-.Active.Cyber.Defence.Measures.pdf)

### Definition of Done

- [x] Investigation completed
- [ ] New issues created
- [ ] Another team member has reviewed
- [ ] Tests are green

**Comment by markgov** [comment]
joined the ministry of justice organisation just awaiting approval

**Comment by markgov** [comment]
also added password to secrets manager

**Comment by markgov** [comment]
https://docs.google.com/document/d/1XijS36bkb0rN3FchQyZzQf0MBQQmFzKb8os2RSH3p_c/edit?usp=sharing
