### ISSUE TITLE
Add test account for delius-core

### ISSUE THREAD

**Issue by georgepstaylor** [ministryofjustice/modernisation-platform#5154]
### Environment details

delius-core already in place, request to add test

### Application Name

delius-core

### Description of application

already in place

### GitHub team slug

hmpps-migration

### Environments

- [ ] Development
- [X] test
- [ ] Preproduction
- [ ] Production

### Environment access level Test

developer

### application

delius-core

### business-unit

HMPPS

### infrastructure-support

probation-webops@digital.justice.gov.uk

### owner

probation-webops@digital.justice.gov.uk

### Subnet sets

- [X] General
- [ ] Isolated

### How do users connect to the application

With a MoJ Official device

### Additional features

Please check any additional features required
- [ ] Additional VPC Endpoints
- [ ] Extended DNS Zones
- [ ] Other - please specify

### Definition of Done

Definition of Done
- [x] account created
- [x] customer informed

**Comment by ASTRobinson** [comment]
delius-core-test environment was successfully created and @georgepstaylor has been informed. I am therefore closing this ticket.
