### ISSUE TITLE
Review state file security

### ISSUE THREAD

**Issue by davidkelliott** [ministryofjustice/modernisation-platform#5166]
### User Story

As an MP engineer
I need to know that my state file is secure
So that I can ensure the security of my application

### Value / Purpose

Regular review to ensure things are secure

### Definition of Done

- [x] Security around state file reviewed
- [x] New issues created if needed
- [x] User docs have been updated
- [x] Another team member has reviewed
- [x] Tests are green

**Comment by dms1981** [comment]
Was able to retrieve logs of bucket access attempts using the following CloudWatch Insights filter:
```
fields @timestamp, @message
| filter eventSource = "s3.amazonaws.com" and requestParameters.bucketName = "modernisation-platform-terraform-state"
| sort @timestamp desc
| limit 20
```
Have used the information I could see to formulate and submit an AWS support request in the bucket account.

**Comment by dms1981** [comment]
My initial thought is that we can secure access using a condition block that matches the account alias to the `environments/members/$alias` key where the objects are stored. I'll need to use a partial match, however, as the account alias will end in an environment name which is not reflected in the key value.

**Comment by dms1981** [comment]
I spent some time investigating this one through the `modernisation-platform-environments` repository with [this branch](https://github.com/ministryofjustice/modernisation-platform-environments/compare/feature/sprinkler-bucket).
It's possible to secure access to files through a combination of tags - eg. `owner` - and a lookup against the `aws:PrincipalAccount` value.
```
data "aws_iam_policy_document" "my-policy" {
  statement {
    sid       = "MyStatement"
    actions   = ["s3:Get*", "s3:Put*"]
    resources = [arn:aws:s3:::my-bucket]
    principals {
      identifiers = ["*"]
      type        = "AWS"
    }
    condition {
      test     = "StringEquals"
      variable = "s3:ExistingObjectTag/owner"
      values   = ["&{aws:PrincipalAccount}"]
    }
  }
}
```
An alternative approach might be to use a combination of local values and data source calls to retrieve AWS Organizational Unit values, and a policy that relates the OU to the directory and subordinate keys. I don't exactly how I'd write it in terraform, but it would look something like this in JSON:
```
{
                Statement = [
                    {
                        Action    = "[s3:Get*, s3:Put*]"
                        Condition = {
                            "ForAnyValue:StringLike" = {
                                "aws:PrincipalOrgPaths" = "root-id/*/modernisation-platform-id/*/modernisation-platform-${application-name}"
                            }
                        }
                        Effect    = "Allow"
                        Principal = {
                            AWS = "*"
                        }
                        Resource  = "arn:aws:s3:::bucket_name/environments/members/${application-name}"
                        Sid       = "RestrictFilesBasedOnOU"
                    },
                ]
            }
        )
```
This OU-based approach, however, would likely be more declarative as it may need a statement for each application.

**Comment by dms1981** [comment]
Moving this to blocked until I can find someone else to review the statefile security for me,

**Comment by dms1981** [comment]
@markgov confirmed access for me
