### ISSUE TITLE
Spike: investigate automated performance testing

### ISSUE THREAD

**Issue by markgov** [ministryofjustice/modernisation-platform#5210]
### User Story

As a modernisation Platform engineer 
I want to be able allow users to performance test their applications
So that end users can find issues

### Value / Purpose

Customers have expressed an interest in performance testing on their applications. We have found that aws does allow for this and possibly has an automated way of doing this as talked about in the follow link https://aws.amazon.com/solutions/implementations/distributed-load-testing-on-aws/

### Definition of Done
- [ ] automated performance monitoring investigated
- [ ] notes made and demoed to team
- [ ] new issue raised if needed

**Comment by mikereiddigital** [comment]
This covers the solution. https://docs.aws.amazon.com/pdfs/solutions/latest/distributed-load-testing-on-aws/distributed-load-testing-on-aws.pdf

Have built it into Sprinkler using the supplied CF template. Will review the contents of the PDF against what's been deployed.

**Comment by mikereiddigital** [comment]
Have the load testing solution installed. Ran a simple test against a httpd server and 1 task over 1 minute generated over 47,000 gets to the httpd server page. Will look at the more advanced features tomorrow.

**Comment by mikereiddigital** [comment]
Link to initial draft of write-up

https://docs.google.com/document/d/1h-GL45FNLxdVcsXG-o7j7buw0MfCZTbv89YJshc-RKI/edit?usp=sharing

**Comment by mikereiddigital** [comment]
Held the demo and Q&A.
