### ISSUE TITLE
Performance hub development legacy migration.

### ISSUE THREAD

**Issue by ep-93** [ministryofjustice/modernisation-platform#5214]
### User Story

As a MP Engineer & Performance Hub Engineer
I want to move our only remaining environment from legacy AWS accounts to Mod Platform
So that our pipeline is slick, our terraform is deployed via namespaces an in a tidy ci cd dpeloyment pipeline. No old terraform manual applies to old accounts, with different connectivity. 

**Even better if** 

As a MP Engineer & Performance Hub Engineer
I need to move our only remaining environment from legacy AWS accounts to Mod Platform
So that or pipeline conforms to XXXX and is the latest agreed version of MP pipeline that ensures XXXXX

Already have.

### Useful Contacts

Jeremy Collins

### Additional Information

The old account is pretty straightforward in terms of resources. There is..

_**S3**_
User generated content in a bucket, used during development. The equivalent bucket already exists in our MP environments, Jeremy is using the cicduser to migrate files from the legacy account to MP dev via cli.

A bucket used for data exchange with the AP. This bucket doesn't exist in MP envs yet, however I have linked Jeremy to our s3 module to help.

**_IAM_** 
There are 2 sets of users / roles / polices for writing to AP buckets / reading from our landing bucket. Jeremy needs to create these resources in MP, then needs to work with AP team to change their pipelines to write to the new S3 bucket in prod

_**RDS**_
Jeremy needs to create the RDS instance in the dev environment on MP.

Once that's done we need to help to restore a snapshot cross-account.

### Definition of Done

Tasks
- [x] Bucket Created
- [x] IAM roles created
- [x] RDS Snapshot moved
- [x] RDS instance created from snapshot in dev.

**Comment by ep-93** [comment]
@SimonPPledger Did you ever get an update on this?

**Comment by ep-93** [comment]
Waiting on @jemnery

**Comment by SimonPPledger** [comment]
from Jeremy "Edd was really helpful, thanks. He couldn't see any issues with my setup, which led the investigation to the Analytical Platform side of this problem. It looks like it was a change their end causing the issue, so I don't think we'll need Edd for the next sprint."

**Comment by ep-93** [comment]
```Really well, thanks to the leg up you gave us.  Some more mucking about with snapshots and KMS keys, but the the DB in a good place, and as of yesterday we've switched to using the new MP instance. I've done a [TF apply](https://github.com/ministryofjustice/modernisation-platform-environments/actions/runs/11817390308) to check dev is all aligned.
I'm going to leave the old RDS running for maybe a week, in case I've missed something. Then I'll take it down and we can get the old account closed.```

**Comment by Kudzai-moj** [comment]
Looks good to me. Can be moved to done
