### ISSUE TITLE
SPIKE: Look at policies and roles to reduce number added 

### ISSUE THREAD

**Issue by SteveLinden** [ministryofjustice/modernisation-platform#5221]
### User Story

As a developer I want to be able to add to a role without running into the maximum.

Recently a call was raised and it hit the maximum and we had 157 failures pop up on the modernisation-platform channel. We don't want this to happen.

This call is to look into the possibilities and get them agreed with the team before we create additional tickets for the work required. 

### Value / Purpose

This will make the number of items in a role reduce and require policies that can be added to roles (as an example).

There may be other ways of reducing the error issue.

### Proposal / Unknowns

If we do this it will make sure additions to roles will be more easily changed.

Documentation will be required to show how this should be done in future - this will be included on future calls.

### Definition of Done

- [ ] README has been updated
- [ ] User docs have been evaluated
- [ ] Other team members have reviewed and approved an approach

**Comment by markgov** [comment]
there are two possible approches we could take with this or even a combination of the first two i am in the process of investigating both at present and putting a document together with my findings

**Comment by markgov** [comment]
I’m this spike should be linked with this spike https://github.com/ministryofjustice/modernisation-platform/issues/3661

**Comment by markgov** [comment]
https://docs.google.com/document/d/1QiZfzVUIFfx_Ds9bfvoJAaZQdMpdP-3V24NEYz42ZiI/edit?usp=sharing

**Comment by dms1981** [comment]
We've agreed to discuss the next steps for this spike after sprint planning

**Comment by markgov** [comment]
meeting arranged for next week to talk it over
