### ISSUE TITLE
[DOCS] Fix grammatical errors in README file and Introduce License section

### ISSUE THREAD

**Issue by singodiyashubham87** [ministryofjustice/modernisation-platform#5299]
I want to fix the typos and grammatical errors in the README file and also want to introduce a LICENSE section showing the license in which the repository is licensed.

Here "for core work" will be replaced by "for the core work"
![image](https://github.com/ministryofjustice/modernisation-platform/assets/93720428/3091716b-346a-4b4b-805d-15e23e43caf2)

Kindly assign me this issue.

**Comment by dms1981** [comment]
Hi @singodiyashubham87 - we have a license defined at an organisation level here: https://github.com/ministryofjustice/.github/blob/main/LICENSE

However, it's probably worth us making this clearer to contributors.

**Comment by singodiyashubham87** [comment]
@dms1981 Still there are typos that need to be fixed, Kindly assign me this issue so that I can fix them.
