### ISSUE TITLE
[DOCS] Add a CODE_OF_CONDUCT file to the repository

### ISSUE THREAD

**Issue by singodiyashubham87** [ministryofjustice/modernisation-platform#5300]
#### Problem or desire

The repository looks incomplete because of the missing CODE_OF_CONDUCT.md file to specify the rules and regulations to follow while contributing to the repository, I want to add that file to the repo.

#### Proposal

Add the CODE_OF_CONDUCT file to the repository with guidelines.

Kindly assign me this issue.

**Comment by dms1981** [comment]
We have a code of conduct defined at an organisation level here: https://github.com/ministryofjustice/.github/blob/main/CODE_OF_CONDUCT.md

Thanks for raising this issue @singodiyashubham87 - we'll look into linking to this code of conduct, as it's not obvious clear in this repository that there's a defined organisation code of conduct

**Comment by singodiyashubham87** [comment]
@dms1981 Okay, If you need any further changes to the documentation then I'm ready to work.

**Comment by SimonPPledger** [comment]
We don't feel this is currently a priority as the code of conduct is available anyway
