### ISSUE TITLE
SPIKE: Investigate if we can use Amazon Inspector

### ISSUE THREAD

**Issue by ewastempel** [ministryofjustice/modernisation-platform#5303]
### User Story

As a Modernisation Platform Engineer
I want to know of security vulnerabilities of AWS resources such as ECR, EC2 and lambda functions
So that it can be mitigated.

### Value / Purpose

More secure MP estate.

### Additional Information

See this document: https://docs.aws.amazon.com/inspector/latest/user/getting_started_tutorial.html#tutorial_activate_scans

### Proposal / Unknowns

Estimate how much work would be involved to implement it and propose a draft solution.

### Definition of Done

- [ ] Document your findings and a draft implementation plan
- [ ] Present your findings to the team and agree on the outcome
- [ ] Update ADR
- [ ] If applicable, come up with user stories

**Comment by SimonPPledger** [comment]
we are using this - but not looking at results - that will be part of another ticket
