### ISSUE TITLE
Spike:  can GHA deploy to multiple environments

### ISSUE THREAD

**Issue by seanprivett** [ministryofjustice/modernisation-platform#532]
## User Story
Investigate to see if a GitHub Actions pipeline can deploy to multiple environments

## Value
Enables us to design with future multi-environments in mind, with confidence that this is possible

## Definition of done
Document and show & tell with the team

- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] tests are green

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by davidkelliott** [comment]
Now completed, documentation on this here - https://github.com/ministryofjustice/modernisation-platform/pull/777
