### ISSUE TITLE
What secrets exist on MP, and how do we rotate them?

### ISSUE THREAD

**Issue by davidkelliott** [ministryofjustice/modernisation-platform#5325]
### User Story

We currently have a list of secrets on the platform here - https://user-guide.modernisation-platform.service.justice.gov.uk/runbooks/rotating-secrets.html#introduction

This issue is to check that there are no other secrets, if there are add them here.

We also want to create a process for regularly rotating all our secrets that we control. (This may be automated if possible)

### Value / Purpose

Ensure we know where all our secrets are and that they are rotated regularly.

### Definition of Done

- [x] Document all secrets
- [x] Agree process and frequency for rotating secrets
- [x] Document process and frequency for rotating secrets
- [x] Another team member has reviewed

**Comment by SimonPPledger** [comment]
we also have this ticket https://github.com/ministryofjustice/modernisation-platform/issues/85
is this now no longer required

**Comment by SteveLinden** [comment]
More secrets appear to be in place than those listed. I will amend the documentation once I check their purpose (and do a pull first)

**Comment by SteveLinden** [comment]
Pull request for the change is in #5496

**Comment by SteveLinden** [comment]
Agreed a 180 day password change with the team. Some are N/A. Currently 7 to amend.
