### ISSUE TITLE
Run `aws-nuke` against `testing-test` account on a regular basis

### ISSUE THREAD

**Issue by dms1981** [ministryofjustice/modernisation-platform#5345]
### User Story

As a Modernisation Platform Engineer
I want to run `aws-nuke` regularly against the `testing-test` account
So that lingering resources are regularly cleaned up

### Value / Purpose

The `testing-test` account is used for the creation of short-lived resources during unit tests. However, when tests do not exit cleanly resources can be left behind which impact future test runs. We should clean the resources in this account on a regular basis.

### Additional Information

https://github.com/ministryofjustice/modernisation-platform-environments/actions/workflows/awsnuke.yml

### Definition of Done

- [x] `testing-test` included in AWS Nuke job
- [ ] Another team member has reviewed
- [ ] Tests are green

**Comment by SteveLinden** [comment]
Both Edd and I have tried to remove this account but have failed. Maybe a real nuke will do it

**Comment by ep-93** [comment]
We do

https://github.com/ministryofjustice/modernisation-platform-environments/actions/runs/6840515258/job/18599869893

`Nuke complete: 0 failed, 10 skipped, 59 finished.`
