### ISSUE TITLE
♻️ Refactor workflow that updates environment approvers

### ISSUE THREAD

**Issue by dms1981** [ministryofjustice/modernisation-platform#5363]
### User Story

As a Modernisation Platform Engineer
I want to revisit the operation of the `terraform-github.yml` action
So that customer environments aren't unduly affected by pull requests

### Value / Purpose

At present, the `terraform-github.yml` action can make changes to environments on the raising of a pull request.
I would like to see that it does the following instead:
* On raising a pull request that affects files, run any associated scripts in a read-only / dry-run fashion
* On merging a pull request into `main`, make changes

### Additional Information

Example of a PR causing changes to environment approvers: https://github.com/ministryofjustice/modernisation-platform/actions/runs/6732697476

### Definition of Done

- [x] File affecting PR changed to run scripts in a read-only/dry run way
- [x] Scripts run in update mode as part of merge
- [x] Changes tested
- [ ] Any documentation updated

**Comment by ASTRobinson** [comment]
Draft PR ([5505](https://github.com/ministryofjustice/modernisation-platform/pull/5505)) created to fix the issue where the git-create-environments.sh was running when a PR was opened, this will now only run against the main branch. Still trying to come up with a smooth approach for a dry-run / read-only method without having to duplicate scripts

**Comment by ASTRobinson** [comment]
The 'Plan' feature has been implemented here: [5551](https://github.com/ministryofjustice/modernisation-platform/pull/5551).

This workflow run shows only the plan running (and not the apply) [/actions/runs/6971559001/job/18972015309](https://github.com/ministryofjustice/modernisation-platform/actions/runs/6971559001/job/18972015309)
This workflow run shows all steps successfully running on merge to main [/actions/runs/6971706574/job/18972676406](https://github.com/ministryofjustice/modernisation-platform/actions/runs/6971706574/job/18972676406)
