### ISSUE TITLE
Document Github Workflows

### ISSUE THREAD

**Issue by philhorrocks** [ministryofjustice/modernisation-platform#537]
## User Story

Document all Github Workflows into an easy to understand document which can also be used a reference int he the user manual
## Value

- [ ] Create workflow graphic
- [ ] Create associated user documentation
- [ ] another team member has reviewed

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by davidkelliott** [comment]
https://app.diagrams.net/#G1w8dZs5vZOoy0dvCnRr5P6GHc3VQRdwLq
