### ISSUE TITLE
Hosting and config management testing summary.

### ISSUE THREAD

**Issue by ep-93** [ministryofjustice/modernisation-platform#5427]
### User Story

As part of the beta service standard advice we’ve been given for reliably operating a service, we’ve been asked ‘What tests are carried out on hosting and config management?’ As our service sits on (in?) MP/

### Value / Purpose

Required from the beta service standard advice.

### Additional Information

Write up and document our testing of config management and hosting. 

### Definition of Done

Example - [ ] Documentation has been written / updated
- [ ] User docs have been updated
- [ ] Another team member has reviewed

**Comment by SimonPPledger** [comment]
currently documented but we need to increase testing scope
