### ISSUE TITLE
Evening Shutdown Script - Reported by Nick Buckingham

### ISSUE THREAD

**Issue by ASTRobinson** [ministryofjustice/modernisation-platform#5436]
### Expected Behavior

PPUD DEV and UAT environment shutdown at 21:00 and start back up at 06:00

### Actual Behavior

following the daylight saving time adjustment where the clocks have rolled back 1 hour the environments are now shutting down at 20:00 and starting back up at 05:00. 

### Account

PPUD

**Comment by markgov** [comment]
This has been corrected by PR https://github.com/ministryofjustice/modernisation-platform/pull/5441
Raising new issue to make a permanent fox

**Comment by markgov** [comment]
https://github.com/ministryofjustice/modernisation-platform/issues/5449
