### ISSUE TITLE
Moving Instance scheduler to event bridge scheduling

### ISSUE THREAD

**Issue by markgov** [ministryofjustice/modernisation-platform#5449]
### User Story

As a Modernisation platform engineer
I need to look at how the instance scheduler lambda is executed 
So that it runs at the correct time no matter what time of the year it is.

### Value / Purpose

Currently the instance scheduler lambda only runs in UTC time zone and there is no way of changing this with the current event bridge rule, but aws has implemented a new service called event bridge scheduler which has much more functionality. 

### Additional Information

https://docs.aws.amazon.com/eventbridge/latest/userguide/using-eventbridge-scheduler.html
terraform documentation
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/scheduler_schedule

### Unknowns Potential pitfalls that could cause the story to expand beyond its original scope. Ideally this section will remain blank.
This is new code and has not been tested

### Definition of Done

Example 
- [ ] Documentation has been written / updated
- [x] New code added and tested
- [ ] README has been updated
- [x] Another team member has reviewed
- [x] Tests are green

**Comment by sukeshreddyg** [comment]
Successfully migrated **instance-scheduler-lambda-function** from CloudWatch Events to EventBridge Scheduler

#6063
