### ISSUE TITLE
DR - Get CIDR ranges for new workspaces.

### ISSUE THREAD

**Issue by ep-93** [ministryofjustice/modernisation-platform#5503]
### User Story

For this story we will need cidr ranges 

https://github.com/ministryofjustice/modernisation-platform/issues/5501

### Value / Purpose

Required for this story https://github.com/ministryofjustice/modernisation-platform/issues/5501 

### Useful Contacts

Edd Proctor

### Definition of Done

Example - [ ] Documentation has been written / updated
- [ ] Ranges have been documented
- [ ] Reserved
- [ ] Another team member has reviewed

**Comment by ep-93** [comment]
Need to arrange workshop

**Comment by SimonPPledger** [comment]
this is no longer required
