### ISSUE TITLE
Pagerduty Users Token issue

### ISSUE THREAD

**Issue by markgov** [ministryofjustice/modernisation-platform#5518]
### User Story

As a modernisation platform engineer
I need to make sure that the user token being used for pager duty is appropriate 
So that it does not get invalidated if a user leaves

### Value / Purpose

We have a user account for PagerDuty, the harder thing is the user account in Slack to be able to link it to for slack connections, we are currently having to use a team members pagerduty user token authenticating with a team members slack user.  what we need to do is find a way to have a user account without using a team members account

### Useful Contacts

Mark Roberts, Dave Elliott

### Definition of Done

Example 
- [ ] Documentation has been written / updated
- [ ] new token created 
- [ ] User docs have been updated
- [ ] Another team member has reviewed
- [ ] Tests are green

**Comment by SimonPPledger** [comment]
this is a nice to have.  for. now we need to remember that it will break if the  owner of the individual account leaves

**Comment by SimonPPledger** [comment]
decided not to progress this
