### ISSUE TITLE
DR - Identify what is region specific

### ISSUE THREAD

**Issue by ep-93** [ministryofjustice/modernisation-platform#5519]
### User Story

As an MP DevOps Engineer
I need want to be able to have the platform & environments deployable in a different region (eu-west-1 currently)
So that if eu-west-2 goes down, we have a running environment / environments.

### Value / Purpose

We need to identify the region specific infrastructure and if it will need to be changed, duplicated etc to handle infrastructure built in eu-west-1

### Useful Contacts

Edd Proctor

### Definition of Done

Example - [ ] Documentation has been written / updated
- [ ] Region specific infrastructure has been found and listed
- [ ] non-region specific infrastructure has been found and listed
- [ ] Reviewed

**Comment by markgov** [comment]
https://miro.com/app/board/uXjVOj85DfM=/

**Comment by markgov** [comment]
spreadsheet updated and notes made on what we could do
