### ISSUE TITLE
Upgrade to Terraform 1.0

### ISSUE THREAD

**Issue by davidkelliott** [ministryofjustice/modernisation-platform#552]
## User Story

As a mp user
I expect to use the latest version of terraform
So that I can make use of the latest features and fixes

## Value

By keeping up-to-date we reduce our risk of accruing technical debt leading to large upgrade projects later

## Definition of done

- [ ] update Terraform
- [ ] update Terraform providers
- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] tests are green

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by ezman** [comment]
Now that 1.0 is out we should probably jump to that.
