### ISSUE TITLE
Correspondence Handling And Processing System (CHAPS)

### ISSUE THREAD

**Issue by fshafaatmoj** [ministryofjustice/modernisation-platform#5539]
### Environment details

We require an environment that will allow us to host a C# application on .NET Framework 4.8 with SQL Server

### Application Name

cdpt-chaps

### Description of application

The Ministerial Correspondence Unit (MCU) receives correspondence from MP on behalf of constituents as well as direct from members of the public. They allocate these to action officers for a response to be drafted and then it is passed to the ministers' office for approval before it is signed by a minister. This solution tracks the answering process from beginning to end and is only and is accessible within the DOM1 domain.

Application is written in 
C# using .NET Framework 4.8
SQL Server for Database
.

### GitHub team slug

central-digital-product-team

### Environments

- [X] Development
- [ ] test
- [X] Preproduction
- [X] Production

### Environment access level Development

developer

### Environment access level Preproduction

developer

### Environment access level Production

developer

### application

Correspondence Handling And Processing System

### business-unit

HQ

### infrastructure-support

central-digital-product-team@digital.justice.gov.uk

### owner

central-digital-product-team@digital.justice.gov.uk

### Subnet sets

- [X] General
- [ ] Isolated

### How do users connect to the application

With a MoJ Official device

### Additional features

Please check any additional features required
- [ ] Additional VPC Endpoints
- [ ] Extended DNS Zones
- [ ] Other - please specify

### Definition of Done

Definition of Done
- [x] account created
- [x] customer informed

**Comment by richgreen-moj** [comment]
Hi @fshafaatmoj these accounts have now been created. You should find all the info you need to use the Mod Platform [here](https://user-guide.modernisation-platform.service.justice.gov.uk/) 

In particular you may wish to read [this guide](https://user-guide.modernisation-platform.service.justice.gov.uk/user-guide/deploying-your-application.html#deploying-your-application) which details how you can deploy your application via automated pipelines.

If you need us we are available on Slack [#ask-modernisation-platform](https://app.slack.com/client/E01066BNN9G/C01A7QK5VM1)
