### ISSUE TITLE
Integrated Fraud System (IFS)

### ISSUE THREAD

**Issue by fshafaatmoj** [ministryofjustice/modernisation-platform#5540]
### Environment details

We require an environment that will allow us to host a C# application on .NET Framework 4.8 with SQL Server

### Application Name

cdpt-ifs

### Description of application

It is a business-critical function for managing fraud cases in different parts of the organisation.

Integrated Fraud System is a .NET Framework 4.8 application built using the MVC design pattern, using a SQL Server database. 

### GitHub team slug

central-digital-product-team

### Environments

- [X] Development
- [ ] test
- [X] Preproduction
- [X] Production

### Environment access level Development

developer

### Environment access level Test

developer

### Environment access level Production

developer

### application

central-digital-product-team

### business-unit

HQ

### infrastructure-support

central-digital-product-team@digital.justice.gov.uk

### owner

central-digital-product-team@digital.justice.gov.uk

### Subnet sets

- [X] General
- [ ] Isolated

### How do users connect to the application

With a MoJ Official device

### Additional features

Please check any additional features required
- [ ] Additional VPC Endpoints
- [ ] Extended DNS Zones
- [ ] Other - please specify

### Definition of Done

Definition of Done
- [x] account created
- [ ] customer informed

**Comment by dms1981** [comment]
Holding off on starting this until we have a new starter to pick it up

**Comment by markgov** [comment]
https://github.com/ministryofjustice/modernisation-platform/pull/5688
https://github.com/ministryofjustice/modernisation-platform/pull/5690

Account created
