### ISSUE TITLE
Alerting for Secrets Rotation

### ISSUE THREAD

**Issue by richgreen-moj** [ministryofjustice/modernisation-platform#5548]
### User Story

As a Mod Platform Engineer...
I want to be alerted when our secrets need to be rotated as per the [documentation](https://user-guide.modernisation-platform.service.justice.gov.uk/runbooks/rotating-secrets.html#how-to-rotate-secrets)...
So that I can ensure that secrets are rotated regularly mitigating the risk of long-lived credentials.

### Value / Purpose

This will ensure that our secrets are being rotated as per the agreed schedule by proactively reminding the MP team via an alert channel.
This story was conceived as a result of https://github.com/ministryofjustice/modernisation-platform/issues/5325 

### Additional Information

Thoughts so far are that this could take the form of a script/reminder that checks the age of the secrets and posts to a Slack channel with a reminder for MP team to update them. This could start to alert a week or so before the expiry to allow time to gather new credentials as in some cases this requires contacting another team.

### Definition of Done

Example - [ ] Documentation has been written / updated
- [ ] README has been updated
- [ ] User docs have been updated
- [x] Another team member has reviewed
- [x] Tests are green

**Comment by dms1981** [comment]
Discussed in standup - raising a GitHub issue is probably better than a Slack message that could be easily lost

**Comment by richgreen-moj** [comment]
Here is my WIP workflow: https://github.com/ministryofjustice/modernisation-platform/blob/feature/5548-secrets-rotation-alerting/.github/workflows/secrets-rotation-reminder.yml

Most recent run https://github.com/ministryofjustice/modernisation-platform/actions/runs/7033390229/job/19139110635 highlights secrets that are over the threshold - I've commented out raising a new issue at the moment as I don't want to spam the repo with test issues but have been testing it locally.

Wondering how important it would be to raise new issues following our new story form template although not sure that's currently possible via gh cli https://github.com/cli/cli/issues/5865 - I might just look to replicate the style of our template for the new issue.

**Comment by richgreen-moj** [comment]
Raised https://github.com/ministryofjustice/modernisation-platform/pull/5631 and incorporated comments from the team. I've now merged in to main - I will verify that it kicks off on schedule today (09:30) and is behaving as expected.

**Comment by richgreen-moj** [comment]
I had made an omission on permissions required to raise gh issues so had to raise https://github.com/ministryofjustice/modernisation-platform/pull/5641 to fix it. This also changed the daily schedule to 11:30 just for convenience that I could watch it running in. 

The script worked and has raised issues as appropriate e.g. 
https://github.com/ministryofjustice/modernisation-platform/actions/runs/7059473706/job/19217097059#step:5:60
and 
https://github.com/ministryofjustice/modernisation-platform/issues/5645

I'll mark this as done. I'll make sure to check that subsequent runs of this over the weekend don't create duplicate issues.
