### ISSUE TITLE
SPIKE - Development environment (Docker container, Vagrant, something similar)

### ISSUE THREAD

**Issue by ep-93** [ministryofjustice/modernisation-platform#5560]
### User Story

As a mod plat devops engineer
I want everyone to be running the same versions of things and have the same things installed
So that we dont have any different behaviours when testing locally or applying.

### Value / Purpose

New starters wouldn't require the few days of brew installs, and veterans in the team would be reminded to update or forced to.

### Additional Information

Investigate this in a timeboxed way, with new people joining it could be useful for everyone to be running the same things. 

### Proposal 

We do this as a spike, someone investigates and presents it, different technologies, solutions, etc. 

### Definition of Done

- [x] Spike investigated
- [x] Docs created
- [x] Presentation given
- [x] Decision made

**Comment by AafAnsari** [comment]
https://docs.google.com/document/d/1ueuOrkVPMsyUgvcgE5zZn-4NJjpMq7w5ckEi250f6gA/edit?usp=sharing
