### ISSUE TITLE
Spike: Add Cymulate to the Modernisation Platform

### ISSUE THREAD

**Issue by davidkelliott** [ministryofjustice/modernisation-platform#5623]
### User Story

As a security engineer
I want to stand up an instance of Cymulate https://cymulate.com/
So that I can perform penetration tests on an MP application

### Value / Purpose

Avoid the need for expensive ITHCs which give little value by offering and in platform testing service.

### Useful Contacts

Simon Heron

### Proposal / Unknowns

We should probably use the security account to host the instance.  This may mean we need to look at the networking there.  So for this spike let's use sprinkler, this means we can also stand up another instance that we can use to test with Cymulate.

Security team (Simon) will provide details on how to install, login details to the main account etc.  We should look to have this in a container if possible for possible hosting on CP.

### Definition of Done

- [x] Instance created
- [x] Penetration test run against another MP application
- [x] Another team member has reviewed
- [x] Demo to the team

**Comment by SimonPPledger** [comment]
Steve want to talk to Sunny about this first, so on hold until then

**Comment by SimonPPledger** [comment]
following on from steve's chat, we can go ahead with this

**Comment by richgreen-moj** [comment]
Found this guide for installing Cymulate agents online - not sure if it'd be of any use - depends on how the MoJ is going to use Cymulate - Self hosted or PAAS/SAAS... https://www.pax8nebula.com/m/3a89f5e68dec23bf/original/Cymulate-Installation-Guide.pdf

**Comment by ep-93** [comment]
I found the same @richgreen-moj , but until we know.. we could do the infrastructure , build a few ec2 instances 2-3 of them and sec groups maybe a load balancer and route 53 entry 

When we get the details we can then finish the story.

**Comment by SteveLinden** [comment]
The install looks relatively straight forward but does this need to be done on each machine or can it be done on the EC2 instance sprinkler lives on?

**Comment by SimonPPledger** [comment]
@SteveLinden we have a licence - well the Security team do

**Comment by SteveLinden** [comment]
An EC2 was, eventually, built for this and I have contacted Sunny to see how we install the application.

**Comment by SteveLinden** [comment]
Sunny has said the people we need to speak to are on leave this week so we can't do anything until they are back in.

**Comment by SteveLinden** [comment]
Contacted [@rajesh.dandamudi](https://mojdt.slack.com/team/U035N5Y0YAK)
 and 
[@Simon Heron](https://mojdt.slack.com/team/URNQVLZ5H) to see what we need to do. Simon has suggested a meeting to kick this off.

**Comment by SteveLinden** [comment]
OK/ Had my (quick) call with the security team. They have some terraform which creates cymulate on a new small instance which can then be set up to run and test. The plan is to do this as a temporary thing as Steve M was concerned about leaving it running in the background.
I will take a look at the code when it's all set up and we can then test it and see how it all connects. I will include the terraform code reference in here once I have it.

**Comment by SteveLinden** [comment]
Having some issues trying to create the security group. It works fine on the plan but the apply fails. Will be looking at this later to see what we can do. It looks like the subnets exist on the core-vpc-sandbox and not on the sprinkler account itself.

**Comment by SteveLinden** [comment]
We abandoned the terraform script provided and copied it into sprinkler. After some iffy errors we got it working in there. Now trying to follow the settings to build the bits needed to allow an install of cymulate.

**Comment by SteveLinden** [comment]
We lost everything over the weekend (20-21/01/2024) so it needed to be rebuilt. Initially this did not work as it was built in a public rather than private zone. This was corrected and it allowed me to run the curl 
curl -o cymulate_agent.zip "https://app.cymulate.com/api/agent/download?arch=64&os=linux&type=zip&isService=false&isInstaller=false&isExecutor=false"

This downloaded the application and the unzip worked. Setting install to allow it to run also worked.
It was then run as sudo (sudo su) with ./install.sh
The one thing needed was the key which was emailed to me by security. Running this with the key showed it as being up on sprinkler.

Will need to get in touch with security about accessing this so we can set up another dummy instance and run some tests. The main bit about installing the cymulate software has, however, been proven.

**Comment by SteveLinden** [comment]
We have proven that cymulate can be installed on an account but not that it will work and find errors etc.

**Comment by SteveLinden** [comment]
Another plan has been opened to look at some outstanding issues around this #6076

**Comment by SteveLinden** [comment]
Need to speak to Simon Heron about seeing cymulate itself.

The PEN test can't be done at the moment by us. As far as we can see it's all in place to be undertaken. Again this is with the security team

**Comment by SteveLinden** [comment]
We have now had a demonstration of the cymulate console with the current environments in place. This shows us what it can check and how the system works.

**Comment by SteveLinden** [comment]
The code for adding the cymulate projects is shown below. Note, this is based on the EC2 environments existing, the correct name for the bastien server and the correct IP for the cymulate environment so a lot is unknown at the time this was entered.

[Link](/Users/stephen.linden/Documents/connect to ec2-user for cymulate)
Connect to the bastion server on sprinkler using
aws sso login --profile sprinkler
aws ssm start-session --target i-0e10f47b6f3c5fbcf --profile sprinkler

i-0e10f47b6f3c5fbcf needs to change to the latest bastion target


From there do a sudo su ec2-user
Then cd 

Add the pem from your computer as mykey.pem if it doesn't exist

From here you can then ssh to the correct place using

ssh -i "mykey.pem" ec2-user@10.231.0.112    -   this has the key needed to connect to the server, check the IP on sprinkler in this case

Answer yes to ensure the login works.

At this point you are then on the "cymulate-test" server as the ec2-user

Now run the curl script
curl -o cymulate_agent.zip "https://app.cymulate.com/api/agent/download?arch=64&os=linux&type=zip&isService=false&isInstaller=false&isExecutor=false"

Unzip the file cymulate_agent.zip
unzip cymulate_agent.zip


Then add x to the install file.
chmod +x install.sh 
And run it as sudo
sudo ./install.sh

Answer N to the first 2 questions then enter the key supplied by the security team, and enter N for the email question (gmail is not available as an option)

To stop cymulate on an EC2 instance you can issue this command - sudo cymulate-kill

**Comment by SteveLinden** [comment]
The code for adding the cymulate projects is shown below. Note, this is based on the EC2 environments existing, the correct name for the bastien server and the correct IP for the cymulate environment so a lot is unknown at the time this was entered.

[Link](/Users/stephen.linden/Documents/connect to ec2-user for cymulate)
Connect to the bastion server on sprinkler using
aws sso login --profile sprinkler
aws ssm start-session --target i-0e10f47b6f3c5fbcf --profile sprinkler

i-0e10f47b6f3c5fbcf needs to change to the latest bastion target

From there do a sudo su ec2-user
Then cd

Add the pem from your computer as mykey.pem if it doesn't exist

From here you can then ssh to the correct place using

ssh -i "mykey.pem" ec2-user@10.231.0.112 - this has the key needed to connect to the server, check the IP on sprinkler in this case

Answer yes to ensure the login works.

At this point you are then on the "cymulate-test" server as the ec2-user

Now run the curl script
curl -o cymulate_agent.zip "https://app.cymulate.com/api/agent/download?arch=64&os=linux&type=zip&isService=false&isInstaller=false&isExecutor=false"

Unzip the file cymulate_agent.zip
unzip cymulate_agent.zip

Then add x to the install file.
chmod +x install.sh
And run it as sudo
sudo ./install.sh

Answer N to the first 2 questions then enter the key supplied by the security team, and enter N for the email question (gmail is not available as an option)

To stop cymulate on an EC2 instance you can issue this command - sudo cymulate-kill
