### ISSUE TITLE
Investigate request to allow cross environment network access

### ISSUE THREAD

**Issue by SimonPPledger** [ministryofjustice/modernisation-platform#5632]
### User Story

As an application team there are times when I want cross account/VPC access within Modernisation Platform. This would enable a number of things - for example for refreshing pre-production from production and allowing some tools - eg OEM to be able to access multiple environments

Currently this is not possible. This story is to look at what providing this access would mean and the impact it would have - which will be documented in an ADR

### Value / Purpose

This will either enable us to provide required functionality or to have a document available to say why that is not possible

### Definition of Done

Example - [ ] Documentation has been written / updated
- [ ] ADR created and agreed
- [ ] ADR approval by Security 
- [ ] New tickets created, if necessary, to provide cross-account access

**Comment by SimonPPledger** [comment]
Will just be an ADR

**Comment by dms1981** [comment]
I'll have a think and discuss it with @davidkelliott . My initial thought here would be that, rather than allowing network traffic between environment VPCs, customers should be empowered to create privatelink endpoints and consume services through them instead.

**Comment by dms1981** [comment]
https://github.com/ministryofjustice/modernisation-platform/pull/6034
