### ISSUE TITLE
DR - KMS region replication 

### ISSUE THREAD

**Issue by ep-93** [ministryofjustice/modernisation-platform#5635]
Linked to this story - https://github.com/ministryofjustice/modernisation-platform/issues/5501 

### User Story

As a mod platform devops engineer
I expect region specific infrastructure to be able to be replicated to another region (KMS in this case)
So that in case of DR, we have what is required to rebuild the platform.

### Value / Purpose

This may already be happening, but please check the following

- The infrastructure is replicating in another region
- That the region can easily be changed
- Document how often this happens and the process it follows for replication.

### Additional Information

Create a multi-Region replica key in the AWS KMS console or by using the ReplicateKey API  

### Proposal / Unknowns

It may already be happening, but the process now fully understood. This process may need to change to allow the region to be changed easily.

### Definition of Done

- [ ] Documentation has been written / updated
- [ ] KMS keys are syncing to eu-west-1
- [ ] Eu-west-1 changed to another region, and tested
- [ ] Process is created for users to copy.,

**Comment by ep-93** [comment]
Whilst initially it was put down as replicated on a list here - https://docs.google.com/spreadsheets/d/1y04642pjDPzcMQPtDYNYs0ue-KnxqFsotnACb5t-LZk/edit#gid=0

Its actually not, so needs to be done.

**Comment by AafAnsari** [comment]
Added new multi-Region KMS keys for 

- securityhub-alarms_key
- environment-management
- dynamodb-state-lock
- pagerduty-secret
- s3-state-bucket
