### ISSUE TITLE
Analyse & determine details of split

### ISSUE THREAD

**Issue by seanprivett** [ministryofjustice/modernisation-platform#564]
## Definition of done

- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] tests are green

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by davidkelliott** [comment]
This has been completed, documentation will be completed as part of the remaining tickets.
