### ISSUE TITLE
Repo interaction visualisation / process map

### ISSUE THREAD

**Issue by seanprivett** [ministryofjustice/modernisation-platform#565]
## Definition of done

- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] tests are green

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by davidkelliott** [comment]
https://app.diagrams.net/#G1VVx248505m8epAHUHeKgLBoiTQ9xGlBD
