### ISSUE TITLE
Upgrading EQUIP

### ISSUE THREAD

**Issue by SimonPPledger** [ministryofjustice/modernisation-platform#5656]
### User Story

As an application support team, I need to ensure that the application is supportable and kept up to date.
ROC - the 3rd party supporting the application -   need to upgrade both the application and the windows servers. There is an additional request to change the way powerbi is used to report against the application.

Unfortunately ROC does not have terraform skills, so we will need to do this work for them.

We think ROC will install the software and we will then create an AMI - but this will need to be confirmed with ROC.

We should also work out how data in EQUIP will update the PowerBI server - and how PowerBI  will be accessed by users  

### Value / Purpose

This is to ensure that the application is supportable

### Useful Contacts
james.ashton@roctechnologies.com
andy.land@roctechnologies.com

### Additional Information

We will track this work as a standard piece of modernisation platform work

### Definition of Done

- [x] Liaise with ROC to determine what needs doing
- [x] Document details
- [x] Create new tickets for doing the work

**Comment by markgov** [comment]
Andy Land
  [11:00](https://mojdt.slack.com/archives/D06AM2NNHRN/p1702465230060159)
I think getting started in the Dev environment is possible pre-Christmas if you guys have availabilty - our resource for that is a guy called Jonny Davey and he's got some time in the next couple of weeks





[11:01](https://mojdt.slack.com/archives/D06AM2NNHRN/p1702465266254419)
I'm going to be away from this Friday though, so in terms of coordination we'd also loop in James Ashton from my side
[11:01](https://mojdt.slack.com/archives/D06AM2NNHRN/p1702465314374139)
tbh I think the most we can reasonably aim for is if you can get the Dev environment started up again and we get Jonny access to it - he hasn't previously had an account in the MP

**Comment by markgov** [comment]
New Code created to add three new windows 2022 server to development

**Comment by markgov** [comment]
https://github.com/ministryofjustice/modernisation-platform-environments/pull/4429

**Comment by markgov** [comment]
https://github.com/ministryofjustice/modernisation-platform-environments/pull/4428

**Comment by ASTRobinson** [comment]
The 3 servers are up and running and I have created Jonny a local administrator account on each of the servers (he has these details).

**Comment by markgov** [comment]
helped Jonny with his connection to the instances this is now sorted closing call
