### ISSUE TITLE
Add permissions for AWS Bedrock to sandbox and developer roles

### ISSUE THREAD

**Issue by davidkelliott** [ministryofjustice/modernisation-platform#5677]
### User Story

As a MP user
I want to be able to use AWS Bedrock via the console, until Terraform support is in place
So that I can create and manage AWS Bedrock services

### Value / Purpose

Enable AWS Bedrock on the platform

### Definition of Done

- [ ] Permissions added
- [ ] Another team member has reviewed
- [ ] Tests are green

**Comment by julialawrence** [comment]
On @davidkelliott 's steer, adding to sandbox role only.
