### ISSUE TITLE
Add provider for eu-central-1 for AWS Bedrock

### ISSUE THREAD

**Issue by davidkelliott** [ministryofjustice/modernisation-platform#5678]
### User Story

As a MP user
I want to have a an AWS provider for the eu-central-1 region
So that I can create AWS Bedrock services

### Value / Purpose

Enable AWS Bedrock on the platform.

### Definition of Done

- [ ] New provider added
- [ ] Another team member has reviewed
- [ ] Tests are green

**Comment by ep-93** [comment]
Merge and deploy this - https://github.com/ministryofjustice/modernisation-platform/pull/5877

Then this - https://github.com/ministryofjustice/modernisation-platform/pull/5879/files

Then edit the providers in the team that need this or maybe all of them and add the line from the PR above.

**Comment by ep-93** [comment]
Okay so the role is deployed everywhere...

https://github.com/ministryofjustice/modernisation-platform-environments/pull/4420

This to test it.. not sure how to though.

**Comment by ep-93** [comment]
Currently its created everywhere and easy to deploy, just copy and paste this PR to the teams that want it. 

https://github.com/ministryofjustice/modernisation-platform-environments/pull/4420
