### ISSUE TITLE
AWS Bedrock access for CICA Copilot

### ISSUE THREAD

**Issue by jennyd** [ministryofjustice/modernisation-platform#5680]
### Environment details

We need a development environment to get access to AWS Bedrock for the CICA Copilot - nothing else will be hosted there.

### Application Name

cica-copilot

### Description of application

The CICA Copilot is a tool for caseworkers to find the relevant parts of their internal documentation for handling applications, so they can work more quickly and consistently. The [application](https://github.com/ministryofjustice/cica-copilot) will be [hosted on the Cloud Platform](https://github.com/ministryofjustice/cloud-platform-environments/tree/main/namespaces/live.cloud-platform.service.justice.gov.uk/cica-copilot-dev) - it has a frontend and an API built with Node.js, and a vector database. The API needs access to an LLM API which is where Bedrock comes in.

### GitHub team slug

cica-copilot-llm-maintainers

### Environments

- [X] Development
- [ ] test
- [ ] Preproduction
- [ ] Production

### Environment access level Development

developer

### application

CICA Copilot

### business-unit

CICA

### infrastructure-support

CICA: infrastructure@cica.gov.uk

### owner

CICA: infrastructure@cica.gov.uk

### Subnet sets

- [X] General
- [ ] Isolated

### How do users connect to the application

Over the public internet

### Additional features

Please check any additional features required
- [ ] Additional VPC Endpoints
- [ ] Extended DNS Zones
- [x] Other - please specify

We need access to AWS Bedrock which is currently available in Frankfurt (`eu-central-1`). Bedrock isn't fully supported in Terraform yet ([some PRs have been merged](https://github.com/hashicorp/terraform-provider-aws/pulls?q=is%3Apr+bedrock+is%3Amerged) but not released yet) - I've discussed this with @davidkelliott and he said it would be possible to give us permissions to manage Bedrock in the AWS console for now, and then move to Terraform as soon as it's supported.

### Definition of Done

Definition of Done
- [ ] account created
- [ ] customer informed

**Comment by sukeshreddyg** [comment]
This ticket is done now (Given sandbox environment for the CICA Copilot)

https://github.com/ministryofjustice/modernisation-platform/pull/5781
https://github.com/ministryofjustice/modernisation-platform/pull/5790

**Comment by jennyd** [comment]
Brilliant, thank you!
