### ISSUE TITLE
Timeout accessing MoJ SMTP relay service from Nomis in Modernisation Platform

### ISSUE THREAD

**Issue by SimonPPledger** [ministryofjustice/modernisation-platform#5713]
### Expected Behavior

As reported by Dom Robinson. 
He needs the Nomis accounts in Mod Platform to be able to communicate with  MoJ SMTP Relay 10.180.104.100  and 10.180.105.100 (some more details here - [MoJO-SMTP-Relay](https://github.com/ministryofjustice/staff-infrastructure-smtp-relay-server#readme) .  Here is a link to the conversation in slack (https://mojdt.slack.com/archives/C01A7QK5VM1/p1668610127017869).  We **think** it needs port 25. We thought it had been sorted out, but it is still not working.

We need to find out where it is failing - and potentially raise a request with Tech Services

### Actual Behavior

it is being timed out
10.26.8.134):
nc -vzw 5 10.180.104.100  25
nc: connect to 10.180.104.100 port 25 (tcp) timed out: Operation now in progress

also timing out  from prod 10.27.12.178

**Comment by dms1981** [comment]
I don't think this is specifically a bug, but more a story to allow traffic from MP ranges to the MOJ SMTP relays.
Our definition of done would look like the following:
- [ ] NACLs checked to allow tcp/25 to 10.0.0.0/8
- [ ] MP `external-inspection` firewall configured to allow tcp/25 to `10.180.104.100/32` & `10.180.105.100/32`

**Comment by SteveLinden** [comment]
Service now call raised
Submitted : 12-12-2023 09:09:34
Request Number : REQ1316682
Estimated Delivery : 17-12-2023

**Comment by SteveLinden** [comment]
Initial call (above) cancelled as Simon required more details. Added additional ones to this
Submitted : 12-12-2023 15:28:17
Request Number : REQ1317707
Estimated Delivery : 17-12-2023

**Comment by SteveLinden** [comment]
Added the firewall rules using https://github.com/ministryofjustice/modernisation-platform/pull/5797 so this call can be closed. The above request is unlikely to take place until well after the new year due to the change shutdown over Christmas (starting 15th December)
