### ISSUE TITLE
SPIKE: AWS directory as a service

### ISSUE THREAD

**Issue by SimonPPledger** [ministryofjustice/modernisation-platform#5736]
### User Story

To enable the fix-and-go platform to be fully decommissioned we need to find a home for their current AD services.
One suggestion is that we use the AWS directory service

This is to look at what it would mean for the Modernisation Platform and also provide info to application team as to what they would need to do (at a very high level)

### Value / Purpose

Currently 2 DSO applications (PlanetFM and CSR) are authenticated via AD that is also running on the same basic infrastructure. So as all DSO is migrated either to ModP or CP, they will also need to move the AD (or replace it). A couple of the options would see it being relocated to ModP.

We also need to check that by putting it in there, it would mean that the networky bits/base connectivity is there to allow for the AD to be consumed in the member accounts (if it is hosted in another member account, we would have to break the rule of no east-west traffic allowed)

### Useful Contacts

Dominic Robinson, Matthew White

### Additional Information

This will enable us to determine whether this is potentially an appropriate solution. We would then need to do further work (via different tickets) to understand and agree the support boundaries, before implementing.

### Definition of Done

Example - [ ] tbc ..

**Comment by dms1981** [comment]
Having spoken to @davidkelliott and @drobinson-moj, this looks quite achievable.

We'd deploy AWS Managed AD in the `core-shared-services` account. I'm not certain on the route to do so, but the most straightforward option is to do so through the [modernisation-platform](https://github.com/ministryofjustice/modernisation-platform) repo, and set up something that allows access to the account for the purposes of domain administration in SSO, and any necessary IAM configuration to allow administration of AWS Managed AD.

We'd look to deploy a cluster in `non_live_data` at first for dev/test, and then add a later cluster in `live_data` for preprod/production.

**Comment by dms1981** [comment]
Based on this, I can see the following tasks that would need to be completed:

- [ ] MP firewall configured to allow traffic from `core-shared-services` VPCs to on-prem domain controllers for Active Directory
- [ ] ServiceNow request raised to allow traffic from `core-shared-services` VPCs to on-prem domain controllers for Active Directory traffic
- [ ] Implement AWS Managed AD in the `non_live_data` VPC in the `core-shared-services` account
- [ ] Configure something to allow SSO access to the `core-shared-services` account
- [ ] Configure anything necessary in IAM for role-based access to Active Directory

**Comment by dms1981** [comment]
I'll raise stories to cover the identified high-level tasks and associate them here then close this spike.

**Comment by dms1981** [comment]
https://github.com/ministryofjustice/modernisation-platform/issues/5809 >> This story covers the SSO access / IAM role based access reqirements. I'll try and refine what those permissions look like with @drobinson-moj or someone they can pass me to who's better placed.

https://github.com/ministryofjustice/modernisation-platform/issues/5810 >> This story covers us creating, testing access to, and then destroying an AWS Managed Microsoft Active Directory deployment.

**Comment by dms1981** [comment]
With regard to any firewall rules or ServiceNow requests these can't be done ahead of time as we'd need to better know what we're communicating with to create rules / raise a request.
