### ISSUE TITLE
MoJ Tech Landscape: Core Apps & Mod Candidates

### ISSUE THREAD

**Issue by christine-elliott** [ministryofjustice/modernisation-platform#574]
## User Story

As a user of the mod platform
I need to understand the tech landscape of the MoJ
So that we can identify potential customers and understand their function

## Value

- Visual map showing tech landscape
- Identify potential customers
- Link to app mod repositories
- know the function of the tech/app
- Size the priority of the tech/app

This will be a living document to be added to and amended as needed to meet needs and landscape changes.

**Comment by davidkelliott** [comment]
https://miro.com/app/board/o9J_lIngYbU=/
