### ISSUE TITLE
Create new environment for electronic monitoring 

### ISSUE THREAD

**Issue by pricemg** [ministryofjustice/modernisation-platform#5833]
### Environment details

This environment will be used as a landing zone and data store for data being transferred from external suppliers who manage the electronic monitoring service to MoJ. 

### Application Name

electronic monitoring data store

### Description of application

The environment will host sftp servers for each data supplier to use to connect and transfer their data into the MoJ estate. This data will then be stored in additional, non-external facing buckets for data retention.

### GitHub team slug

hmpps-electronic-monitoring-data-store

### Environments

- [X] Development
- [ ] test
- [X] Preproduction
- [X] Production

### Environment access level Development

sandbox

### Environment access level Preproduction

developer

### Environment access level Production

view-only

### application

electronic monitoring data store

### business-unit

HMPPS

### infrastructure-support

Data engineering: dataengineering@digital.justice.gov.uk

### owner

Data engineering: dataengineering@digital.justice.gov.uk

### Subnet sets

- [x] General
- [ ] Isolated

### How do users connect to the application

Over the public internet

### Additional features

Please check any additional features required
- [ ] Additional VPC Endpoints
- [ ] Extended DNS Zones
- [ ] Other - please specify

### Other information

This project will be used as a landing zone and data store for historic data that has been collected by suppliers for the electronic monitoring scheme. 

We have three suppliers who need to transfer data over, and following discussions with cyber security and technical architects the proposed solution is outlined in the image below. Each supplier will have a unique S3 bucket to deposit their data into, via an sftp server hosted for each bucket. This sftp server will use MFA to ensure only assured users can access. Part of this will involve setting a list of allowed IPs for each supplier x sftp server (IP addresses to be confirmed). Therefore we will need to do some configuring of firewall/ports once those are known.

see also conversation [here](https://mojdt.slack.com/archives/C01A7QK5VM1/p1702992988422009)

<img width="703" alt="image" src="https://github.com/ministryofjustice/modernisation-platform/assets/10746018/402f20a4-4017-47cb-b786-8261708103cb">

### Definition of Done

Definition of Done
- [ ] account created
- [ ] customer informed

**Comment by SimonPPledger** [comment]
We want to discuss this with Matthew before preceding. Dave Elliott to reach out

**Comment by sukeshreddyg** [comment]
New environments has been created for electronic monitoring. Please note: Application name amended to electronic-monitoring-data instead of electronic-monitoring-data-store to meet the requirements not exceeding the application name to 30 characters (https://user-guide.modernisation-platform.service.justice.gov.uk/user-guide/creating-environments.html#requesting-an-environment)

#5864

**Comment by mikereiddigital** [comment]
Matt Price requested the view-only for production be amended to developer & so this has been applied via this PR - https://github.com/ministryofjustice/modernisation-platform/pull/6032
