### ISSUE TITLE
Bug - Error: Failed to persist state to backend on modernisation-platform 

### ISSUE THREAD

**Issue by SteveLinden** [ministryofjustice/modernisation-platform#5859]
### Expected Behavior

The state should save without issues. 

### Actual Behavior

We get the above error as seen in https://github.com/ministryofjustice/modernisation-platform/actions/runs/7285740796/job/19855252914#step:7:113 as an example 

### Steps to Reproduce the Problem

Run a full release that amends everything, e.g. adding a role access change. The number that happen is not consistent but it has been happening more recently.

### Version

Example is the run for PR #5840 

### Modules

modernisation-platform

**Comment by ewastempel** [comment]
The error to be fixed:
```
Error: Failed to save state

Error saving state: failed to upload state: operation error S3: PutObject,
failed to rewind transport stream for retry, request stream is not seekable

Error: Failed to persist state to backend

The error shown above has prevented Terraform from writing the updated state
to the configured backend. To allow for recovery, the state has been written
to the file "errored.tfstate" in the current working directory.

Running "terraform apply" again at this point will create a forked state,
making it harder to recover.

To retry writing this state, use the following command:
    terraform state push errored.tfstate
```

**Comment by dms1981** [comment]
https://mojdt.slack.com/archives/C015UBQ78MR/p1702984257007459 << You can see a short Slack conversation with our AWS TAM here where we were given some guidance / linked to the S3 performance design considerations whitepaper.

https://docs.aws.amazon.com/AmazonS3/latest/userguide/optimizing-performance.html

**Comment by ewastempel** [comment]
Thanks David, but according to the doc, we are not hitting the limit in a single workflow run. FYI, the implemented solution is not looking into the limits, but is to push the errored state.

**Comment by ewastempel** [comment]
The state push fix for the state persistence failure is now rolled out to the scheduled baseline workflow with temporarily suppression of slack alerts for when the state push is successful.
There will be separate issues to track the fix rollout to other workflows.
Also, once https://github.com/hashicorp/terraform/issues/34528 is fixed, the alerting should be re-enabled.

**Comment by ewastempel** [comment]
To roll out the fix to other repos/workflows see this issue: https://github.com/ministryofjustice/modernisation-platform/issues/6038
