### ISSUE TITLE
Move member infrastructure code from mp repo to environments

### ISSUE THREAD

**Issue by davidkelliott** [ministryofjustice/modernisation-platform#5926]
### User Story

We have some member infrastructure code in the mp repo, things such as SES users.  We should move this code back across to the environment repo, and check that there is a test in place to make sure that this infrastructure requires a review from the MP team - https://github.com/ministryofjustice/modernisation-platform-environments/blob/main/scripts/terraform-plan-evaluator.sh#L5

### Value / Purpose

Keep all member code in one place.

### Definition of Done

- [x] Member code moved
- [x] Resources moved in terraform state (import + remove)
- [x] Team affected have been informed
- [x] Another team member has reviewed
- [x] Tests are green

**Comment by ep-93** [comment]
Happy to do this or help with this, as it might be a similar process used with the data platform migration!

**Comment by ep-93** [comment]
Environments Repo   Mod Plat Repo  Git pull on both.  Create branch on both  On both, terraform state pull > prod.tfstate  From the mod platform repository run this command.

terraform state mv -state=prod.tfstate -state-out=/Users/edward.proctor/moj-devops/modernisation-platform-environments/terraform/environments/observability-platform/prod.tfstate module.amazon_managed_grafana_remote_cloudwatch_iam_policy module.amazon_managed_grafana_remote_cloudwatch_iam_policy  If the output is right, run again without -dry-run  (module.managed_grafana is an example, yours will be different, to find what you want to move, “terraform state list | grep -v ram” list will show you)
  terraform state push prod.tfstate - both sides.
  Move the code from mod platform to environments.  Locally run a terraform plan and hopefully see no changes (maybe tags)

**Comment by sukeshreddyg** [comment]
Need to move the member infrastructure from `MP` repo to the following environments

1. **Ccms-ebs**
2. **Corporate-staff-rostering**
3. **Delius-jitbit**
4. **Planetfm**
5. **PPUD**
6. **Equip**

**Comment by sukeshreddyg** [comment]
* Copy the necessary code from the specific environment in the 'mp-repo' to the 'mp-environments' repository. 
* Execute the terraform import command for the transferred resources.
  
   Eg: `terraform import aws_iam_user.<resource name> <username>`
