### ISSUE TITLE
Move current member resources to new environments repo

### ISSUE THREAD

**Issue by davidkelliott** [ministryofjustice/modernisation-platform#597]
## User Story

Now we have an environments repo for user resources we should move the current user resources across.

## Value

Keep the core accounts clean

## Definition of done

- [ ] readme has been updated
- [ ] user docs have been updated
- [x] another team member has reviewed
- [ ] tests are green

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by donmasters** [comment]
Test lab environments have now been migrated to modernisation-platform-environments repository

closing ticket
