### ISSUE TITLE
Solution for migrating HMPPS domain from azure

### ISSUE THREAD

**Issue by drobinson-moj** [ministryofjustice/modernisation-platform#5970]
### User Story

As a DSO tech lead
I need to create some EC2s instances directly in the Modernisation Platform Live and Non-Live data VPCs
So that I can migrate domain controllers from Azure FixNGo without running into environment isolation problems.

### Value / Purpose

Allows us to decommission the Azure FixNGo platform in the longer term.  In the short term can also avoids domain controller traffic traversing the AWS - Azure VPN in theory improving performance of domain reliant services (Remote Desktop, Planet FM and CSR/MyDetail)

### Useful Contacts

Dominic Robinson; David Sibley; David Elliot

### Additional Information

Background can be found in https://dsdmoj.atlassian.net/browse/DSOS-2415

Following discussion with Dom Robinson/David Sibley/David Elliot, we agreed tactical solution to solve migration of Azure FixNGo domains while both PlanetFM and CSR/MyDetail applications exist, hence creation of this ticket.

The solution falls outside of the normal architecture since the AZURE.noms.root domain spans both development and test environments, and the HMPPS.noms.root domain spans both pre-production and production.  Creating Domain Controllers (DCs) in development/test/preproduction/production won't work as they need to sync with each other. 

We need the ability to create resources directly in the Live / Non-Live VPCs to avoid the environment isolation issue.  The ask is for a pipeline and associated terraform infra to allow us to do this .  Core-shared-services potentially.  The actual terraform for creating the instances will be managed by DSO team so outside of the scope for this ticket.

### Proposal / Unknowns

Proposal: EC2 instances are built in Live and Non-Live data.

### Definition of Done

- [ ] Solution has been communicated with DSO team [Dominic Robinson]
- [ ] DSO team have verified they can run terraform using the given solution

**Comment by SimonPPledger** [comment]
Check to see whether this is via an AMI or a new build

**Comment by drobinson-moj** [comment]
Re AMI - plan to use our `hmpps_windows_server_2022` existing AMI image and configure the DC tools using powershell (hopefully automating as much as we can)

**Comment by dms1981** [comment]
Talked this one through with @drobinson-moj via Slack. The short version is that code for new instances would be placed [here](https://github.com/ministryofjustice/modernisation-platform/blob/main/terraform/environments/core-shared-services), and picked up and run by [this action](https://github.com/ministryofjustice/modernisation-platform/blob/main/.github/workflows/core-shared-services-deployment.yml).

We'd still need to talk about the work required for permissions to access and administer the instances, but could use the `instance-management` role in the interim.
