### ISSUE TITLE
Equip powerBi server

### ISSUE THREAD

**Issue by markgov** [ministryofjustice/modernisation-platform#5981]
### User Story

As a modernisation platform engineer
I need to create a new EC2 for an upgrade to powerbi
So that the equip team can continue with there upgrade work
Confirmed that this will be in production only.

### Value / Purpose

This server requires external access to the internet specifications as bellow

### Additional Information

Powerbi server

2019
8 gig
8 core
Relatively fast storage
20gb D
Outbound internet connection

GW suffix

### Definition of Done

Example
- [x] New resource created
- [ ] Another team member has reviewed
- [ ] Tests are green

**Comment by SimonPPledger** [comment]
Simon to confirm this is production only
