### ISSUE TITLE
Move from tfsec to trivy in all other team repositories

### ISSUE THREAD

**Issue by markgov** [ministryofjustice/modernisation-platform#5983]
### User Story

As a Modernisation Platform Engineer
I want to migrate from tfsec to trivy
So that we continue to benefit from up-to-date secure code analysis

trivy is now being favoured over tfsec, they are still using the same base rules so this isn't urgent but we should still change at some point.
https://github.com/aquasecurity/tfsec/blob/master/docs/guides/trivy.md

### Value / Purpose

The move on the modernisation platform repo was done on the following issueMove from tfsec to trivy
[#3336](https://github.com/ministryofjustice/modernisation-platform/issues/3336)

see the two PR's in the issue on what needs to be changed
we now need to implement that change on all other repo's that the modernisation platform owns

### Definition of Done

Example 
- [ ] Add and change existing code to use trivy
- [ ] All repos migrated over to trivy
- [ ] Another team member has reviewed additional pr's
- [ ] Tests are green

**Comment by SimonPPledger** [comment]
Before we do this we need to check and correct the earlier trivy implementation - ie we need to enable skipping features

**Comment by ep-93** [comment]
https://github.com/ministryofjustice/modernisation-platform-terraform-ssm-patching/pull/352/files

One down.

**Comment by ep-93** [comment]
Merged - https://github.com/ministryofjustice/modernisation-platform-terraform-ssm-patching/pull/352/files


Waiting - 

https://github.com/ministryofjustice/modernisation-platform-terraform-ec2-instance/pull/347

https://github.com/ministryofjustice/modernisation-platform-terraform-module-template/pull/344

https://github.com/ministryofjustice/modernisation-platform-terraform-loadbalancer/pull/401/

https://github.com/ministryofjustice/modernisation-platform-terraform-member-vpc/pull/369


Created branches on all modules.
