### ISSUE TITLE
Investigate & resolve failing actions action failing in modernisation-platform-terraform-ecs

### ISSUE THREAD

**Issue by mikereiddigital** [ministryofjustice/modernisation-platform#5990]
### Expected Behavior

run-go-unit-tests (go-terratest.yml) should run without error when a new PR is raised. Also Terraform Static Analysis test is failing on a number of non-fatal errors when run.

### Actual Behavior

run-go-unit-tests action is failing with the following error:

`TestECSModule 2024-01-15T16:18:30Z retry.go:99: Returning due to fatal error: FatalError{Underlying: error while running command: exit status 1; ╷
│ Error: configuring Terraform AWS Provider: no valid credential sources for Terraform AWS Provider found.
│ 
│ Please see https://registry.terraform.io/providers/hashicorp/aws
│ for more information about providing credentials.
│ 
│ AWS Error: failed to refresh cached credentials, no EC2 IMDS role found, operation error ec2imds: GetMetadata, failed to get API token, operation error ec2imds: getToken, http response error StatusCode: 400, request to EC2 IMDS failed
│ 
│ 
│   with provider["registry.terraform.io/hashicorp/aws"].testing-ci-user,
│   on providers.tf line 9, in provider "aws":
│    9: provider "aws" {
│ 

╵}
    apply.go:15: 
        	Error Trace:	/home/runner/work/modernisation-platform-terraform-ecs/modernisation-platform-terraform-ecs/test/apply.go:15
        	            				/home/runner/work/modernisation-platform-terraform-ecs/modernisation-platform-terraform-ecs/test/ecs_test.go:26
        	Error:      	Received unexpected error:
        	            	FatalError{Underlying: error while running command: exit status 1; ╷
        	            	│ Error: configuring Terraform AWS Provider: no valid credential sources for Terraform AWS Provider found.
        	            	│ 
        	            	│ Please see https://registry.terraform.io/providers/hashicorp/aws
        	            	│ for more information about providing credentials.
        	            	│ 
        	            	│ AWS Error: failed to refresh cached credentials, no EC2 IMDS role found, operation error ec2imds: GetMetadata, failed to get API token, operation error ec2imds: getToken, http response error StatusCode: 400, request to EC2 IMDS failed
        	            	│ 
        	            	│ 
        	            	│   with provider["registry.terraform.io/hashicorp/aws"].testing-ci-user,
        	            	│   on providers.tf line 9, in provider "aws":
        	            	│    9: provider "aws" {
        	            	│ 
        	            	╵}
        	Test:       	TestECSModule`

### Steps to Reproduce the Problem

Manually run action or trigger via PR.

**Comment by SimonPPledger** [comment]
not required - this is an archived repo
