### ISSUE TITLE
Script for environment repo tf workspace/state file creation

### ISSUE THREAD

**Issue by davidkelliott** [ministryofjustice/modernisation-platform#601]
## User Story

We need to have workspaces and state files for the new environment repository created automatically.

## Value

Without this it will be a manual process and I'll be very sad.

## Questions / Assumptions

We can hopefully extend the existing script, as it builds the state files using an ephemeral folder configuration
https://github.com/ministryofjustice/modernisation-platform/blob/main/scripts/loop-through-terraform-workspaces.sh

## Definition of done

- [ ] readme has been updated
- [ ] user docs have been updated
- [x] another team member has reviewed
- [ ] tests are green

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by donmasters** [comment]
This script has been refactored and now includes the creation of state files for member accounts in the modernisation-platform-environments repository

Closing
