### ISSUE TITLE
Equip - build new servers in production 

### ISSUE THREAD

**Issue by SimonPPledger** [ministryofjustice/modernisation-platform#6018]
### User Story

User Story
As an application support team, I need to ensure that the application is supportable and kept up to date.
ROC - the 3rd party supporting the application - need to upgrade both the application and the windows servers. 
Unfortunately ROC does not have terraform skills, so we will need to do this work for them.

We have built the development servers and ROC has confirmed they are working as expected
This ticket is to build the servers in production - there will be a later ticket to help them migrate.

ROC can confirm server spec

### Value / Purpose

This is to ensure that the application is supportable

### Useful Contacts

[james.ashton@roctechnologies.com](mailto:james.ashton@roctechnologies.com) [andy.land@roctechnologies.com](mailto:andy.land@roctechnologies.com)

### Definition of Done

-  [ ] Documentation has been written / updated
- [ ]  Liaise with ROC to confirm sizings
- [ ] Servers built
- [ ] Another team member has reviewed
- [ ] Tests are green

**Comment by markgov** [comment]
New servers deployed

**Comment by markgov** [comment]
Contacted user and he is happy with the new prod servers
