### ISSUE TITLE
New MP environment `maat-cd-api`

### ISSUE THREAD

**Issue by vc13837** [ministryofjustice/modernisation-platform#6029]
### Environment details

I would like a new environment for the application MAAT (Means Assessment Administration Tool) Court Data API please.

### Application Name

maat-cd-api

### Description of application

This is a Java based Spring Boot Application which will be hosted on AWS Environment. The application is being deployed on to the AWS ECS container service. This is a Facade application to the existing LAA legacy Applications MAAT/MLRA. laa-maat-court-data-api orchestrates the traffics between Court Data Adaptor/Common Platform and MAAT/MLRA.

### GitHub team slug

laa-aws-infrastructure

### Environments

- [X] Development
- [X] test
- [X] Preproduction
- [X] Production

### Environment access level Development

developer

### Environment access level Test

developer

### Environment access level Preproduction

developer

### Environment access level Production

developer

### application

Means Assessment Administration Tool Court Data API

### business-unit

LAA

### infrastructure-support

laa_ops@digital.justice.gov.uk

### owner

laa-crime-apps@digital.justice.gov.uk

### Subnet sets

- [X] General
- [ ] Isolated

### How do users connect to the application

Over the public internet

### Additional features

Please check any additional features required
- [ ] Additional VPC Endpoints
- [ ] Extended DNS Zones
- [ ] Other - please specify

### Definition of Done

Definition of Done
- [ ] account created
- [ ] customer informed

**Comment by mikereiddigital** [comment]
Just to confirm @vc13837 on the basis that an environment rename will result in that being destroyed you're going to review this request & amend it once you've discussed it with your colleagues in the LAA Ops team. Thanks.

**Comment by davidkelliott** [comment]
On hold pending discussions on if a new environment is needed.

**Comment by davidkelliott** [comment]
https://mojdt.slack.com/archives/C06A07N525C/p1706100842757569?thread_ts=1705935733.430049&cid=C06A07N525C

>Hi folks, we have made the decision to just go ahead and have MAAT and MAAT CD API in the same accounts on MP with the same Terraform states, so that we can begin work on MAAT migration immediately. We will have further considerations on the impact of this once we are at the stage of cutting over MAAT CD API.
