### ISSUE TITLE
New environment for `delius-mis`

### ISSUE THREAD

**Issue by georgepstaylor** [ministryofjustice/modernisation-platform#6031]
### Environment details

Accounts for the delius MIS application stack. We'll be migrating these from the hmpps aws accounts and we're separating the MIS stack into it's own set of accounts.

### Application Name

delius-mis

### Description of application

A stack containing Oracle DBs, Nextcloud and SAP Business Object servers

### GitHub team slug

```
hmpps-migration - sandbox/developer
hmpps-dba - instance management
```
```
hmpps-migration as codeowners
```

### Environments

- [X] Development
- [X] test
- [X] Preproduction
- [X] Production

### Environment access level Development

sandbox

### Environment access level Test

developer

### Environment access level Preproduction

developer

### Environment access level Production

developer

### application

delius-mis

### business-unit

HMPPS

### infrastructure-support

probation-webops@digital.justice.gov.uk

### owner

probation-webops@digital.justice.gov.uk

### Subnet sets

- [X] General
- [ ] Isolated

### How do users connect to the application

With a MoJ Official device

### Additional features

Please check any additional features required
- [ ] Additional VPC Endpoints
- [ ] Extended DNS Zones
- [ ] Other - please specify

### Definition of Done

Definition of Done
- [ ] account created
- [ ] customer informed

**Comment by georgepstaylor** [comment]
```
{
  "account-type": "member",
  "codeowners": ["hmpps-migration"],
  "environments": [
    {
      "name": "development",
      "access": [
        {
          "github_slug": "hmpps-migration",
          "level": "sandbox",
          "nuke": "exclude"
        },
        {
          "github_slug": "hmpps-dba",
          "level": "sandbox",
          "nuke": "exclude"
        }
      ]
    },
    {
      "name": "test",
      "access": [
        {
          "github_slug": "hmpps-migration",
          "level": "developer"
        },
        {
          "github_slug": "hmpps-dba",
          "level": "instance-management"
        }
      ]
    },
   {
      "name": "preproduction",
      "access": [
        {
          "github_slug": "hmpps-migration",
          "level": "developer"
        },
        {
          "github_slug": "hmpps-dba",
          "level": "instance-management"
        }
      ]
    },
   {
      "name": "production",
      "access": [
        {
          "github_slug": "hmpps-migration",
          "level": "developer"
        },
        {
          "github_slug": "hmpps-dba",
          "level": "instance-management"
        }
      ]
    }
  ],
  "tags": {
    "application": "delius-mis",
    "business-unit": "HMPPS",
    "infrastructure-support": "probation-webops@digital.justice.gov.uk",
    "owner": "probation-webops@digital.justice.gov.uk"
  },
  "github-oidc-team-repositories": [
    "ministryofjustice/hmpps-delius-operational-automation",
    "ministryofjustice/hmpps-openldap-container"
  ]
}
```

**Comment by Khatraf** [comment]
**New environment setup is complete.** 
Account creation PR #6036
Networking PR #6044
