### ISSUE TITLE
📖 Read group IDs from AWS IAM Identity Center

### ISSUE THREAD

**Issue by jacobwoffenden** [ministryofjustice/modernisation-platform#6035]
### User Story

As a Modernisation Platform customer
I want to be able to group IDs from AWS IAM Identity Center
So that I don't have to hardcode an ID after retrieving it from the few people that have access to the root account

### Value / Purpose

Observability Platform's Amazon Managed Grafana can integrate with AWS IAM Identity Center to synchronise users into groups as they login, this forms part of our RBAC strategy

Currently we have to ask a colleague with sufficient permissions in the root account to retrieve the ID, then hardcode it into our configuration, instead it would be nicer to retrieve the ID by using [`aws_identitystore_group`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/identitystore_group), for example:

```hcl
data "aws_identitystore_group" "this" {
  identity_store_id = tolist(data.aws_ssoadmin_instances.main.identity_store_ids)[0]

  alternate_identifier {
    unique_attribute {
      attribute_path  = "DisplayName"
      attribute_value = var.name
    }
  }
}
```

### Useful Contacts

@jacobwoffenden

### Additional Information

AWS IAM Identity Center resides in the root account, and I can't see a delegated administrator for this component, therefore I would imagine a new role needs provisioning in the root account with the minimum permissions to read from AWS IAM Identity Center, so we can consume it the same as the existing `core` providers available to use in `modernisation-platform-environments`'s `platform_providers.tf`

### Definition of Done

Example - [ ] Documentation has been written / updated
- [ ] README has been updated
- [ ] User docs have been updated
- [ ] Another team member has reviewed
- [ ] Tests are green

**Comment by ep-93** [comment]
Could we get some more information please @jacobwoffenden , maybe after our stand up sometime, just to walk us through it? Thanks

**Comment by dms1981** [comment]
A role does exist for operations involving identitycenter in the root account and can be assumed through this block:
```
provider "aws" {
  region = "eu-west-2"
  alias  = "sso-management"
  assume_role {
    role_arn = "arn:aws:iam::${local.environment_management.aws_organizations_root_account_id}:role/ModernisationPlatformSSOAdministrator"
  }
}
```
So presumably we could do something similar by replicating this with read-only permissions, and allowing it to be assumed by IAM roles in the Modernisation Platform OU?

**Comment by dms1981** [comment]
I think we could do something around creating a new read-only provider in the MOJ root account; we have one already that covers SSO administration [here](https://github.com/ministryofjustice/aws-root-account/blob/main/management-account/terraform/iam-roles.tf#L76), so we ought to be able to use that as a template for what we want; a read-only role that can be assumed by member accounts in the Modernisation Platform OU, and then used to provided IdentityCenter information through terraform data calls.

**Comment by jacobwoffenden** [comment]
> Could we get some more information please @jacobwoffenden , maybe after our stand up sometime, just to walk us through it? Thanks

@ep-93 this got lost in my GitHub notifications 😭 do you still need information? ping me on Slack if you do!

**Comment by dms1981** [comment]
NB. There's now a role in the root account that can be assumed by accounts in the Modernisation Platform OU allowing read-only access to Identity Center: ModernisationPlatformSSOReadOnly

**Comment by dms1981** [comment]
Just about there! Once [this PR](https://github.com/ministryofjustice/aws-root-account/pull/868) is in, then a block like this ought to work just fine:
```
provider "aws" {
  region = "eu-west-2"
  alias  = "sso-readonly"
  assume_role {
    role_arn = "arn:aws:iam::${local.environment_management.aws_organizations_root_account_id}:role/ModernisationPlatformSSOReadOnly"
  }
}

data "aws_ssoadmin_instances" "example" {
  provider = aws.sso-readonly
}

data "aws_identitystore_group" "example" {
  provider = aws.sso-readonly
  identity_store_id = tolist(data.aws_ssoadmin_instances.example.identity_store_ids)[0]

  alternate_identifier {
    unique_attribute {
      attribute_path  = "DisplayName"
      attribute_value = "observability-platform"
    }
  }
}
```

**Comment by dms1981** [comment]
OK! This one's implemented, but the `alternate_identifier {}` block didn't want to behave. I was able to retrieve the group information with a `filter {}` block, though, so it might just be me.
```
data "aws_identitystore_group" "example" {
  provider = aws.sso-readonly
  identity_store_id = tolist(data.aws_ssoadmin_instances.example.identity_store_ids)[0]

  filter {
    attribute_path  = "DisplayName"
    attribute_value = "observability-platform"
  }
}
```
