### ISSUE TITLE
Set up job to create a cymulate account directly.

### ISSUE THREAD

**Issue by SteveLinden** [ministryofjustice/modernisation-platform#6076]
### User Story

As a dev ops engineer I would like to be able to set up an EC2 instance and create access to cymulate on there.

### Value / Purpose

This will allow us to create the cymulate instance that could then be used to check access to the system and ensure that our connections will work as expected. It would also allow us to evaluate routines to ensure they work as expected and that our firerule settings are correct.

### Useful Contacts

Stephen Linden

### Additional Information

To run the install routine a new key would be needed from the security team to allow us access to cymulate. This should only be needed once on the initial setup has been completed but we need to double check this with the security team.
Contacts in security, we have dealt with, are @rajesh.dandamudi ([rajesh.dandamudi@digital.justice.gov.uk](mailto:rajesh.dandamudi@digital.justice.gov.uk)) and @Simon Heron ([simon.heron@digital.justice.gov.uk](mailto:simon.heron@digital.justice.gov.uk)).

We also need to arrange a demo of cymulate (or gain access) to allow us to correctly define the tests we want to run.

Cymulate stays alive (even after a nuke it appears) and can only be stopped by killing it - see the document attached.
[connect to ec2-user for cymulate.txt](https://github.com/ministryofjustice/modernisation-platform/files/14095310/connect.to.ec2-user.for.cymulate.txt)

Finally, the information above assume the same values are used to connect to the bastion and EC2 user. This needs to be looked at as any rebuild will amend the identifier and, possibly, the IP address. 

### Proposal / Unknowns

Creation of the script to connect to the instance and set up the install job may be an issue - a pem file needs to be created but could possibly be added to secrets in AWS.
The key to install is also needed from security so this could be an issue. It hasn't been on the spike so far.

### Definition of Done

Example - [ ] Documentation has been written / updated
- [ ] User docs have been updated
- [ ] Another team member has reviewed
- [ ] Tests are green

**Comment by ep-93** [comment]
Find out if docker image / AMI

**Comment by SteveLinden** [comment]
May not need to be done as they have an AMI in place which they are amending to add kubectl

**Comment by SimonPPledger** [comment]
Sunny has confirmed that this is no longer required - Cymulate did not meet their requirements
