### ISSUE TITLE
Revoking Network access

### ISSUE THREAD

**Issue by ewastempel** [ministryofjustice/modernisation-platform#6108]
### User Story

As an MP engineer
I need to understand how to block or limit networking access in a swiftly manner
So that I can mitigate against malicious actions.
This is just to produce documentation as to what we would have to do for different scenarios.

### Value / Purpose

When a cyber attack occurs it can be difficult to know straight away what actions need to be taken.
This ticket is to prepare the team for such event by producing a documentation on what needs to be done to block networking access to the platform or certain areas of it.

### Additional Information

This should include a list of code areas/ resources that would need amending and it should explain what each change means in practice.

### Proposal / Unknowns

This ticket should produce documentation(s) in the User Guide and/or README files.

### Definition of Done

- [x] Team runbook updated including scenarios and potential actions
- [ ] docs succesfully uploaded to github
- [ ] Another team member has reviewed

**Comment by SteveLinden** [comment]
Making notes of what we should check and block (and where that is) if we need to. Nothing specific, just a bit more general at the moment.
I will put those in the readme documents and put together a how to and put this in our documentation.

**Comment by SteveLinden** [comment]
More changes made to the documentation. The idea of setting up another TGW was discussed and we decided against it. There is a request in place to set up a root table denying all access to the system which can be used. The information from the result will be sent to a "blackhole" as per the instructions from terraform.

**Comment by SteveLinden** [comment]
See #6242 for details.

**Comment by dms1981** [comment]
Personally I think I'd be looking at these angles:
- [] Blocking access for something entering via the internet
- [] Blocking access for something leaving via the internet
- [] Blocking access for something moving internally inside the Modernisation Platform
- [] Blocking access for something leaving via an internal route (eg, TGW)
- [] Blocking access for something entering via an internal route (again, eg TGW)

**Comment by ewastempel** [comment]
The above list is what we're after in terms of the entry and exit points . To help you start on this, think of all different networking devices that are used within MP and managed by MP (TGW, IGW, route tables, firewall and others) and how you can utilise them in order to block the access for each of the above scenarios. Also, think about the impact on the services and document it. Look at it also from a different angle: isolating a single service or an environment vs blocking ingress/egress in multiple or all services/environments. Can we even isolate a single service? If so, how. Otherwise, which resources in the member accounts should we look at (WAF, LB, SG, others).

**Comment by SteveLinden** [comment]
Following various discussions the original PR was closed and a new piece of work set up. This is called - runbooks/block-network-access-if-needed.html.md.erb. It's also been added to the index.
Although Ewa has expressed a preference to showing/suggesting how to do this in code the instructions will still be for the console. The preference here is speed of implementation and NOT having to correct the code . If the code is changed and a step missed or it needs to be turned back to its old version there is a possibility of introducing incorrect changes. I would rather this not happen.

**Comment by SteveLinden** [comment]
Changes made, items moved about and put into PR https://github.com/ministryofjustice/modernisation-platform/pull/6339

**Comment by SteveLinden** [comment]
PR closed. New one will be generated

**Comment by SteveLinden** [comment]
Following discussions with David I have started again (sort of) and agreed what we will cover.

**Comment by SteveLinden** [comment]
Finally completed
