### ISSUE TITLE
Documentation: Revoking User Access

### ISSUE THREAD

**Issue by ewastempel** [ministryofjustice/modernisation-platform#6109]
### User Story

As an MP engineer
I need to understand how to block or limit user access in a swiftly manner
So that I can mitigate against malicious actions.
This is just to produce documentation as to what we would have to do for different scenarios.

### Value / Purpose

When a cyber attack occurs it can be difficult to know straight away what actions need to be taken.
This ticket is to prepare the team for such event by producing a documentation on what needs to be done to block user access (individual, team, automation/repo, etc.)

### Additional Information

This should include a list of code areas/ resources that would need amending and it should explain what each change means in practice. It should also break it down into specific scenarios.

### Proposal / Unknowns

This ticket should produce documentation(s) in the User Guide and/or README files.

### Definition of Done

- [ ] Team runbook updated including scenarios and potential actions
- [ ] docs succesfully uploaded to github
- [ ] Another team member has reviewed

**Comment by richgreen-moj** [comment]
I have a draft PR https://github.com/ministryofjustice/modernisation-platform/pull/6181 for a new "revoking user access" runbook I am currently writing.
