### ISSUE TITLE
Spike: is there a need for two code scanning workflows

### ISSUE THREAD

**Issue by markgov** [ministryofjustice/modernisation-platform#6111]
### User Story

As a Modernisation platform engineer
I need to investigate if there is a need for two code scanning workflows
So that we are not doubling up on work

### Value / Purpose

with the move to trivy we have an opportunities to revisit the need for two code scanning work flows could this all be done on one workflow. is so would it be all done under the terraform secure code analyst or the normal secure code analyst workflow.

what changes need to be done 
can the changes be done
 

### Useful Contacts

Mark Roberts

### Definition of Done

Example 
- [ ] Documentation has been written
- [ ] New issue raised to do the work

**Comment by SimonPPledger** [comment]
yes there is

**Comment by markgov** [comment]
I have attempted to get this working on the github actions module and have failed due to the current the way that the scanning is being done. this is because we are doing a for loop and it runs the trivy command on each loop based on the directory it is scanning. it would basically over write the sarif file on each pass or run though the loop also the only way i have got it to output the file was to amend it for everyone and this also negates the output of the results to the log file as it is dumping into the sarif file.
