### ISSUE TITLE
Bug: Remove bucket_versioning and bucket_force_destroy from bastion linux module

### ISSUE THREAD

**Issue by davidkelliott** [ministryofjustice/modernisation-platform#6114]
### Expected Behavior

TFlint is failing because bucket_versioning and bucket_force_destroy are declared but not used:
https://github.com/ministryofjustice/modernisation-platform-terraform-bastion-linux/actions/runs/7742030400/job/21110231383?pr=350

### Actual Behavior

These should be removed from the module, please note this is a breaking change, and the environments repo will need to be updated to remove references to these variables.

### Steps to Reproduce the Problem

1. Run TFlint in the module

**Comment by mikereiddigital** [comment]
Unit Test has run after removing some of the 100+ buckets in testing-test and clearing down IAM resources that had not been created by previous runs but which had not been cleared. Will now complete the PR and create a new release.
