### ISSUE TITLE
Fix SonarCloud vulnerabilities

### ISSUE THREAD

**Issue by AafAnsari** [ministryofjustice/modernisation-platform#6129]
### User Story

At the time of working on this [story](https://github.com/ministryofjustice/modernisation-platform/issues/4998) the following vulnerability was dismissed as there was no fix available.

https://github.com/ministryofjustice/modernisation-platform/security/code-scanning/965

Please revisit this vulnerability in 6 months to check if the fix is available and resolve/dismiss as appropriate.

https://osv.dev/list?ecosystem=&q=GO-2022-0646

## Value

Reducing security risk.

### Value / Purpose

Reducing security risk.

### Definition of Done

Example - [ ] Documentation has been written / updated
- [ ] README has been updated
- [ ] User docs have been updated
- [ ] Another team member has reviewed
- [ ] Tests are green

**Comment by dms1981** [comment]
I can see that @AafAnsari closed the vulnerability this linked to, and given its age I don't think that the Go team is likely to be remediating this, so I'll defer to Aaf and add this link to Google's discussion of the vuln:

https://security.googleblog.com/2023/04/supply-chain-security-for-go-part-1.html
