### ISSUE TITLE
Decide on what versions of things to use in performance hub

### ISSUE THREAD

**Issue by davidkelliott** [ministryofjustice/modernisation-platform#613]
## User Story

As a performance hub developer and mp engineer
I need to know what version of my application products to run in AWS
So that I can upgrade my products if needed and provide the correct AWS infrastructure

## Value

We need to understand if this is a straight lift and shift or if upgrade work is required.  Ideally we want to lift and shift and upgrade work can be done later on the platform.

## Questions / Assumptions

The main things we are looking at are:
Windows server version
SQL server version
.NET version

## Definition of done

- [ ] versions are specified in the high level design
- [ ] another team member has reviewed

## Reference

From Jeremy:
.NET 4.8 can be installed on Windows Server up to v 2019 (.NET 4.7.2 preinstalled).
Server v2016 would also be fine.
Hub updated to .NET 4.8 - tested in dev & deployed to staging 👍

Current architecture:
https://docs.google.com/document/d/1UZB_QuPoDRE39UYsStB2CDK7VjVf6MUE/edit

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by ezman** [comment]
Had another meeting with Jeremy, and it has been decided that we will move to Windows 2019 Server and SQL Server 2019. We have also confirmed that it is also fine to use the Windows 2019 with .NET 5 which is used by GitHub actions.
