### ISSUE TITLE
Spike: Review security of across account role assumption

### ISSUE THREAD

**Issue by davidkelliott** [ministryofjustice/modernisation-platform#6169]
### User Story

As a security engineer
I want to ensure cross account role assumption is done as securely as possible
So that the platform is as secure as it can be

### Value / Purpose

Ensure we are following security best practice and guidelines.

### Additional Information

Risk register number 68, see there for additional security guidance.

Suggest timeboxing this to 3 days.

### Definition of Done

- [x] Cross account role assumption reviewed
- [x] Propose changes identified
- [x] Another team member has reviewed
- [x] New ticket created

**Comment by SimonPPledger** [comment]
Qns: what role(s) is this? 
What is good practise ?

**Comment by ep-93** [comment]
Looking into 

Permission Boundaries

**Comment by ep-93** [comment]
https://docs.google.com/document/d/1H8JK5uB5lNRJBOvxKuBJ-dTnkIeDy2o7qycl8yLuPLE/edit?usp=sharing

**Comment by ep-93** [comment]
_### **_Roles that need investigating_**_ 

**High Priority**

- ad-fixngo-ec2-roles


**Just to see if we can tie it down more** 

- AWS-SSM-AutomationExecutionRole
- circleci_iam_role



I'm creating tickets to investigate - https://github.com/ministryofjustice/modernisation-platform/issues/8418


<meta charset="utf-8"><b style="font-weight:normal;" id="docs-internal-guid-7b870beb-7fff-8d87-8add-e7be186625c6"><div dir="ltr" style="margin-left:0pt;" align="left">
Role | Location | Usage
-- | -- | --
Collaborator | Here in the mod platform account | Required for collaborators who login to the mod platform to be able to run local plans on their accounts.
vpc_flow_log | Here in core-vpc | No warnings, looks good
ad-fixngo-ec2-roles | Here in core-shared-services | They have "sts:AssumeRole" with a wildcard Ad-fixngo-ec2-access needs to be reviewed. Flagged as insecure. I can assume it from any account, very few permissions on it but still.
member-delegation |   |  
common_statements | Here | No fixes required, but the wildcards are a little scary, but its just read only so no need to fix.
data-engineering-state-access | Here | No fixes required.
grafana_athena_assume_role_policy | Here | No fixes required.
cortex_xsiam_role | Here | No fixes required.
ssm-cross-account-access |   | Addressed by David.
AWS-SSM-AutomationExecutionRole |   | A lot of wildcards, should be reviewed.
MemberInfrastructureAccess |   | No fixes required.
circleci_iam_role | Here | Nothing scary, but could be reduced I imagine.

**Comment by mikereiddigital** [comment]
We discussed this as a team at today's standup & am happy it's complete.
