### ISSUE TITLE
Spike: Review pipeline role permissions

### ISSUE THREAD

**Issue by davidkelliott** [ministryofjustice/modernisation-platform#6170]
### User Story

As a security engineer
I expect pipelines to have the minimum permissions required
So that the principal of least privilege is followed

### Value / Purpose

Ensure we are meeting security best practices

### Additional Information

Risk register number 67.  See there for further guidance.

Suggested timebox of 5 days

### Definition of Done

- [x] Pipline roles reviewed
- [x] Changes made where appropriate
- [x] User docs have been updated
- [x] Another team member has reviewed
- [x] Tests are green

**Comment by dms1981** [comment]
Discussed this at refinement - we think this has mostly been completed vs the risk register entry, but we want to go back over the roles used by pipelines to make sure they're not broad (eg iam:PassRole) without good reason.

**Comment by dms1981** [comment]
From the AWS documentation on iam:PassRole as a permission in a policy associated with a role...
> You can only use the PassRole permission to pass an IAM role to a service that shares the same AWS account.

Any cross-account use would have to be deliberate, with the creation of permissions to assume the role and a trust policy attached.

**Comment by dms1981** [comment]
Informed relevant customers via Slack.

**Comment by dms1981** [comment]
Actions taken:
[x] Roles used by pipelines checked for `iam:PassRole` scoping.
  [x] Applied constraint to `MemberInfrastructureAccess`
  [x] No constraint required for `ModernisationPlatformGithubActionsRole`
[x] Confirmed `iam:PassRole` is only relevant inside a single account
[x] Informed team members where unconstrained use of `iam:PassRole` is present in the environments repository.

**Comment by Khatraf** [comment]
Closing this issue as completed as the definition of done has been met and necessary changes have been applied.
