### ISSUE TITLE
Add read-only access of AWS Backup plans & job history for Platform Users.

### ISSUE THREAD

**Issue by mikereiddigital** [ministryofjustice/modernisation-platform#6238]
### User Story

As a platform member account user I should be be able to view existing AWS Backup plans, resource assignments and a history of backup jobs so that our users can have confirmation that backups are being taken for their production & non-production databases and other data sources.

### Value / Purpose

This has been requested by a platform user and whilst the end-user documentation covers the standard AWS Backup schedules, it is understandable that platform users will want to see both the plans and the job history, particularly if there are concerns of timing & duration.

### Additional Information

https://mojdt.slack.com/archives/C01A7QK5VM1/p1708015007534269

### Definition of Done

Example - 
- [ ] Policy(ies) amended to allow read-only access to these resources by modernisation platform developer users.
- [ ] User docs have been updated
- [x] Access has been tested by an end-user.
- [ ] Tests are green

**Comment by dms1981** [comment]
https://docs.aws.amazon.com/aws-backup/latest/devguide/access-control.html

**Comment by Khatraf** [comment]
After reviewing the current permissions setup for platform users, I can see that developer role already has the `arn:aws:iam::aws:policy/ReadOnlyAccess` policy attached, which includes the required read-only access to AWS Backup services. 
This access has been tested by an end-user and has been confirmed to work as intended.
