### ISSUE TITLE
Performance hub create infrastructure

### ISSUE THREAD

**Issue by davidkelliott** [ministryofjustice/modernisation-platform#624]
## User Story

As an mp engineer
I need to work with the performance hub team to create the terraform infrastructure as code
So that my application can be hosted

More info to follow after high level design

## Definition of done

- [ ] the ECS cluster and database have been created from code

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by ezman** [comment]
We now have the cluster running and database, along with the bastion access to the db mgmt server. Closing this ticket, the outstanding work will follow in a new ticket.
