### ISSUE TITLE
TFSEC - CKV_TF_1: "Ensure Terraform module sources use a commit hash". NOTE this is draft - requires further information.

### ISSUE THREAD

**Issue by mikereiddigital** [ministryofjustice/modernisation-platform#6240]
### Expected Behavior

TFSEC is failing with CKV_TF_1 as references to remote modules do not use a ref or a commit hash e.g. https://github.com/ministryofjustice/modernisation-platform-environments/actions/runs/7932068549/job/21657664603?pr=5090.

### Actual Behavior

See above.

### Steps to Reproduce the Problem

Re-run TFSEC.

**Comment by dms1981** [comment]
We don't generally apply fixes to customer code in `modernisation-platform-environments`, but you could bring this to the attention of the customer?
