### ISSUE TITLE
Create new route table denying all access 

### ISSUE THREAD

**Issue by SteveLinden** [ministryofjustice/modernisation-platform#6242]
### User Story

As a modernisation platform engineer I require a new root table to deny all access to the system. It should be called block-all-access and will be 0.0.0.0/0 - deny.

The best way to do this is follow this code from terraform - you can send restricted access to a "blackhole".

                  _resource "aws_ec2_transit_gateway_route" "example" {
                  destination_cidr_block         = "0.0.0.0/0"
                  blackhole                      = true
                  transit_gateway_route_table_id = aws_ec2_transit_gateway.example.association_default_route_table_id
                  }_ 
                  

### Value / Purpose

This ties into #6108 and will be used for all environments which are being attacked.

### Additional Information

Currently (16.02.2024) there are a lot of environments that require amendment. It is suggested that the TGW is removed - after noting its current name - and this option is to restrict other access.

### Proposal / Unknowns

This has not really been tested so we are assuming it will be a "quick-win" if we need to limit access to the accounts.

### Definition of Done

- [ ] Documentation has been written (in progress)/amended
- [ ] README has been updated
- [ ] User docs have been updated were necessary
- [ ] Another team member has reviewed
- [ ] Tests are green

**Comment by dms1981** [comment]
Closed as not required
