### ISSUE TITLE
Customisable retention periods for AWS Backup Plans in Non-Production Accounts.

### ISSUE THREAD

**Issue by mikereiddigital** [ministryofjustice/modernisation-platform#6250]
### User Story

As a member account user, I would like to customise the retention duration backups generated of AWS Backup in non-production accounts if 30 days is not required.

### Value / Purpose

A shorter retention period will reduce the overall cost of keeping them.

### Useful Contacts

maciej.matysiak@digital.justice.gov.uk

### Additional Information

Raised as a question in the #ask-modernisation-platform channel.

### Definition of Done

Example - [ ] Documentation has been written / updated
- [ ] Suggestion reviewed and feasibility determined
- [ ] AWS Backup & IAM policies amended.
- [ ] Changes tested and reviewed
- [ ] Confirmed as working with CCMS Ops team.

**Comment by ep-93** [comment]
I'm going to say this is blocked until the bug for baselines is fixed, as thats a blocker for new accounts with an annoying workaround. Ticket is - https://github.com/ministryofjustice/modernisation-platform/issues/7497
