### ISSUE TITLE
DR -  Dynamo DB multi region

### ISSUE THREAD

**Issue by ep-93** [ministryofjustice/modernisation-platform#6258]
### User Story

Change the  Dynamo DB,  modernisation-platform-terraform-state-lock table in the mod-platform account to be multi regional, copied to eu-west-1.

### Value / Purpose

Required for DR.

### Definition of Done

- [ ] Another team member has reviewed
- [ ] Dynamo DB is multi regional

**Comment by SimonPPledger** [comment]
do we need this - or would we just recreate it?
