### ISSUE TITLE
Create testing strategy

### ISSUE THREAD

**Issue by seanprivett** [ministryofjustice/modernisation-platform#628]
## User Story

A testing strategy to inform decisions around:

1.  Smoke testing
2. How we can test without breaking the platform and/or applications
3. How we test infrastructure
4. Defining the borders between AWS core components and our platform (we don't want to test the former)
5. How we define the borders between our platform testing and application testing

## Definition of done

- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] tests are green

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by davidkelliott** [comment]
More detailed ticket for the networking side of things here - https://github.com/ministryofjustice/modernisation-platform/issues/1036
