### ISSUE TITLE
Remove `cortex-xsiam` accounts

### ISSUE THREAD

**Issue by dms1981** [ministryofjustice/modernisation-platform#6298]
### User Story

As a Modernisation Platform Product Owner
I want to remove any accounts for the `cortex-xsiam` application
So that applications not being migrated to MP do not have accounts on MP

### Value / Purpose

After further discussion with @mTouhid, the `cortex-xsiam` application provision in #6112 will no longer be deployed on MP. This issue should cover the removal of any provisioned accounts for the application.

### Useful Contacts

@dms1981, @mTouhid

### Additional Information

[Deleting an environment (AWS account)](https://user-guide.modernisation-platform.service.justice.gov.uk/runbooks/deleting-an-environment.html)

### Definition of Done

- [ ] `cortex-xsiam-development` removed
- [ ] `cortex-xsiam-production` removed
- [ ] Tests are green

**Comment by richgreen-moj** [comment]
PR with changes made so far https://github.com/ministryofjustice/modernisation-platform/pull/6413

We have followed the [guide](https://user-guide.modernisation-platform.service.justice.gov.uk/runbooks/deleting-an-environment.html) and have been making updates to it as we progress.

Next step is to get someone with root access to move the accounts to the 'root OU' so we can then go and delete the account.

**Comment by richgreen-moj** [comment]
Accounts have been deleted finally, we did encounter some issues with the New Environment workflow being triggered mid-progress which created two additional accounts. This is all documented in [Slack](https://mojdt.slack.com/archives/C013RM6MFFW/p1710158699597139)
