### ISSUE TITLE
Spike: Low Priority Pager duty alerts - review

### ISSUE THREAD

**Issue by SimonPPledger** [ministryofjustice/modernisation-platform#6314]
### User Story

As a modernisation platform engineer
I want to look at our low priority pagerduty alerts
So that we are only receiving alerts that require a response. However this might not be possible.
This is to confirm what we want to do with these alerts rather than fix them (for now)

### Value / Purpose

We regularly see the following alarms in our `#modernisation-platform-low-priority-alarms` Slack channel:

[Sum unauthorised-api-calls GreaterThanOrEqualToThreshold 1.0](https://moj-digital-tools.pagerduty.com/incidents/Q0V8ACALY459ON?utm_campaign=channel&utm_source=slack)

[Sum sign-in-failures GreaterThanOrEqualToThreshold 1.0](https://moj-digital-tools.pagerduty.com/incidents/Q37S6NNQSXY6VW?utm_campaign=channel&utm_source=slack)

[Sum iam-policy-changes GreaterThanOrEqualToThreshold 1.0](https://moj-digital-tools.pagerduty.com/incidents/Q1S9MW41A5ZFL6?utm_campaign=channel&utm_source=slack)

This ticket will involve taking a look at the alerts we receive in the `#modernisation-platform-low-priority-alarms` channel and assessing if we need to be alerted for them.

Ideally we should only receive alerts for incidents that require our attention.

### Additional Information

We should ensure that we don't compromise our adherence to AWS Security Hub Security Standards.

### Definition of Done

- [ ] Alarms investigated and triggers identified and what the thresholds are
- [ ] We agree whether these are necessary
- [ ] If not necessary, look at options to stop alerting and resolve cause if possible
- [ ] If necessary raise new tickets to resolve the cause of the alert

**Comment by dms1981** [comment]
Are these linked to Security Hub Control Standards? If we modify these alerts, will we affect our Security Hub compliance metric? Could we just not push these alerts through to Slack?

**Comment by ewastempel** [comment]
For [Sum iam-policy-changes GreaterThanOrEqualToThreshold 1.0](https://moj-digital-tools.pagerduty.com/incidents/Q1S9MW41A5ZFL6?utm_campaign=channel&utm_source=slack) make it specific to IAM policies that are used in our pipelines/SSO roles (all the roles that we own).

**Comment by ewastempel** [comment]
For [Sum unauthorised-api-calls GreaterThanOrEqualToThreshold 1.0](https://moj-digital-tools.pagerduty.com/incidents/Q0V8ACALY459ON?utm_campaign=channel&utm_source=slack)
and
[Sum sign-in-failures GreaterThanOrEqualToThreshold 1.0](https://moj-digital-tools.pagerduty.com/incidents/Q37S6NNQSXY6VW?utm_campaign=channel&utm_source=slack) adjust the threshold to notify when it happens on mass.

**Comment by SimonPPledger** [comment]
believe this is replaced by https://github.com/ministryofjustice/modernisation-platform/issues/1535 - but want to keep it open until we have confirmation

**Comment by SimonPPledger** [comment]
closing as it is a duplicate
