### ISSUE TITLE
[Spike] Scheduled baseline duration

### ISSUE THREAD

**Issue by SimonPPledger** [ministryofjustice/modernisation-platform#6316]
### User Story

As a Modernisation Platform Engineer
I want to reduce the duration that my scheduled baseline job takes to complete
So that I can implement changes and updates with more agility

### Value / Purpose

As the platform grows it is likely that the scheduled baseline will take even longer than it currently does, which will hamper our delivery.

* We want to look at what we can do to reduce the run time.
* One option is amending the scheduled baseline to only look at changes.
* Another option would be to increase the concurrency with which jobs run.

### Additional Information

https://github.com/ministryofjustice/modernisation-platform/blob/main/.github/workflows/scheduled-baseline.yml

### Definition of Done

- [x] Spike appropriately timeboxed (**1 day**)
- [ ] Identify some options
- [ ] Agreeing with team which ones to try
- [ ] tickets raised to implement the agreed options

**Comment by markgov** [comment]
concurrency definition
https://stackoverflow.com/questions/74737407/what-is-concurrency-in-github-actions

**Comment by markgov** [comment]
document written up and shared with the team
https://docs.google.com/document/d/1w-XzjdZBd8LDRKr-GaqkOqxJ6cEN021NDpIjDClGAUE/edit?usp=sharing

**Comment by markgov** [comment]
https://github.com/ministryofjustice/modernisation-platform/issues/6534
