### ISSUE TITLE
[Spike] Limits and quotas (accounts, environments and APIs)

### ISSUE THREAD

**Issue by SimonPPledger** [ministryofjustice/modernisation-platform#6319]
### User Story

As a Modernisation Platform Engineer
I want to identify limits and quotas relate to account provisioning
So that I can identify and address any potential limits to the size of the platform

### Value / Purpose

As the **platform** continues to grow we need to understand if there are any limits to the size of our AWS estate.

* Are there any hard limits on the account creation process?
* Is there a maximum number of environments we can have?
* Are there any limits/quotas on APIs (eg, SSO?)?
* Is there a limit to the number of accounts that can be part of the MOJ AWS Organization?
* Pipeline failures related to quota limits; what are these?

Is there anything else we need to consider?

What about non-AWS APIs that we make use of such as PagerDuty and GitHub?

Understanding these limits now will give us chance to address them before hitting them - or, at worst, knowing we have reached a limit

### Additional Information

* https://docs.aws.amazon.com/organizations/latest/userguide/orgs_reference_limits.html
* https://docs.aws.amazon.com/ram/latest/userguide/service-quotas.html
* https://docs.aws.amazon.com/singlesignon/latest/userguide/limits.html
* https://docs.aws.amazon.com/vpc/latest/tgw/transit-gateway-quotas.html

### Proposal / Unknowns

We're not sure on the scope here; picking up this ticket we don't expect to comprehensively cover everything we do or might use, but we'll cast a wide net.

### Definition of Done

- [ ] Appropriately timebox spike (**3 days**)
- [ ] Document any limits and quotas
- [ ] Consider, and document, potential resolutions or workarounds (perhaps in a user runbook)
- [ ] Review with team
- [ ] Raise tickets where we think we should change our approach to avoid hitting quotas

**Comment by richgreen-moj** [comment]
To answer "_Is there a limit to the number of accounts that can be part of the MOJ AWS Organization?_"
https://docs.aws.amazon.com/organizations/latest/userguide/orgs_reference_limits.html

I imagine the number of accounts doesn't have a hard limit as you can request an increase. 
The number of OUs looks to be 1000. I think we create an OU per application and MP is just part of the larger org so I'm not sure if another team is monitoring that overall to assess the impact?

**Comment by Khatraf** [comment]
Please see final draft of [document](https://docs.google.com/document/d/150k_RM_4Cw2g_5Ed1iCcm4rZFWSQhW_2chHprFLhkh8/edit?usp=sharing) and I have also shared it with the team for their review.

**Comment by Khatraf** [comment]
Please see final draft of [document](https://docs.google.com/document/d/150k_RM_4Cw2g_5Ed1iCcm4rZFWSQhW_2chHprFLhkh8/edit?usp=sharing) and I have shared it with the team for their review.
