### ISSUE TITLE
Major update to github pages publisher v4.0.0

### ISSUE THREAD

**Issue by richgreen-moj** [ministryofjustice/modernisation-platform#6333]
### User Story

As  a MP engineer
I want to update the tech docs github page publisher to the latest version
So that the platforms dependencies are kept up to date

### Value / Purpose

The [tech docs github page publisher](https://github.com/ministryofjustice/tech-docs-github-pages-publisher) has had a major upgrade (v4.0.0). We need to review the breaking changes and update to the latest version.

For more information see this [Slack post](https://mojdt.slack.com/archives/CFE5ZQAQ7/p1708623618440489)

We make use of this in the [publish-gh-pages](https://github.com/ministryofjustice/modernisation-platform/blob/42fe9153176eaa9fec75485561a1604955712f63/.github/workflows/publish-gh-pages.yml#L27) repo

### Additional Information

In the Slack post David Read mentions that we shouldn't be using the crown logo in our docs - we should keep an eye on whether the [issue he raised with CDDO ](https://github.com/alphagov/tech-docs-gem/issues/347)has been addressed before implementing the ticket.

### Definition of Done

- [x] Any breaking changes been reviewed to assess any remediation required
- [x] Remediation completed and version updated
- [x] Testing completed successfully
- [x] Another team member has reviewed

**Comment by ASTRobinson** [comment]
https://insidegovuk.blog.gov.uk/2024/02/19/updating-gov-uks-crown/?mc_cid=a695e35983&mc_eid=2f7192c536
