### ISSUE TITLE
[Spike] Code quality / maintainability

### ISSUE THREAD

**Issue by SimonPPledger** [ministryofjustice/modernisation-platform#6334]
### User Story

As a Modernisation Platform Owner
I want a solid and well-maintained code base
So that the we minimise the risk of introducing errors

### Value / Purpose

As the platform continues to grow it becomes even more critical that we ensure that we have a solid and well maintained code base - this includes all code, but also any modules that we have.

This ticket is to look at what we can do to ensure that we continue to have a well maintained code base.

Having a well understood and maintained code base reduces the risk of introducing errors or half completing changes (eg if we patch modules, but we miss out an old module that we later re-introduce).

### Additional Information

* https://github.com/ministryofjustice/modernisation-platform
* https://github.com/orgs/ministryofjustice/repositories?q=modernisation-platform

### Proposal / Unknowns

* Should this issue include selecting module candidates for archiving where they're unused?
* Is this a candidate for using a Large Language Model to look at our publically available code and assess it for consistency in approaches (eg, use of `for` expressions, `local` values, etc)

### Definition of Done

- [x] Agree an appropriate timebox for this spike
- [x] Assess coverage of `dependabot` checks for keeping code up-to-date
- [x] Do we have sufficient test coverage? Are these tests suitably visible?
- [x] Document how we can ensure code is maintained and where we have gaps
- [x] Report back to team / via comments on this issue
- [x] Raise any tickets required to address gaps

**Comment by dms1981** [comment]
On the topic of Dependabot, we have good coverage of our terraform and github actions.
Repositories with a broader folder structure make use of a script-and-action approach to generate the dependabot file, as Dependabot does not presently support wildcards in its `directory:` value.

The following repositories would benefit from having the script-and-action approach extended to them:
 - [ ] modernisation-platform-terraform-baselines
 - [ ] modernisation-platform-terraform-ecs-cluster

**Comment by dms1981** [comment]
On the topic of tests, again we have generally good coverage but both gaps and scope for improvements exist. With regards improvement, we currently make use of Terratest, but we could rewrite to use native Terraform test functionality. We could also do with checking our test code to ensure that we are testing all things resources created in the module and carrying out a simple linting / naming consistency pass.

The following repositories do not have any unit tests at present:
- [ ] modernisation-platform-ami-builds
- [ ] modernisation-platform-configuration-management
- [ ] modernisation-platform-cp-network-test
- [ ] modernisation-platform-incident-response
- [ ] modernisation-platform-terraform-baselines
- [ ] modernisation-platform-terraform-cross-account-access
- [ ] modernisation-platform-terraform-dns-certificate
- [ ] modernisation-platform-terraform-iam-superadmins
- [ ] modernisation-platform-infrastructure-test
- [ ] modernisation-platform-terraform-member-vpc

General objectives applicable to *all* repositories would be as follows:
- [ ] Evaluate if [Terraform tests](https://developer.hashicorp.com/terraform/language/tests) are a suitable replacement for Terratest
- [ ] Comb through existing tests for consistency; adopt a common name (unit_test.go?), pass files through a linter, add any missing tests for created resources, ensure we are not using hard coded values for resources (eg `name = test-bucket` vs `name_prefix = test-bucket` or `role_name = test-role` vs `role_name = test-role-${random_string.name}`

**Comment by dms1981** [comment]
On the topic of the scope of modules we have, I saw a few modules where I think a discussion on archiving is warranted:
- [ ] modernisation-platform-cp-network-test (appears minimally used, are there better tools available now?)
- [ ] modernisation-platform-terraform-aws-vm-import (only appears to be used by xhibit portal team, are other teams now using the AWS Migration tools instead?)
- [ ] modernisation-platform-terraform-dns-certificates (appears unfinished; either finish it or remove it?)
- [ ] modernisation-platform-terraform-iam-superadmins (given that SSO access is our first-choice method, how relevant is this module?)
- [ ] modernisation-platform-infrastructure-test (appears mostly abandoned and unused)
- [ ] modernisation-platform-terraform-s3-bucket-replication-role (should this be rolled into the main s3-bucket module?)

**Comment by ewastempel** [comment]
Interesting finds David, my opinion on:

- modernisation-platform-terraform-iam-superadmins - **if we are the only team using it (for superadmin IAM), I would suggest keeping it as a module (if it makes sense) but inside the MP repo**

- modernisation-platform-terraform-s3-bucket-replication-role - **yes, if sensible**

- However, it might be that we think having smaller external modules is a worthwhile path to follow, in which case we should consider the scope of the modules in the main modernisation-platform repository and decide if any are in scope to be promoted to separate modules of their own. - **definitely worth a thought**

**Comment by davidkelliott** [comment]
@ewastempel the only reason that we may want to keep the admin users in a separate repo is that it adds an extra layer of hassle, eg, to change admin users you need to get 2 PRs approved, so there is less chance an admin user can be added or removed by accident

**Comment by ewastempel** [comment]
> @ewastempel the only reason that we may want to keep the admin users in a separate repo is that it adds an extra layer of hassle, eg, to change admin users you need to get 2 PRs approved, so there is less chance an admin user can be added or removed by accident

Cool, that makes sense.
