### ISSUE TITLE
[Spike] IAM roles and policies

### ISSUE THREAD

**Issue by SimonPPledger** [ministryofjustice/modernisation-platform#6335]
### User Story

As an engineer on the modernisation platform
I want to assess the IAM roles we provide for customers
So that the policies we attach to them are manageable, and adhere to a least-access principle

### Value / Purpose

We provide roles to customers through single sign-on (SSO) with attached IAM policies defined in terraform.

This issue is to look at the roles we provide and assess the risk is with the current policies. 
* Should we split out some of the activities from the developer role?
* Are we trying to cater for a range of specific needs, and in doing so providing greater access than requested to teams?
* What would an appropriate level of disaggregation look like if we think we need to split out roles?
* By breaking up policies we might be able to get around size limitations?

This will help us to reduce the risk of changes negatively impacting the environment - either by accident or design.

The `developer` role is of particular interest as it caters for many different elements. We may also want to consider roles where multiple policies are attached.

### Useful Contacts

Katie who is looking at, among other things, role-based requirements

### Additional Information

* https://repost.aws/knowledge-center/iam-increase-policy-size
* https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_iam-quotas.html#reference_iam-quotas-entity-length

### Definition of Done

- [ ] Appropriately timebox spike (3 days?)
- [ ] Discuss typical customer use cases for console access with user researcher
- [ ] Assess current policies
- [ ] Assess mapping of policies-to-roles
- [ ] Identify any way to improve manageability and security of policies
- [ ] Report findings back to the team
- [ ] Raise further tickets as appropriate

**Comment by ep-93** [comment]
Julia had a great idea in this thread too. https://moj.enterprise.slack.com/archives/C013RM6MFFW/p1708354195372729

**Comment by ep-93** [comment]
Doc - https://docs.google.com/document/d/1vYCAtQpHgBBSMXgs7--uTwV7idt3cI3HRTZ1kKrZMCQ/edit?usp=sharing

With the people present we decided to go with the easier option for now.
