### ISSUE TITLE
Sandbox to investigate bedrock

### ISSUE THREAD

**Issue by carlosMoJ** [ministryofjustice/modernisation-platform#6337]
### Environment details

I would like to get access to a sandbox where I can investigate bedrock. I am part of the Apprenticeship programme (Digital and Technology specialist msc) and approaching the final project stage. 

Initially I would like just a dev environment - is it possible to create afterwards pre-production and production stages if required? But initially, just dev.

### Application Name

Apprenticeship-Bedrock

### Description of application

I am thinking of creating some kind of chatbot which will take data out of one (or two) of our applications (publicly available data) and interact with users providing answers and links referring to their queries. I was thinking of using .NET

### GitHub team slug

justicedata

### Environments

- [X] Development
- [ ] test
- [ ] Preproduction
- [ ] Production

### Environment access level Development

sandbox

### application

apprenticeship-bedrock

### business-unit

Platforms

### infrastructure-support

carlos.fernandez@justice.gov.uk

### owner

carlosMoJ

### Subnet sets

- [X] General
- [ ] Isolated

### How do users connect to the application

Over the public internet

### Additional features

Please check any additional features required
- [ ] Additional VPC Endpoints
- [ ] Extended DNS Zones
- Bedrock Console

### Definition of Done

Definition of Done
- [ ] account created
- [ ] customer informed

**Comment by dms1981** [comment]
Customer given access through Analytical Platform rather than Modernisation Platform.
