### ISSUE TITLE
Nomis to MoJ SMTP relay - validate connectivity for port 587

### ISSUE THREAD

**Issue by SimonPPledger** [ministryofjustice/modernisation-platform#6342]
### Expected Behavior

As reported by Dom Robinson.

He needs the Nomis accounts in Mod Platform to be able to communicate with MoJ SMTP Relay 10.180.104.100 and 10.180.105.100 (some more details here - [MoJO-SMTP-Relay](https://github.com/ministryofjustice/staff-infrastructure-smtp-relay-server#readme) . 

Here is a link to the conversation in slack (https://mojdt.slack.com/archives/C01A7QK5VM1/p1668610127017869). 

This has been set up for nomis test and production - and it should allow port 25 and port 587

Everything works for port 25.

But for port 587 it is timing out. However looking at the logs:

![Image](https://github.com/ministryofjustice/modernisation-platform/assets/45791941/4170b79a-5842-464d-9de7-51c7f9cb4a4e)

We have spoken to the core network team and they say port 587 is open.

nomis test is 10.26.8.134
and production - 10.27.12.178

### Actual Behavior

it is being timed out

### Steps to Reproduce the Problem

nc -vzw 5 10.180.104.100  587

**Comment by SteveLinden** [comment]
Checked and the port 587 is open in the logs. Port 25 works and networks tell us 587 also exists. Port 587 does not work

**Comment by SteveLinden** [comment]
I've had a look at the logs and it appears to work but it seems to stop at the external inspection VPC

**Comment by SteveLinden** [comment]
@dms1981 ran through various checks and found that the current setting was 10.180.104.0/22 which would not pick up the correct address. This was changed to use another that was in place which picked up the 100 part for this and 105. 

This has been added to the system

**Comment by SimonPPledger** [comment]
We now know connectivity is in place. The problem is that the mail server doesn't listen on port 587. Dom is looking to get this resolved
