### ISSUE TITLE
Create new environment for Data Engineering data sharing tool

### ISSUE THREAD

**Issue by lalithanagarur** [ministryofjustice/modernisation-platform#6343]
### Environment details

This environment will enable external suppliers upload data to MoJ and download data from MoJ. The current purpose is to serve data sharing capabilities for BOLD projects but will be enhanced in the future for other data engineering data sharing. 

### Application Name

data engineering data sharing

### Description of application

The environment will host a SFTP server. Each data supplier will have a user role to connect to the SFTP server for upload and download of data. The uploaded data will immediately be moved to a landing bucket in the Analytical Platform using a managed workflow. The data for external suppliers to download will come from the Analytical Platform and will be stored in a S3 bucket and IAM Role + Policies will be used to control which bucket paths will be accessible and visible to each user. 

![diagram (2)](https://github.com/ministryofjustice/modernisation-platform/assets/123457715/18f72c9d-48e6-4fa5-a5f5-f99e1ba74e01)

### GitHub team slug

data-engineering-data-sharing

### Environments

- [X] Development
- [ ] test
- [x] Preproduction
- [X] Production

### Environment access level Development

sandbox

### Environment access level Preproduction

developer

### Environment access level Production

view-only

### application

data engineering data sharing

### business-unit

Platforms

### infrastructure-support

Data engineering: dataengineering@digital.justice.gov.uk

### owner

Data engineering: dataengineering@digital.justice.gov.uk

### Subnet sets

- [X] General
- [ ] Isolated

### How do users connect to the application

Over the public internet

### Additional features

Please check any additional features required
- [ ] Additional VPC Endpoints
- [ ] Extended DNS Zones
- [ ] Other - please specify

### Definition of Done

Definition of Done
- [ ] account created
- [ ] customer informed

**Comment by Gary-H9** [comment]
Superceded by #6364.
