### ISSUE TITLE
Setup Dev AWS account for operations-engineering

### ISSUE THREAD

**Issue by levgorbunov1** [ministryofjustice/modernisation-platform#6361]
### Environment details

Operations Engineering need a sandbox AWS environment to test AWS infrastructure operations. 
- ideally admin access to core AWS services. 
- Need to be able to test automatic Route 53 operations.

### Application Name

operations-engineering

### Description of application

Operations Engineering need a sandbox AWS environment to test AWS infrastructure operations. 
- ideally admin access to core AWS services. 
- Need to be able to test automatic Route 53 operations.

### GitHub team slug

operations-engineering

### Environments

- [X] Development
- [ ] test
- [ ] Preproduction
- [ ] Production

### Environment access level Development

sandbox

### application

operations-engineering

### business-unit

operations-engineering

### infrastructure-support

operations-engineering@digital.justice.gov.uk

### owner

operations-engineering@digital.justice.gov.uk

### Subnet sets

- [X] General
- [ ] Isolated

### How do users connect to the application

Over the public internet

### Additional features

Please check any additional features required
- [ ] Additional VPC Endpoints
- [ ] Extended DNS Zones
- [ ] Other - please specify

### Definition of Done

Definition of Done
- [X] account created
- [X] customer informed

**Comment by SimonPPledger** [comment]
@connormaglynn - can we discuss this

**Comment by sukeshreddyg** [comment]
New environment setup is complete.
