### ISSUE TITLE
Creation of `analytical-platform-ingestion` 

### ISSUE THREAD

**Issue by Gary-H9** [ministryofjustice/modernisation-platform#6364]
### Environment details

This request supersedes this existing issue [here](https://github.com/ministryofjustice/modernisation-platform/issues/6343). In short, the purpose of the `analytical-platform-ingestion` environment will be to ingest data into the Analytical Platform in the same manner described in the other issue. This piece of work is going to be owned by the Analytical Platform from instantiation and therefore we've elected to adopt this naming - `analytical-platform-ingestion`. 

Content from the other issue:
"This environment will enable external suppliers upload data to MoJ and download data from MoJ. The current purpose is to serve data sharing capabilities for BOLD projects but will be enhanced in the future...."

### Application Name

analytical-platform-ingestion

### Description of application

The purpose of this environment will be to ingest data into the Analytical Platform.

The environment will host a SFTP server. Each data supplier will have a user role to connect to the SFTP server for upload and download of data. The uploaded data will immediately be moved to a landing bucket in the Analytical Platform using a managed workflow. The data for external suppliers to download will come from the Analytical Platform and will be stored in a S3 bucket and IAM Role + Policies will be used to control which bucket paths will be accessible and visible to each user.

![image](https://github.com/ministryofjustice/modernisation-platform/assets/26419401/afb6e6c0-583c-4065-a5bb-070418d82380)

### GitHub team slug

analytical-platform

### GitHub code owner team slug

analytical-platform

### GitHub actions reviewer team slug

analytical-platform

### Environments

- [X] Development
- [ ] test
- [ ] Preproduction
- [X] Production

### Environment access level Development

sandbox

### Environment access level Production

developer

### application

analytical-platform-ingestion

### business-unit

platforms

### infrastructure-support

analytical-platform@digital.justice.gov.uk

### owner

Analytical Platform

### Subnet sets

- [ ] General
- [X] Isolated

### How do users connect to the application

Over the public internet

### Additional features

We will need to allow inbound connections from external partners. 

Outbound connections will also be required for data extraction. 

### Definition of Done

Definition of Done
- [x] account created
- [x] customer informed

**Comment by ASTRobinson** [comment]
account created and the user informed.
