### ISSUE TITLE
[SPIKE] Trial attribute-based access control in `sprinkler-development`

### ISSUE THREAD

**Issue by dms1981** [ministryofjustice/modernisation-platform#6389]
### User Story

As a modernisation platform customer
I want to use attribute-based access control
So that I can restrict access to my resources to my team when in shared environments

### Value / Purpose

Through the [Configure Auth0 SAML assertion](https://github.com/ministryofjustice/modernisation-platform/issues/6055) story we now supply a string of a user's GitHub teams during SSO.

Now that we have Modernisation Platform customers deploying resources into our `core-shared-services` environment we would like to add some additional conditions to how the policy attached to the `instance management` for specific accounts.

The purpose of this story will be to find out how to add some additional policy statements to the [instance-management](https://github.com/ministryofjustice/modernisation-platform/blob/main/terraform/environments/bootstrap/single-sign-on/policies.tf#L577) policy, but only in a single environment as applying ABAC to all uses of the `instance-management` role may not be desirable.

### Useful Contacts

@dms1981

### Additional Information

https://repost.aws/knowledge-center/iam-ec2-resource-tags
https://aws.amazon.com/blogs/security/configure-aws-sso-abac-for-ec2-instances-and-systems-manager-session-manager/

### Definition of Done

- [x] Spike timeboxed
- [x] ABAC condition applied to `instance-management` policy in `sprinkler-development`
- [x] ABAC tested
- [ ] ABAC demo'd to team
- [x] Follow-up issue to implement this in appropriate shared environment(s) raised

**Comment by dms1981** [comment]
Tagged myself for this one, but happy to pass it over to anyone else who's interested in trying it.

**Comment by markgov** [comment]
PR updated so that the new statement is only applicable to three accounts
https://github.com/ministryofjustice/modernisation-platform/pull/7111

**Comment by markgov** [comment]
After talking with AWS found that i need to add in permission to block session manager on ec2 these permission are 
"ssmmessages:CreateControlChannel",
                "ssmmessages:CreateDataChannel",
                "ssmmessages:OpenControlChannel",
                "ssmmessages:OpenDataChannel"
when i tried to stop the ec2 with the instance management role it would not let me do it so this proves the permissions are working as intended i just need to check shared services and cooker now

**Comment by markgov** [comment]
Looking into this more it seems that simply adding in the code to the iam role is not the only thing that needs to be done as we also need to enable Enable identity-aware sessions within the root sso account and also add in some attributes for the github team as well. I do not know what the affect of enabling this on the sso account will do so going to talk it over with the team to discuss the way forward

**Comment by markgov** [comment]
ok so basically because it's an sso role it not just a simple case of adding the condition code of
"Condition": {
                "StringLike": {
                    "aws:ResourceTag/Owner": "${aws:PrincipalTag/github_team}"
                }
to the iam role you need to map the github_team in the iam identity managemnt  in sso so it know what it's looking for. but also we need to enable the  Attributes for access control so that we are using ABAC once that is enable we can add in the start adding in a key which would be the github_team and then the path which would come from the saml

**Comment by markgov** [comment]
moving to block while we talk about the impacts of enabling Attributes for access control
