### ISSUE TITLE
Migrating NOC AWS accounts to Modernisation Platform

### ISSUE THREAD

**Issue by SimonPPledger** [ministryofjustice/modernisation-platform#6416]
### User Story

Following on from conversations with the Network Operations team (NOC), we plan to migrate their production and non-production AWS accounts to sit within the modernisation platform.
We need to advise the people below in advance of making any changes.

### Value / Purpose

In the first instance this will allow them to take advantage of some of the guardrails we have in place. 

### Useful Contacts

nicholas.fan@justice.gov.uk
shuja.uddin1@justice.gov.uk

### Additional Information

They currently access their AWS accounts via github. They don't use Pre-prod at moment - but want to going forward. They do have a 'dev' environment that is within their production AWS account.
In the future we would them to move to a 'normal' member account. We should also use this ticket to look at where we can improve the NOC teams management of the accounts.

### Proposal / Unknowns

n/a

### Definition of Done

Example - [ ] Documentation has been written / updated
- [ ] Accounts migrated
- [ ] Any necessary documentation created
- [ ] Any recommendations document, reviewed and suggested to NOC team

**Comment by markgov** [comment]
PR created in draft mode for noc migration

**Comment by markgov** [comment]
NOC production account moved to modernisation platform and secure base line run all PRS merged and accounts removed and imported from the terraform state file
