### ISSUE TITLE
Complete production ready checklist for corporate staff rostering

### ISSUE THREAD

**Issue by davidkelliott** [ministryofjustice/modernisation-platform#6441]
## User Story

As a modernisation platform engineer
I need to be confident that I have all the information I need for supporting new applications as they go live
So that I can effectively provide support.
Details are provided here:
https://user-guide.modernisation-platform.service.justice.gov.uk/user-guide/production-ready-checklist.html

## User Type(s)

MP engineers

## Value

Ensure code quality and security of the platform

## Definition of done

- [ ] checklist udpated
- [ ] reviewed by another team member

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by markgov** [comment]
found 27 HIGH severity level findings in Security Hub

**Comment by markgov** [comment]
the 27 highs have been explained and accepted
