### ISSUE TITLE
complete production ready checklist for CDPT-CHAPS

### ISSUE THREAD

**Issue by SimonPPledger** [ministryofjustice/modernisation-platform#6446]
## User Story

As a modernisation platform engineer
I need to be confident that I have all the information I need for supporting new applications as they go live
So that I can effectively provide support.
Details are provided here:
https://user-guide.modernisation-platform.service.justice.gov.uk/user-guide/production-ready-checklist.html

Note that the team have been though this, but we need to validate (and there is an error with the format on the go live date)

## User Type(s)

MP engineers

### Value / Purpose

Ensure code quality and security of the platform

### Useful Contacts

Alistair Curtis or Deepika Patel (DM)

### Definition of Done

- [ ] checklist updated
- [ ] Go live date format corrected in json
- [ ] reviewed by another team member

**Comment by dms1981** [comment]
* Added monitoring configuration
* Configured AWS Shield with a count value of 10000 for initial baselining.
* Confirmed SSM agent installed
* Confirmed runbook populated
* [TODO] Yet to confirm code against MOJ technical / security guidance
* Application tested
* Go-live data populated in MP repository
* [TODO] Yet to check application monitoring / logging
* Support contact details confirmed in application runbook
* No team support required

**Comment by dms1981** [comment]
Completed infrastructure review. Passed findings on to team.
