### ISSUE TITLE
Oasys National Reporting environment in modernisation-platform-environments

### ISSUE THREAD

**Issue by robertsweetman** [ministryofjustice/modernisation-platform#6452]
### Environment details

Test, preproduction and production environments will contain 4-7(?) EC2 instances and associated networking/security groups etc. Consists of (some) Windows 2012 R2, Rhel 6.9 and Tomcat webservers on Rhel 7.4 - age of some of these OS's is due to the current application stack. There are moves being considered by the nart team to upgrade application components (some work began on this in Azure) but work will be ongoing to see whether this can be automated/achieved.

### Application Name

oasys-national-reporting

### Description of application

Similar to nomis-combined-reporting, connects to OASYS and allows users to run reports from their MoJo devices on the data which is available in a separate table for reporting in the oasys db instances. We will need to establish connectivity between instances in this new environment and oasys. The environment won't contain oracle db's itself, just connections to Oasys

### GitHub team slug

studio-webops

### Environments

- [X] Development
- [X] test
- [X] Preproduction
- [X] Production

### Environment access level Development

sandbox

### Environment access level Test

developer

### Environment access level Preproduction

developer

### Environment access level Production

developer

### application

Oasys National Reporting/ONR

### business-unit

HMPPS

### infrastructure-support

digital-studio-operations-team@digital.justice.gov.uk

### owner

Mark Richardson

### Subnet sets

- [X] General
- [ ] Isolated

### How do users connect to the application

With a MoJ Official device

### Additional features

Please check any additional features required
- [ ] Additional VPC Endpoints
- [ ] Extended DNS Zones
- [ ] Other - please specify

### Definition of Done

Definition of Done
- [x] account created
- [x] customer informed

**Comment by robertsweetman** [comment]
Okay, made a mistake, business unit is HMPPS :)

**Comment by ASTRobinson** [comment]
The account was successfully created and Robert was informed.
