### ISSUE TITLE
Re: 'Environments (AWS accounts) architecture'

### ISSUE THREAD

**Issue by mikejwhat** [ministryofjustice/modernisation-platform#6480]
Is this supposed to be public??

Problem with 'Environments (AWS accounts) architecture' (https://user-guide.modernisation-platform.service.justice.gov.uk/concepts/environments/architecture.html)

**Comment by dms1981** [comment]
Hi @mikejwhat - yes it is! It follows our existing guidance on working in the open, and is further described in code in a separate public repository.

* https://technical-guidance.service.justice.gov.uk/documentation/standards/storing-source-code.html
* https://github.com/ministryofjustice/aws-root-account

**Comment by SteveMarshall** [comment]
Another good reference on why this repo (and lots of our others) are in the open is my blog post from 2017: [Why we code in the open](https://mojdigital.blog.gov.uk/2017/02/21/why-we-code-in-the-open/). Thanks for your question, @mikejwhat!
