### ISSUE TITLE
Adding Merge queue functionality to modernisation platform repo 

### ISSUE THREAD

**Issue by markgov** [ministryofjustice/modernisation-platform#6483]
### User Story

As a Modernisation platform engineer
I want to try and implement github merge queue functionality to our repo 
So that we can hopefully stop merge errors from happening

**Limit to modernisation-platform repo and the scheduled baseline workflow**

### Value / Purpose

we are now looking to implement merge queue on the modernisation platform repo so that we can help prevent merge errors but also after this has been setup and implemented we will need to look at the bulk merger tool so that is accounts for merge queues as at present it does not.

### Useful Contacts

Mark Roberts

### Additional Information

https://docs.google.com/presentation/d/16lyNggKjwjlZRb_rcnMdckF-EKjr07JNEzKb6mm8NeQ/edit#slide=id.g13cb8a0db7d_0_0

### Definition of Done

Example 
- [x] Merge queue enabled
- [x] code added to workflows to take advantage of merge queues
- [x] bulk merger tool amended and tested
- [x] Another team member has reviewed
- [x] Tests are green

**Comment by ASTRobinson** [comment]
merge queue was enabled yesterday on the modernisation-platform repo, I did have to raise PR https://github.com/ministryofjustice/modernisation-platform/pull/6727 so that the required `.github/workflows/opa-policies.yml` checks could run on the merge queue branch.

**Comment by ASTRobinson** [comment]
PR https://github.com/ministryofjustice/bulk-merger/pull/3 has now been tested with a combination of repos with merge-queue enabled and not and all PRs were successfully merged/added to the merge-queue.

**Comment by ASTRobinson** [comment]
I am closing this issue as the merge queue has been successfully enabled on the modernisation platform and the bulk-merge tool has been updated to handle repos with the merge-queue enabled.
