### ISSUE TITLE
🧹 Clean up unit tests

### ISSUE THREAD

**Issue by dms1981** [ministryofjustice/modernisation-platform#6492]
### User Story

As a Modernisation Platform Engineer
I want to freshen up our unit tests
So that we have more consistent standards in how we write and use unit tests

### Value / Purpose

As part of a [recent spike](https://github.com/ministryofjustice/modernisation-platform/issues/6334) some inconsistency was noted in our unit tests. This story should achieve the following:
* Use of a common name for unit tests. EG `test/unit_test.go`
* Check that tests cover all important functions in module
* Conduct a hygiene pass on code in `test/unit-test/*.tf`
  * EG, ensure some randomness is used in resource names
  * See [here](https://terratest.gruntwork.io/docs/#testing-best-practices) for other thoughts on best use of Terratest

### Definition of Done

- [x] Cleanup pass completed
- [x] Unit tests pass

**Comment by connormaglynn** [comment]
## Some useful commands to find  

You can use the following command to get all repositories with the string "modernisation-platform-terraform" in them 👇 

```bash
$ gh api -X GET orgs/ministryofjustice/teams/modernisation-platform/repos -f 'per_page=100' | jq -r '.[] | select(.archived == false) | .name' | grep modernisation-platform-terraform
modernisation-platform-terraform-iam-superadmins
modernisation-platform-terraform-environments
...
```

Using the output here we can clone all the repositories locally 👇 

```bash
$ MP_REPOS=$(gh api -X GET orgs/ministryofjustice/teams/modernisation-platform/repos -f 'per_page=100' | jq -r '.[] | select(.archived == false) | .name' | grep modernisation-platform-terraform)
$ while IFS= read -r repo ; do git clone "https://github.com/ministryofjustice/${repo}.git"; done <<< "$MP_REPOS"
```

We can then check which repositories have tests locally with 👇 

```bash
$ MP_REPOS=$(gh api -X GET orgs/ministryofjustice/teams/modernisation-platform/repos -f 'per_page=100' | jq -r '.[] | select(.archived == false) | .name' | grep modernisation-platform-terraform)
$ while IFS= read -r repo ; do cd "${repo}" && printf "- https://github.com/ministryofjustice/${repo} Files: " && find test | xargs echo  && cd ../  ; done <<< "$MP_REPOS"
```

I've separated the output of the last command into repos with tests and repos without them

**Repos with tests**
- https://github.com/ministryofjustice/modernisation-platform-terraform-s3-bucket Files: test test/go.mod test/go.sum test/unit-test test/unit-test/outputs.tf test/unit-test/locals.tf test/unit-test/main.tf test/unit-test/versions.tf test/unit-test/base_variables.tf test/unit-test/secrets.tf test/unit-test/providers.tf test/unit-test/networking.auto.tfvars.json test/s3_bucket_creation_test.go
- https://github.com/ministryofjustice/modernisation-platform-terraform-s3-bucket-replication-role Files: test test/s3_replication_role_test.go test/go.mod test/go.sum test/unit-test test/unit-test/outputs.tf test/unit-test/locals.tf test/unit-test/main.tf test/unit-test/versions.tf test/unit-test/base_variables.tf test/unit-test/secrets.tf test/unit-test/providers.tf test/unit-test/networking.auto.tfvars.json test/README.md
- https://github.com/ministryofjustice/modernisation-platform-terraform-bastion-linux Files: test test/go.mod test/bastion_test.go test/go.sum test/unit-test test/unit-test/outputs.tf test/unit-test/bastion_linux.json test/unit-test/locals.tf test/unit-test/main.tf test/unit-test/versions.tf test/unit-test/base_variables.tf test/unit-test/secrets.tf test/unit-test/providers.tf test/unit-test/networking.auto.tfvars.json test/README.md
- https://github.com/ministryofjustice/modernisation-platform-terraform-aws-vm-import Files: test test/go.mod test/aws_vm_import_test.go test/go.sum test/unit-test test/unit-test/outputs.tf test/unit-test/locals.tf test/unit-test/application_variables.json test/unit-test/main.tf test/unit-test/versions.tf test/unit-test/base_variables.tf test/unit-test/secrets.tf test/unit-test/providers.tf test/unit-test/networking.auto.tfvars.json test/README.md
- https://github.com/ministryofjustice/modernisation-platform-terraform-loadbalancer Files: test test/go.mod test/load_balancer_test.go test/go.sum test/unit-test test/unit-test/outputs.tf test/unit-test/locals.tf test/unit-test/main.tf test/unit-test/versions.tf test/unit-test/base_variables.tf test/unit-test/secrets.tf test/unit-test/providers.tf test/unit-test/networking.auto.tfvars.json
- https://github.com/ministryofjustice/modernisation-platform-terraform-module-template Files: test test/unit-test test/unit-test/outputs.tf test/unit-test/locals.tf test/unit-test/main.tf test/unit-test/versions.tf test/unit-test/base_variables.tf test/unit-test/secrets.tf test/unit-test/providers.tf test/unit-test/networking.auto.tfvars.json test/README.MD test/module_test.go
- https://github.com/ministryofjustice/modernisation-platform-terraform-pagerduty-integration Files: test test/go.mod test/go.sum test/unit-test test/unit-test/outputs.tf test/unit-test/locals.tf test/unit-test/main.tf test/unit-test/versions.tf test/unit-test/providers.tf test/readme.md test/pagerduty_integration_test.go
- https://github.com/ministryofjustice/modernisation-platform-terraform-lambda-function Files: test test/go.mod test/lambda_test.go test/go.sum test/unit-test test/unit-test/outputs.tf test/unit-test/locals.tf test/unit-test/main.tf test/unit-test/versions.tf test/unit-test/base_variables.tf test/unit-test/secrets.tf test/unit-test/providers.tf test/unit-test/networking.auto.tfvars.json test/README.MD
- https://github.com/ministryofjustice/modernisation-platform-terraform-ssm-patching Files: test test/go.mod test/go.sum test/unit-test test/unit-test/outputs.tf test/unit-test/locals.tf test/unit-test/main.tf test/unit-test/versions.tf test/unit-test/base_variables.tf test/unit-test/secrets.tf test/unit-test/providers.tf test/unit-test/networking.auto.tfvars.json test/README.MD test/module_test.go
- https://github.com/ministryofjustice/modernisation-platform-terraform-ec2-autoscaling-group Files: test test/go.mod test/go.sum test/unit-test test/unit-test/data.tf test/unit-test/outputs.tf test/unit-test/locals.tf test/unit-test/main.tf test/unit-test/versions.tf test/unit-test/security-groups.tf test/unit-test/base_variables.tf test/unit-test/secrets.tf test/unit-test/providers.tf test/unit-test/networking.auto.tfvars.json test/README.MD test/module_test.go
- https://github.com/ministryofjustice/modernisation-platform-terraform-ec2-instance Files: test test/go.mod test/go.sum test/unit-test test/unit-test/data.tf test/unit-test/outputs.tf test/unit-test/locals.tf test/unit-test/main.tf test/unit-test/versions.tf test/unit-test/security-groups.tf test/unit-test/base_variables.tf test/unit-test/secrets.tf test/unit-test/providers.tf test/unit-test/networking.auto.tfvars.json test/README.MD test/module_test.go
- https://github.com/ministryofjustice/modernisation-platform-terraform-ecs-cluster Files: test test/go.mod test/go.sum test/unit-test test/unit-test/outputs.tf test/unit-test/locals.tf test/unit-test/main.tf test/unit-test/versions.tf test/unit-test/base_variables.tf test/unit-test/secrets.tf test/unit-test/providers.tf test/unit-test/networking.auto.tfvars.json test/README.MD test/module_test.go
- https://github.com/ministryofjustice/modernisation-platform-terraform-dns-certificates Files: `test test/go.mod test/go.sum test/unit-test test/unit-test/data.tf test/unit-test/outputs.tf test/unit-test/locals.tf test/unit-test/main.tf test/unit-test/versions.tf test/unit-test/base_variables.tf test/unit-test/secrets.tf test/unit-test/providers.tf test/unit-test/networking.auto.tfvars.json test/unit-test/.terraform.lock.hcl test/README.MD test/module_test.go`

**Repos without tests**
- https://github.com/ministryofjustice/modernisation-platform-terraform-iam-superadmins Files: find: test: No such file or directory
- https://github.com/ministryofjustice/modernisation-platform-terraform-environments Files: find: test: No such file or directory
- https://github.com/ministryofjustice/modernisation-platform-terraform-baselines Files: find: test: No such file or directory
- https://github.com/ministryofjustice/modernisation-platform-terraform-cross-account-access Files: find: test: No such file or directory
- https://github.com/ministryofjustice/modernisation-platform-terraform-member-vpc Files: find: test: No such file or directory
