### ISSUE TITLE
New Environment - Analytical Platform Compute

### ISSUE THREAD

**Issue by BrianEllwood** [ministryofjustice/modernisation-platform#6503]
### Environment details

These accounts will contain the compute for the new Analytical Platform 

### Application Name

analytical-platform-compute

### Description of application

Analytical Platform compute, EKS, EFS, QuickSight, SageMaker

### GitHub team slug

analytical-platform

### GitHub code owner team slug

analytical-platform

### GitHub actions reviewer team slug

analytical-platform

### Environments

- [X] Development
- [X] test
- [ ] Preproduction
- [X] Production

### Environment access level Development

sandbox

### Environment access level Test

developer

### Environment access level Production

developer

### application

analytical-platform-compute

### business-unit

Platforms

### infrastructure-support

analytical-platform@digital.justice.gov.uk

### owner

analytical-platform@digital.justice.gov.uk

### Subnet sets

- [ ] General
- [X] Isolated

### How do users connect to the application

Over the public internet

### Additional features

Please check any additional features required
- [X] Additional VPC Endpoints (Bedrock)
- [ ] Extended DNS Zones
- [ ] Other - please specify

### Other information

We are looking for a networking replica of our current `data-platform-apps-and-tools` accounts which these replacing and which we're looking to retire. We know this is a bespoke request so we weren't sure how to request it. 

### Definition of Done

Definition of Done
- [ ] account created
- [ ] customer informed

**Comment by ASTRobinson** [comment]
notes from account setup request:

`Greetings! Apologies for the confusion. I think what we're after is the same setup as ingestion and dpat but not sure how we'd best request it. For data platform apps and tools we requested general + vpc, but for ingestion we requested isolated + inet gateway + nat gateways for outbound internet. I'm really sorry for asking for non-standard offering twice. We'll take a steer from you on how best to request this.`

**Comment by dms1981** [comment]
I think for the purposes of this request we should constrain ourselves to the account setup. When it comes to resource creation - eg. isolated VPC - we can work with engineers from AP to define a CIDR range they can use that's in a routable address range.

**Comment by SteveLinden** [comment]
All accounts created. Did not continue to the networking stage of the account build as it has been set up as isolated.

Brian has confirmed that the accounts exist and are accessible (I did a check before I contacted him).
