### ISSUE TITLE
Scheduled baseline

### ISSUE THREAD

**Issue by markgov** [ministryofjustice/modernisation-platform#6534]
### User Story

As a modernisation platform engineer
I need to try and improve the way the scheduled baseline works
So that we can achieve a performance increase

### Value / Purpose

This is a ticket raised off the back of [Spike] Scheduled baseline duration
[#6316](https://github.com/ministryofjustice/modernisation-platform/issues/6316) where we have discussed possible ways to improve the performance of the workflow.

we have talked about this in a meeting a decided that the probable best approach is to try and limit the work flow to only run based on changes to the terraform.

The plan is to change the way the workflows work and to only apply artifacts based on the terraform plan.

### Useful Contacts

Mark Roberts

### Definition of Done

Example 
- [ ] new code written
- [ ] Another team member has reviewed
- [ ] Tests are green

**Comment by SimonPPledger** [comment]
this will not save any time
