### ISSUE TITLE
Acknowledge receipt of MP Account Request

### ISSUE THREAD

**Issue by richgreen-moj** [ministryofjustice/modernisation-platform#6547]
### User Story

As an MP Engineer
I want to acknowledge a customers request for a new environment
So that they know that it is being looked at and when they might expect to receive it etc.

### Value / Purpose

Recently we added a step to our account creation process where we notify the originator that their account request has been completed and point them to guidance https://github.com/ministryofjustice/modernisation-platform/issues/3451

This issue is to do a similar function but at the start of the process, so once a new account request issue has been submitted perhaps a comment is added to the issue that @'s the originator to acknowledge receipt and perhaps give some more detail on when they might expect to recieve their account.

We'd need to work on what that message says, perhaps it could include:

- that we will review the info provided for suitability and be in touch if there are any issues (review by TA?)
- when the work might be scheduled ("in our next sprint")

This could also email group inbox or alert somewhere so that we are aware when they come in and can review for suitability.

Should we have a flag/label on account creations when they are "ready to do"?  Almost like the way we use the "needs refining" label.

This is all done informally now so perhaps there is no need for this but I feel like we often get prompted in the Ask channel etc after people create the issue - which is fine - but this might make the customer experience more ... polished :)

### Definition of Done

- [ ] Agree on message/mechanism for alerting originator
- [ ] Implement and test solution
- [ ] Another team member has reviewed

**Comment by davidkelliott** [comment]
Do we need to do this or do we just need to update our guidance to say something like "after submitting a new account request we will prioritise it and take it into the next sprint..." or something similar?
