### ISSUE TITLE
AWS Bedrock Access for CICA Data extraction tool

### ISSUE THREAD

**Issue by Adenipex** [ministryofjustice/modernisation-platform#6559]
### Environment details

We require a development environment to get access to AWS Bedrock & Textract for the CICA Data extraction tool. These are the AWS services that would be used.

### Application Name

cica-data-extraction 

### Description of application

The CICA data extraction tool is a solution for caseworkers to search and highlight specific useful data within a case application and supporting case documents. 

This would enable caseworkers filter through necessary information quicker .

The application would be hosted on the Cloud platform but would need access via the API to an LLM in Bedrock .

### GitHub team slug

cica-extract-tool-admins

### Environments

- [X] Development
- [ ] test
- [ ] Preproduction
- [ ] Production

### Environment access level Development

developer

### application

CICA-Data-extraction

### business-unit

CICA

### infrastructure-support

infrastructure@cica.gov.uk

### owner

infrastructure@cica.gov.uk

### Subnet sets

- [X] General
- [ ] Isolated

### How do users connect to the application

Over the public internet

### Additional features

Please check any additional features required
- [ ] Additional VPC Endpoints
- [ ] Extended DNS Zones
- [x] Other - please specify

### Other information

The nearest approved region we can use for Bedrock is Frankfurt (eu-central-1).
We would need temporary permissions to manager Bedrock from AWS console pending when Bedrock is fully supported on terraform. Thank you

### Definition of Done

Definition of Done
- [x] account created
- [x] customer informed

**Comment by dms1981** [comment]
Moved this one to `blocked` pending a discussion with @jennyd .

**Comment by dms1981** [comment]
Discussed with @davidkelliott ; as this application is going to use a combination of textract and bedrock, this one is appropriate for the Modernisation Platform so I'll bring this out of blocked.
