### ISSUE TITLE
Remediate OPA codebase in prep for v1.0

### ISSUE THREAD

**Issue by richgreen-moj** [ministryofjustice/modernisation-platform#6602]
### User Story

As an MP Engineer
I need to remediate the code for our suite of OPA policy tests
So that they conform to the latest versions of the technology

### Value / Purpose

This blog https://blog.openpolicyagent.org/opa-1-0-is-coming-heres-what-you-need-to-know-c8fb0d258368 describes some of the changes that will be required to OPA test policies so that the code will be ready for when version 1.0 is released later in 2024.

The purpose of this story is to update the code so that it future proofed with the imminent update.

### Useful Contacts

@richgreen-moj

### Additional Information

https://blog.openpolicyagent.org/opa-1-0-is-coming-heres-what-you-need-to-know-c8fb0d258368

### Definition of Done

- [ ] Have read the blog and identified changes required
- [ ] Implement changes to the code
- [ ] Test compatibility with v1 using `opa check --rego-v1`
- [ ] Reviewed by another team member
- [ ] OPA tests are passing

**Comment by markgov** [comment]
so i have found that we will need to change 4 files in the modplatform repo and change the import to rego.v1 but after creating a Pr i found that we are locking the version of conftest and regal to lower version than are available so unable to test i have updated the pr to use the latest versions but now coming across parsing issues which i am having to look at now

**Comment by markgov** [comment]
PR complete all rego files are V1 ready and all tests are passing
