### ISSUE TITLE
GitHub Action Status Badges - Dashboard / Status Page

### ISSUE THREAD

**Issue by ASTRobinson** [ministryofjustice/modernisation-platform#6676]
### User Story

As a…user of the modernisation platform
I want to… be able to see the status of GitHub workflow actions 
So that… I can easily identify any issues.

### Value / Purpose

The purpose of this dashboard would be to allow our users and stakeholders an overview of the health of our GitHub workflow actions so any issues are openly visible and could reduce requests in the ask channel. 

### Useful Contacts

Aaron Robinson

### Additional Information

https://user-guide.modernisation-platform.service.justice.gov.uk/user-guide/workflow-status.html
https://shields.io/badges/git-hub-actions-workflow-status

### Proposal / Unknowns

I have created a basic dashboard page [here](https://user-guide.modernisation-platform.service.justice.gov.uk/user-guide/workflow-status.html) showing all the actions from the modernisation-platform repo. This needs to be re-designed to include all repo's in a user-friendly view. 

### Definition of Done

Example - [ ] Documentation has been written / updated
- [ ] Dashboard Overview Status Page Published to GitHub Pages
- [ ] Another team member has reviewed
- [ ] Tests are green

**Comment by mikereiddigital** [comment]
Excludes - modernisation-platform-environments.

Update - have the links working for each image. Also have fixed table column widths using style. Looking next at how to use different font sizes.

**Comment by mikereiddigital** [comment]
Links that work in the markdown preview extension in VSCode are failing in the browser. Will investigate.

**Comment by mikereiddigital** [comment]
So Github pages strips out any custom links. This is done as a security measure. The solution is to add adjacent text with the link to the workflow.
