### ISSUE TITLE
🧪 Improve Quality and Coverage of Unit Tests in `modernisation-platform-instance-scheduler`

### ISSUE THREAD

**Issue by connormaglynn** [ministryofjustice/modernisation-platform#6687]
### User Story

As a Modernisation Platform Engineer
I expect to have a high confidence that unit tests will capture any errors in my code
So that I can be confident my changes do not contain bugs or unintended breaking changes

### Value / Purpose

The value of increasing the unit test coverage in the instance scheduler is to ensure engineers can be aware sooner if their changes break anything since unit tests are quick and easy to run locally.

This also has the benefit of being less dependent on our current integration testing process to capture bugs, meaning we can start to move away from this implementation of quality assurance.

Ideally, as well, properly unit testing the code will help highlight areas of the code that can/should be refactored to be more modular, less coupled and ultimately easier to test, read and understand.

### Additional Information

- Relates to https://github.com/ministryofjustice/modernisation-platform-instance-scheduler/issues/138
- Discussion about the integration testing strategy currently implemented can be found in this [thread](https://mojdt.slack.com/archives/C013RM6MFFW/p1712051311040569)
- You can create a coverage web page of the code by running the following command (although I had to delete the integration test file first) 
```bash
go test -coverprofile=coverage.out && go tool cover -html="coverage.out"
```

### Definition of Done

- [ ] Unit test coverage is ~95% (ideally as close to 100% as possible!)
- [ ] Appropriate assertions are in the tests to verify the logic is working as expected (getting the coverage is easy, ensuring the right assertions to correctly test the logic is the hard part!)
- [ ] Where appropriate, code has been refactored to be more modular, readable and testable (ideally, do this after writing the tests for that functionality to ensure no breaking changes)
- [ ] All code branches of functional code execution have coverage and assertions to ensure functional changes will trigger a failing test
- [ ] Another team member has reviewed
- [ ] Tests are green

**Comment by ewastempel** [comment]
@connormaglynn and I have caught up and agreed to close this ticket and make further improvements to the code quality by using our 10% time dedicated to L&D.

Closing this issue.
