### ISSUE TITLE
BUG: Redeploy After Nuke Job fails in MP Env repo

### ISSUE THREAD

**Issue by richgreen-moj** [ministryofjustice/modernisation-platform#6702]
### Expected Behavior

This workflow has been failing for the last few months https://github.com/ministryofjustice/modernisation-platform-environments/actions/workflows/nuke-redeploy.yml

### Actual Behavior

https://github.com/ministryofjustice/modernisation-platform-environments/actions/runs/8497997331 shows an unsuccessful run. 

It fails on acquiring the state lock for:

- sprinkler-development
- cooker-development
- tipstaff-development

**Comment by ASTRobinson** [comment]
draft PR created: https://github.com/ministryofjustice/modernisation-platform/pull/6789

**Comment by ASTRobinson** [comment]
PR is now merged in, I will check the outcome of the nuke redeploy scheduled job on Monday.
