### ISSUE TITLE
[SPIKE] NCSC - backup and recovery recommendations

### ISSUE THREAD

**Issue by SimonPPledger** [ministryofjustice/modernisation-platform#6734]
### User Story

Following review with NCSC they have made the following recommendations

**Backup and Recovery**
The platform will leverage AWS Backup for backup and recovery services. The detail of this is to be confirmed, but our understanding is this provides “Backup as a Service” for key AWS services. Using AWS Backup as the only backup solution could leave the Modernisation Platform unprotected against some failure scenarios, e.g. a malicious insider deleting all resources within an account. 

**NCSC's Recommendation:** Consider the following NCSC guidance. https://www.ncsc.gov.uk/guidance/principles-for-ransomware-resistant-cloud-backups 
**MoJ Response:** We will review this document as a separate ticket. Action: Raise ticket

This should look at both EC2 and RDS and any other resources that can be backed up.

### Value / Purpose
Improve the security of the platform

### Definition of Done

- [ ] Document reviewed and recommendations made
- [ ] Agreement on which recommendations to implement and which to ignore
- [ ] If required, raise tickets to implement any new changes

**Comment by ep-93** [comment]
https://docs.google.com/document/d/1b-YnoUE7ecC0qFd2bFpe86KO_VVJT0VVVX2RzbX_LpQ/edit?usp=sharing
