### ISSUE TITLE
📝 Create runbook for `core-logging-production` account

### ISSUE THREAD

**Issue by dms1981** [ministryofjustice/modernisation-platform#6763]
### User Story

As a Modernisation Platform Engineer
I want to write a runbook
So that I can recreate resources for the `core-logging-production` account if the need arises

### Value / Purpose

[This backlog issue](https://github.com/ministryofjustice/modernisation-platform/issues/1908) identifies key platform components that may need to be recreated.

For the `core-logging-production` account we may need to recreate any or all of the following:

* The AWS account
* Resources inside the account
  * AWS S3 bucket for logs
  * AWS KMS key used to encrypt bucket contents
  * AWS resources used by PagerDuty

### Definition of Done

- [x] Runbook written
- [ ] Another team member has reviewed

**Comment by Khatraf** [comment]
I reviewed the runbook, and it looks good to me. It can be found here in our user guide:https://user-guide.modernisation-platform.service.justice.gov.uk/runbooks/recreate-core-logging-production-account.html#core-logging-production-account-setup
