### ISSUE TITLE
📝 Create runbook for `core-network-services` account

### ISSUE THREAD

**Issue by dms1981** [ministryofjustice/modernisation-platform#6765]
### User Story

As a Modernisation Platform Engineer
I want to write a runbook
So that I can recreate resources for the `core-network-services` account if the need arises

### Value / Purpose

[This backlog issue](https://github.com/ministryofjustice/modernisation-platform/issues/1908) identifies key platform components that may need to be recreated.

For the `core-network-services` account we may need to recreate any or all of the following:

* The AWS account
* Resources inside the account used by customers
  * Egress VPCs (with Network Firewalls & NAT gateways)
  * Inspection VPC (with Network Firewall)
  * Transit Gateway (RAM shares, peering to MOJ TGW)
  * Route53 zones and delegations

### Useful Contacts

@dms1981 

### Additional Information

This could be particularly challenging if we try and tackle the creation of and configuration of RAM shares into core-vpc-* accounts. There are TGW attachments that would be created as well as RAM shares and potentially retagging. For the sake of this runbook, a best effort on how to tackle these unknowns is sufficient.

This is also probably a really good one to pair with someone on if you're not confident about the moving parts involved.

### Definition of Done

- [x] Runbook written
- [x] Another team member has reviewed

**Comment by mikereiddigital** [comment]
Have reviewed & so moving to done.
