### ISSUE TITLE
📝 Create runbook for `core-shared-services-production` account

### ISSUE THREAD

**Issue by dms1981** [ministryofjustice/modernisation-platform#6766]
### User Story

As a Modernisation Platform Engineer
I want to write a runbook
So that I can recreate resources for the Modernisation Platform account if the need arises

### Value / Purpose

[This backlog issue](https://github.com/ministryofjustice/modernisation-platform/issues/1908) identifies key platform components that may need to be recreated.

For the `core-shared-services-production` account we may need to recreate any or all of the following:

* The AWS account
* Resources inside the account used by customers
  * VPCs for shared infrastructure
  * AMI builder & resources (eg, S3 bucket)
  * Instance Scheduler
  * Shared KMS keys

### Definition of Done

- [ ] Runbook written
- [ ] Another team member has reviewed

**Comment by Kudzai-moj** [comment]
Reviewed the steps and they clearly show how to recreate the account in the event of deletion/corruption
