### ISSUE TITLE
📝 Create runbook for `core-vpc-$environment` accounts

### ISSUE THREAD

**Issue by dms1981** [ministryofjustice/modernisation-platform#6767]
### User Story

As a Modernisation Platform Engineer
I want to write a runbook
So that I can recreate resources for the Modernisation Platform account if the need arises

### Value / Purpose

[This backlog issue](https://github.com/ministryofjustice/modernisation-platform/issues/1908) identifies key platform components that may need to be recreated.

For the `core-vpc-$environment` accounts we may need to recreate any or all of the following:

* The AWS accounts
* Resources inside the account used by customers
  * VPCs
  * RAM shares, VPC endpoints
  * Transit Gateway connectivity

### Definition of Done

- [x] Runbook written
- [ ] Another team member has reviewed

**Comment by Kudzai-moj** [comment]
Runbooking has been written and PR was merged successfully. Awaiting closure

**Comment by Khatraf** [comment]
I've reviewed the runbook and it looks good to me. Runbook can be found in our user guide here: https://user-guide.modernisation-platform.service.justice.gov.uk/runbooks/recreate-core-vpc-$environment-accounts.html
