### ISSUE TITLE
New EDW MP Accounts

### ISSUE THREAD

**Issue by ffteva-moj** [ministryofjustice/modernisation-platform#6790]
### Environment details

The migration of the EDW application will soon start from the Landing Zone to MP. Therefore new accounts are required.

### Application Name

edw

### Description of application

EDW is running on oracle database 10.2.0.4. There are cdc streams from CWA into EDW and EDW links into other databases via dblinks. It is built via an app and cloudwatch templates/stack, running on an m4.xlarge EC2, alongside route53, volumes, S3, AMI and Key management service.

### GitHub team slug

laa-aws-infrastructure

### Environments

- [X] Development
- [X] test
- [X] Preproduction
- [X] Production

### Environment access level Development

developer

### Environment access level Test

developer

### Environment access level Preproduction

developer

### Environment access level Production

developer

### application

edw

### business-unit

LAA

### infrastructure-support

aws-webops-laa@digital.justice.gov.uk

### owner

aws-webops-laa@digital.justice.gov.uk

### Subnet sets

- [ ] General
- [ ] Isolated

### How do users connect to the application

With a MoJ Official device

### Additional features

Please check any additional features required
- [ ] Additional VPC Endpoints
- [ ] Extended DNS Zones
- [ ] Other - please specify

### Definition of Done

Definition of Done:
- [ ] account created
- [ ] customer informed

**Comment by SteveLinden** [comment]
Passed to Sukesh as it will enable some testing he is undertaking.
