### ISSUE TITLE
Archiving github issues within the Modernisation Platform project

### ISSUE THREAD

**Issue by SimonPPledger** [ministryofjustice/modernisation-platform#6807]
### User Story

There is a limit in the number of tickets we can have within a github project - which is 1200. We are around this number now. When we hit the limit we are no longer able to raise tickets.

Tickets can be archived within the project. There is currently a beta version that might solve the problem, but there are limitations to the beta version - meaning it doesn't appear to be suitable.

This ticket is to look at how we can address this in the short term - while we are waiting for the beta version to be fully implemented.

This ticket is to identify and implement an archiving process.
We will still need to be able to view these tickets at a later date.

### Value / Purpose

If we don't do this people will be unable to raise new tickets

### Definition of Done

- [ ] Archiving option developed and tested
- [ ] Process implemented
- [ ] Documentation created

**Comment by ewastempel** [comment]
This is resolved now (archived 10 sprints worth of issues manually)
