### ISSUE TITLE
Add PreProd + Prod for `delius-core`

### ISSUE THREAD

**Issue by georgepstaylor** [ministryofjustice/modernisation-platform#6815]
### Environment details

delius-core already in place, request to add PreProd + Prod 

### Application Name

delius-core

### Description of application

Access block for each env should look like this:
```
      "access": [
        {
          "github_slug": "hmpps-migration",
          "level": "developer"
        },
        {
          "github_slug": "hmpps-dba",
          "level": "developer"
        },
        {
          "github_slug": "unilink",
          "level": "developer"
        }
      ]
```

### GitHub team slug

hmpps-migration

### GitHub code owner team slug

hmpps-migration

### GitHub actions reviewer team slug

hmpps-migration

### Environments

- [ ] Development
- [ ] test
- [X] Preproduction
- [X] Production

### Environment access level Preproduction

developer

### Environment access level Production

developer

### application

delius

### business-unit

HMPPS

### infrastructure-support

probation-webops@digital.justice.gov.uk

### owner

probation-webops@digital.justice.gov.uk

### Subnet sets

- [X] General
- [ ] Isolated

### How do users connect to the application

With a MoJ Official device

### Additional features

Please check any additional features required
- [ ] Additional VPC Endpoints
- [ ] Extended DNS Zones
- [ ] Other - please specify

### Definition of Done

Definition of Done
- [ ] account created
- [ ] customer informed

**Comment by Kudzai-moj** [comment]
Waiting on Sukesh to finish task on removal of default VPC. Once i have green light, this will come out of blocked
