### ISSUE TITLE
Evaluate Security Risks and Implement Controls for `kms:CreateGrant` Permission in `Github OIDC` role

### ISSUE THREAD

**Issue by sukeshreddyg** [ministryofjustice/modernisation-platform#6845]
### User Story

As a Modernisation Platform engineer
I want to investigate potential security risks associated with granting the kms:CreateGrant permission to the GitHub OIDC role. Additionally, I aim to explore the feasibility of adding conditions to restrict the usage of this permission to prevent unauthorized granting of keys to users and roles.

### Value / Purpose

The purpose of this issue is to ensure security of our key management system by thoroughly assessing the risks introduced by granting the `kms:CreateGrant` permission. By implementing appropriate safeguards, we aim to mitigate the risk of unauthorized access to keys.

### Additional Information

This permission, `kms:CreateGrant`, is required for the purpose of copying snapshots

### Definition of Done

- [x] Identify security risks associated with the newly added permission.
- [x] Document findings and recommendations in a comprehensive report.
- [x] Ensure that the implementation aligns with best practices and complies with security standards.
- [x] Another team member has reviewed
- [x] Tests are green

**Comment by Khatraf** [comment]
https://docs.google.com/document/d/16ZOZ0B29oo2hJ5yPZcxa2On4WDX23OHIjKuHQo1fAgY/edit

**Comment by richgreen-moj** [comment]
Ticket reviewed. The DoD is complete. Looks good to me - we now have stricter permissions on the use of `kms:CreateGrant`. 
Nice work @Khatraf 👍
