### ISSUE TITLE
SPIKE - Investigate mechanism to avoid concurrent instances of scheduled baseline running.

### ISSUE THREAD

**Issue by mikereiddigital** [ministryofjustice/modernisation-platform#6857]
### User Story

As an Modernisation Platform Engineer I want to ensure that instances of the scheduled baseline job are allowed to complete before any new instances of that job are kicked off and so help avoid situations where jobs fail due to multiple concurrent instances of that job running.

Is this still an issue?

### Value / Purpose

A more reliable schedule baseline job will require less time & effort of the team in monitoring & restarting failed jobs.

### Definition of Done

- [x] Confirm this is still an issue
- [x] Options assed and a proposal written up & shared with the team.
- [x] Further tickets raised if required.

**Comment by richgreen-moj** [comment]
This thread might be useful for some options we have previously considered... https://mojdt.slack.com/archives/C013RM6MFFW/p1713864650598349

**Comment by mikereiddigital** [comment]
A simple workflow in one of my personal repos shows how this could work - https://github.com/mikereiddigital/test2/blob/main/.github/workflows/concurrency-test.yml

This is the behaviour:

1. The first action is started.
2. The second action is started and waits for the first to complete.
3. If a third action is started before the 1st one completes, then this action runs after the first and the second one is cancelled as the latter is considered a higher priority.

The key take away from this test is:
- "concurrency" provides the means to prevent multiple instances of the workflow running at once.
- The "cancel-in-progress: false" prevents the first action from being stopped and so allows it to run to completion.
- If multiple actions are queued, only the latest one will be allowed to run, thus reducing the time by which the latest version will be completed.

I will investigate how we can ensure that all instances of workflow are run in order, regardless of how many are queuing.

**Comment by richgreen-moj** [comment]
Hi @mikereiddigital - there's a lot of talk in [this thread](https://github.com/orgs/community/discussions/12835) about the `cancel-in-progress: false` not behaving as we'd expect. I've not tested it though.

**Comment by mikereiddigital** [comment]
Thanks @richgreen-moj the last line of my above comment looks to see if there is a fix for that. I'm also looking today at how concurrency behaves when the workflow is a composite of multiple actions - which is what baselines is.

**Comment by mikereiddigital** [comment]
As an update, setting concurrency & cancel-in-progress=false at the workflow level (not at the job level) means that for multi-job workflows, the first action will complete before the 2nd runs. However, as with above, running a 3rd action cancels the 2nd.

**Comment by mikereiddigital** [comment]
Investigating how the concurrency option could be used alongside a bespoke locking mechanic to prevent the 3rd action from running before the paused 2nd workflow, such as a dynamo DB or other stateful record that is created when the 1st workflow commences. Any subsequent actions starting will check for the existence of this lock & if it exists, the action is cancelled. The lock would be cleared when the first workflow completes.

However, this solution is not feasible as the 2nd action is paused as soon as it runs and then cancelled if the the 3rd action is triggered. As such the lock would never be encountered.


Looking at alternatives to the use of concurrency to solve this issue, the following options may be considered.

1. By testing whether any of the existing baselines workflows are in progress, we can at the start of the workflow either:
 
- Automatically cancel the start of the new action with a message that an existing baselines action is already running. This test can use the the github api and the curl command to list any running actions of a given name & then on the basis of the output either stop the workflow or allow it to continue.

-  The same test but run as a workflow in its own right & as a test for any PR that would trigger the baselines workflow. Any existing action would fail the test and so prevent the merge from progressing.

2. A trigger of an approval stage if the workflow is triggered either manually or via a PR. The examples I have looked at do not use environments but instead use the chrnorm/deployment-approval-action 3rd party workflow when the test "github.event_name != 'schedule'" is true. This is a simple addition but it needs the engineer triggering the workflow to be aware. Perhaps this in conjunction with the test above would help provide evidence to the engineer to make a decision as whether to run the workflow or not.

**Comment by mikereiddigital** [comment]
The team discussed the above findings and agreed that:

1. The issue is not currently having a impact on the running of the workflow.
2. Concurrency and it's existing implementation is accepted and the behaviour with 3+ queued workflows noted.
3. Tickets raised to add concurrency & the fix for running actions in strict sequence to be applied when available.

These tickets are https://github.com/ministryofjustice/modernisation-platform/issues/8212 and https://github.com/ministryofjustice/modernisation-platform/issues/8215

**Comment by SimonPPledger** [comment]
definition of done complete and tickets raised
