### ISSUE TITLE
Review migration roles assigned to teams

### ISSUE THREAD

**Issue by davidkelliott** [ministryofjustice/modernisation-platform#6921]
### User Story

As a mp engineer
I want users to be using the correct roles
So that the principal of least privilege is upheld

### Value / Purpose

Make sure teams are not using roles they no longer need.

### Proposal / Unknowns

The migration role should only be used whilst migrating the application, after cutover it should be reverted back to developer or whichever role is appropriate.

### Definition of Done

- [ ] Roles reviewed
- [ ] Teams who have migrated with these roles contacted
- [ ] Migration access revoked
- [ ] Baselines run successfully with new access levels

**Comment by dms1981** [comment]
In short, if an application has gone live, there should be no use of the `migration` role.
