### ISSUE TITLE
Add alerting for MP Environments PRs that need approval

### ISSUE THREAD

**Issue by richgreen-moj** [ministryofjustice/modernisation-platform#6941]
### User Story

As a MP engineer
I want to be alerted when members raise PRs which contan certain resources that need a review
So that I am made aware of the PR before the member even contacts the ask channel

### Value / Purpose

As a follow on from https://github.com/ministryofjustice/modernisation-platform/issues/6889
This story is to implement some alerting or posting to slack when a member raises a PR that has been marked as needing MP approval e.g. adding eks clusters etc.

### Useful Contacts

@richgreen-moj @sukeshreddyg

### Additional Information

Perhaps this could also be in place for any change requiring the MP approval e.g. changes to the `platform_*.tf` resources 

### Definition of Done

- [ ] Alerting mechanism agreed (slack etc.)
- [ ] Update workflow to send alerts where the relevant conditions are met
- [ ] Tested workflow successfully
- [ ] User docs have been updated
- [ ] Another team member has reviewed

**Comment by SteveLinden** [comment]
Going to look at this and base it on the details in  reusable_terraform_plan_apply.yml assuming the notification can the added to this.

**Comment by dms1981** [comment]
Some discussion to be had in the team as to the utility of this - are we adding extra noise that won't be acted upon?

**Comment by SimonPPledger** [comment]
After discussion we do not want to continue with this feature
