### ISSUE TITLE
Create genesys-call-centre-data environment

### ISSUE THREAD

**Issue by gwionap** [ministryofjustice/modernisation-platform#6980]
### Environment details

The environment will contain an S3 bucket and associated IAM role for an external supplier ([Genesys](https://www.genesys.com/)) to export data to us. This data will then be stored in additional, non-external facing buckets for data retention.

### Application Name

genesys-call-centre-data

### Description of application

This project will be used as a landing zone and data store for call centre data for MoJ operating units sent to us by Genesys. They will be using AWS IAM roles to send this data to us and put it in an S3 bucket of our choosing. From discussions with Analytical Platform team, we think it would be best for this to be done in it's own dedicated AWS account with isolated networking.

### GitHub team slug

genesys-call-centre-data

### GitHub code owner team slug

genesys-call-centre-data

### GitHub actions reviewer team slug

genesys-call-centre-data

### Environments

- [X] Development
- [ ] test
- [ ] Preproduction
- [X] Production

### Environment access level Development

sandbox

### Environment access level Production

view-only

### application

genesys-call-centre-data

### business-unit

Platforms

### infrastructure-support

Data engineering: dataengineering@digital.justice.gov.uk

### owner

Data engineering: dataengineering@digital.justice.gov.uk

### Subnet sets

- [ ] General
- [X] Isolated

### How do users connect to the application

Over the public internet

### Additional features

Please check any additional features required
- [ ] Additional VPC Endpoints
- [ ] Extended DNS Zones
- [ ] Other - please specify

### Other information

Happy to discuss and / or provide an architecture diagram via Slack if useful.

### Definition of Done

Definition of Done
- [x] account created
- [x] customer informed

**Comment by dms1981** [comment]
Closed as per [this discussion](https://mojdt.slack.com/archives/C01A7QK5VM1/p1715600958674109). The data that this account was to hold can be ingested through `analytical-platform-ingestion`.

**Comment by davidkelliott** [comment]
Now proceeding to use this as part of a pilot - https://mojdt.slack.com/archives/C01A7QK5VM1/p1716821903748909?thread_ts=1715600958.674109&cid=C01A7QK5VM1
