### ISSUE TITLE
CloudFormation Stack deployment using Terraform

### ISSUE THREAD

**Issue by vc13837** [ministryofjustice/modernisation-platform#6991]
### User Story

As an Ops Engineer migrating the application CWA
I need to deploy the WAFv2 Web ACL using CloudFormation
So that the migration of CWA can continue without changes to existing security rules

### Value / Purpose

I would like to deploy WAFv2 Web ACL in Modernisation Platform. However with Terraform there is an issue where the rules cannot go more than 3 levels deeps - https://github.com/hashicorp/terraform-provider-aws/issues/15580, thus current work around is to deploy using CloudFormation.

The only resource being deployed via CloudFormation is `AWS::WAFv2::WebACL`, thus other resource creation can be blocked policy-wise to stop other users using CloudFormation as a workaround to deploy any resources they like.

### Useful Contacts

Vincent Cheung (via Slack please)

### Proposal / Unknowns

Assumption:
- Changes to the security rules of the Web ACL is not acceptable by the application team

### Definition of Done

- [ ] laa-aws-infrastructure GitHub team (i.e. LAA Ops) can use Terraform via the infra pipeline to deploy CloudFormation Stack to create WAF v2 Web ACL

**Comment by davidkelliott** [comment]
Proposed solution:

Add permissions for cloudformation to the memberinfrastructureaccess role
Add [aws_cloudformation_stack](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudformation_stack) to the plan evaluator
User to store cloudformation template in environments repo and deploy with the tf resource above

**Comment by mikereiddigital** [comment]
Have reviewed the list of policy actions for cloudformation in https://docs.aws.amazon.com/service-authorization/latest/reference/list_awscloudformation.html. I have excluded those permissions that pertain to operations on stack resources (e.g. CreateChangeSet) and stack-set operations and instead included only those permissions that deal with the stack itself.

**Comment by mikereiddigital** [comment]
Issues with the `cloudformation:ResouceTypes` variable is resulting in the condition not allowing AWS::WAFv2::WebACL types to be created. Have spent time with AWS reviewing the policy. Will be talking to them again today.

**Comment by mikereiddigital** [comment]
This is a summary of the issue. The current proposed change is to add the following:
`
    statement {
      effect = "Allow"
      actions = [
          "cloudformation:ListStacks",
          "cloudformation:DescribeStacks",
          "cloudformation:DeleteStack",
          "cloudformation:GetTemplate"
      ]
      resources = ["*"] #tfsec:ignore:AWS099 tfsec:ignore:AWS097
  }

  statement {
      effect = "Allow"
      actions = [
          "cloudformation:CreateStack",
          "cloudformation:UpdateStack"
      ]
      resources = ["*"] #tfsec:ignore:AWS099 tfsec:ignore:AWS097
      condition {
        test     = "StringEquals"
        variable = "cloudformation:ResourceTypes"
        values   = ["AWS::WAFv2::WebACL"]
      }
  }
`
However the condition of the 2nd statement is preventing Create & Update stack operations even through the resource being create / added is an AWS::WAFv2::WebACL. e.g.

`
resource "aws_cloudformation_stack" "teststack" {
  name = "newteststack"
  template_body = <<EOF
{
  "AWSTemplateFormatVersion": "2010-09-09",
  "Resources": {
    "WAFWebACL": {
      "Type": "AWS::WAFv2::WebACL",
      "Properties": {
        "Name": "testscljson",
        "Scope": "REGIONAL",
        "DefaultAction": {
          "Allow": {}
        },
        "VisibilityConfig": {
          "SampledRequestsEnabled": true,
          "CloudWatchMetricsEnabled": true,
          "MetricName": "testacljsonmetric"
        }
      }
    },
    "WAFWebACLTwo": {
      "Type": "AWS::WAFv2::WebACL",
      "Properties": {
        "Name": "testscljsontwo",
        "Scope": "REGIONAL",
        "DefaultAction": {
          "Allow": {}
        },
        "VisibilityConfig": {
          "SampledRequestsEnabled": true,
          "CloudWatchMetricsEnabled": true,
          "MetricName": "testacljsonmetrictwo"
        }
      }
    }
  }
}
EOF
`
WIll be talking to AWS again later today at 4pm.

**Comment by mikereiddigital** [comment]
On hold as this and the work Mark is undertaking both need sprinkler IAM and will conflict with the other.

**Comment by mikereiddigital** [comment]
Given the issues using the documented statements, we are putting in place a short-term workaround whereby cloudformation permissions will be added but these will be trapped by the plan evaluator script and the PR will require MP approval.

**Comment by mikereiddigital** [comment]
Also PR - https://github.com/ministryofjustice/modernisation-platform/pull/7215

**Comment by mikereiddigital** [comment]
Once both PRs are applied I'll contact LAA Ops to confirm they can now create cf stacks. I will also create a new ticket for when we have a solution from AWS.

**Comment by mikereiddigital** [comment]
New ticket added for the follow-up work - https://github.com/ministryofjustice/modernisation-platform/issues/7220

**Comment by mikereiddigital** [comment]
Shceduled baseline run and the change has been applied. Have contacted VIncent with the update.
