### ISSUE TITLE
Move AWS Shield Advanced protection to Terraform

### ISSUE THREAD

**Issue by davidkelliott** [ministryofjustice/modernisation-platform#7032]
### User Story

As a MP user
I want to enable AWS Shield Advanced protection via code
So that I can reliably reproduce my environment

### Value / Purpose

Reduce clickops and improve consistency of the platform

### Additional Information

When we originally started using Shield Advanced there weren't any Terraform resources, so we manually enabled it using the instructions here:

https://user-guide.modernisation-platform.service.justice.gov.uk/runbooks/enabling-shield-advanced.html#enabling-aws-shield-advanced-for-production-applications

Now Terraform resources exist - https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/shield_protection we should start using them and import existing objects into Terraform

### Proposal / Unknowns

Update guidance and example code to use Terraform where possible.
Update existing user code and import existing objects to Terraform.

### Definition of Done

- [ ] Write module to transpose manual steps
- [ ] Implement module in `example`
- [ ] User docs have been updated
- [ ] Another team member has reviewed
- [ ] Tests are green

**Comment by dms1981** [comment]
https://github.com/ministryofjustice/modernisation-platform/issues/2112 << some of the research here might have useful insights

**Comment by dms1981** [comment]
Originally this issue was to include the migration of customer clickops into infrastructure-as-code, but given the number of customers we'd need to move and the amount of coordination with them that will require I think we should move that to a separate ticket
