### ISSUE TITLE
Regularly check application details

### ISSUE THREAD

**Issue by davidkelliott** [ministryofjustice/modernisation-platform#7047]
### User Story

As an MP engineer
I expect to have up-to-date contact details for application support
So that I can contact them if I need to

### Value / Purpose

Ensure the MP user contact details are up to date and valid, ensure that we don't keep accounts which are no longer needed

### Proposal

Create a process (ideally automated) to contact users and get them to confirm their application details, or make changes as needed on a regular basis.

Also Required:

- A new userguide that explains how to request or make an amendment to an owner entry in an env file.
- A new runbook that covers the use of Gov Notify, what secrets and how to access them.

Could also include checking run books as part of this

### Definition of Done

- [x] Process / automation created
- [x] User docs & runbook have been updated
- [x] Another team member has reviewed
- [x] Tests are green

**Comment by ewastempel** [comment]
The check of the runbooks stems from this [thread](https://mojdt.slack.com/archives/C013RM6MFFW/p1716215800888919) where it would be useful to know the supporting team's slack channel details.

**Comment by dms1981** [comment]
We looked at this in refinement but we would like a bit more guidance on what validation looks like.
For example, if use a tool (potentially a GitHub action) to check that a slack channel exists, is that sufficient? Alternatively, do we need some kind of positive response from the channel to consider the check successful?

**Comment by dms1981** [comment]
Having discussed this further in refinement, an ideal solution would involve positive feedback - eg, send a message with a link, customer clicks link, we assume it's all good.

However, for a minimum we just need to send the message. What we could also do is look is how collaborators are aged out with a GitHub issue - could we do something like "raise issue, alert customer  `github_team` somehow (via Github or Slack?), let them close if it's fine". This might lead to some junk issues, and we probably don't want to do this regularly.

Even then at a bare minimum a regular issue to do this manually may also be enough.

How about how we keep our documents up to date? Can we use that to do something similar to how the Manual Spaniel works from a review date in the environments json? (We'd need to add that review date key.)

**Comment by dms1981** [comment]
Proposed solution:

1. Add `review-date` to environments/*.json files.
2. Use GitHub action to create an issue at review date.
3. Tag the relevant GitHub team in the issue (or maybe use Notify to send an email too?).
4. Customer closes issue or updates as appropriate.

**Comment by mikereiddigital** [comment]
Suggestion that instead of a review-date we undertake these checks on a fixed schedule. Otherwise we will be updating the .json files with new review dates.

**Comment by mikereiddigital** [comment]
Have a working draft of a script that pulls the value of "owner" from each of the environments/.json files but noticed that the value for opg-lpa-data-store.json has an additional value "OPG MLPA: opgteam+modernising-lpa@digital.justice.gov.uk". Will ask them if the prefix could be removed.

**Comment by mikereiddigital** [comment]
Spent a lot of time dealing with the behaviour of the command "gh issue create". With the -p flag set (to Modernisation Platform) the issue is not created and instead throws a GraphQL error stating that the "Classic" project cannot be accessed. This appears to be caused by the project "Modernisation Platform" no longer being a Classic project but one of the new type of issue-based ones. As such the -p / --project field is not required.

**Comment by mikereiddigital** [comment]
Looking at the gov notify service, I need to create a new email template and reference that.

**Comment by mikereiddigital** [comment]
In addition to the above scope, we will also require:
- A new userguide that explains how to request or make an amendment to an owner entry in an env file.
- A new runbook that covers the use of Gov Notify, what secrets and how to access them.

**Comment by mikereiddigital** [comment]
Latest version of the job & scripts - https://github.com/ministryofjustice/modernisation-platform/tree/issue/7407-rebased

**Comment by mikereiddigital** [comment]
Discussed and agreed the following:
- Job will be run monthly.
- Issue created and notification sent at 6 monthly intervals after the creation of the environment.

We can obtain the first commit date of the env file as that reference.

**Comment by mikereiddigital** [comment]
The above branch now includes email notification via Gov Notify. Add a new template earlier (ID 93afef96-ea0b-470f-bd20-edf44e0acdb9) which includes fields for the required values. 

Have tested this with sprinkler - the current version of the code limits the notifications to just that environment. Once I have confirmed a team to test this with I will amend that restriction. The final version will see these environment-specific restrictions removed.

**Comment by mikereiddigital** [comment]
Latest run & tested with @connormaglynn - https://github.com/ministryofjustice/modernisation-platform/actions/runs/11520129547

**Comment by mikereiddigital** [comment]
Link to PR - https://github.com/ministryofjustice/modernisation-platform/pull/8351

**Comment by mikereiddigital** [comment]
Amended PR - https://github.com/ministryofjustice/modernisation-platform/pull/8351

**Comment by mikereiddigital** [comment]
PR covering the final part of the ticket - https://github.com/ministryofjustice/modernisation-platform/pull/8361
