### ISSUE TITLE
Decommissioning hmpps-intelligence-management-development and hmpps-intelligence-management-production accounts

### ISSUE THREAD

**Issue by ewastempel** [ministryofjustice/modernisation-platform#7052]
### User Story

The following accounts are not used anymore and can now be decommissioned:
- hmpps-intelligence-management-development
- hmpps-intelligence-management-production accounts

Therefore this ticket is to make sure the deletion of the above accounts takes place.

### Value / Purpose

Cost savings.
Addressing security risks.
Reducing technical debt.

### Useful Contacts

TA: gareth.davies@digital.justice.gov.uk, Dev: brian.carr@digital.justice.gov.uk

### Additional Information

In case of issues with the remaining resources in these accounts, Dev: brian.carr@digital.justice.gov.uk can be contacted (available on slack).

### Definition of Done

- [x] hmpps-intelligence-management-development is deleted
- [x] hmpps-intelligence-management-production is deleted

**Comment by dms1981** [comment]
https://user-guide.modernisation-platform.service.justice.gov.uk/runbooks/deleting-an-environment.html

**Comment by SteveLinden** [comment]
Awaiting another change to be completed before this can be undertaken.

**Comment by SteveLinden** [comment]
Other work has been completed (and code amended as required) so this has now started

**Comment by SteveLinden** [comment]
The process has been completed. The accounts still show up in the list but they are inaccessible.

**Comment by SteveLinden** [comment]
All completed now
