### ISSUE TITLE
📖 Ability to run static code analysis locally

### ISSUE THREAD

**Issue by jacobwoffenden** [ministryofjustice/modernisation-platform#7062]
### User Story

As a customer of the Modernisation Platform
I want to be able to run static code analysis the same as it is in GitHub Actions
So that I can shorten the feedback loop of failing static code analysis warnings

### Value / Purpose

Having the ability to run Checkov and Trivy locally with all the same parameters/flags that the GitHub Actions workflow uses would allow me as an engineer to remediate issues **before** having to wait for GitHub Actions to fail.

### Useful Contacts

@jacobwoffenden

### Additional Information

I've started this already (https://github.com/ministryofjustice/modernisation-platform-environments/blob/main/scripts/member-static-analysis.sh) but haven't yet put the effort into transpiling https://github.com/ministryofjustice/github-actions/tree/main/terraform-static-analysis parameters/flags

### Hypothesis
If we... [do a thing] Then... [this will happ]

### Proposal 
A proposal that is something testable, don't worry whether it works or not, it's a place for ideas.

### Unknowns 
Potential pitfalls that could cause the story to expand beyond its original scope. Ideally this section will remain blank.

### Definition of Done

- [x] Documentation has been written / updated
- [x] Another team member has reviewed
- [x] Tests are green

**Comment by markgov** [comment]
Going to write a how to documentation for this issue that way if other people want do somthing simila we can just link the doc to them

**Comment by markgov** [comment]
PR Merged documentation is up

**Comment by markgov** [comment]
Documentation created on our user guide on how to install and run the static code analysis

**Comment by Khatraf** [comment]
Ticket reviewed and the document can be found [here](https://user-guide.modernisation-platform.service.justice.gov.uk/user-guide/how-to-setup-code-scanning-locally.html#how-to-setup-code-scanning-software-locally). It provides clear instruction to run SCA locally, so moving it to done.
