### ISSUE TITLE
Consolidate the s3 bucket replication module into the s3 module. 

### ISSUE THREAD

**Issue by ep-93** [ministryofjustice/modernisation-platform#7076]
### User Story

As a mod platform engineer
I want to have as few possible modules to manage, but still provide as many features as possible.
So that there are less repos to update / maintain

### Value / Purpose

The replication module is used by few, and it makes sense to consolidate it into the s3 module due to their similarities,  and reduce our time spent keeping it updated.

### Useful Contacts

Edd Proctor

### Additional Information

Khatra has started this, and I've come along to help.

### Proposal / Unknowns

We need to improve the unit tests in the s3 bucket to cover new features as well as this one, checking happy and sad paths for multiple replication buckets in the same reason etc.

### Definition of Done

- [ ] Documentation has been written / updated
- [ ] README has been updated
- [ ] User docs have been updated
- [ ] Another team member has reviewed
- [ ] Tests are green

**Comment by Khatraf** [comment]
New [release](https://github.com/ministryofjustice/modernisation-platform-terraform-s3-bucket/releases/tag/v.8.0.0) created and follow up ticket raised for the archival of [modernisation-platform-terraform-s3-bucket-replication-role](https://github.com/orgs/ministryofjustice/projects/17/views/1?pane=issue&itemId=66549385).
