### ISSUE TITLE
Contact MP Customers who don't have SSM Agents installed on their instances

### ISSUE THREAD

**Issue by richgreen-moj** [ministryofjustice/modernisation-platform#7088]
### User Story

As a MP engineer
I want to identify and make contact with MP customers who are not running SSM agent on their instances
So that I can ensure that all instances on MP that can possibly host the agent have it installed

### Value / Purpose

Following on from https://github.com/ministryofjustice/modernisation-platform/issues/2415 this issue would be to run the [script](https://github.com/ministryofjustice/modernisation-platform-security/actions/workflows/monitor-ssm-managed-instances.yml) that has been generated in the MP Security repo and get a list of the instances without the SSM agent installed and then contact the customers who we think should be able to get the agent installed based on the platform information. If there is no platform info available we would need to make contact to find out the possibility of installing the SSM agent.

### Useful Contacts

@richgreen-moj @davidkelliott

### Definition of Done

- [x] [SSM monitoring script](https://github.com/ministryofjustice/modernisation-platform-security/actions/workflows/monitor-ssm-managed-instances.yml) has been run to get results
- [x] Customers on list with instances that should be able to host SSM agent are contacted to ask them to install/activate it or attach the relevant IAM policy (where it is already pre-baked)
- [ ] Where no platform details are available contact customers to establish whether the SSM agent could be installed/activated
- [ ] Another team member has reviewed

**Comment by ASTRobinson** [comment]
follow on ticket created and suggested actioning in 1-2 months to allow teams time to arrange for the SSM agent to be installed where possible - https://github.com/ministryofjustice/modernisation-platform/issues/7444

**Comment by ASTRobinson** [comment]
As previously stated all customers have been chased and requested to install / active SSM where possible. Some teams have added these actions to their backlog and will be actioned over the next couple of sprints. I have therefore also created a follow-on ticket (https://github.com/ministryofjustice/modernisation-platform/issues/7444) to re-run the script and assess how the tidy up is going in 1 - 2 months.
