### ISSUE TITLE
Removal of some equip servers

### ISSUE THREAD

**Issue by SimonPPledger** [ministryofjustice/modernisation-platform#7089]
### User Story

Following on from the equip windows server upgrade, the following servers can be deleted:

nps-cor-a-SF01.equip.local
nps-cor-a-SF03.equip.local
nps-cor-a-eqp03.equip.local
nps-cor-a-eqp01.equip.local
nps-cor-a-eqp02.equip.local

### Value / Purpose

This will save some money

### Useful Contacts

Jonny Davey and Mark Roberts

### Definition of Done

 - [ ] servers decommissioned
- [ ] any documentation changed?
- [ ] Jonny Davey advised

**Comment by dms1981** [comment]
@markgov - are these for both Equip environments, and are they both still managed in code or have they been orphaned?

**Comment by markgov** [comment]
All in code as far as i can see

**Comment by dms1981** [comment]
Confirmed that all listed instances are managed in code and to be removed from both environments.
