### ISSUE TITLE
Discuss and decide working principles within the team

### ISSUE THREAD

**Issue by jakemulley** [ministryofjustice/modernisation-platform#71]
As we're growing as a team, we should discuss and decide working principles within the team and document these openly and publicly.

**Comment by kcbotsh** [comment]
[Modernisation platform team alliance V1.0 03:11:20.pdf](https://github.com/ministryofjustice/modernisation-platform/files/5482508/Modernisation.platform.team.alliance.V1.0.03.11.20.pdf)
