### ISSUE TITLE
New Dev Account for CICA - Tariff application

### ISSUE THREAD

**Issue by SimonPPledger** [ministryofjustice/modernisation-platform#7101]
### Environment details

A new environment to allow for Tariff to be migrated to 

### Application Name

Tariff

### Description of application

Tarriff has a database and weblogic app servers - see attached architecture diagram
![AWSArchitecture](https://github.com/ministryofjustice/modernisation-platform/assets/45791941/b8d720de-c4e6-4d2b-91ef-a525e2b3c2c8)

### GitHub team slug

cica-mp-tariff

### GitHub code owner team slug

cica-mp-tariff

### GitHub actions reviewer team slug

cica-mp-tariff

### Environments

- [X] Development
- [ ] test
- [ ] Preproduction
- [ ] Production

### Environment access level Development

developer

### application

Tariff

### business-unit

CICA

### infrastructure-support

Infrastructure@cica.gov.uk

### owner

ALAN.TERRY@cica.gov.uk

### Subnet sets

- [X] General
- [ ] Isolated

### How do users connect to the application

Over the public internet

### Additional features

Please check any additional features required
- [ ] Additional VPC Endpoints
- [ ] Extended DNS Zones
- [ ] Other - please specify

### Other information

network connectivity is being discussed separately

### Definition of Done

Definition of Done
- [ ] account created
- [ ] customer informed

**Comment by SteveLinden** [comment]
There is already a tariff ID in place for CICA. The slug is different but it should be in place and work. If not I will replace the slug with the one listed here.

**Comment by SteveLinden** [comment]
The account that is in place can be removed (I'll create a new call for that) and this one can be created as cica-tariff.

**Comment by SteveLinden** [comment]
New cica-tariff-development environment created.
