### ISSUE TITLE
modernisation-platform-terraform-loadbalancer = Has Outdated input.regex for Parsing Application Load Balancer Logs

### ISSUE THREAD

**Issue by colinbjohnson** [ministryofjustice/modernisation-platform#7107]
### Expected Behavior

The [modernisation-platform-terraform-loadbalancer](https://github.com/ministryofjustice/modernisation-platform-terraform-loadbalancer) module should use the input.regex as provided here: https://docs.aws.amazon.com/athena/latest/ug/application-load-balancer-logs.html.

- AWS has recently added a new field `unknown_fields`
- The field `target_status_code` is a `string` in the AWS documentation and an `int` in the given module
- The field `trace_id ` is named `trace_header` in the given module
- The field `matched_rule_priority` is a `string` in the AWS documentation and an `int` in the given module 
- The field `traceability_id` in the AWS documentation is named `trace_id` in the given module

### Actual Behavior

This fields either:

- do not exist in the given module but do exist in Application Load Balancer Logs
- match AWS names in their own documentation
- use the wrong types for different fields

### Steps to Reproduce the Problem

Compare the documentation here https://docs.aws.amazon.com/athena/latest/ug/application-load-balancer-logs.html#create-alb-access-logs-table with the file here https://github.com/ministryofjustice/modernisation-platform-terraform-loadbalancer/blob/main/main.tf.

**Comment by colinbjohnson** [comment]
BTW - I would be happy to submit a pull request to address this (if desired).

**Comment by SimonPPledger** [comment]
Hi, that would be great, feel free to raise a pull request
