### ISSUE TITLE
DR - Update MP modules to not be region specific

### ISSUE THREAD

**Issue by davidkelliott** [ministryofjustice/modernisation-platform#7146]
### User Story

As an MP user
I want to be able to easily change module regions
So that in a DR situation I can change the region without needing a new module release

### Value / Purpose

To make changing regions during a DR scenario as easily as possible.

### Additional Information

See current DR guidance here which requires regions to be updated in all of our modules - https://user-guide.modernisation-platform.service.justice.gov.uk/runbooks/dr-process.html#repo-module-list

### Proposal 

Update modules so that there is an input for the region.  The default region should be eu-west-2 (or whatever the module currently uses) so that it isn't a breaking change.

This region can then be set once at a member account level and easily changed.

### Definition of Done

- [x] Modules updated to accept different regions (with current region as default)
- [x] User docs have been updated
- [ ] Another team member has reviewed
- [x] Tests are green

**Comment by dms1981** [comment]
Further to my previous, the scope here is all of our modules. That's a lot of modules.

**Comment by ep-93** [comment]
https://docs.google.com/document/d/1mJWlTyjezla-WSJV3ul8UMsfaHdWqi_xoHYboYbONVQ/edit?usp=sharing

**Comment by ep-93** [comment]
Fixed one, looking now at config management 

https://github.com/search?q=repo%3Aministryofjustice%2Fmodernisation-platform-configuration-management%20%20eu-west-2&type=code

yml files have it hardcoded in.

**Comment by ep-93** [comment]
Docs PR = https://github.com/ministryofjustice/modernisation-platform/pull/8192

**Comment by mikereiddigital** [comment]
Hi @ep-93 if you confirm the DoDs are done I will review :)

**Comment by mikereiddigital** [comment]
Have reviewed the changes & will move to done.
