### ISSUE TITLE
🔧 Update MPE application workflow files

### ISSUE THREAD

**Issue by jacobwoffenden** [ministryofjustice/modernisation-platform#7160]
Following the conversation between myself, @ewastempel, @georgepstaylor and @davidkelliott (https://mojdt.slack.com/archives/C01A7QK5VM1/p1717497987776109) it was agreed that `analytical-platform-compute` and `delius-core` would be the first environments to have the updated workflow file via https://github.com/ministryofjustice/modernisation-platform-environments/pull/6393

A pull request has been created to update the source template (https://github.com/ministryofjustice/modernisation-platform/pull/7159)

This change needs rolling out to all application workflow files manually.

**Comment by dms1981** [comment]
https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request << relevant `types:` for a Pull Request
https://docs.github.com/en/rest/using-the-rest-api/issue-event-types?apiVersion=2022-11-28 << descriptions of the different `types:`

**Comment by richgreen-moj** [comment]
I've re-raised a PR https://github.com/ministryofjustice/modernisation-platform/pull/7214 that Jacob had drafted in https://github.com/ministryofjustice/modernisation-platform/pull/7159 to remove types from the template workflow file.

This will stop newly created applications inheriting this mode of operation. Next steps will be to retrospectively update the existing workflow files in Mod Platform Environments.

**Comment by richgreen-moj** [comment]
Putting on hold until I merge the final PR on Tues 18th June @ 12:00 - MP users have been warned of the change via ask/update channels
