### ISSUE TITLE
Investigation into ccms-ebs-production AWS backup costs

### ISSUE THREAD

**Issue by mikereiddigital** [ministryofjustice/modernisation-platform#7167]
### User Story

As a Modernisation Platform Engineer
I expect that the backup of production EBS and other block & file storage devices using AWS Backup is working as expected and that backup images are retained as necessary so as to keep costs to the minimum for the size of devices being backed up.
CCMS backup costs are running higher than expected and the purpose of this story is to ensure that these costs align with what is expected for the volumes of data in scope.

### Value / Purpose

This will ensure that the AWS Backup jobs for production are offering best value.

### Useful Contacts

Maciej Matysiak

### Definition of Done

- Undertake investigation of AWS Backups in ccms-ebs-production
- Confirm breakdown of costs and the contributing factors
- Identify any changes that can be made to reduce the costs.
- Share findings with CCMS team and discuss next steps with them.

**Comment by ep-93** [comment]
Useful command 

`aws backup list-recovery-points-by-backup-vault --backup-vault-name everything | grep -B 15 2024- | sed -n 's/RecoveryPointArn//p' | grep snapshot/ | sed 's/^.*arn/arn/' |  sed 's/,//g' | sed 's/"//g'`

**Comment by SteveLinden** [comment]
Snapshots are currently back to 13/05/2024 (42 pages of them) so this might be costly.

**Comment by SteveLinden** [comment]
Passed on the suggestion of switching off automated backups (based on our documentation) and I was told they are switched off. I checked the first EC2 location and they are still on with the tags.
@ep-93 has been looking at removing the current backups

**Comment by SteveLinden** [comment]
I've had a little scoot around and their backup costs are >£16K per month (and the moment).
It appears, from their backup settings, that they are backing lots, possibly only weekly, and retaining this for 30 days. This means it will always be on the most expensive storage and is not archived. Currently (13th June - backup due to run tonight) they have 883 recovery points.
I think to reduce their costs they need to analyse what they are backing up and their retention periods. 
Additionally there are daily snapshots taken on the EC2 environments that probably also need to be examined. These are daily and could, possibly, be reduced by changing the settings via terraform.

**Comment by SteveLinden** [comment]
Today (14th) 845 recovery points
The backup of config-20230118200416177600000003 "Completed with issues" regularly and would need to be checked.

**Comment by SteveLinden** [comment]
Moved into blocked until we get a response to our questions. They are currently busy

**Comment by dms1981** [comment]
@SteveLinden - can you work with the CCMS-EBS team to understand what their backup strategy is? You might need to ask questions here, and then produce a flowchart or diagram that you can present to the team.

**Comment by SteveLinden** [comment]
Contacted Maciej Matysiak on Slack and he is going to look into whether they can remove the standup jobs from their backup. This may reduce their costs considerably.

**Comment by SteveLinden** [comment]
They appear to be looking into this by themselves at the moment. There is nothing on our side that can be undertaken. The backups they are making will be tested at some point to make sure they are acceptable. We are going to close this call based on the details we have.
