### ISSUE TITLE
SPIKE: Assess viability of custom backup retention periods for AWS Backups of production account data.

### ISSUE THREAD

**Issue by mikereiddigital** [ministryofjustice/modernisation-platform#7168]
### User Story

As a platform user I would like to have the option to vary the retention period of production backups using AWS Backup so that costs can be reduced where possible.

### Value / Purpose

This will give platform users the option to use smaller retention periods for less important data in their production accounts.

### Definition of Done

- Undertake review of AWS Backup code and determine feasibility of user-defined retention periods 
- Present findings to team and agree next steps.

**Comment by dms1981** [comment]
We discussed this in refinement - we think the better option is for customers to handle their bespoke backup needs rather than trying to cater for all possible uses.
