### ISSUE TITLE
Use Observability platform for Modernisation Platform cost metrics

### ISSUE THREAD

**Issue by davidkelliott** [ministryofjustice/modernisation-platform#7169]
### User Story

As an MP Product manager, service owner and MP user
I want to view platform costs in total, broken down into sensible categories (TBC as part of issue)
So that I can use the data to drive cost savings

### Value / Purpose

Replace a manual process of cost metrics with automated dashboards which are easily accessible to mp PM and service owner to view their cost metrics.

### Additional Information

When doing this work it would be beneficial to do it at an AWS org level, so that we could also monitor total AWS spend, off platform AWS spend, platforms AWS spend, and application AWS spend in future issues.

### Proposal / Unknowns

Not sure where this should be done - maybe in the MOJ Master Account?

### Definition of Done

- [x] Total cost metrics for the modernisation platform on the observability platform
- [x] User docs have been updated
- [ ] Another team member has reviewed
- [x] Tests are green

**Comment by dms1981** [comment]
We think this is probably best handled through integrating the MOJ Master account (organizational root) with observability platform, but we have a lot of unknowns here along the way to a defined outcome.

**Comment by sukeshreddyg** [comment]
One approach is to:

1. Create a new report in the Cost Explorer saved reports.
2. Export that data to store in S3 using data exports by creating a new report.

However, there are a few questions regarding this implementation:

1. We don't have permissions to create an S3 bucket in the root account.
2. It's unclear whether we can create an S3 bucket in a cross account (i.e., in the MP account). If it is possible, then we can easily implement this solution.

**Comment by ASTRobinson** [comment]
I have raised a question on the #ask-obervability-platform channel if this setup & configuration is feasible: https://aws.amazon.com/blogs/mt/visualize-and-gain-insights-into-your-aws-cost-and-usage-with-amazon-managed-grafana/

also I have imported two billing dashboards which can used with the current data sources (our core-accounts) to see costs across the different services in AWS. 

https://g-9d213fbc19.grafana-workspace.eu-west-2.amazonaws.com/d/AWSBilling/aws-billing-1?orgId=1
https://g-9d213fbc19.grafana-workspace.eu-west-2.amazonaws.com/d/AWSBillin/aws-billing-2?orgId=1

**Comment by ASTRobinson** [comment]
threat started in the #ask-obervability-platform https://mojdt.slack.com/archives/C05QXHR697S/p1722330176200169 proposing setup and configuration of a billing dashboard using a [AWS Cost and Usage Report (CUR)](https://docs.aws.amazon.com/cur/latest/userguide/what-is-cur.html) with Athena data source as detailed in this article (https://aws.amazon.com/blogs/mt/visualize-and-gain-insights-into-your-aws-cost-and-usage-with-amazon-managed-grafana/).

I believe Jacob might already be investigating a similar solution, not sure if this should be moved to blocked until obs-plat have investigated or could be placed back into to do as Sukesh might interested in this ticket? Otherwise, I can resume working upon my return from annual leave.

**Comment by ASTRobinson** [comment]
following the meeting with Jacob & Gary we have come up with the following potential solution: 

![Image](https://github.com/user-attachments/assets/77050ed6-aa10-4be2-8d61-51071b25d64d)

**Comment by ASTRobinson** [comment]
core-billing account has been created: https://github.com/ministryofjustice/modernisation-platform/pull/7763

Observability Platform tenant onboarding has been started: https://github.com/ministryofjustice/modernisation-platform/pull/7775

**Comment by ASTRobinson** [comment]
I have been working on a cross-account replication module that I hope to add to https://github.com/ministryofjustice/modernisation-platform-terraform-s3-bucket but I haven't quite got there yet (working through some issues and figuring out testing). I have also spoken with the Observability platform team regarding the configuration of the Athena data source for use in our `core-logging` environment, I will be parking the replication module while I focus on this tomorrow and hopefully will be able to get something up in Grafana.

**Comment by ASTRobinson** [comment]
work in progress to add Athena data source in observability platform: https://github.com/ministryofjustice/modernisation-platform-environments/tree/obs-plat/athena-datasource

also in progress is an update to the tenant to switch on the Athena data: https://github.com/ministryofjustice/terraform-aws-observability-platform-tenant/pull/52

(FYI: issue also raised on analytical-platform to track athena request: https://github.com/ministryofjustice/analytical-platform/issues/5382)

**Comment by ASTRobinson** [comment]
Athena polices updated and moj cost usage reports bucketed created in core-logging https://github.com/ministryofjustice/modernisation-platform/pull/8121

**Comment by ASTRobinson** [comment]
updated diagram, work still in progress ![Screenshot 2024-10-01 at 13 36 08](https://github.com/user-attachments/assets/89e5110c-8ff3-47b4-b226-82db3a445d4d)

**Comment by ASTRobinson** [comment]
The setup for querying the AWS Cost and Usage Report (CUR) from Grafana using Athena is complete.

- **S3 Bucket & Replication:** A central S3 bucket hosts the CUR (moj master account), with replication enabled to the core-logging account, allowing Grafana to access and query the CUR data via Athena.

- **Athena Workgroup & IAM Policies:** Athena workgroups were created, and IAM policies were configured to ensure secure, cross-account access between Grafana and Athena. This includes permissions for the glue.amazonaws.com, lambda.amazonaws.com, and logs.amazonaws.com services.

- **Data Refresh & Security:** A Lambda function was deployed to trigger updates via AWS Glue Crawler, using KMS-encrypted CloudWatch logs and SSE-KMS for S3 and Glue resources.

- **Testing & Verification:** Verified data retrieval by running sample CUR queries in Grafana via Athena, ensuring data consistency and appropriate permissions. 

CUR Dashboard can be found here: https://g-9d213fbc19.grafana-workspace.eu-west-2.amazonaws.com/d/be1r6gxhztzi8d/athena-cost-and-usage-report/

**Comment by ASTRobinson** [comment]
User documentation page created as per feedback from stand up this morning: https://user-guide.modernisation-platform.service.justice.gov.uk/user-guide/cost-metrics.html#cost-metrics 

moving across for review/closure

**Comment by markgov** [comment]
All aspects of the ticket have been complete
