### ISSUE TITLE
Use observability platform for modernisation platform cost metrics per application

### ISSUE THREAD

**Issue by davidkelliott** [ministryofjustice/modernisation-platform#7170]
### User Story

As an MP Product manager, service owner and MP user
I want to view platform costs per application
So that I can use the data to drive cost savings

### Value / Purpose

Replace a manual process of cost metrics with automated dashboards which are easily accessible to mp PM and service owner to view their cost metrics.

### Additional Information

When doing this work it would be beneficial to do it at an AWS org level, so that we could also monitor total AWS spend, off platform AWS spend, platforms AWS spend, and application AWS spend in future issues.

### Definition of Done

- [x] Total cost metrics for the modernisation platform on the observability platform split per application
- [x] README has been updated
- [x] User docs have been updated
- [x] Another team member has reviewed
- [x] Tests are green

**Comment by dms1981** [comment]
See #7169 - we think there's a lot of commonality in how to get the data for both of these issues, although the information to be surfaced will be different in each.

**Comment by dms1981** [comment]
Two thoughts here. Both #7169 and #7170 probably have the same requirement of hooking up the org root to observability platform. Once that's done, the question of how to display the data is the differentiator in these tickets, and they may well be repointed to a `3` once that first hard part has been achieved.

**Comment by ASTRobinson** [comment]
I have updated the Cost and Usage Report Dashboard ([athena-cost-and-usage-report](https://g-9d213fbc19.grafana-workspace.eu-west-2.amazonaws.com/d/be1r6garztzi8d/athena-cost-and-usage-report?orgId=1)) to include an `Account_id` variable which allows our users to select single or multiple accounts allowing them to drill down and see specific costs. 

documentation has also been updated in PR https://github.com/ministryofjustice/modernisation-platform/pull/8467 which can viewed here: https://user-guide.modernisation-platform.service.justice.gov.uk/user-guide/cost-metrics.html#using-the-account-id-filter

**Comment by SimonPPledger** [comment]
I think we can tidy this up, but the basics are here and look good - they have already helped the digital-prison-reporting team understand exactly where their costs have increased

**Comment by richgreen-moj** [comment]
I've reviewed this as well and I agree with Simon's comments above. All the DoD is complete. 
Over time perhaps we will tweak it as needed when more users have had the opportunity to use it. 
Nice one @ASTRobinson  👍
