### ISSUE TITLE
Migrate clickops AWS Shield Advanced implementations into code

### ISSUE THREAD

**Issue by dms1981** [ministryofjustice/modernisation-platform#7185]
### User Story

As a Modernisation Platform Engineer
I want to ensure production customers using AWS Shield Advanced do so through Terraform code
So that AWS Shield Advanced resources are implemented and managed in line with our other infrastructure

### Value / Purpose

When we introduced our original guidance on implementing AWS Shield Advanced for production applications, we had no way to achieve this through Terraform. Through #7032 we created a small module in the [modernisation-platform-environments](https://github.com/ministryofjustice/modernisation-platform-environments/tree/main/terraform/modules/shield_advanced) repository which accomplishes all the clickops tasks through code (with an example [here](https://github.com/ministryofjustice/modernisation-platform-environments/blob/main/terraform/environments/example/shield.tf)).

My initial research showed AWS Shield protections in place for the following accounts, so we ought to contact the relevant teams and find out if they want us to coordinate with them and implement the shield module, or if they want to accomplish it independently.

It's worth noting that the `aws_wafv2_web_acl` resource that's created via AWS Firewall Manager in the MOJ `organisation-security` account will need to be imported so that it can then be managed through code.

EG:
```
import {
  id = "00000000-0000-0000-0000-000000000000/FMManagedWebACLV2-shield_advanced_auto_remediate-1234567890123/REGIONAL"
  to = module.shield.aws_wafv2_web_acl.main
}
```

| | Application | Contact | Notes |
| --- | --- | --- | --- |
| ✅ | analytical-platform-compute-production | #ask-analytical-platform | _Analytical Platform team will handle this_ |
| ✅ | analytical-platform-ingestion-production | #ask-analytical-platform | _Analytical Platform team will handle this_ | 
| ✅ | CCMS-EBS-production | #laa-appops | _LAA AppOps will handle this_ |
| ✅ | cdpt-chaps-production | central-digital-product-team@digital.justice.gov.uk | _Implemented by MP team with CDPT oversight_ |
| ✅ | cdpt-ifs-production | central-digital-product-team@digital.justice.gov.uk | _Implemented by MP team with CDPT oversight_ |
| ✅ | dacp-production | DTS-ITServiceDesk@justice.gov.uk | _Protection configured by DTS team_ |
| ✅ | data-platform-apps-and-tools-production | #ask-analytical-platform | _Analytical Platform team will handle this_ |
| ✅ | delius-jitbit-production | #ask-probation-hosting | _Probation team will handle this_ |
| ✅ | electronic-monitoring-data-production | #em-engineers-moj-madetech | _Not required_ |
| ✅ | equip-production | #ask-modernisation-platform | _Implemented by MP team_ |  
| ✅ | hmpps-domain-services-production | #ask-digital-studio-ops | _DSO team will handle this_ | 
| ✅ | hmpps-oem-production | #ask-digital-studio-ops | _DSO team will handle this_ |
| ✅ | laa-oem-production | #laa-appops | _LAA AppOps will handle this_ |
| ✅ | MLRA-production | #laa-appops | _LAA AppOps will handle this_ |
| ✅ | NCAS-production | dts-legacy-apps-support-team@hmcts.net | _Protection configured by DTS team_ |
| ✅ | nomis-combined-reporting-production | #ask-digital-studio-ops | _DSO team will handle this_ |
| ✅ | nomis-data-hub-production | #ask-digital-studio-ops | _DSO team will handle this_ |
| ✅ | NOMIS-production | #ask-digital-studio-ops | _DSO team will handle this_ |
| ✅ | OASYS-production | #ask-digital-studio-ops | _DSO team will handle this_ |
| ✅ | performance-hub-production | #performance-hub | _Implemented in code according to Performance Hub team_ |
| ✅ | planetFM-production | #ask-digital-studio-ops | _DSO team will handle this_ |
| ✅ | PPUD-production | #ppud-migration-team | _Implemented by MP team with PPUD oversight_ |
| ✅ | PRA-production | dts-legacy-apps-support-team@hmcts.net | _Protection configured by DTS team_ |
| ✅ | tipstaff-production | DTS-ITServiceDesk@justice.gov.uk | _Protection configured by DTS team_ |
| ✅ | wardship-production | DTS-ITServiceDesk@justice.gov.uk | _Protection configured by DTS team_ |
| ✅ | xhibit-portal-production | #ext-xhibitportal | _Implemented by MP team with xhibit-portal oversight_ |

### Definition of Done

- [x] ClickOps implementations migrated into code
- [ ] Migrations into code implemented in conjunction with code owners (eg. `Studio Webops`)
- [x] New issues raised where production services have not been updated from `count` to `block`

**Comment by dms1981** [comment]
[Contacted #ask-analytical-platform](https://mojdt.slack.com/archives/C06TFT94JTC/p1725879418199219).

**Comment by dms1981** [comment]
[Contacted #ask-probation-hosting](https://mojdt.slack.com/archives/C032BQQHJE5/p1725879611217469).

**Comment by dms1981** [comment]
[Contacted #ask-laa-ops](https://mojdt.slack.com/archives/CEL68S0LD/p1725879687036349).

**Comment by dms1981** [comment]
[Contacted #ask-digital-studio-ops](https://mojdt.slack.com/archives/C6D94J81E/p1725880160491839).

**Comment by dms1981** [comment]
[Contacted #performance-hub](https://asdslack.slack.com/archives/CUX4J4NNB/p1725880604214309).

**Comment by dms1981** [comment]
[Contacted #ext-xhibitportal](https://mojdt.slack.com/archives/C01B17VU6RY/p1725881313232279).

**Comment by dms1981** [comment]
Waiting on the implementation of [#7858](https://github.com/ministryofjustice/modernisation-platform-environments/pull/7858) in the modernisation-platform-environments repository before moving this to review.

I anticipate some conversations with the teams which will be implementing shield advanced through code by themselves, but those won't be tracked here and we'll have sight of PRs by the teams that are taking responsibility for this.

**Comment by dms1981** [comment]
Raised https://github.com/ministryofjustice/modernisation-platform/issues/7975.

**Comment by dms1981** [comment]
OK! In summary, the owners of all the listed accounts have been contacted. A majority have chosen to implement AWS Shield Advanced through code by themselves. Others I have worked with. I still expect to field questions from teams through DMs, but as that's outside of our control I think this issue is done.

**Comment by richgreen-moj** [comment]
Reviewed ticket and content that this is complete (albeit there may be a need for some ongoing assistance)- looks very thorough and well documented - thanks @dms1981 👍
