### ISSUE TITLE
S3 Lifecycle Rule (exclude Glacier)

### ISSUE THREAD

**Issue by ASTRobinson** [ministryofjustice/modernisation-platform#7186]
### User Story

As a... user of the modernisation platform and [ami-builds](https://github.com/ministryofjustice/modernisation-platform-ami-builds) repo 
I want to… be able to exclude certain S3 buckets from moving to long-term storage (Glacier) 
So that… my ami-builds process does not fail and get held up waiting for items to be restored. 

### Value / Purpose

once or twice a year the artefact bucket used in the ami-builds process requires retrieval from Glacier storage which is causing our users a delay in the ami-builds process and increasing intervention from the modernisation platform team via the ask-channel to retrieve the files and resolve the issue. 

### Useful Contacts

Ijaz Sultan and Dominic Robinson

### Additional Information

S3 Bucket in question: mod-platform-image-artefact-bucket20230203091453221500000001
https://mojdt.slack.com/archives/C01A7QK5VM1/p1717671578917679

### Proposal / Unknowns

I propose that we create a new Lifecycle rule which excludes the move to Glacier storage after 365 days step, which could then be applied to certain buckets if required. 

### Definition of Done

- [x] New S3 Bucket Lifecycle rule created and applied to S3 Bucket (see additional information) 
- [ ] README / User docs have been updated
- [ ] Another team member has reviewed
- [ ] Tests are green

**Comment by richgreen-moj** [comment]
Consider this PR https://github.com/ministryofjustice/modernisation-platform/pull/7191 to disable glacier

**Comment by richgreen-moj** [comment]
Just referencing this slack thread regarding the issue: https://mojdt.slack.com/archives/C01A7QK5VM1/p1718027647334379?thread_ts=1718011793.297219&cid=C01A7QK5VM1

**Comment by richgreen-moj** [comment]
Dominic's PR https://github.com/ministryofjustice/modernisation-platform/pull/7191 has now been merged which stops artefacts in the `mod-platform-image-artefact-bucket20230203091453221500000001` bucket being transitioned to Glacier and enables additional tagging permission so `aws s3 cp` can be used in member accounts.

**Comment by richgreen-moj** [comment]
I've recovered some files for HMPPS out of Glacier storage and they are now unblocked. The new lifecycle policy will stop items moving in and make sure the AMI pipelines don't fail. See this thread for all the updates: https://mojdt.slack.com/archives/C01A7QK5VM1/p1717671578917679
