### ISSUE TITLE
Contact MP members with hardcoded ECS/EKS AMIs to suggest alternative ways to stay up to date

### ISSUE THREAD

**Issue by richgreen-moj** [ministryofjustice/modernisation-platform#7188]
### User Story

As a MP Engineer,
I want to contact members who are using outdated/hardcoded ECS/EKS AMIs to suggest alternative ways of keeping their infrastructure patched with the latest updates,
So that the security best practices are followed on the platform

### Value / Purpose

Follow on from https://github.com/ministryofjustice/modernisation-platform/issues/2413

This issue would involve contacting the applications that were highlighted in the SPIKE as having hardcoded AMI values to suggest one of the options to keep their infrastructure up to date with the latest versions. 

The applications identified were:

- analytical-platform-compute
- data-platform-apps-and-tools
- apex
- cdpt-ifs
- mlra
- performance-hub
- maat
- tribunals

Options they could consider:

1. Use Fargate (serverless) approach so that instance patch management is managed by AWS. (Use the MP [module](https://github.com/ministryofjustice/modernisation-platform-terraform-ecs-cluster) for this)
2. Use a Terraform data call to retrieve the latest ECS/EKS-optimised AMI image by querying the Systems Manager Parameter Store API
3. Reconsider whether workloads would be appropriate for Cloud Platform

### Useful Contacts

@richgreen-moj @davidkelliott

### Definition of Done

- [x] Members have been contacted to discuss options
- [x] Record outcome of discussions

**Comment by Khatraf** [comment]
I've created a spreadsheet to document the outcomes of the discussions with members regarding their applications.
https://docs.google.com/spreadsheets/d/1aKL6CstYGka1ZPUE74RTjYZIGejWyNL4MhrK-mt8Jwc/edit?gid=0#gid=0

**Comment by Khatraf** [comment]
Tickets have been raised to test and implement a solution to avoid hardcoding ECS AMIs for 3 applications (apex, mlra and maat) over the next couple of months. I have added a comment in ticket #7189 to confirm successful implementation.
