### ISSUE TITLE
Apply solution for cloudformation:ResourceTypes to member-access policy

### ISSUE THREAD

**Issue by mikereiddigital** [ministryofjustice/modernisation-platform#7220]
### User Story

As a Modernisation Platform Engineer I want to apply the original member-access policy change as planned in issue 6991 - https://github.com/ministryofjustice/modernisation-platform/issues/6991 - so that the scope of the policy's permissions are only for the user need.

This work is dependent on the outcome of a support case in sprinkler - https://support.console.aws.amazon.com/support/home?region=eu-west-2#/case/?displayId=171759620300231&language=en

### Value / Purpose

As above, we want our policies to only grant those permissions that are needed. 

### Definition of Done

- [ ] Solution confirmed by AWS & tested in sprinkler with them via support call.
- [ ] Change to member-access policy applied via PR & rolled out via scheduled baselines job.
- [ ] LAA Ops informed of the change.

**Comment by Khatraf** [comment]
It is not possible to use Terraform to restrict actions to specific CloudFormation resource types, such as AWS::WAFv2::WebACL, using the cloudformation:ResourceTypes condition key. This can however be managed through the AWS CLI and SDK APIs. 
For this reason, we will continue using the current approach of reviewing PRs picked up by the plan evaluator related to CloudFormation resources and approving them as appropriate.

**Comment by mikereiddigital** [comment]
I've reviewed and have moved to done.
