### ISSUE TITLE
Integrate CloudWatch Alarms with Slack

### ISSUE THREAD

**Issue by jakemulley** [ministryofjustice/modernisation-platform#73]
As part of [modernisation-platform-terraform-baselines](https://github.com/ministryofjustice/modernisation-platform-terraform-baselines/tree/main/modules/securityhub-alarms) we create CloudWatch Alarms to comply with the CIS AWS Foundations Benchmark security standard.

We should integrate these with Slack channels so they're visible to everyone in the team rather than having to individually subscribe people. We should be able to specify a Slack channel to post these to, so we can reuse it for any accounts configured within the Modernisation Platform.

**Comment by davidkelliott** [comment]
We've used this module in CCMS which was pretty easy to set up - https://github.com/terraform-aws-modules/terraform-aws-notify-slack

**Comment by davidkelliott** [comment]
This has been done with https://github.com/ministryofjustice/modernisation-platform/issues/1334
