### ISSUE TITLE
Unit Tests for Cloudtrail/Support modules in Baselines

### ISSUE THREAD

**Issue by richgreen-moj** [ministryofjustice/modernisation-platform#7307]
### User Story

As a MP Engineer
I need to write some unit tests for the Cloudtrail and Support sub-modules sin the Baselines module
So that I can increase the confidence in the modules

### Value / Purpose

As a follow-on from https://github.com/ministryofjustice/modernisation-platform/issues/6490 this ticket is to add missing unit tests for some of the sub-modules in the MP Baselines module.

There are roughly 9 resources for unit testing.

### Useful Contacts

@richgreen-moj 

### Additional Information

Follow-on from https://github.com/ministryofjustice/modernisation-platform/issues/6490

### Definition of Done

- [x] Missing unit tests added
- [x]  New unit tests pass
- [x]  Another team member has reviewed

**Comment by ep-93** [comment]
cloudtrail ✅ - write a follow-up story to test (8 resources) https://github.com/ministryofjustice/modernisation-platform/issues/7307

support ✅ - write a follow-up story to test (1 resource) https://github.com/ministryofjustice/modernisation-platform/issues/7307


These are the resources we need to test.

**Comment by mikereiddigital** [comment]
I'm picking up this one as I've not done much with unit tests & go before. If anyone wants to pair with me on it then do shout. :)

**Comment by mikereiddigital** [comment]
Branch containing the completed support module unit test - https://github.com/ministryofjustice/modernisation-platform-terraform-baselines/tree/issue/7307

**Comment by sukeshreddyg** [comment]
Added unit tests for the `Support` and `CloudTrail` modules.

https://github.com/ministryofjustice/modernisation-platform-terraform-baselines/pull/547

**Comment by markgov** [comment]
just checked and the unit test is failing

**Comment by mikereiddigital** [comment]
Go issue resolved with PR https://github.com/ministryofjustice/modernisation-platform-terraform-baselines/pull/551

**Comment by markgov** [comment]
All looks good
