### ISSUE TITLE
🔀 Attach and cutover Analytical Platform Compute's VPC on MoJO TGW

### ISSUE THREAD

**Issue by jacobwoffenden** [ministryofjustice/modernisation-platform#7313]
### User Story

As a customer of Modernisation Platform
I want to attach `analytical-platform-compute`'s VPCs to MoJO TGW
So that we can continue to route to the corporate network

### Value / Purpose

Analytical Platform inherited two VPCs from Data Engineering that contain their Airflow and EKS setup. We are migrating this to Analytical Platform Compute but need to retain network connectivity to Modernisation Platform and Azure (HMCTS SDP).

### Useful Contacts

@jacobwoffenden

### Additional Information

We have reused the existing ranges from Data Engineering Airflow infrastructure:

- `10.200.0.0/16` (airflow-development)
- `10.201.0.0/16` (airflow-production)

but have further split `10.200.0.0/16`, resulting in the following:

- `10.200.0.0/18` (analytical-platform-compute-development)
- `10.200.64.0/18` (analytical-platform-compute-test)
- `10.201.0.0/16` (analytical-platform-compute-production)

Analytical Platform acknowledge the range clash with LAA (10.200.0.0/20), so until this is retired in 2025, we will only route out from `10.200.64.0/18` in non-production

### Proposal / Unknowns

Attach analytical-platform-compute VPCs to MoJO TGW

### Definition of Done

- [x] VPCs attached to MOJ TGW

**Comment by dms1981** [comment]
RAM shares of the Transit Gateway have been created and are visible in the `analytical-platform-compute-*` accounts. Once the attachments have been created we'll amend the routing in conjunction with the AP team.

**Comment by dms1981** [comment]
As an update, this is most done. The VPCs in question are attached to the MOJO Transit Gateway and associated with the Modernisation Platform TGW route table, but routes have been neither added nor propagated to send traffic through to these replacement VPCs.

**Comment by dms1981** [comment]
`analytical-platform-compute-test` VPC has been propagated into the MP route table on the MOJ TGW, and successfully contacted the remote file share via VPN & CloudGateway.
`analytical-platform-compute-production` VPC will be propagated at a later date.
