### ISSUE TITLE
👥 Apply ABAC to `core-shared-services`

### ISSUE THREAD

**Issue by dms1981** [ministryofjustice/modernisation-platform#7410]
### User Story

As a Modernisation Platform Customer
I want to have access only to my resources in shared environments
So that I can reasonably be sure that other teams cannot manage my resources when using a shared SSO role.

### Value / Purpose

The `instance-management` role is used to provide teams with a limited-access entrypoint into AWS accounts. For example, an application may want to provide support persons with a way to manage instances without having wider permissions. This works well in single-application situations such as our standard offering to customers (one account per application environment).

However, in shared environments (such as our core-shared-services account) offering this role to multiple teams means that they will all have permissions across the account, granting them the ability to take actions on other resources provisioned for other teams.

Through [this spike](https://github.com/ministryofjustice/modernisation-platform/issues/6389) we looked at how to use Attribute Based Access Controls to restrict access based on matching values in the `github_teams` principal with a resource tag (nominally also called `github_teams`). For this story we will apply ABAC to the `instance-management` role in the `core-shared-services` account

### Useful Contacts

@dms1981

### Additional Information

I used the following condition in the `sprinkler-development` account:
```
{
    "Sid": "TestABAC",
    "Effect": "Deny",
    "Action": [
        "*"
    ],
    "Resource": [
        "arn:aws:ec2:eu-west-2:*:instance/i-*"
    ],
    "Condition": {
        "ForAnyValue:StringNotLike": {
            "aws:PrincipalTag/github_team": [
                "*:${aws:ResourceTag/github_team}:*",
                "${aws:ResourceTag/github_team}:*",
                "*:${aws:ResourceTag/github_team}"
            ]
        },
        "Null": {
            "aws:ResourceTag/github_team": "false"
        }
    }
},
```

**NB.** The `StringNotLike` condition has multiple clauses so that the string match can take place at any point in the `github_teams` principaltag value which looks roughly like this: `my-first-team:my-second-team:my-third-team`

### Definition of Done

- [x] ABAC IAM policy condition applied to `instance-management` role/policy in `core-shared-services` account.
- [x] Documentation updated (readme.md, user-guide?)
- [x] Customers informed of updates (eg. how to use this in core-shared-services)

**Comment by markgov** [comment]
initial PR created
https://github.com/ministryofjustice/modernisation-platform/pull/7464

**Comment by markgov** [comment]
Redone the actions to actions * so it should cover everything now

**Comment by markgov** [comment]
PR merged and deployed

**Comment by markgov** [comment]
New PR created as tests failed in core shared services re-tested in sprinkler still working as expected

**Comment by markgov** [comment]
Documentation created and merged
