### ISSUE TITLE
AWS Firehose for production vpc-flow logs in core-logging, shared-servies and security using wrong endpoint.

### ISSUE THREAD

**Issue by mikereiddigital** [ministryofjustice/modernisation-platform#7424]
### Expected Behavior

The xsiam endpoints for the production firehose transfers for core-shared-services, core-logging and core-security are using the wrong endpoint - preprod rather than prod. The source code is missing the local "xsiam" that should be in locals.tf which references the data items for the secret. As such the terraform build defaults to nonprod.

core-shared-services - https://github.com/ministryofjustice/modernisation-platform/blob/main/terraform/environments/core-shared-services/firehose.tf

core-logging - https://github.com/ministryofjustice/modernisation-platform/blob/main/terraform/environments/core-logging/firehose.tf

core-security - https://github.com/ministryofjustice/modernisation-platform/blob/main/terraform/environments/core-security/firehose.tf

### Actual Behavior

The firehose resources are deployed referencing non-prod endpoints.

### Account

core-logging, core-shared-services and core-security.

**Comment by mikereiddigital** [comment]
PR for core-logging - https://github.com/ministryofjustice/modernisation-platform/pull/7431

**Comment by mikereiddigital** [comment]
PR for core-shared-services and core-security - https://github.com/ministryofjustice/modernisation-platform/pull/7433

**Comment by mikereiddigital** [comment]
Have informed Leo Marini (Leonardo.Marini@justice.gov.uk) and will keep this open until he confirms the feeds are being received.

**Comment by mikereiddigital** [comment]
Fixed an issue with the transfers from core-network-services - https://github.com/ministryofjustice/modernisation-platform/pull/7438

**Comment by SimonPPledger** [comment]
Need to add info to user docs - for each feed firehose resource should send info about data set

**Comment by mikereiddigital** [comment]
Also:

- Update our user docs with information on the feeds and their coverage.
- Follow up with AWS why XSIAM are not receiving the meta-data fields.

**Comment by mikereiddigital** [comment]
Spoke with AWS who confirmed the commonAttribute pair of strings is in the header (metadata) of the transfer, not the payload body. Have asked Leo to confirm whether this is accessible at the Corext Xsiam endpoints.

**Comment by mikereiddigital** [comment]
PR for the runbook - https://github.com/ministryofjustice/modernisation-platform/pull/7456

**Comment by mikereiddigital** [comment]
This is the link to the page that I've shared with Leo - https://user-guide.modernisation-platform.service.justice.gov.uk/runbooks/integration-with-protective-monitoring.html#sharing-of-platform-operational-data-with-security-operations-via-aws-data-firehose
