### ISSUE TITLE
New CICA-TARIFF environments

### ISSUE THREAD

**Issue by SimonPPledger** [ministryofjustice/modernisation-platform#7434]
### Environment details

We have created the Dev CICA-TARIFF environments, this is to also create TST, Pre-prod and prod

### Application Name

CICA-TARIFF

### Description of application

Tarriff has a database and weblogic app servers - see attached architecture diagram
![AWSArchitecture](https://github.com/ministryofjustice/modernisation-platform/assets/45791941/b8d720de-c4e6-4d2b-91ef-a525e2b3c2c8)

### GitHub team slug

cica-mp-tariff 

### GitHub code owner team slug

cica-mp-tariff

### GitHub actions reviewer team slug

cica-mp-tariff

### Environments

- [ ] Development
- [X] test
- [X] Preproduction
- [X] Production

### Environment access level Test

developer

### Environment access level Preproduction

developer

### Environment access level Production

developer

### application

CICA-TARIFF

### business-unit

CICA

### infrastructure-support

Infrastructure@cica.gov.uk  

### owner

 ALAN.TERRY@cica.gov.uk

### Subnet sets

- [X] General
- [ ] Isolated

### How do users connect to the application

Over the public internet

### Additional features

Please check any additional features required
- [ ] Additional VPC Endpoints
- [ ] Extended DNS Zones
- [ ] Other - please specify

### Definition of Done

Definition of Done
- [x] account created
- [x] team reivew
- [x] customer informed

**Comment by SteveLinden** [comment]
PR https://github.com/ministryofjustice/modernisation-platform/pull/7567 created for the new account creation.

**Comment by SteveLinden** [comment]
There was an issue with this but @dms1981  re-ran and it cleared the issue.
Latest (for the networking) PR is https://github.com/ministryofjustice/modernisation-platform/pull/7572

**Comment by SteveLinden** [comment]
Issue on the the neworking side which may be related to a code change made in another PR.
@dms1981 is going to look at this with/for me to see if we can get the networks created. Currently there are no VPCs or subnets in place. There should be 1 and 9 of these.

**Comment by SteveLinden** [comment]
David added the RAM shares and I have asked team to review the changes.

**Comment by ewastempel** [comment]
Reviewed, the VPC and subnets are shared, IAM developer role is created. It looks healthy.
