### ISSUE TITLE
NCSC - validate backups by doing a restore

### ISSUE THREAD

**Issue by SimonPPledger** [ministryofjustice/modernisation-platform#7441]
### User Story

**Following on from NCSC review**
**Recommendation**: Regularly test the process of restoring from a backup to ensure the process works and is well understood by the Platform Team prior to an incident. 

This ticket is to test the restore of platform as well as application (eg state files) elements

### Value / Purpose

This will give us confidence that we are able to restore components in case of an issue

### Definition of Done

- [x] Agree on what we are going to restore and where
- [x] carry out the restore
- [x] Test the restore is successful
- [x] Document the backup and restore process and describe the scope of what is going to be backed up and restored.
- [x] Raise more tickets if we feel more testing is required

PS - Try is as a member, not admin

**Comment by Khatraf** [comment]
For this ticket, it was agreed that the focus would be on:
1. Copying the replica of member state file in eu-west-1 and restoring it in eu-west-2.
2. Test the backup for an EC2 instance in one of our testing environments and see if it's successfully is backed up and can be restored.

**Comment by richgreen-moj** [comment]
Ticket reviewed, DoD completed and a runbook to replicate the processes has been documented here:
https://user-guide.modernisation-platform.service.justice.gov.uk/runbooks/backup-restore-process.html#backup-and-restore-of-terraform-statefile-amp-ec2
