### ISSUE TITLE
Contact MP Customers who don't have SSM Agents installed on their instances - 2nd Wave

### ISSUE THREAD

**Issue by ASTRobinson** [ministryofjustice/modernisation-platform#7444]
### User Story

Following on from https://github.com/ministryofjustice/modernisation-platform/issues/7088 (05/07/2024) where all teams were notified of any instances not running the SSM agent and requested to arrange installation (where possible), this ticket is to run the script and reach out to the teams where the SSM agent is not installed (suggested waiting 1-2 months before actioning ticket). 

_As a MP engineer
I want to identify and make contact with MP customers who are not running SSM agents on their instances
So that I can ensure that all instances on MP that can possibly host the agent have it installed_

### Value / Purpose

_Following on from https://github.com/ministryofjustice/modernisation-platform/issues/2415 this issue would be to run the [script](https://github.com/ministryofjustice/modernisation-platform-security/actions/workflows/monitor-ssm-managed-instances.yml) that has been generated in the MP Security repo and get a list of the instances without the SSM agent installed and then contact the customers who we think should be able to get the agent installed based on the platform information. If there is no platform info available we would need to make contact to find out the possibility of installing the SSM agent._

### Useful Contacts

Aaron Robinson / Rich Green

### Additional Information

Script can be found [here](https://github.com/ministryofjustice/modernisation-platform-security/actions/workflows/monitor-ssm-managed-instances.yml)

### Definition of Done

- [x] [SSM monitoring script](https://github.com/ministryofjustice/modernisation-platform-security/actions/workflows/monitor-ssm-managed-instances.yml) has been run to get results
- [x] Customers on list with instances that should be able to host SSM agent are contacted to ask them to install/activate it or attach the relevant IAM policy (where it is already pre-baked)
- [x] Add instances to the risk register where the SSM agent cannot be installed/activated.

**Comment by richgreen-moj** [comment]
@ASTRobinson will get the last spreadsheet and attach a link to the ticket.

**Comment by Kudzai-moj** [comment]
Ran Script [here](https://github.com/ministryofjustice/modernisation-platform-security/actions/runs/11343425964)

**Comment by Kudzai-moj** [comment]
I have sent the below email to all teams/users with instances without the SSM agent... 


_Hello XXXX team,

I hope this message finds you well.

As part of our ongoing efforts to enhance our operational capabilities and in line with our [Production Ready Checklist](https://user-guide.modernisation-platform.service.justice.gov.uk/user-guide/production-ready-checklist.html), we need to ensure that the AWS Systems Manager Agent (SSM Agent) is installed on all EC2 instances across the Modernisation Platform.

To achieve this, I kindly request that you install the SSM Agent on your EC2 instances. Below is a list of identified instances without the SSM Agent. The installation process is straightforward, and many AMIs come with the SSM Agent pre-installed.

If you encounter any issues or have any questions during the installation process, please do not hesitate to reach out for assistance via the [#ask-modernisation-platform](https://moj.enterprise.slack.com/archives/C01A7QK5VM1) channel. 

Thank you for your cooperation in this important initiative.

Best regards,

Aaron Robinson_

 
Account ID | Account Name | Instance ID | Instance Name | SSM Status
-- | -- | -- | -- | --
1234567890 | xxxx-development | i-1234567890 | instance-name | Not Managed

**Comment by Kudzai-moj** [comment]
Started getting replies. We have some false positives. Reviewing the list (129 instances) against SSM Inventory. If large number of false positives are identified will have to raise a ticket to fix the script.

**Comment by Kudzai-moj** [comment]
Sent more emails to for people who did not respond

**Comment by Kudzai-moj** [comment]
Logic added to remove false positives. Checking results to see if any false positives still exist.

**Comment by Kudzai-moj** [comment]
For List of instances to be excluded, see [this link](https://docs.google.com/spreadsheets/d/1n_IHMUjJC4Ae0ms5AxN44RuUGO_-K7xAnasn3HGIx2w/edit?gid=0#gid=0).

**Comment by Kudzai-moj** [comment]
Resourse who can install or answer questions around moj-network-operation instances ins returning from annual leave on Monday 28 October. Will put the ticket in blocked until she returns

**Comment by Kudzai-moj** [comment]
Had meeting with Nicholas Fin for today to discuss his instances that does not have SSM installed. Meeting got cancelled today moved to tomorrow

**Comment by Kudzai-moj** [comment]
Had a meeting with Nicholas and sent follow up email with value of installing SSM and a user data script we have from in our code. Waiting for an update from him once thats done/ he gives us a list of instances that should be added to the risk register. See the instances below,

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:////Users/kudzai.mtoko/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip.htm">
<link rel=File-List
href="file:////Users/kudzai.mtoko/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip_filelist.xml">

</head>

<body link="#467886" vlink="#96607D">


Account   Name | Email | Manual Check | Instance ID | Instance Name
-- | -- | -- | -- | --
moj-network-operations-centre-preproduction | MOJNOC@justice.gov.uk | No | i-02315e9ab49832ff4 | OPENSWAN-EC2
moj-network-operations-centre-preproduction | MOJNOC@justice.gov.uk | No | i-0353292f94b2d9357 | NLB Test
moj-network-operations-centre-production | MOJNOC@justice.gov.uk | No | i-0dd071634a2793af1 | MOJ-NS-NOC-ION-002
moj-network-operations-centre-production | MOJNOC@justice.gov.uk | No | i-0967f522f57ca0530 | MOJ-NS-NOC-SWAPSVR001
moj-network-operations-centre-production | MOJNOC@justice.gov.uk | No | i-0a69252c667fdfa5f | MOJ-NS-NOC-ION-001
moj-network-operations-centre-production | MOJNOC@justice.gov.uk | No | i-00164851f54a4b161 | MOJ-NS-NOC-PALOVM01
moj-network-operations-centre-production | MOJNOC@justice.gov.uk | No | i-013efa1497d75ac11 | MOJ-NS-NOC-XSIAMBROKER001
moj-network-operations-centre-production | MOJNOC@justice.gov.uk | No | i-08607f127c9053d32 | MOJ-NS-NOC-PALOVM02
moj-network-operations-centre-production | MOJNOC@justice.gov.uk | No | i-0c3af78b90d53bd2f | MOJ-NS-NOC-XSIAMBROKER002
moj-network-operations-centre-production | MOJNOC@justice.gov.uk | No | i-0d81805de6dda6817 | MOJ-NS-NOC-PAN02A
moj-network-operations-centre-production | MOJNOC@justice.gov.uk | No | i-0f2ba0dab8812f968 | MOJ-NS-NOC-PAN01A
moj-network-operations-centre-production | MOJNOC@justice.gov.uk | No | i-03b0cade3b946f5af | Guacamole 30
moj-network-operations-centre-production | MOJNOC@justice.gov.uk | No | i-0eb735f3778cf6d34 | MOJ-NS-NOC-TEMP-SYSLOG



</body>

</html>

**Comment by Kudzai-moj** [comment]
Answers have come from the MOJNOC and the instances have been added to the exclusion list.

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:////Users/kudzai.mtoko/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip.htm">
<link rel=File-List
href="file:////Users/kudzai.mtoko/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip_filelist.xml">
<style>

</style>
</head>

<body link="#467886" vlink="#96607D">
<meta charset=utf-8>
<span data-teams=true>


moj-network-operations-centre-preproduction | i-02315e9ab49832ff4 | OPENSWAN-EC2 | Not Managed | Test device only - Not required as will be   shutdown
-- | -- | -- | -- | --
moj-network-operations-centre-preproduction | i-0353292f94b2d9357 | NLB Test | Not Managed | Test device only - Not required as will be shutdown
moj-network-operations-centre-production | i-0077ab995a013e100 | netbox | Not Managed | Test device only - Not required as will be shutdown
moj-network-operations-centre-production | i-00436f85d169dbc9f | Aruba ClearPass Policy Manager | Not Managed | Managed by Vendor
moj-network-operations-centre-production | i-07d9030e2d7d6adc4 | PHPIPAM | Not Managed | Shutdown/Not Live/No changes to be made
moj-network-operations-centre-production | i-0dd071634a2793af1 | MOJ-NS-NOC-ION-002 | Not Managed | Managed by Vendor
moj-network-operations-centre-production | i-0967f522f57ca0530 | MOJ-NS-NOC-SWAPSVR001 | Not Managed | Managed by Vendor
moj-network-operations-centre-production | i-084fed5c016b8a8f2 | EC2-NLB-11 | Not Managed | Test device only - Not required as will be shutdown
moj-network-operations-centre-production | i-0a69252c667fdfa5f | MOJ-NS-NOC-ION-001 | Not Managed | Managed by Vendor
moj-network-operations-centre-production | i-064f0f8f90a226852 | MOJ-NS-NOC-SWWEB002 | Not Managed | Shutdown/Not Live/No changes to be made
moj-network-operations-centre-production | i-05d153302f033bc1d | ITHC-BSI-KALI-Linux | Not Managed | Shutdown/Not Live/No changes to be made
moj-network-operations-centre-production | i-00164851f54a4b161 | MOJ-NS-NOC-PALOVM01 | Not Managed | Managed by Vendor
moj-network-operations-centre-production | i-013efa1497d75ac11 | MOJ-NS-NOC-XSIAMBROKER001 | Not Managed | Managed by Vendor
moj-network-operations-centre-production | i-08607f127c9053d32 | MOJ-NS-NOC-PALOVM02 | Not Managed | Managed by Vendor
moj-network-operations-centre-production | i-0c3af78b90d53bd2f | MOJ-NS-NOC-XSIAMBROKER002 | Not Managed | Managed by Vendor
moj-network-operations-centre-production | i-0d81805de6dda6817 | MOJ-NS-NOC-PAN02A | Not Managed | Managed by Vendor
moj-network-operations-centre-production | i-0f2ba0dab8812f968 | MOJ-NS-NOC-PAN01A | Not Managed | Managed by Vendor
moj-network-operations-centre-production | i-05ed21567311505a9 | test-ulinux-swagent | Not Managed | Test device only - Not required as will be shutdown
moj-network-operations-centre-production | i-007c13410fb54df7d | ArubaAirWave | Not Managed | Managed by Vendor
moj-network-operations-centre-production | i-07f76175c68ec2d82 | testaruba | Not Managed | Test device only - Not required as will be shutdown



</body>

</html>

**Comment by Kudzai-moj** [comment]
Instances in exclusion list have been added to risk register. Can now be closed

https://docs.google.com/spreadsheets/d/1qncGrSJF7No6hRIKOGGfcvaXsk_MvVG6FoHEar4iz74/edit?gid=1230140326#gid=1230140326

**Comment by Khatraf** [comment]
Moving this done as customers have been notified and non-compliant instances added to the risk register.
