### ISSUE TITLE
Rename `github_slug` to `sso_group_name`

### ISSUE THREAD

**Issue by davidkelliott** [ministryofjustice/modernisation-platform#7446]
### User Story

As a MP user
I want to be able to define either github team names or entraID group names
So that I can authenticate with either github or entraID

### Value / Purpose

Moving to justice EntraID authentication will mean the current attribute name `github_slug` will not make sense, this name is more universal and a better description which covers both authentication methods.

### Definition of Done

- [ ] Advise MP customers we will be changing this value in our environments/*.json files
- [ ] Rename `github_slug` to `sso_group_name` in environment files
- [ ] Rename `github_slug` to `sso_group_name` in all scripts and other references (documentation?)
- [ ] update user guidance to explain that this is the name of the identity center group name used for SSO, which can either be a Github team name or a EntraID group.

**Comment by Khatraf** [comment]
Reviewed- no reference to github_slug found for mod platform repo, so has successfully been renamed to sso_group_name & email update sent to members about the change to their json file.
