### ISSUE TITLE
Create a new process for validating requests to add Collaborators

### ISSUE THREAD

**Issue by richgreen-moj** [ministryofjustice/modernisation-platform#7507]
### User Story

As a MP Engineer
I need to be able to verify that requests to access environments on the MP as a collaborator come from a trustworthy source
So that I am confident that requests are legitimate and do not pose a security threat

### Value / Purpose

This ticket would be to add a little bit of governance to the collaborator onboarding process. Currently we get requests via Slack and action as per this process https://user-guide.modernisation-platform.service.justice.gov.uk/runbooks/adding-collaborators.html#adding-collaborators-to-modernisation-platform-accounts

As the platform grows it may not be easy for us to verify who ought be able to add collaborators and to which environments. A new process could add a bit more of an audit trail and a standardised way to check that the request comes from a legitimate source.

Some ideas have been discussed [here](https://mojdt.slack.com/archives/C013RM6MFFW/p1720786891984999) for ways we could implement this e.g. adding a new issue template.

### Useful Contacts

@richgreen-moj

### Definition of Done

- [x] Agree on a process with the team
- [x] Document process and create any templates etc. as required
- [ ] Communicate any changes to members

**Comment by dms1981** [comment]
My next step is to put a simple paragraph of validation into the team runbook on adding collaborators. Something lightweight such as:
* Contact the requestor via Slack
* Confirm the details in the GitHub request
* Get the email address of the new collaborator so that they can be given their login details
* Action the new collaborator in line with this document

**Comment by ASTRobinson** [comment]
Reviewed - New process created using issue template and documentation created/updated.
