### ISSUE TITLE
Create member account SCPs

### ISSUE THREAD

**Issue by davidkelliott** [ministryofjustice/modernisation-platform#751]
## User Story

Add an SCP that will prevent member accounts from doing things we don't want them to do.
We will need to give some thought as to how we do this, but probably something like we apply the policy to the Modernisation OU, the member accounts inherit it and we write the policy so that it excludes accounts that we don't want to be affected by it, eg core accounts.

## Value

Security and ensuring users can only create and do things that we want them to be able to do.

## Questions / Assumptions

We will need to have a workshop probably to look at what policies we want to set and how we will set them.

## Definition of done

- [x] scp in place for all member accounts
- [ ] readme has been updated
- [ ] user docs have been updated
- [x] another team member has reviewed
- [ ] tests are green

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by donmasters** [comment]
Update: 

It has been decided to have three sub OUs under the Modernisation-Platform OU. This change will enable better permission control using SCPs i.e restrictions required for member accounts could not be applied to core accounts.

The changes to OUs have been made in code but are now being tested before being rolled out.

**Comment by donmasters** [comment]
OUs and accounts have now been reconfigured as described above

Nest step is to Code and implement the base SCP's for each sub-OU

**Comment by donmasters** [comment]
Sub OUs of Modernisation Platform now have SCPs applied. Testing has been completed on member accounts to ensure restrictions are in place.

Closing ticket
