### ISSUE TITLE
Make KMS key replicas.

### ISSUE THREAD

**Issue by ep-93** [ministryofjustice/modernisation-platform#7514]
### User Story

As a Mod Platform Engineer
Now we have decided that eu-west-1 is the fallback / DR region,  our multi region KMS keys need to have a slight change 
So that they are copied to eu-west-1. 

### Value / Purpose

Currently keys have been changed from single region to multi region, but require a few lines of code to copy that key to a specified region.

### Useful Contacts

Edd Proctor

### Additional Information

https://github.com/ministryofjustice/modernisation-platform/blob/main/terraform/modernisation-platform-account/secrets.tf#L30

Adding this.

### Definition of Done

- [x] Identify all multi region replica KMS keys.
- [x] Add code like here - https://github.com/ministryofjustice/modernisation-platform/blob/main/terraform/modernisation-platform-account/secrets.tf#L30
- [ ] Move all things to USE multi region keys.

**Comment by markgov** [comment]
Needs more clarification on the second point made after the DOD

**Comment by Kudzai-moj** [comment]
Added the multi region replica keys below, and merged PR

- environment-management-multi-region
- s3-state-bucket-multi-region
- pagerduty-secret-multi-region
- dynamodb-state-lock-multi-region
