### ISSUE TITLE
NCSC: VPC security - documentation

### ISSUE THREAD

**Issue by SimonPPledger** [ministryofjustice/modernisation-platform#7531]
### User Story

NCSC said:
"**VPC Security**
Each VPC is provisioned with its own public, private, and data subnets. There are two further subnets spanning all VPCs (Transit Gateway and Protected) – these provide connectivity to VPC endpoints and other applications via Transit Gateway. 
If multiple legacy apps are deployed into the same VPC, the compromise of a single app could present a risk of lateral movement. The reliance is on Product teams to implement Security Groups to mitigate this risk. Transit Gateway rules are implemented on a case-by-case basis and therefore no connectivity between VPCs is provided by default.

**Risk**: Poorly configured Security Groups could allow lateral movement within VPCs. 

This ticket is to review and update our documentation on security groups, providing examples of good, well defined VPC security groups.

### Value / Purpose

Improve the security within VPCs by ensuring that application team created VPCs are secure

### Definition of Done

- [ ] Documentation updated
- [ ] Reviewed and approved and implemented
- [ ] Documentation advertised on slack (ask and update channels)
- [ ] Documentation sent out to app teams' contacts?

**Comment by dms1981** [comment]
We already check for overly permissive security groups with Security Hub - are our notifications here not sufficiently visible?

**Comment by dms1981** [comment]
Are our examples in the `example` environment of sufficient quality that customers can see these as best practice? I don't think there's any real value in creating parallel documentation to what AWS already offer through their Well Architected framework in the security pillar, and their supporting documentation.

**Comment by dms1981** [comment]
Do we also sufficiently mitigate this risk through our use of secure code analysis tools like `trivy` and `checkov`?

**Comment by dms1981** [comment]
https://docs.aws.amazon.com/wellarchitected/latest/security-pillar/welcome.html

**Comment by dms1981** [comment]
We think that we adequately mitigate against this risk through the following:
* Secure code analysis tools that run as part of deployment pipelines
* Use of AWS SecurityHub to advise on insecure security groups
* Examples of good practice in our `example` environment
* Our production-ready review checklist

We don't think that adding further documentation will provide a major differentiator; the AWS Well Architected Framework `security` pillar offers excellent advise, and writing parallel documentation is unlikely to improve matters.

Beyond this, platform customers own their own infrastructure code, and we don't think we're best placed to pro-actively advise on the quality of the `Terraform` that they write although we're certainly happy to respond to requests.
