### ISSUE TITLE
Modify json change notifications to send to user slack channel

### ISSUE THREAD

**Issue by davidkelliott** [ministryofjustice/modernisation-platform#7570]
### User Story

As an MP user
I want json file change notifications to go to my team slack channel
So that the message is direct and relevant to me

### Value / Purpose

Currently the notifications go through to the update channel, this channel is for updates which affect all teams, not individual team updates. Updates should go to a team's slack channel if present or if not no slack notification only email.

https://github.com/ministryofjustice/modernisation-platform/blob/main/.github/workflows/new-environment.yml#L365 

### Additional Information

We will need to add a `slack-channel` field to the environment json files.  (we don't need to add to all now, just to the documentation and update example, sprinkler etc so that users know how to do it.)

As a result of the Member information spike https://github.com/ministryofjustice/modernisation-platform/issues/6317 it would be ideal if we could start tagging more info in organisations so that we can query pertiinent member information from one place so can we also tag the account `slack-channel` in organisations.

### Definition of Done

- [x] Add `slack-channel` to environment files
- [x] Tag account in organisations with `slack-channel`
- [x] Amend workflow to send to team channel (or skip if not present)
- [x] Update documentation
- [x] Announce new feature in update channel

**Comment by richgreen-moj** [comment]
Looks good to me @sukeshreddyg nice work 👍
