### ISSUE TITLE
[BUG] RAM share creation failing with new accounts

### ISSUE THREAD

**Issue by dms1981** [ministryofjustice/modernisation-platform#7580]
### Expected Behavior

When we create new accounts, the relevant `core-vpc-*-deployment` action should run.
This action has two jobs:
* `core-vpc-*-deployment-plan-apply`
* `member-account-ram-association`
If we add new environments inside an existing `environments/*.json` we should trigger this action, run the relevant VPC deployment, and create the necessary RAM shares.

### Actual Behavior

In a recent pull request that added extra environments to the `environments/cica-tariff.json` file the necessary RAM shares were not created.

From reading the relevant GitHub actions logs it appears that the changed environments are not correctly being passed in as arguments to the script that sets up the RAM shares:
```
[+] Starting up RAM association for account cica-tariff-preproduction of application cicatariffpreproduction
[+] ./terraform/environments/cicatariffpreproduction/networking.auto.tfvars.json does not exist, skipping RAM share.
```
This has resulted in a team member having to run commands like the following to set up the RAM shares manually:
```
terraform workspace select $name-of-workspace
terraform apply -target="module.ram-ec2-retagging[0].data.aws_subnets.associated"
terraform apply
```

### Steps to Reproduce the Problem

1. View this [pull request](https://github.com/ministryofjustice/modernisation-platform/pull/7572/files).
2. View this [GitHub Action execution](https://github.com/ministryofjustice/modernisation-platform/actions/runs/10057539380).
3. Review this [shell script](https://github.com/ministryofjustice/modernisation-platform/blob/main/scripts/get-applications-and-run-ram.sh).

**Comment by sukeshreddyg** [comment]
A similar issue that was fixed previously is happening again.https://github.com/ministryofjustice/modernisation-platform/issues/6048

**Comment by ASTRobinson** [comment]
confirmed that https://github.com/ministryofjustice/modernisation-platform/pull/7641 has resolved the issue. moving to Done.
