### ISSUE TITLE
New environments for LAA SMTP

### ISSUE THREAD

**Issue by vc13837** [ministryofjustice/modernisation-platform#7592]
### Environment details

DEV, TST, PRE, PROD

### Application Name

laa-mail-relay

### Description of application

These environments will contain a Postfix Server with SES set up to relay emails from various LAA applications in MP to users.

### GitHub team slug

laa-aws-infrastructure

### GitHub code owner team slug

laa-aws-infrastructure

### GitHub actions reviewer team slug

laa-aws-infrastructure

### Environments

- [X] Development
- [X] test
- [X] Preproduction
- [X] Production

### Environment access level Development

sandbox

### Environment access level Test

developer

### Environment access level Preproduction

developer

### Environment access level Production

developer

### application

LAA Mail Relay

### business-unit

LAA

### infrastructure-support

laa_ops@digital.justice.gov.uk

### owner

laa_ops@digital.justice.gov.uk

### Subnet sets

- [X] General
- [ ] Isolated

### How do users connect to the application

Over the public internet

### Additional features

Please check any additional features required
- [ ] Additional VPC Endpoints
- [ ] Extended DNS Zones
- [x] Other - please specify - we shall be requesting for production access for SES ourselves

### Other information

Please also add in **no nuke destroy** weekly for the sandbox DEV environment

### Definition of Done

Definition of Done
- [ ] account created
- [ ] customer informed

**Comment by mikereiddigital** [comment]
Kicked off account creation. Will check on updates at 11.20

**Comment by sukeshreddyg** [comment]
We are experiencing issues with the account alias due to a conflict with an existing alias. Although we renamed the closed account to a different alias, the change was not successfully applied on AWS's side. We currently do not have the necessary permissions to resolve this issue and will wait until Monday for Ewa's assistance to move the account from closed OU to root OU.

**Comment by mikereiddigital** [comment]
Issues overcome. laa-mail-relay development created & Vincent informed. Creating test now. Will create the other two tomorrow.

**Comment by mikereiddigital** [comment]
Test created and Vincent informed.

**Comment by ASTRobinson** [comment]
ticket reviewed and environments successfully created, moving to Done.
