### ISSUE TITLE
SPIKE: Cortex XSIAM IAM integration review

### ISSUE THREAD

**Issue by davidkelliott** [ministryofjustice/modernisation-platform#7605]
### User Story

As a security engineer
I want to view IAM data in Cortex XSIAM
So that I have better quality user data and can alert on IAM issues

### Value / Purpose

Improve data in cortex leading to better findings.

### Useful Contacts

Ashwin John

### Definition of Done

- [ ] Review [integration](https://docs-cortex.paloaltonetworks.com/r/Cortex-XSIAM/Cortex-XSIAM-Documentation) and see if it is appropriate
- [ ] Demo to team your finding and discuss with team to decide if we want to go ahead
- [ ] If we decide to go ahead create a new ticket with the steps required

**Comment by markgov** [comment]
@davidkelliott can we have some more information on this issue

**Comment by davidkelliott** [comment]
So the key things to consider when reviewing the integration would be:
1. What permissions does it need and are we happy with it having those permissions?
2. What data does it take, are we ok to share this data? Who will see this data? Is that ok?
3. How does it integrate?  Are there any risks involved?
4. IAM users are in the modernisation-platform account, is that the only account it would be useful or are there other accounts.
5. When reviewed an presented to team, Ewa / Dave / Simon make a call on if we want to go ahead with this.

**Comment by dms1981** [comment]
Also, is this what we're looking to do? https://docs-cortex.paloaltonetworks.com/r/Cortex-XSIAM/Cortex-XSIAM-Administrator-Guide/Ingest-Cloud-Assets-from-AWS

There's no direct integration I could see that references pulling IAM data from AWS, but the closest I could see is the above link to retrieve an inventory of assets which ought to include IAM data.

**Comment by ashwinmoj** [comment]
For more information on the requirements for these integrations, please refer to the following links:
•	[AWS IAM Integration](https://xsoar.pan.dev/docs/reference/integrations/aws---iam) 
•	[AWS IAM Identity Center Integration](https://xsoar.pan.dev/docs/reference/integrations/aws---iam-identity-center)
•	[AWS Integrations Authentication](https://xsoar.pan.dev/docs/reference/articles/aws-integrations---authentication)

**Comment by ashwinmoj** [comment]
Hi, could I please ask if there have been any updates on reviewing this task?

**Comment by ashwinmoj** [comment]
To provide additional context for this request: the purpose of this integration is to enhance alerts from the AWS environment on the XSIAM platform. Specifically, we aim to use this integration for alert enrichment by querying information about Amazon resources, which will assist the SOC in investigating AWS-related alerts. 

I've attached the list of commands available on XSIAM after the IAM integration is complete. We are specifically interested in the commands that query information, rather than making any changes to the platform. This includes commands starting with aws-iam-get and aws-iam-list. So when configuring the integration, we need to set up a role that allows these commands to be executed.

[AWS IAM vs AWS Identity Center commands.xlsx](https://github.com/user-attachments/files/16763528/AWS.IAM.vs.AWS.Identity.Center.commands.xlsx)

Mod Platform data is already being ingested on XSAIM via Amazon S3 and Cloudwatch. The SOC team will be the primary users of this data, investigating any alerts from the AWS environment and escalating any concerning incidents according to the agreed process.

**Comment by ashwinmoj** [comment]
For the integration we’ll need to use the Access Key and Secret Key authentication option. 

As part of the configuration for the Access Key and Secret Key authentication you create a role and can specify granular IAM permissions. This looks to be the list of actions you can choose from: [Actions - AWS Identity and Access Management](https://docs.aws.amazon.com/IAM/latest/APIReference/API_Operations.html) . This will allow you to only give the account the privileges it needs for the particular commands you would like to use. 

Full steps for setting up the account and integration for the  Access Key and Secret Key authentication option are here: [AWS Integrations - Authentication | Cortex XSOAR](https://xsoar.pan.dev/docs/reference/articles/aws-integrations---authentication#configuration-using-access-key-and-secret-key)

**Comment by richgreen-moj** [comment]
So far I've just been reading up on all the information provided above. I'm meeting with Ashwin today so I can get an example of the kinds of alerts that are coming through so I can better understand the user need and whether the solution proposed is going to meet that.

**Comment by richgreen-moj** [comment]
I had another meeting last Thursday (5th Sept) with Ashwin and a group of SOC engineers to go through some more example alerts. One was another ec2 instance uploading to s3 and I tried to explain that the public IP was that of a NAT GAteway endpojnt (i.e. not traceable to a real user) The majority of users are identifiable in the root account (AWS SSO) although that doesn't hold much info (i.e. no genuine contact details/info regarding users). Also we found that one alert was for Cloud Platform which wasn't hooked into the AWS SSO etc.

I offered the possibility of testing the IAM integration in the Modernisation Platform account where we have a limited set of collaborator users but I think Ashwin was going to hold another internal meeting to discuss what kind of integration would add the most benefit to the SOC as they are getting many alerts across multiple platforms.

**Comment by ashwinmoj** [comment]
Before using AWS Organizations, you need to perform several configuration steps in your AWS environment.
Prerequisites

- Attach an instance profile with the required permissions to the Cortex XSIAM server or engine that is running on your AWS environment.
- The instance profile requires the following minimum permission: sts:AssumeRole.
- The instance profile requires permission to assume the roles needed by the AWS integrations.

Configure AWS Settings

1. Create an IAM role for the instance profile.
2. Attach a role to the instance profile.
3. Configure the necessary IAM roles that the AWS integration can assume.

**Comment by richgreen-moj** [comment]
https://github.com/ministryofjustice/modernisation-platform/issues/7897 << This is the new story for enabling AWS Organisations integration
