### ISSUE TITLE
Create workflow to deploy modernisation-platform-account terraform

### ISSUE THREAD

**Issue by davidkelliott** [ministryofjustice/modernisation-platform#761]
## User Story

https://github.com/ministryofjustice/modernisation-platform/tree/main/terraform/modernisation-platform-account

This Terraform currently needs to be run manually, we should create a Github Actions workflow for this to avoid having to run it manually as a superadmin.

Here is an example of a workflow that runs a Terraform plan and apply - https://github.com/ministryofjustice/modernisation-platform/blob/main/.github/workflows/terraform-github.yml

## Value

By running things on pipelines we ensure the same process and same versions etc are followed every time.  This adds consistency, reduces errors.  It also means we are not manually running things with a powerful role where a mistake could be dangerous.

## Definition of done

- [ ] workflow created for this terraform
- [ ] readme has been updated
- [ ] another team member has reviewed

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by SteveLinden** [comment]
Need a new workflow in the workflows pointing to the modernisation-platform-account.

New yml file created called modernisation-platform-account.yml and amended to point to the correct location.
