### ISSUE TITLE
Plan a Disaster Recovery test

### ISSUE THREAD

**Issue by SimonPPledger** [ministryofjustice/modernisation-platform#7611]
### User Story

As a user of the platform I need to be confident that, should something go wrong with the platform I can still work.
This ticket is to pull together a plan, to cover scope, liasing with a willing application team and agreeing approach/responsibilities

### Value / Purpose

To provide confidence in how we would recreate the platform in another region

### Definition of Done

- [x] Confirm DR scenario that we are testing
- [x] Document our approach to testing DR
- [ ] Agree an approach with one of the application teams
- [x] Agree and document a plan 
- [x] Raise more tickets

**Comment by ep-93** [comment]
https://docs.google.com/document/d/1fkWdHL2pHzg1l__g5AMF9FbTWpsJ_Hj8yzKX3fI7ypY/edit?usp=sharing

Documented issues, to proceed we need a TGW in Ireland.
