### ISSUE TITLE
Resolve the different versions of Go & dependencies used across unit tests.

### ISSUE THREAD

**Issue by mikereiddigital** [ministryofjustice/modernisation-platform#7613]
### User Story

As a Modernisation Platform Engineer 

I want our Go/Terratest Unit Tests to use the right version of Go and have dependencies that are up to date for the version used. 

This PR - https://github.com/ministryofjustice/modernisation-platform-terraform-module-template/pull/424 for the terraform module-template shows the change to dependabot to include Go unit test files in its scope.

### Value / Purpose

This will ensure that our tests continue to work & avoid security vulnerabilities due old much older versions being used.

### Definition of Done

- [x] Review & agree with team that the issue requires resolution as described above.
- [x] Roll out across all repositories containing unit tests, ensuring each unit test continues to work correctly after any updates.

**Comment by ASTRobinson** [comment]
I have checked all the MP repos and enabled Dependabot for Go dependencies and bumped the Go version to 1.23.

Example PR's:
Bump Go Version: https://github.com/ministryofjustice/modernisation-platform-terraform-baselines/pull/607
Enable Dependabot for Go: https://github.com/ministryofjustice/modernisation-platform-github-oidc-provider/pull/452

This was discussed in standup this morning and the team agreed with the implemented solution, passing for review/close.
