### ISSUE TITLE
Comment out Example Terraform code as default

### ISSUE THREAD

**Issue by richgreen-moj** [ministryofjustice/modernisation-platform#7621]
### User Story

As a MP Engineer
I expect the Example account to be in a clear (error/free) state 
So that I can quickly start testing my changes in the environment

### Value / Purpose

The proposal here is that we default the Example Terraform code to be hashed out so that the environment is virtually empty to simplify the process of using the environment to test our changes etc.

This came from a discussion in retro where people were finding the TF code in a state of error when trying to test small changes and needing to spend a lot of time clearing these before being able to use the environment for testing.

This comes from 

### Additional Information

This was a retro action from 05/08/24

### Definition of Done

- [x] Hash out Example code
- [x] PR raised and approved/merged

**Comment by markgov** [comment]
Created a PR to hash out unneeded resources
https://github.com/ministryofjustice/modernisation-platform-environments/pull/8266

**Comment by markgov** [comment]
Terraform plan works fine locally but when the workflow runs the plan errors still working on this.

**Comment by markgov** [comment]
commented out most if not all resources the only issue is aws shield module webacl which does an import from the root account but working on a workaround at the moment

**Comment by markgov** [comment]
PR now Merged and there are no errors and resources are now down to a minimum

**Comment by markgov** [comment]
Issue ready for review

**Comment by sukeshreddyg** [comment]
Have reviewed. Moving to done.
