### ISSUE TITLE
Unable to add ekr endpoint for us east 1

### ISSUE THREAD

**Issue by davidkelliott** [ministryofjustice/modernisation-platform#763]
## Expected Behavior

Endpoint added successfully

## Actual Behavior

Adding endpoint - `com.amazonaws.us-east-1.ecr.dkr` the the development core vpc failed.

## Steps to Reproduce the Problem

  1. Add endpoint to the networkflile
  1. Apply terraform (or watch workflow to see if it fails
  1.

**Comment by dms1981** [comment]
Looking at this one I think it's just missing the registry ID, but after discussing the matter with @davidkelliott we're going to close this and revisit it if the need rearises.
