### ISSUE TITLE
Create New Account - PR for new files not fully populating networking.auto.tfvars.json

### ISSUE THREAD

**Issue by mikereiddigital** [ministryofjustice/modernisation-platform#7670]
### Expected Behavior

The two PRs that are generated (steps 4.1 and 4.2) in the New Account process (https://user-guide.modernisation-platform.service.justice.gov.uk/runbooks/creating-accounts-for-end-users.html#creating-aws-accounts-for-teams) when a completely new application account is created did not fully populate the values for business_unit & set. The result was the jobs for the networking stage failed.

### Actual Behavior

See PR https://github.com/ministryofjustice/modernisation-platform/pull/7635/files and specifically https://github.com/ministryofjustice/modernisation-platform/pull/7635/files#diff-b1eeba5454593bf18b56be3d6740ddf670aeee0249f3ef165808be73c6e1e14b for the issue.

The initial PR that generated these files was https://github.com/ministryofjustice/modernisation-platform/pull/7634

### Steps to Reproduce the Problem

Create new development environment using the same scope of the environments/.json as per this PR - https://github.com/ministryofjustice/modernisation-platform/pull/7634.

### Account

Modernisation Platform & Modernisation Platform Environments.

**Comment by sukeshreddyg** [comment]
pipeline has [failed](https://github.com/ministryofjustice/modernisation-platform/actions/runs/10400724344/job/28801826371#step:11:1736) due to a scheduled brownout of the tag protections API.
To address this issue, I have raised a ticket that needs to be refined. #7687

**Comment by sukeshreddyg** [comment]
I have tested this with a `new account` and was able to create it without any errors. The process successfully generated the automated environment files as expected, which are responsible for setting the parameters in `networking.auto.tfvars.json`
