### ISSUE TITLE
Signed commits and github-actions[bot]

### ISSUE THREAD

**Issue by dms1981** [ministryofjustice/modernisation-platform#7689]
### User Story

As a Modernisation Platform Engineer
I want to find a way for `github-actions[bot]` to sign its commits
So that we can continue to require signed commits in our repositories

### Value / Purpose

In a recent PR it was observed that the `github-actions[bot]` pushed a linting change into the branch. This commit was no signed, causing the PR to fail to meet our branch protection rules for signed commits.

Therefore we need to research and, if sensible, implement a way for the `github-actions[bot]` to sign its commits.

### Definition of Done

- [x] Options for signing commits by `github-actions[bot]` identified
- [x] Best option implemented across MP repositories
- [x] Solution tested successfully
- [x] Solution demonstrated to team

**Comment by ASTRobinson** [comment]
Example bot PR: https://github.com/ministryofjustice/modernisation-platform/pull/7709

**Comment by jacobwoffenden** [comment]
FWIW we use this https://github.com/planetscale/ghcommit-action 

https://github.com/ministryofjustice/analytical-platform/blob/fc64a650265ec6cf3ff6f8b62e72784fed09a936/.github/workflows/repository-dependabot-configuration-generator.yml#L39-L48

**Comment by markgov** [comment]
https://github.com/Nautilus-Cyberneering/pygithub/blob/main/docs/how_to_sign_automatic_commits_in_github_actions.md
found this while looking up some information

**Comment by mikereiddigital** [comment]
There are two workflows in scope:

- A scheduled workflow that runs daily on week days and which sweeps the existing code and generates a PR with any identified changes - ministryofjustice/modernisation-platform/blob/main/.github/workflows/format-code.yml

- A workflow that runs on any PR which calls the action ministryofjustice/github-actions/code-formatter which scans the code of the PR generates required changes and updates the PR with them. It is this workflow that the above description refers to.

**Comment by mikereiddigital** [comment]
The suggested approach is to use planetscale/gscommit-action as set out in @jacobwoffenden's example above. This allows us to avoid maintaining gpg keys as secrets & sharing them between workflows. The first step will be to implement this in the code-formatter action and to test it via a commit ref from one of the formatter workflows in a lesser-used module.

**Comment by jacobwoffenden** [comment]
I forgot to mention actually, when using our robot's token, its allows GitHub Actions to trigger workflows, when using GitHub Actions' token this is not allowed

**Comment by mikereiddigital** [comment]
Completed testing.

**Comment by mikereiddigital** [comment]
Thanks for the info @jacobwoffenden.

**Comment by mikereiddigital** [comment]
This PR was applied for the scheduled formatter workflow in modernisation-platform. I will check the run this afternoon for issues.

For the change to the ministryofjustice/github-actions/code-formatter I will prepare a PR using the same 3rd party workflow and will offer it to Ops Engineering for review. If it is not approved & a new release ready then this ticket cannot be completed by me before cop tomorrow.

**Comment by mikereiddigital** [comment]
PR reverted (via this https://github.com/ministryofjustice/modernisation-platform/pull/7798) as the use of planetscale/gscommit-action is considered too risky for bot-generated PRs.

**Comment by mikereiddigital** [comment]
The suggested solution now is to following a similar approach to how it is set out here - https://github.com/planetscale/ghcommit and to use the GraphQL API createCommitOnBranch mutation to generate signed commits that are created via a workflow.

**Comment by robertsweetman** [comment]
👍 for this please

**Comment by ep-93** [comment]
https://github.com/ep-93/house-of-fun/commit/2dbb54f99183c2afa407f0883f506e793d614f5f

Workflow that worked

https://github.com/ep-93/house-of-fun/actions/runs/10795145787/job/29941105329

https://github.com/ep-93/house-of-fun/actions/runs/10795145787/workflow

Now need to put this into the two jobs Mike mentioned.

**Comment by ep-93** [comment]
Last workflow run - https://github.com/ministryofjustice/modernisation-platform/actions/runs/10944167073/job/30385372555

Needs a little tidying but looks like its working. 

Could remove things I have added for debugging, or not, whatever you fancy.

PR - https://github.com/ministryofjustice/modernisation-platform/pull/7940

Showing verified commit - https://github.com/ministryofjustice/modernisation-platform/commit/daa7764505f8bc0b3fe394c346a13a0faeead990




What should happen. 

Merge it, check it - If the branch already exists it does error, but I believe thats the same as the current one, could add something for that. 

Create a ticket from this for the trimming down and adding maybe something to have a script outside of the workflow for this.

**Comment by mikereiddigital** [comment]
Approved, merged and applied the above PR. Will look at the 2nd part of the change - the github-actions/code-formatter next week when I'm back.

**Comment by mikereiddigital** [comment]
I'm off on leave on Monday & Tuesday next week so I'm moving this to blocked. Will pick it up again on Wednesday when back.

**Comment by mikereiddigital** [comment]
This PR addresses a bug in the previous version whereby the newly created branch needs to be pushed up to remote in order for the API to references it.

**Comment by mikereiddigital** [comment]
Still unable to successfully push the json file in a format that the api accepts. The json format for the API is here - https://docs.github.com/en/graphql/reference/input-objects#filechanges and the branch here - https://github.com/ministryofjustice/modernisation-platform/tree/issue/7689-bugfix

**Comment by mikereiddigital** [comment]
@ASTRobinson found the issue and this PR updates the daily workflow in modernisation-platform. Will start on the next workflow later.

**Comment by mikereiddigital** [comment]
We found & dealt with another bug caused by the addition of the /n to the file-contents. This has been removed & confirmed as working.

**Comment by mikereiddigital** [comment]
The final stage of this ticket for this workflow (https://github.com/ministryofjustice/github-actions/tree/main/code-formatter) which is called by the format-code workflow in modernisation-platform modules e.g. https://github.com/ministryofjustice/modernisation-platform-instance-scheduler/blob/main/.github/workflows/format-code.yml

**Comment by mikereiddigital** [comment]
Have draft working version of the new remote action in https://github.com/ministryofjustice/github-actions/blob/feature/signed-commits/code-formatter/action.yml.

As an example, a PR here https://github.com/ministryofjustice/modernisation-platform-terraform-bastion-linux/pull/542 using a new version of the local formatter calling the above draft has the output:

![Image](https://github.com/user-attachments/assets/c77b98bc-b64b-40bb-a328-a5f5d4af54a5)

To do:
- tidy up draft working version and replace hard-coded owner & repo with variables.
- Final testing and confirm candidate for PR
- Create PR for review within MP
- Review PR with Ops Eng.
- New release of github-actions repo.
- Update local module workflows with new ref.

**Comment by mikereiddigital** [comment]
PR for the github-actions formatter change - https://github.com/ministryofjustice/github-actions/pull/270

**Comment by mikereiddigital** [comment]
New release of the code-formatter - https://github.com/ministryofjustice/github-actions/releases/tag/v18.2.0

**Comment by mikereiddigital** [comment]
PRs for modules:

- https://github.com/ministryofjustice/modernisation-platform-terraform-bastion-linux/pull/544
- https://github.com/ministryofjustice/modernisation-platform-ami-builds/pull/875
- https://github.com/ministryofjustice/modernisation-platform-configuration-management/pull/1017
- https://github.com/ministryofjustice/modernisation-platform-terraform-module-template/pull/465

- https://github.com/ministryofjustice/modernisation-platform-terraform-ecs-cluster/pull/272
- https://github.com/ministryofjustice/modernisation-platform-terraform-s3-bucket/pull/547
- https://github.com/ministryofjustice/modernisation-platform-terraform-aws-vm-import/pull/487
- https://github.com/ministryofjustice/modernisation-platform-terraform-pagerduty-integration/pull/455

- https://github.com/ministryofjustice/modernisation-platform-terraform-loadbalancer/pull/531
- https://github.com/ministryofjustice/modernisation-platform-terraform-ssm-patching/pull/488
- https://github.com/ministryofjustice/modernisation-platform-terraform-ec2-instance/pull/483
- https://github.com/ministryofjustice/modernisation-platform-terraform-ec2-autoscaling-group/pull/427

- https://github.com/ministryofjustice/modernisation-platform-terraform-lambda-function/pull/102
- https://github.com/ministryofjustice/modernisation-platform-terraform-baselines/pull/602
- https://github.com/ministryofjustice/modernisation-platform-terraform-cross-account-access/pull/434
- https://github.com/ministryofjustice/modernisation-platform-terraform-environments/pull/419

- https://github.com/ministryofjustice/modernisation-platform-terraform-iam-superadmins/pull/474
- https://github.com/ministryofjustice/modernisation-platform-terraform-member-vpc/pull/498
- https://github.com/ministryofjustice/modernisation-platform-github-oidc-role/pull/386
- https://github.com/ministryofjustice/modernisation-platform-instance-scheduler/pull/1245

- https://github.com/ministryofjustice/modernisation-platform-cp-network-test/pull/18
- https://github.com/ministryofjustice/modernisation-platform-github-oidc-provider/pull/450
- https://github.com/ministryofjustice/modernisation-platform-terraform-aws-chatbot/pull/54
- https://github.com/ministryofjustice/modernisation-platform-terraform-aws-data-firehose/pull/24

**Comment by mikereiddigital** [comment]
I'll double check tomorrow morning whether I've missed any.

**Comment by mikereiddigital** [comment]
Check done. Moving to review.

**Comment by dms1981** [comment]
Confirmed new actions release is correctly signing commits±
