### ISSUE TITLE
Format Code workflow to generate signed commits.

### ISSUE THREAD

**Issue by mikereiddigital** [ministryofjustice/modernisation-platform#7690]
### User Story

As a member of staff in the MOJ who wishes to create a PR in either the Modernisation-Platform repo or in those MP managed modules
I need any commits generated by the code formatter workflow to be signed. 
So that PRs containing these commits do not block the merging of an approved PR.

### Value / Purpose

Without this issue resolved, MP staff will need to either intervene to help the user.

### Definition of Done

- [ ] Changes identified so code formatter workflow generates signed commits.
- [ ] Changes test & confirmed as working in one of the MP-managed repositories.
- [ ] Roll out changes across all MP-managed repositories.
- [ ] Review with team & close.

**Comment by SimonPPledger** [comment]
closing as a duplicate
