### ISSUE TITLE
Set Maximum session duration for OIDC Role in AWS

### ISSUE THREAD

**Issue by ASTRobinson** [ministryofjustice/modernisation-platform#7707]
### User Story

As a user of the modernisation platform
I want to increase the maximum session duration for the OIDC role to longer than the default 1 hour
So that I can run GitHub Actions for longer than 1 hour without hitting the role timeout.

### Value / Purpose

This will help users with long-running GitHub actions like patching updates to complete jobs without hitting our AWS role configuration limits and becoming the blocker.

### Additional Information

GitHub actions have a default timeout of 6 hours.

Note: Public repositories have free GitHub Action minutes so GitHub Action minutes are only a concern if the repo is Private/Internal

Slack request & thread can be found here: https://mojdt.slack.com/archives/C01A7QK5VM1/p1723642741120779

OIDC Role - Increase Max Session Duration from 1 to 2 hours - https://github.com/ministryofjustice/modernisation-platform/pull/7682
OIDC Role - Increase Max Session Duration from 2 to 4 hour - https://github.com/ministryofjustice/modernisation-platform/pull/7704

### Definition of Done

- [x] Maximum session duration for OIDC role set to ideal duration i.e 6 hours

**Comment by dms1981** [comment]
Having discussed this in refinement, we think a 6 hour default is acceptable. If necessary we can configure custom configuration of timeouts in a later sprint.

**Comment by ASTRobinson** [comment]
Ticket reviewed. I have logged in to one of the AWS environments and confirmed that the timeout is showing as 6 hours. I am moving the ticket to done.
