### ISSUE TITLE
Adding more user information to the member json files

### ISSUE THREAD

**Issue by SimonPPledger** [ministryofjustice/modernisation-platform#7752]
### User Story

As a product manager I want to have all the information we need as easily available as possible to the team.

As a result of the Member information spike https://github.com/ministryofjustice/modernisation-platform/issues/6317 it would be ideal if we could start tagging more info in organisations so that we can query pertinent member information from one place. 
Ticket #7570 is adding the application slack channel to member json files, this ticket is to look at what else, if anything, would be useful -  eg any service urls, incident response hours, priority of the application (ie in the top x applications or not)

### Value / Purpose

This should make working on incidents easier as it could potentially allow us to prioritise but also to find all the key info we need

### Definition of Done

- [x] Investigate useful items of data
- [x] Agree within team whether this would be of benefit
- [x] Make changes required to enable application teams to add the new information

**Comment by markgov** [comment]
This is for items that can be consumed programatically and talks with Simon to get further information

**Comment by markgov** [comment]
created brainstorm session and it has been decided that this needs a separate meeting which i have setup for monday moving issue to block until after this meeting has concluded

**Comment by markgov** [comment]
need to add the following to the sprinkler json file
critical-national-infastructure

**Comment by markgov** [comment]
New Issue created for missing OPA tests
https://github.com/ministryofjustice/modernisation-platform/issues/8185

**Comment by markgov** [comment]
added new section to json file and created an opa policy test for the new section opa test currently failing investigating why

**Comment by markgov** [comment]
Need to amend all the environment json files to show the new section based on the following spreadsheet
https://docs.google.com/spreadsheets/d/1IxzkAyX_yW-2jDg3NieH5onT6N274IoNNnitAbKYFnc/edit?gid=1878908955#gid=1878908955

**Comment by markgov** [comment]
installed conftest locally using brew
ran the following command  and got

```
~/git/modernisation-platform/policies │ on feat/JSON-file-amendments *4 ▓▒░ conftest verify -p ./environments                                                 ░▒▓ 1 х │ at 16:44:54
FAIL - environments/environment-definitions_test.rego -  - data.policies.environments.test_critical_national_infastructure_empty

14 tests, 13 passed, 0 warnings, 1 failure, 0 exceptions, 0 skipped
```

**Comment by richgreen-moj** [comment]
@markgov - I fixed this for you having spent similar frustration looking at this before. See [this commit](https://github.com/ministryofjustice/modernisation-platform/commit/1e73ca1d203287b9337ee5ceb9389b6be06a8aaf)

2 issues:

1. You had the `"environments": []` in your test scenario but were testing for the absence of it so it needed to go.
2. The wording in the test has to be exactly identical to the wording in the policy or it doesn't register that they are linked.

I also fixed the typo 😸  (can talk through next week if unclear). Tests passing now!

**Comment by markgov** [comment]
Have updated the PR so that the opa test now work and also added in the filed to all environment json files this pr is the following
https://github.com/ministryofjustice/modernisation-platform/pull/8191

**Comment by markgov** [comment]
started working on the go program that pulls all this information out of the json files

**Comment by markgov** [comment]
Main Pr moved after moving the field to under the tags section and created PR to update the runbook documentation for new accounts
https://github.com/ministryofjustice/modernisation-platform/pull/8297

**Comment by markgov** [comment]
now deployed to all accounts except AP accounts and documentation pr has also been merged
