### ISSUE TITLE
LAA data platform sandbox

### ISSUE THREAD

**Issue by donovan-moj** [ministryofjustice/modernisation-platform#778]
### Application Name

LAA data platform sandbox

### Github team slug

laa-technical-architects

### Environments

- [x] Development
- [ ] Test
- [ ] Preproduction
- [x] Production

### Tags

tag | value
--- | ---
application | LAA data platform sandbox
business-unit | LAA
owner | donovan.artz@digital.justice.gov.uk

### Connectivity

would it be possible to access cloudwatch data in CP?
also, would like to expose API endpoint here to applications in LAA's AWS VPCs?

### Additional features

- [x] Bastion
- [x] Additional VPC Endpoints
- [ ] Extended DNS Zones

**Comment by davidkelliott** [comment]
Closing for now, LAA to use their existing sandpit environment for the time being.
