### ISSUE TITLE
collaborator s3 upload permissions

### ISSUE THREAD

**Issue by wullub** [ministryofjustice/modernisation-platform#7800]
### User Story

As a mod platform customer 
I need to be able to give collaborators ONLY permissions to upload artifacts to s3 - in particular the mod-platform-image-artefact-bucket20230203091453221500000001 bucket inside core-shared-services-production.
So that they can keep giving us software releases for oasys

https://mojdt.slack.com/archives/C01A7QK5VM1/p1724772031490929

### Value / Purpose

This is essential for the continuing collaboration with capita and their software

### Useful Contacts

DSO dev - William Gibbon, capita collaborator - Carl Last, oasys product manager - Howard Smith

### Definition of Done

- [x] s3-operator or s3-uploader role created
- [x] Carl Last (CarlDevCap) ,  Martin Hiorns (martinhiorns-capita) , Morgan Boniface (morgan-boniface) added as collaborators and given the role
- [ ] Confirm a collaborator can upload to mod platform artifact bucket

**Comment by dms1981** [comment]
Creating SSO roles can be seen here: https://user-guide.modernisation-platform.service.justice.gov.uk/runbooks/adding-a-new-sso-user-role.html

However, it's worth having a think about what we're doing here. This might be more of a `modernisation-platform` scope where we add this in our bootstrap code and create a role across the MP member accounts? Have a look at how collaborators presently assume a role in a member account and work out from there what's required to create a role scoped to S3.
