### ISSUE TITLE
Issue on new-environments.yml

### ISSUE THREAD

**Issue by SteveLinden** [ministryofjustice/modernisation-platform#7804]
### Expected Behavior

The routine should run without issue - failed on the deployment of https://github.com/ministryofjustice/modernisation-platform-environments/pull/7634

### Actual Behavior

It comes up with an error (below) which should not happen.

```
Run files=$(git diff --name-only --diff-filter=AM @^ -- 'environments/*.json' | uniq | sed 's#environments/##' | sed 's/\.json$//' | base64 )
Error: Unable to process file command 'output' successfully.
Error: Invalid format 'ZXh0Y2xvdWQK'
```
### Steps to Reproduce the Problem

Run the above PR.

**Comment by SteveLinden** [comment]
Example error (from the revert of the above code)
https://github.com/ministryofjustice/modernisation-platform/actions/runs/10631217325/job/29472804617#step:6:17

**Comment by SimonPPledger** [comment]
I believe this is no longer required - but @SteveLinden can you confirm - and add a description of what was required

**Comment by SimonPPledger** [comment]
This was fixed separately
