### ISSUE TITLE
Investigate management/monitoring of root account/codebase

### ISSUE THREAD

**Issue by richgreen-moj** [ministryofjustice/modernisation-platform#7824]
### User Story

As a MP engineer
I want to investigate how we are going to manage/monitor the root account/codebase
So that we have clear processes in place

### Value / Purpose

This ticket is needed to investigate what processes/procedures need to be put in place for when MP take over more responsibility for the root account and codebase 

Things to consider:

- What is being managed?
- How are issues managed?
- Who manages it currently and what are the working processes?
- What permissions are required to carry out actions in root account?

### Definition of Done

- [x] Carry out investigation
- [x] Document findings
- [x] Discuss current processes with root account working group to identify any issues
- [x] Discuss findings with team
- [x] Write follow-up stories or any agreed documentation

**Comment by Kudzai-moj** [comment]
https://docs.google.com/document/d/1PclgktSalrR6kPznQenAV-olnrxxLjvMVCxDcE2OLWk/edit#heading=h.ujp9662uvfg5

**Comment by Kudzai-moj** [comment]
**Tickets raised**

Permissions Review for Mod Platform Engineering role - #8205

**Comment by Kudzai-moj** [comment]
I have raised tickets that are required for now. Will ensure we refine one ticket from current root account kanban board tomorrow in refinement meeting.

https://github.com/orgs/ministryofjustice/projects/17/views/1?pane=issue&itemId=80208732

**Comment by Kudzai-moj** [comment]
I have created new document for root account, raised tickets that are needed for now and made sure we start pulling kanban tickets in our refinement session. This ticket should be ok to close pending review

**Comment by mikereiddigital** [comment]
Hi @Kudzai-moj has the last DoD item been completed? If so I will review :)

**Comment by SimonPPledger** [comment]
The tickets have been raised - moving to done
