### ISSUE TITLE
Tunnel endpoint lifecycle control & alerting for NOMS-Transit-Live-VPN

### ISSUE THREAD

**Issue by richgreen-moj** [ministryofjustice/modernisation-platform#7833]
### User Story

As an engineer/application owner
I want to be notified when there is scheduled maintenance for the NOMS-Transit-Live-VPN
So that I have an opportunity to deconflict the maintenance work with data-load jobs 

### Value / Purpose

There are regular data-load jobs occurring for the applications that depend on the NOMS-Transit-Live-VPN between AWS/Azure. These take a long time (2hrs plus) and when AWS carries out maintenance on one of the tunnels it's enough to negatively impact the job (i.e. the legacy application behind this cannot cope with that).

Having raised an issue with AWS they have suggested the use of tunnel endpoint lifecycle control so that maintenance work can be advertised via health alerts and then give application owners a chance to deconflict this work with the data-load jobs.

This ticket would enable this feature and add alerting to the relevant teams when this work is being carried out. Further details in the slack chat link provided below.

### Useful Contacts

@robertsweetman @richgreen-moj

### Additional Information

Slack conversation this originated from... https://mojdt.slack.com/archives/C01A7QK5VM1/p1725436120844999?thread_ts=1724852177.759589&cid=C01A7QK5VM1

https://docs.aws.amazon.com/vpn/latest/s2svpn/tunnel-endpoint-lifecycle.html

https://docs.aws.amazon.com/health/latest/ug/cloudwatch-events-health.html

### Definition of Done

- [x] Enable tunnel endpoint lifecycle control for the NOMS-Transit-Live-VPN 
- [x] Subscribe to AWS Health notifications for upcoming tunnel endpoint replacements (Using eventbridge rule)
- [x] Set up alerts by creating an SNS topic and AWS chatbot and deliver to relevant channels - use #dba_alerts_prod 
- [x] Notify teams that alerting is in place

**Comment by SimonPPledger** [comment]
Had a quick chat with Robert Sweetman - and will pull into this sprint as it is impacting production reporting

**Comment by richgreen-moj** [comment]
https://github.com/ministryofjustice/modernisation-platform/pull/7848 << draft PR raised to enable the required changes. I am waiting to hear back from the team on an acceptable time to apply this change as it will cause a brief outage to the VPN as the new settings are applied.

**Comment by richgreen-moj** [comment]
Tunnel endpoint lifecycle control is enabled. I've also set up some alerting to notify members of the #dba_alerts_prod channel when we receive health alerts regarding the NOMIS VPN.

We've not yet received a health alert to fully test this setup and I might ask AWS if they are able to spoof one just so we can check the setup is working.

**Comment by richgreen-moj** [comment]
Support case raised to get test health alert sent: https://support.console.aws.amazon.com/support/home?region=eu-west-2#/case/?displayId=172587225800992&language=en

**Comment by richgreen-moj** [comment]
Looks like you can only get a sample health event that is not specific to a resource ID so I can't test this exactly although I have done some tests in the console to verify that my eventbridge rule pattern should match a health event containing a specific resource.

I think the work is complete for this ticket and we can either leave on hold and wait to see if we get an event in the near future or I'll just keep monitoring it and we can address any issues if they arise.

**Comment by richgreen-moj** [comment]
Next time we get an alert advertising a VPN tunnel replacement (this should be an email to our inbox and 🤞 an alert to #dba_alerts_prod) then I imagine the process will be someone from the application team will contact ask channel to arrange accepting a tunnel replacement manually at a convenient time.

**Comment by ASTRobinson** [comment]
ticket reviewed and all requirements met. however, I guess we won't truly know until the alert fires but for now, moving to done and if there are any issues when the alert does trigger this ticket could revisited.
