### ISSUE TITLE
Enable AWS Organisations integration to link root account with Cortex XSIAM

### ISSUE THREAD

**Issue by richgreen-moj** [ministryofjustice/modernisation-platform#7897]
### User Story

As a SOC engineer
I want to enrich the information in security alerts in Cortex XSIAM
So that I have more detailed information e.g. can identify which application/owner is affected

### Value / Purpose

Following some engagement with the SOC in https://github.com/ministryofjustice/modernisation-platform/issues/7605 it was decided that we should explore using the AWS Organisations Integration to link the root account (MOJ Master) with Cortex XSIAM as the SOC feel this would better enrich the info in the alerts they are getting for AWS accounts.

### Useful Contacts

@ashwinmoj @richgreen-moj @davidkelliott 

### Additional Information

- AWS Orgs Integration docs: https://xsoar.pan.dev/docs/reference/integrations/aws---organizations

- For instructions on setting up integrations, see [AWS Integrations - Authentication](https://xsoar.pan.dev/docs/reference/articles/aws-integrations---authentication#configuration-using-access-key-and-secret-key)

- We should consider the impact of integrating with XSIAM, and do if appropriate. 

- Careful consideration should be given on the permissions provided (i.e. limit to read-only "list" type actions)

For more context contact Ashwin John [ashwinmoj](https://github.com/ashwinmoj)

This will also require input from the root account team  #aws-root-account in slack

### Definition of Done

- [x] Review docs and best way to enable the integration
- [x] Decide on appropriate permissions to be given 
- [x] Create relevant infra in the root account (user/roles etc.)
- [x] Work with SOC/Ashwin to enable the integration in Cortex Xsiam (handover credentials)
- [x] Verify that the SOC are able to query the API through the integration
- [x] Update any documentation as required

**Comment by ashwinmoj** [comment]
I will be on annual leave for two weeks starting from next week and will return on September 30th. During my absence, @YasJustice/ yaasseen.aumeer@justice.gov.uk from the MIP team will be available for any assistance or inquiries related to these tickets.

**Comment by richgreen-moj** [comment]
Documentation has been reviewed. The [guide](https://xsoar.pan.dev/docs/reference/articles/aws-integrations---authentication) says:
_"When self hosted outside the AWS environment in a remote network, the AWS Integrations should use: Access Key and Secret Key authentication option."_
As Cortex XSIAM is hosted outside of AWS we will need to follow this strategy.

**Comment by richgreen-moj** [comment]
Having created a `XsoarIntegration` user in the root `moj-master` account, @ewastempel used her elevated powers to generate a set of access keys (currently held in secrets manager in MP account) so that I could share them with Yaasseen. 

We set up the integration over a teams call and Yaasseen tested it by querying the org. He was able to retrieve a list of all the AWS accounts in the organisation and their respective tags etc. directly in the XSIAM app.

As we now have over two sets of long-lived access credentials shared with XSIAM (this one in root account and another in core-logging) it might be worth us raising an issue to think about how we manage these on an on-going basis e.g. being alerted to manually rotate them on a regular basis and potentially storing them centrally (e.g. MP account) and updating the trust relationship on roles in the various accounts they need to access.

**Comment by richgreen-moj** [comment]
Follow-on issue raised to look at long term management of credentials https://github.com/ministryofjustice/modernisation-platform-security/issues/24

**Comment by Khatraf** [comment]
Reviewed – All criteria in the definition of done have been met, and user have confirmed that everything works as intended. I have verified that their access keys were used today and that they have been assigned read-only permissions to AWS Org so I'm happy to close this.
