### ISSUE TITLE
Automate Daily Report of Previous Day's Pipeline Failures and Notifications to Slack

### ISSUE THREAD

**Issue by sukeshreddyg** [ministryofjustice/modernisation-platform#7902]
### User Story

As a Modernisation Platform Engineer
 I want to receive a report at 9 AM every day that lists all pipeline failures from the previous day so that our team can check whether the failures have been addressed or still need attention. The report should be sent via Slack or provide a link to a Grafana dashboard, ensuring that the team can easily review pipeline status.

### Value / Purpose

* Proactively track unresolved pipeline failures from the previous day.
* Ensure visibility across the team about the health of pipelines.
* Improve operational efficiency by automating the notification process and reducing manual checks.
* Allow the team to address any issues promptly, minimizing potential disruptions.

### Definition of Done

- [x] Set up an automated process to gather a list of all pipelines that failed during the previous day.
- [x] Ensure that both newly failed and unresolved failures are captured for the previous day.
- [x] Automate sending a daily Slack message at 9 AM that either includes a link to the Grafana dashboard showing the previous day's pipeline failures or a list of failed pipelines
- [x] If there are no pipeline failures from the previous day, send a message to Slack indicating "No pipeline failures detected from the previous day."

**Comment by mikereiddigital** [comment]
Looking at this, the most straight forward approach is to have a script that:
- Gets the most recent failed action for a workflow during the past 12 hours.
- Put that list together as a json that includes a link to the actions in question
- Sends that json via the existing slack webhook for modernisation-platform.

An addition could be a Grafana report that allows the user to get all failed actions for a given time period, similar to that used for open PRs.

**Comment by mikereiddigital** [comment]
Current draft output of the slack report:
![Image](https://github.com/user-attachments/assets/c3a5dc86-5e17-4f8f-9501-09f7043dd5c9)

**Comment by mikereiddigital** [comment]
Progress so far:
1 - A script that pulls all failed workflows with no subsequent successful run from modernisation-platform for the required period (testing as 90 days but can be set to 1) and outputs that as a json file.
2 - A script that takes that json list of failed workflows and generates a json payload for slack.
3 - A short script that sends the payload to slack. 

Am testing this on one of my own repos and messages to my own slack channel. When this is tuned I will apply in mod platform.

**Comment by mikereiddigital** [comment]
This branch contains the latest working version that's been tested in my personal repo. https://github.com/ministryofjustice/modernisation-platform/tree/issue/7902

**Comment by mikereiddigital** [comment]
PR created - https://github.com/ministryofjustice/modernisation-platform/pull/8414

**Comment by mikereiddigital** [comment]
I'm happy that the merged PR covers all of the DoD requirements. I will look into a Grafana report in the Observability platform as part of my 10% time later in the week.

**Comment by Kudzai-moj** [comment]
I have reviewed and seen the Daily reports. Working as expected. Can be closed
