### ISSUE TITLE
Restrict iam:PassRole for Github OIDC role

### ISSUE THREAD

**Issue by Khatraf** [ministryofjustice/modernisation-platform#7907]
### User Story

As a Modernisation Platform engineer
I want to restrict the use of the iam:PassRole action for the OIDC role
So that the permissions are not overly permissive, and only specific roles can be passed to services

### Value / Purpose

The value of implementing this is to improve security by ensuring that iam:PassRole is only used with specific roles, reducing the risk of privilege escalation or misuse.  By adding the iam:PassedToService condition key or specifying resource ARNs, it aligns with best practices for least privilege access control.

### Additional Information

- https://docs.aws.amazon.com/IAM/latest/UserGuide/access-analyzer-reference-policy-checks.html#access-analyzer-reference-policy-checks-security-warning-pass-role-with-star-in-resource
- https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_use_passrole.html

### Definition of Done

- [ ] Update the IAM policy and ensure implementation follow security best practices
- [ ] Test and validate the policy changes to ensure they function as intended without impacting existing services.
- [ ] Another team member has reviewed
- [ ] Tests are green

**Comment by dms1981** [comment]
Having investigated this I need to reach out to some of the role users. One strand of users appear to make use of the role for ECR related tasks in build pipelines. A second strands make use of the role for environment automation tasks such as ansible playbooks.

For the first case, `iam:passrole` isn't a factor as the role is used to directly interact with ECR. For the second case I might be able to scope passrole with an `iam:PassedToService` condition so I've reached out to see what services might be in scope.

**Comment by Kudzai-moj** [comment]
I've reviewed this and am happy it's complete.

**Comment by dms1981** [comment]
https://github.com/ministryofjustice/modernisation-platform/pull/8443 << This PR also relates. Found out after we'd added the `PassedToService` condition that ECS Tasks users were negatively impacted, but this PR fixed the problem.
