### ISSUE TITLE
Create application-ci user in each member account

### ISSUE THREAD

**Issue by davidkelliott** [ministryofjustice/modernisation-platform#795]
## User Story

As an application developer
I need to have user credentials to access my AWS account
So that I can deploy my application

## Value

By adding an application-ci user to each member AWS account, it enables application teams to log in via SSO and generate credentials so that they can access their account programatically to make deployments.

## Questions / Assumptions

This should be done as part of the initial account set up (delegate access).
Users will be able to use SSO to create and rotate credentials.
Permissions for the user will allow the minimum required

## Definition of done

- [x] application-ci user created for each account
- [x] new application-ci group created
- [x] new application-ci policy created and attached to group
- [x] application-ci user added to application-ci-group
- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [x] tests are green

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by philhorrocks** [comment]
I have created the initial branch for the setup of the cicd member account. This

**Comment by philhorrocks** [comment]
This needs to be tested

**Comment by philhorrocks** [comment]
I have tested the code and the sso-baselines and delegate-access code work. There seems to be an issue related to the secure baselines module as it complaining that the guard-duty instance is already installed.

**Comment by philhorrocks** [comment]
This has been tested with the scheduled baseline workflow and seems to be working ok
