### ISSUE TITLE
Integrate ServiceNow bot with Modernisation Platform repositories

### ISSUE THREAD

**Issue by dms1981** [ministryofjustice/modernisation-platform#7951]
### User Story

As a Change and Release lead
I want to integrate ServiceNow with Modernisation Platform GitHub repositories
So that ServiceNow can track changes happening in GitHub

### Value / Purpose

As part of a wider initiative to give ServiceNow visibility into GitHub changes we've been asked to give the `operations-engineering-servicenow` GitHub account `admin` permissions for our repositories. This user account is tied to a bot.

Hopefully this is pretty simple - something like this in our [github directory](https://github.com/ministryofjustice/modernisation-platform/tree/main/terraform/github):
```
resource "github_repository_collaborator" "servicenow" {
  for_each   = toset(local.list-of-repositories)
  repository = each.key
  username   = "operations-engineering-servicenow"
  permission = "admin"
}
```

### Additional Information

The following Slack conversations are useful starting points:
* https://mojdt.slack.com/archives/C01A7QK5VM1/p1726475633280699
* https://mojdt.slack.com/archives/C01A7QK5VM1/p1726582136645589

### Definition of Done

- [ ] New account added as administrator to MP repositories
- [ ] Customer confirms ServiceNow integration

**Comment by dms1981** [comment]
On discussion with @connormaglynn we'd like to understand the requirement for `admin` access prior to implementing this.

**Comment by markgov** [comment]
Closing this issue as admin is too high access request for our repo David Elliot to reply with requester
