### ISSUE TITLE
Delete delius-mis-test

### ISSUE THREAD

**Issue by Kudzai-moj** [ministryofjustice/modernisation-platform#7965]
### User Story

Andrew Moore [requested](https://moj.enterprise.slack.com/archives/C01A7QK5VM1/p1726654493444269) that the delius-mis-test account be deleted. 

Development, preproduction and production are still needed

### Value / Purpose

Cost Saving

### Useful Contacts

Andrew Moore

### Definition of Done

- [x] Account Deleted

**Comment by ASTRobinson** [comment]
reviewed by @ASTRobinson, account successfully deleted, moving to done 🙌
