### ISSUE TITLE
Request to delete expired production certificates

### ISSUE THREAD

**Issue by mark-butler-solirius** [ministryofjustice/modernisation-platform#7992]
Hi

In relation to an issue previously discussed with David Sibley, can I please request deletion of the following expired certificates in 5 separate AWS accounts, all with the domain name **modernisation-platform.service.justice.gov.uk**? 

They are preventing deployment of updates to the 5 services because their status has been set to 'Expired' and 'Not in Use'. 

I do not seem to have sufficient privileges to manually delete them and our updated terraform does not recognise they need to be deleted.

[DACP](https://moj.awsapps.com/start/#/console?account_id=500540837707&role_name=modernisation-platform-developer)
https://eu-west-2.console.aws.amazon.com/acm/home?region=eu-west-2#/certificates/5269c4d0-98bf-4471-95a7-e490eba6681f

[NCAS](https://moj.awsapps.com/start/#/console?account_id=077274413728&role_name=modernisation-platform-developer)
https://eu-west-2.console.aws.amazon.com/acm/home?region=eu-west-2#/certificates/1609ebd0-4c12-4d75-b268-652adefa9b3f
https://eu-west-2.console.aws.amazon.com/acm/home?region=eu-west-2#/certificates/5e108407-791c-4d69-8967-1ae0edfbca90 
This account contains the expired cert and a failed cert

[PRA](https://moj.awsapps.com/start/#/console?account_id=303170019013&role_name=modernisation-platform-developer)
https://eu-west-2.console.aws.amazon.com/acm/home?region=eu-west-2#/certificates/1bf9e29a-7faa-449c-8689-588800d82779

[Tipstaff](https://moj.awsapps.com/start/#/console?account_id=017977998587&role_name=modernisation-platform-developer) 
https://eu-west-2.console.aws.amazon.com/acm/home?region=eu-west-2#/certificates/ad9bc0c1-a636-43a9-b8f1-da4d1ddfd29c

[Wardship](https://moj.awsapps.com/start/#/console?account_id=077344000950&role_name=modernisation-platform-developer) 
https://eu-west-2.console.aws.amazon.com/acm/home?region=eu-west-2#/certificates/075cf8a4-65ef-4c6e-bd64-c0873bf2051e

Thank you

**Comment by Kudzai-moj** [comment]
I have deleted the expired certificates. Waiting to hear from Mark if he can now successfully deploy then ticket will be ready to close

**Comment by Kudzai-moj** [comment]
Mark, has confirmed that all deployments worked [successfully](https://mojdt.slack.com/archives/C01A7QK5VM1/p1726840132202339). Can now be closed.

**Comment by richgreen-moj** [comment]
Reviewed. Resources destroyed and successful deployment from Mark confirmed 👍
