### ISSUE TITLE
Spike: Can we monitor and alert on IP usage

### ISSUE THREAD

**Issue by davidkelliott** [ministryofjustice/modernisation-platform#8024]
### User Story

As an MP engineer
I want to be alerted if we start to run out of IP addresses in our shared core-vpc subnets
So that I can take action to prevent hitting limits

### Value / Purpose

This will address risk 26, by being able to monitor IP addresses in use (the only shared resource that could potentially be abused) we ensure that we find out before it's too late if we start to reach the IP limit or if one application uses them excessively.

### Additional Information

Could we make use of capacity reservations - https://aws.amazon.com/about-aws/whats-new/2023/08/amazon-vpc-ip-address-utilization-metrics-aws-resources/

Or a script?

### Definition of Done

- [x] Investigate how we can monitor for the number of IPs remaining in the core vpc shared subnets (data, private and public)
- [x] Document options - this might just be one - and agree approach
- [ ] If this is easy then implement
- [ ] Otherwise raise a ticket to implement

**Comment by dms1981** [comment]
We can monitor the remaining IP addresses in VPCs and subnets through the use of `VpcIPUsage` and `SubnetIPUsage` via VPC IPAM in the organisational-security account.

Breaching alarms can then be reported through an SNS topic into AWS ChatBot or PagerDuty as appropriate.

We'd need to select a VPC IPAM scope to RAM share out to the relevant OU - probably Modernisation Platform Core - where it can be accepted and associated with our `core-vpc-production` VPCs.

CloudWatch Metric alarms would need to be configured in the `organisational-security` account.

**Comment by dms1981** [comment]
https://aws.amazon.com/about-aws/whats-new/2023/08/amazon-vpc-ip-address-utilization-metrics-aws-resources/

https://aws.amazon.com/blogs/networking-and-content-delivery/amazon-vpc-ip-address-manager-best-practices/

**Comment by dms1981** [comment]
From some light reading of the [best practices](https://aws.amazon.com/blogs/networking-and-content-delivery/amazon-vpc-ip-address-manager-best-practices/) document I would suggest two VPC IPAM scopes:
`modernisation-platform-development-test` and `modernisation-platform-preproduction-production`.

As there is no subdivision in the `Modernisation Platform Core` OU between dev-test and preprod-prod, if we're only interested in monitoring IP address utilisation in our `core-vpc-*` accounts, then RAM sharing with the relevant `core-vpc-*` accounts is the most constrained method. However, if we're interested in also monitoring IP utilisation in our other `core-*` VPCs we may as well share direct to the OU.

VPCs would then be associated with the relevant VPC IPAM scope.

Maintaining two separate scopes would allow us to be more selective in how we report our alerts - while impending address exhaustion in a dev/test VPC would be disruptive, it wouldn't potentially be service breaking like the same event in a preprod/prod VPC.

**Comment by dms1981** [comment]
I looked into this further with AWS Support. We found a parsing error around `region/Region` that has been reported back to the IPAM team which was affecting our ability to view all resources in a region. Beyond that, though, I think this one needs some rethinking in light of how metrics are passed in from IPAM to CloudWatch.

You can see the documentation here: https://docs.aws.amazon.com/vpc/latest/ipam/cloudwatch-ipam-res-util.html

An alternative that I'm exploring is enabling _Network Address Usage metric settings_ in VPCs, and tracking the `NetworkAddressUsage` metric as described here: https://docs.aws.amazon.com/vpc/latest/userguide/vpc-cloudwatch.html

**Comment by dms1981** [comment]
Network Address Usage is useful, but I don't think it's relevant to us or likely to be a concern. In our business-unit VPCs we use `/21` blocks. A VPC has a default quota of 64000 NAU units, and from the table [here](https://docs.aws.amazon.com/vpc/latest/userguide/network-address-usage.html) we'd be unlikely to come close to reach 20% of the cap.

**Comment by dms1981** [comment]
That leaves us with one final option. A lambda that publish custom metrics into CloudWatch. You can see an open source example in Python here: https://github.com/zoph-io/subnet-watcher

I'd presume we need to do something like the following:
1. Write a lambda that monitors available IP addresses in a VPC & its subnets.
2. Have that lambda publish into CloudWatch custom metric
3. Create a metric alarm for the custom metric that pipes into SNS
4. Have SNS report into Slack; via PagerDuty or Chatbot, or some other method.
