### ISSUE TITLE
🐛 Instance-Sheduler build-test-push.yml failing to run

### ISSUE THREAD

**Issue by ASTRobinson** [ministryofjustice/modernisation-platform#8027]
### Expected Behavior

The `build-test-push` GitHub action should run the go tests on pull requests to ensure no breaking changes are merged in.

### Actual Behavior

The docker image fails to build due to dependencies requiring a minimum go version of 1.21.

### Steps to Reproduce the Problem

run workflow https://github.com/ministryofjustice/modernisation-platform-instance-scheduler/blob/main/.github/workflows/build-test-push.yml

### Workaround

A temporary workaround to specify and manually install a specific Go version has been implemented here on PR https://github.com/ministryofjustice/modernisation-platform-instance-scheduler/pull/1216 

### Proposal / Suggestions

use one of the [official Go Docker images](https://hub.docker.com/_/golang) for the build process 🐳 It'd save us having to manually install Go - and dependabot should be able to raise PRs to bump the docker image version, which will bump the Go version

also of note: but it looks like [lambda/go:1 is being deprecated](https://aws.amazon.com/cn/blogs/compute/migrating-aws-lambda-functions-from-the-go1-x-runtime-to-the-custom-runtime-on-amazon-linux-2/) in favor of lambda/provided:al2 🧓 🐳

**Comment by richgreen-moj** [comment]
With this [PR](https://github.com/ministryofjustice/modernisation-platform-instance-scheduler/pull/1241) I've removed the need to install go at the "builder" stage and instead have used the `golang` base image to simplify the process.

It also replaces the base image of the final container with `lambda/provided:al2` as `lambda/go:1` is being deprecated.

This is merged into main and the workflow is working and passing tests. Over time the `golang` docker image should be kept up to date by dependabot in tandem with the other go dependencies that are being updated.

**Comment by mikereiddigital** [comment]
Looks good to me. @richgreen-moj if you create a ticket to have the golang docker version added to dependabot I will move it to done :)
