### ISSUE TITLE
SPIKE: Member Logging analysis

### ISSUE THREAD

**Issue by davidkelliott** [ministryofjustice/modernisation-platform#803]
## User Story

As a modernisation platform engineer 
I need to understand logging needs and options
So that I can build a logging platform

## Value

We need a way to access logs for the platform, and our users to access their application infrastructure, and application logs.

This ticket is probably linked, and could be closed pending the result of this spike

## Questions / Assumptions

We should reuse / align with other MoJ areas where possible.

## Definition of done

- [ ] Analysis on logging options on the market
- [ ] Analysis of logging options within the moj currently available
- [ ] Discussion with other areas of the MoJ / Operations Engineering on any areas which could be reusable
- [ ] Options paper with solutions that we should spike to inform a decision.
- [ ] another team member has reviewed

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by davidkelliott** [comment]
Spoke with David Read, Cloud Platform is looking to move Elastic to Loki, it's on their roadmap for early next year. https://github.com/ministryofjustice/cloud-platform/blob/main/architecture-decision-record/023-Logging.md

**Comment by davidkelliott** [comment]
We have decided to continue with the centralisation of the platform logging, but put the member logging centralisation on hold for the moment until we better understand the needs of users.  We are working closer with cloud platform now and hope to find a common solution with them or operations engineering.

**Comment by dms1981** [comment]
Is this worth bringing back up in light of us having a user researcher? (Hello @ScottSeaward !)

**Comment by dms1981** [comment]
Closed this one in light of the existence of Observability Platform's existence
