### ISSUE TITLE
Remove .terraform.lock.hcl files from the repository and add to the ignore file.

### ISSUE THREAD

**Issue by davidkelliott** [ministryofjustice/modernisation-platform#805]
## User Story

Remove `.terraform.lock.hcl` files from the modernisation-platform repository and add to the .gitignore file

## Value

Because we are running our Terraform on pipelines, this file never gets committed unless we run the Terraform locally.  We should remove this from the repo and rely on the versioning in the `versions.tf` file.  If we want something to not go above a certain version we should use ~> rather than =>

See here for more info on Terraform versioning - https://www.terraform.io/docs/language/expressions/version-constraints.html
See here for example of it added to the .gitignore file - https://github.com/ministryofjustice/modernisation-platform-environments/blob/main/.gitignore#L7

## Definition of done

- [ ] .terraform.lock.hcl files removed from repository
- [ ] .terraform.lock.hcl added to .gitignore

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by SteveLinden** [comment]
Removed the .terraform.lock.hcl files and added that to the gitignore file.
Pushed the change up as Remove_.terraform.lock.hcl_files

**Comment by SteveLinden** [comment]
Pull request created. All checks passed.

**Comment by SteveLinden** [comment]
Merged to master.
