### ISSUE TITLE
Integrating AWS Security Hub Alerts into Slack via PagerDuty for High and Critical Findings

### ISSUE THREAD

**Issue by sukeshreddyg** [ministryofjustice/modernisation-platform#8076]
### User Story

As a security engineer, I need to set up an automated system that sends high or critical severity findings from AWS Security Hub in individual member accounts to Slack via PagerDuty. The solution should be deployed using our Baseline Module, ensuring that the security alerts follow predefined automation and infrastructure standards. The system must update the status of findings to `Notified` once they are processed.

### Value / Purpose

This solution will enhance the team's visibility into critical security issues across all AWS accounts within MP OU . By filtering and sending only high or critical severity findings to Slack through PagerDuty, it will prevent alert fatigue, improve incident response times, and ensure that findings are properly tracked with updated statuses. 

### Additional Information

**Architecture:** Based on the provided architecture diagram, each member account uses AWS EventBridge and SNS to capture Security Hub findings. A Lambda function is then used to updating the Security Hub finding's workflow status to "Notified" upon successful notification.
**Slack Integration:** A separate Slack channel should be created to handle these alerts, ensuring that only relevant high/critical findings are posted for quick action.

![architecture2](https://github.com/user-attachments/assets/f9c3acf3-fae6-450b-9642-d093bc1f0cc3)

### Definition of Done

- [x] Implement the architecture using the Baseline Module, ensuring that AWS Security Hub findings are processed and sent from each member account to PagerDuty, then to Slack.
- [ ] Once a finding is sent to PagerDuty, the Lambda function should update the finding's workflow status to **Notified** in AWS Security Hub.
- [x] Create and configure a dedicated Slack channel where high and critical alerts from PagerDuty will be posted.
- [ ] Test the entire workflow by generating findings of various severities and verifying that only high/critical findings are forwarded and the workflow status is updated correctly.

**Comment by SimonPPledger** [comment]
We have decided not to progress with this - at least for now - so closing

**Comment by richgreen-moj** [comment]
Branch created on baselines module to add eventbridge rule and sns topic... https://github.com/ministryofjustice/modernisation-platform-terraform-baselines/compare/main...feature/8076-sec-hub-slack-alerting#

**Comment by richgreen-moj** [comment]
I tested raising alerts in pagerduty by running some local TF against the Sprinkler env. These are detailed in https://github.com/ministryofjustice/modernisation-platform/pull/8283

Here's a sample of the alert received:
https://mojdt.slack.com/archives/C02PFCG8M1R/p1729257726772899

This was for one test security group i created with port 22 open. Interestingly that one action seems to have raised about 8 alerts as we have multiple standards enforcing the same type of rule. This is potentially something we might want to look at suppressing in a future ticket.

Next steps are to either apply this properly everywhere or decide on whether it needs a dedicated channel etc.

**Comment by richgreen-moj** [comment]
Update on progress:

- I've updated the [baselines module](https://github.com/ministryofjustice/modernisation-platform-terraform-baselines/blob/main/modules/securityhub/main.tf#L66-L231) to include an EB rule which matches Security Hub events that are `HIGH` or `CRITICAL` which triggers an SNS topic that is connected to PagerDuty.
- I've implemented a new dedicated PagerDuty service for [Security Hub](https://moj-digital-tools.pagerduty.com/service-directory/PN4O28R) 
- I've implemented a dedicated slack channel [#modernisation-platform-security-hub-alerts](https://moj.enterprise.slack.com/archives/C07SNBJBVC6) to receive the alerts when any new security hub findings are raised (which match the associated EventBridge rule)

Observations:

- We are getting a lot of alerts! Too many to concentrate on. I've raised a follow-up ticket https://github.com/ministryofjustice/modernisation-platform/issues/8325 to tune the alerts as I've noticed some patterns that are causing duplications e.g. common rules in the different standards that we've applied
- I raised a [support case](https://support.console.aws.amazon.com/support/home?region=eu-west-2#/case/?displayId=172960348000566&language=en) about this with AWS. They have suggested why we might be seeing so many alerts...

  1. We have config rules enabled which continually check some of the standards that are applied in SecurityHub so these will trigger the EB rule even though they are for something that was first noticed in the past
  2. We can use [Security Hub automations](https://aws.amazon.com/blogs/security/aws-security-hub-launches-a-new-capability-for-automating-actions-to-update-findings/) to update details on findings without the need for Lambda functions etc.

**Comment by richgreen-moj** [comment]
Link to a related root account issue [#857 Investigate enabling central configuration in security hub](https://github.com/ministryofjustice/aws-root-account/issues/857)

**Comment by richgreen-moj** [comment]
I've not implemented a Lambda function to update workflow statuses as I feel the changes in the ticket raised above could significantly impact the way Security Hub findings are managed across the platform. I think perhaps now it's better to look at these tickets and then re-visit everything that has been applied so far.

**Comment by ASTRobinson** [comment]
Ticket was reviewed and I can confirm the alerts are going to the newly created slack channel and accept the justification regarding the lambda function not being implemented as yet but follow-up tickets have been created to address outstanding work required. I am therefore moving ticket to closed.
