### ISSUE TITLE
Terratest failing in modernisation-platform-terraform-lambda-function.

### ISSUE THREAD

**Issue by mikereiddigital** [ministryofjustice/modernisation-platform#8146]
### Expected Behavior

Terratest should run without errors.

### Actual Behavior

Link to the error in question - https://github.com/ministryofjustice/modernisation-platform-terraform-lambda-function/actions/runs/11146181204/job/30979083841?pr=102#step:6:1058

### Steps to Reproduce the Problem

- Run the terratest workflow by creating a new PR for an unrelated change.
- Test should fail with a similar error

### Modules

modernisation-platform-terraform-lambda-function

**Comment by dms1981** [comment]
We think issue has been resolved - @ASTRobinson ; can you confirm?

**Comment by ASTRobinson** [comment]
yes this issue is resolved, the docker image which the test uses has been fixed in the below PR:

https://github.com/ministryofjustice/modernisation-platform-instance-scheduler/pull/1246
