### ISSUE TITLE
Review Testing Strategy for Instance Scheduler Module

### ISSUE THREAD

**Issue by richgreen-moj** [ministryofjustice/modernisation-platform#8161]
### User Story

As a MP Engineer
I expect the tests on the Instance Scheduler module to be representative of the environment that it will be run in
So that i have confidence when making changes/maintenance to the module

### Value / Purpose

We recently made some [maintenance updates](https://github.com/ministryofjustice/modernisation-platform-instance-scheduler/pull/1241) to the container build in the [instance scheduler]( https://github.com/ministryofjustice/modernisation-platform-instance-scheduler) module and the status checks/unit tests [passed](https://github.com/ministryofjustice/modernisation-platform-instance-scheduler/actions/runs/11125188540) successfully.

We subsequently found that there was an issue with the container when it was run in the unit tests for the [lambda function](https://github.com/ministryofjustice/modernisation-platform-terraform-lambda-function/tree/main) module as can be seen in [this example](https://github.com/ministryofjustice/modernisation-platform-terraform-lambda-function/actions/runs/11146181204/job/30980851633#step:6:1048) 

```
│ Error: invoking Lambda Function (instance-scheduler-lambda-function-114): {"errorType":"Runtime.ExitError","errorMessage":"RequestId: 075fdbb1-d817-42eb-a662-165f3f7f5610 Error: Runtime exited with error: exit status 127"}
│ 
│   with aws_lambda_invocation.test_invocation,
│   on main.tf line 152, in resource "aws_lambda_invocation" "test_invocation":
│  152: resource "aws_lambda_invocation" "test_invocation" {
│ 
╵}
    apply.go:15: 
        	Error Trace:	/home/runner/work/modernisation-platform-terraform-lambda-function/modernisation-platform-terraform-lambda-function/test/apply.go:15
        	            				/home/runner/work/modernisation-platform-terraform-lambda-function/modernisation-platform-terraform-lambda-function/test/module_test.go:20
        	Error:      	Received unexpected error:
        	            	FatalError{Underlying: error while running command: exit status 1; ╷
        	            	│ Error: invoking Lambda Function (instance-scheduler-lambda-function-114): {"errorType":"Runtime.ExitError","errorMessage":"RequestId: 075fdbb1-d817-42eb-a662-165f3f7f5610 Error: Runtime exited with error: exit status 127"}
        	            	│ 
        	            	│   with aws_lambda_invocation.test_invocation,
        	            	│   on main.tf line 152, in resource "aws_lambda_invocation" "test_invocation":
        	            	│  152: resource "aws_lambda_invocation" "test_invocation" {
        	            	│ 
        	            	╵}
        	Test:       	TestLambdaCreation
```

The purpose of this story is to investigate why the tests on the instance scheduler repo are not replicant of the ones in the lambda function module as the container build updates which were made caused the instance scheduler to fail the next time it was triggered.

### Useful Contacts

@richgreen-moj @ASTRobinson @connormaglynn

### Definition of Done

- [x] Review testing strategy to see if any improvement can be made
- [x] Carry out any identified improvements
- [ ] Update any documentation as required

**Comment by ASTRobinson** [comment]
Following an investigation into several testing options—including creating new Go tests and adding a Lambda function unit test to replicate the initial failure cases (see [test suite](https://github.com/ministryofjustice/modernisation-platform-terraform-lambda-function/tree/main/test)) - I found that the SAM CLI, already being used for build and validation, can also invoke AWS Lambda functions locally. This allowed us to leverage the [SAM local invoke](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-cli-command-reference-sam-local-invoke.html) command for local Lambda testing.

Examples of SAM invoke tests:

- [Successful SAM invoke test](https://github.com/ministryofjustice/modernisation-platform-instance-scheduler/actions/runs/11682558642/job/32529929402)
- [Failing SAM invoke test](https://github.com/ministryofjustice/modernisation-platform-instance-scheduler/actions/runs/11681879279/job/32527843077)

A key issue I encountered was that GitHub Actions reports a successful exit code for the SAM CLI command even if the Lambda invocation fails (similar issue detailed here: [GitHub issue](https://github.com/aws/aws-sam-cli/issues/1081)). To address this, I implemented a workaround that captures the SAM output as a variable and checks for errors using grep.

**Comment by ASTRobinson** [comment]
above PR merged in and checked tests are running correctly. moving over for review

**Comment by mikereiddigital** [comment]
I've reviewed this and am happy it's complete.
