### ISSUE TITLE
Understanding The Modernisation Platforms Carbon Footprint

### ISSUE THREAD

**Issue by SimonPPledger** [ministryofjustice/modernisation-platform#8168]
### User Story

As a product manager I want to know what the carbon footprint of the modernisation platform is.
We have been provided with a few open source providers of tools that could measure the footprint.

https://www.apptio.com/products/cloudability/ (IBM)
https://greenpixie.com/  Amazon recommend them over Cloudablity
https://sopht.com/en/ 

This ticket is to look at https://greenpixie.com/   in the first instance and understand:
What it would report on
what it would not work for
what we would need to do to make use of it

It may be useful to compare it to the other suggestions if time allows

This is to cover AWS elements of modernisation platform - including applications

### Value / Purpose

By knowing what the carbon footprint is we can then look at what we can do to reduce it in a measurable way. The plan is we would then use this as a metric for the team.
Reducing the carbon footprint is likely to save money, however we should clearly be looking to reduce carbon footprint anyway

### Useful Contacts

julien.nioche@digital.justice.gov.uk

### Definition of Done

- [x] Document produced outlining points above
- [x] Document presented to the team
- [x] New tickets created if we want to proceed or
- [x] netw tickets created to look at other options if necessary

**Comment by Kudzai-moj** [comment]
Done some background reading into Green Ops and the above solutions.

I have emailed green pixie and sopht for more details and potential demo that i can present to the team for both solutions.

The IBM solution is for Fin Ops and not Green Ops

**Comment by Kudzai-moj** [comment]
Document with findings - https://docs.google.com/document/d/17wdbMib1Oc0Pg-UfUtL1I_dyKSjIV_0oHmaVZL-5k5Y/edit?tab=t.0

**Comment by Kudzai-moj** [comment]
Have a meetings with reps from green pixie and sopht today.

Also had a chat with Julien Nioche and he sent me the links below to have a read

https://www.linkedin.com/pulse/environmental-impact-cloud-common-crawl-case-study-julien-nioche-at8xf

https://podcasts.castplus.fm/e/m849x5pn-7-cameron-casher-and-benjamin-davy-cloud-carbon-footprint-sustainability-aws-gcp-azure-vs-aws-azure-and-gcp-sustainability-dashboards

https://www.cloudcarbonfootprint.org/

https://learn.greensoftware.foundation/

https://podcasts.castplus.fm/e/m849x5pn-7-cameron-casher-and-benjamin-davy-cloud-carbon-footprint-sustainability-aws-gcp-azure-vs-aws-azure-and-gcp-sustainability-dashboards

https://www.cloudcarbonfootprint.org/

https://learn.greensoftware.foundation/

**Comment by Kudzai-moj** [comment]
Turns out i was wrong. IBM does does provide Greenops services. I have a meeting with them today

**Comment by Kudzai-moj** [comment]
[About Sopht 2024.pdf](https://github.com/user-attachments/files/17677027/About.Sopht.2024.pdf)

**Comment by Kudzai-moj** [comment]
Greenpixie vs AWS

**Comment by Kudzai-moj** [comment]
I have raised ticket [#8463](https://github.com/ministryofjustice/modernisation-platform/issues/8463) as an output this ticket. Simon has confirmed that ticket can now be closed
https://mojdt.slack.com/archives/C013RM6MFFW/p1731337566881729?thread_ts=1731323183.737909&cid=C013RM6MFFW
