### ISSUE TITLE
Add Linters to Root Account

### ISSUE THREAD

**Issue by Kudzai-moj** [ministryofjustice/modernisation-platform#8206]
### User Story

Follow up ticket from #7824

As a Modernisation Platform Engineer

I need/want/expect to Add linters to Root Account Code base

So that we maintain code quality

### Value / Purpose

Adding Linters will ensure that our code adheres to best practices and coding standards, enforce a consistent coding style and  enables us to catch errors early

### Definition of Done

- [ ] Review of Current Code to See where linting needs to be added
- [ ] Add linting to code base
- [ ] Create Additional tickets if required

**Comment by dms1981** [comment]
MOJ [AWS Root Account](https://github.com/ministryofjustice/aws-root-account/) already has a linter job here: https://github.com/ministryofjustice/aws-root-account/actions/workflows/mega-linter.yml
