### ISSUE TITLE
🧱 Break Down #8078 Into Smaller Issues

### ISSUE THREAD

**Issue by connormaglynn** [ministryofjustice/modernisation-platform#8224]
### User Story

As a Modernisation Platform Engineer
I need/want/expect to have reasonable units of work to complete issue #8078 
So that each issue can be sized and refined individually and appropriately planned into sprints

### Value / Purpose

During refinement of #8078 the team decided that the issue was too large and needed to be broken down into smaller tasks.

The purpose of this ticket is to do an initial investigation into how to complete the work of #8078 and create further sub-tasks for the implementation of a solution.

### Useful Contacts

@connormaglynn

### Additional Information

NA

### Definition of Done

- [ ] We have a proposed solution for #8078
- [ ] If appropriate, further sub-issues have been created for #8078 to implement the solution

**Comment by davidkelliott** [comment]
Keeping main issue for the main mp repo, envs repo issue created here - https://github.com/ministryofjustice/modernisation-platform-security/issues/34
