### ISSUE TITLE
Create new environment

### ISSUE THREAD

**Issue by ross75** [ministryofjustice/modernisation-platform#8231]
### Environment details

Testing environment for cica-copilot please. Development account already exists.

### Application Name

cica-copilot

### Description of application

Application will be to use Claude in Bedrock to be the backbone of an app in Cloud Platform for analysis \ search of operational documentation. Sandbox as Bedrock unable to be terraformed as yet. Exclude from nuke please.

### SSO Group Name

cica-copilot-llm-maintainers

### GitHub code owner team slug

cica-copilot-llm-maintainers

### GitHub actions reviewer team slug

cica-copilot-llm-maintainers

### Environments

- [ ] Development
- [x] test
- [ ] Preproduction
- [ ] Production

### Environment access level Test

sandbox

### application

cica-copilot

### business-unit

CICA

### infrastructure-support

infrastructure@cica.gov.uk

### owner

infrastructure@cica.gov.uk

### Subnet sets

- [x] General
- [ ] Isolated

### How do users connect to the application

Over the public internet

### Additional features

Please check any additional features required
- [ ] Additional VPC Endpoints
- [ ] Extended DNS Zones
- [x ] Other - please specify Please exclude from nuke 

### Definition of Done

Definition of Done
- [ ] account created
- [ ] customer informed

**Comment by Khatraf** [comment]
CICA-copilot already has a development account with sandbox permissions, and a bedrock policy is attached to it. Test environments aren't typically intended for sandbox access or clickops operations so waiting to hear back from requestor to see if they can use their dev account to perform their tasks.

**Comment by ross75** [comment]
Thanks Khatra, have discussed and happy to continue using existing sandbox environment.
