### ISSUE TITLE
Create Reusable Workflows in a Central Repository

### ISSUE THREAD

**Issue by richgreen-moj** [ministryofjustice/modernisation-platform#8236]
### User Story

As a MP Engineer
I want to create a set of reusable workflows in a central repository 
So that I reduce duplication/maintenance of repetitive code

***Not fully agreed when presented as part of the SPIKE but on the backlog for consideration if it makes sense in future**

### Value / Purpose

As part of the [reusable workflow spike](https://github.com/ministryofjustice/modernisation-platform/issues/7108) the following workflows were identified as potential candidates for being converted to reusable workflows and hosted in a central repo:

- [code-scanning.yml](https://github.com/ministryofjustice/modernisation-platform-terraform-module-template/blob/main/.github/workflows/code-scanning.yml)
- [documentation.yml](https://github.com/ministryofjustice/modernisation-platform-terraform-module-template/blob/main/.github/workflows/documentation.yml)
- [format-code.yml](https://github.com/ministryofjustice/modernisation-platform-terraform-module-template/blob/main/.github/workflows/format-code.yml)
- [go-terratest.yml](https://github.com/ministryofjustice/modernisation-platform-terraform-module-template/blob/main/.github/workflows/go-terratest.yml)
- [scorecards.yml](https://github.com/ministryofjustice/modernisation-platform-terraform-module-template/blob/main/.github/workflows/scorecards.yml)
- [terraform-static-analysis.yml](https://github.com/ministryofjustice/modernisation-platform-terraform-module-template/blob/main/.github/workflows/terraform-static-analysis.yml)

All the maintenance for these repos could then be localised to this central account e.g. dependabot updates and any other changes. We could then make regular releases (e.g. weekly) and dependabot would update all the calling workflows in the module repositories to keep them in sync.

**Benefits**

- These workflows are part of the [Terraform Module template](https://github.com/ministryofjustice/modernisation-platform-terraform-module-template/tree/main/.github/workflows) and so they are replicated across all of our modules (roughly 28).

- This means we are maintaining around 168 workflows vs 6.

- Dependabot is raising multiple duplicate PRs for updating a total of 25 GitHub actions living inside these workflows which requires extra time/maintenance from engineers. (700 dependabot updates vs 25) 

- When we want to make changes to these workflows we need to raise 28 x PRs to make the changes whereas with this method we'd make the change once and then let dependabot sync the remote repositories. The unit tests local to the repositories would ensure compatibility before these changes are merged.

### Useful Contacts

@richgreen-moj

### Definition of Done

- [ ] Create new repo
- [ ] Create reusable workflows (including parameters for unique inputs)
- [ ] Update module repos to call reusable workflows
- [ ] Update module `dependabot.yml` files to keep reusable workflows up to date
- [ ] Establish release cycle for central repository
- [ ] Update documentation

**Comment by kcbotsh** [comment]
Will not be progressed at this point after team discussion
