### ISSUE TITLE
Create alarms for Cortex SQS queues

### ISSUE THREAD

**Issue by dms1981** [ministryofjustice/modernisation-platform#8248]
### User Story

As a SOC PM team member
I want to be alerted when my application is not pickup up queue messages
So that I can troubleshoot my application

### Value / Purpose

Cortex XSIAM polls our SQS queues to find out when new logs are written to S3 buckets.

When Cortex XSIAM does not properly process objects, queue messages can build up - either waiting to be picked up or left in-flight.

If we set up some monitoring and alert the SOC Protective Monitoring team they can be notified of potential issues.

### Additional Information

We haven't asked the SOC Protective Monitoring team if they'd like us to put this in, or how best to deliver an alert message.

### Definition of Done

- [x] SOC Protective Monitoring team engaged
- [x] Cloudwatch monitoring set up
- [x] Alert notification set up
- [x] Testing carried out (EG, with a threshold of `1` on the monitors)

**Comment by mikereiddigital** [comment]
Contacted Adrian Warman who is head of the Soc team (according to the org chart that DE circulated). Will also talk to Leonardo.

**Comment by mikereiddigital** [comment]
Looking at the queues themselves, each has a message retention period of 4 days before queued items drop off and are lost. I suggest that we use a metric of 8 hours as the threshold for the alarm. That way there is over 3 1/2 days to resolve the issue whilst avoiding a too low a threshold whereby normally busy periods are treated as exceptions. I will set this period as a local so it can be amended for tuning purposes.

**Comment by mikereiddigital** [comment]
PR created with the alarms, sns topics & policies, kms key & policy and chatbots for each slack channel. https://github.com/ministryofjustice/modernisation-platform/pull/8503

**Comment by mikereiddigital** [comment]
Moving to blocked whilst I wait for a response from Tom.

**Comment by mikereiddigital** [comment]
No response. Have added mod platform low priority alarms via this PR. https://github.com/ministryofjustice/modernisation-platform/pull/8586 to alert us in the event an issue arises with a build up of unclaimed messages.

**Comment by mikereiddigital** [comment]
Agreed at standup that we won't continue to wait for the channel id. Instead we will apply the change as and when the details are provided.
