### ISSUE TITLE
Can we allow members to add their own Terraform providers?

### ISSUE THREAD

**Issue by dms1981** [ministryofjustice/modernisation-platform#8272]
### User Story

As a Modernisation Platform Customer
I need to add providers to my `terraform { required_providers { ... } }`
So that I can supply providers that my code requires

### Value / Purpose

Modernisation Platform customers have an ongoing need to manage their own terraform code, including specifying their own providers and versions. At present the only location that they can specify the relevant `providers` is in the `platform_versions.tf` file which is created from a standard template.

There is a risk that this file can be overwritten by a script in the Modernisation Platform repository - [replace-platform-files-with-templates.sh](https://github.com/ministryofjustice/modernisation-platform/blob/main/scripts/replace-platform-files-with-templates.sh).

We should find a way to allow customers to specify their own providers as they require.

### Definition of Done

- [x] Assess possible options
  - [x] Should we refactor `platform_versions.tf` to `versions.tf` and update our templates?
  - [x] Should we just remove `platform_versions.tf` from the overwrite script?
  - [x] Would we need to update the CODEOWNERS file to allow customer management without our oversight? 
- [x] Chosen option implemented

**Comment by dms1981** [comment]
I think it's worth pointing out here that customers can define providers separately in modules, so keeping this gated doesn't give us the control that we might think it does. Personally I think this should be open to customers to adjust as their infrastructure requires.

**Comment by dms1981** [comment]
https://github.com/ministryofjustice/modernisation-platform-environments/pull/8674

**Comment by mikereiddigital** [comment]
I've reviewed this issue & moving to done.
