### ISSUE TITLE
🌐 Attach Analytical Platform Ingestion VPCs to MoJO TGW

### ISSUE THREAD

**Issue by jacobwoffenden** [ministryofjustice/modernisation-platform#8275]
### User Story

As an Analytical Platform Engineer
I want to connect our Analytical Platform Ingestion VPCs to MoJO TGW
So that we can route to DOM1 from our DataSync deployment

### Value / Purpose

I am not in any team has write access to https://github.com/ministryofjustice/deployment-tgw/ so I cannot make the required changes

### Useful Contacts

@jacobwoffenden

### Additional Information

Similar request to https://github.com/ministryofjustice/deployment-tgw/

Is part of this work https://github.com/ministryofjustice/analytical-platform/issues/5175

### Definition of Done

- [x] RAM share TGW
- [x] Add relevant configuration to route ranges

**Comment by dms1981** [comment]
RAM share created here: https://github.com/ministryofjustice/deployment-tgw/pull/255
Attachment created here: https://github.com/ministryofjustice/deployment-tgw/pull/256

Tested with @jacobwoffenden that connectivity through to internal MOJ network for things such as DNS lookups and SMB access is successful
