### ISSUE TITLE
SPIKE: AWS Budgets

### ISSUE THREAD

**Issue by jakemulley** [ministryofjustice/modernisation-platform#83]
Add a single budget rule to see if this is useful. Can this be done by resource, by account?

What are the notification options? Let's go with the simplest, which is probably an email to our group gmail.

Do we want alerts to go to tenants as well? Should probably keep it to notifications to the platform team at first.

Adding budgets will allow us to be alerted to excessive or unusual usage

This is probably a duplicate of #1897

**Comment by ewastempel** [comment]
Eg using up lots of IPs, large instances, lots of resources etc.

Org level alerting so that it can see everything in the OU
Could be a billing thing

**Comment by SimonPPledger** [comment]
I think budget only gives a view on cost rather than any other resources. I had a look to see if i could set up a budget for ModP, but I don't have the access
