### ISSUE TITLE
Automation to create KMS keys per business unit

### ISSUE THREAD

**Issue by davidkelliott** [ministryofjustice/modernisation-platform#833]
## User Story

As a modernisation platform user
I need encrypt things like snapshots with a shared KMS key
So that I can move encrypted things between accounts

## Value

See [KMS ADR here](https://github.com/ministryofjustice/modernisation-platform/blob/main/architecture-decision-record/0008-use-kms-in-shared-services-for-cross-account-encryption.md)

## Definition of done

- [ ] keys for existing business units created in the core-shared-services-account
- [ ] keys will be created per business unit automatically upon business unit creation
- [ ] there will be an RDS, EBS, and General key per business unit
- [ ] key policy will only allow access to accounts with the relevant business unit
- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] tests are green

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by dms1981** [comment]
Brought this one back into `doing` as it failed to be successfully applied. I'll investigate the cause and submit another PR for a fix branch to resolve this.
