### ISSUE TITLE
Create `electronic-monitoring-data-preproduction` environment

### ISSUE THREAD

**Issue by dms1981** [ministryofjustice/modernisation-platform#8386]
### Environment details

Requested by @pricemg in [this PR](https://github.com/ministryofjustice/modernisation-platform/pull/8353).

### Application Name

electronic-monitoring-data

### Description of application

See PR in `Environment details`; this story tracks the creation of a preprod environment.

### SSO Group Name

hmpps-electronic-monitoring-data-store

### Environments

- [ ] Development
- [ ] test
- [x] Preproduction
- [ ] Production

### Environment access level Preproduction

developer

### application

electronic-monitoring-data

### business-unit

HMPPS

### infrastructure-support

dataengineering@digital.justice.gov.uk

### owner

Data engineering: dataengineering@digital.justice.gov.uk

### Subnet sets

- [x] General
- [ ] Isolated

### How do users connect to the application

Over the public internet

### Additional features

Please check any additional features required
- [ ] Additional VPC Endpoints
- [ ] Extended DNS Zones
- [ ] Other - please specify

### Other information

https://github.com/ministryofjustice/modernisation-platform/pull/8353

https://github.com/ministryofjustice/modernisation-platform/pull/8378

https://github.com/ministryofjustice/modernisation-platform/pull/8385

### Definition of Done

Definition of Done
- [x] account created
- [x] customer informed

**Comment by dms1981** [comment]
Informed customer via Slack

**Comment by mikereiddigital** [comment]
Have reviewed & will move to done.
