### ISSUE TITLE
lake formation administrator user (CI user)

### ISSUE THREAD

**Issue by ep-93** [ministryofjustice/modernisation-platform#8408]
### User Story

As a Mod Platform user
I expect to be able to use lake formation correctly, without permission errors, as a role/account has not been assigned as admin. 

Two roles need to be added:

- CI user role for AWS Nuke purposes.

- Sandbox role for the account. 

### Value / Purpose

So teams can use lake formation without custom setups and deployment methods, our pipeline should work.

### Context / Background

Nuke failures in electronic monitor data because of lake formation resources that cannot be removed.

The goal is to add the required role ARN to the list of "Data Lake Administrators". This is separate to IAM permissions and is defined within Lake Formation itself.

In terraform this list is defined here - https://github.com/ministryofjustice/modernisation-platform-environments/blob/main/terraform/environments/analytical-platform-compute/lakeformation-data-lake-settings.tf

Data resources will need to be added for the two roles in question. 

To test that these roles have been successfully added:

 - log onto the analytic-platform-compute-development account as ModPlatformEngineer. 

- Access Lake Formation

- On the left-side menu, select "Administration", then "Administrative Roles and Tasks"

- Then scroll down to find the list of "Data lake administrators". The two new roles should be listed there.

### Useful Contacts

Edd Proctor
Mike Reid

### Additional Information

Line 331 - https://github.com/ministryofjustice/modernisation-platform-environments/compare/main...em-lf-dbt

Looking up a role and making it a lake_formation admin, we could use something similar to make a few of our roles admins by default.

### Definition of Done

- [ ] Add sandbox role and ci user role to the administrator list.
- [ ] Test via the console & confirm role is added.

**Comment by Kudzai-moj** [comment]
I have created the code and tested changes using cooker and it worked. Currently there is a temporary change freeze on analytic-platform-compute. I will push the PR once this freeze has been lifted

**Comment by Kudzai-moj** [comment]
I have created a run book and contacted the 3 customers that are currently using lake formation to add the 2 roles to their admin list.

I have also created a follow up t[icket](https://github.com/ministryofjustice/modernisation-platform/issues/8619) to see the best way to manage these roles long term.
