### ISSUE TITLE
Investigate permissions on listed roles.

### ISSUE THREAD

**Issue by ep-93** [ministryofjustice/modernisation-platform#8418]
### User Story

As a mod platform engineer, theres one role that AWS has flagged as very open, and two others that may be able to be locked down further. We should investigate these and see what can be done.

**_High Priority_**

- ad-fixngo-ec2-roles - core shared services only, although flagged by AWS it needs a wildcard so it can be accessed by all of our accounts.
- member-shared-services - core shared services only, although flagged by AWS it needs a wildcard so it can be accessed by all of our accounts.

_**Just to see if we can tie it down more**_

- AWS-SSM-AutomationExecutionRole - Created by us, all is required for patching. 
- circleci_iam_role - We could reduce it, but that would limit the team using it if any further changes are required with new resource types.

### Value / Purpose

It came from this spike. https://github.com/ministryofjustice/modernisation-platform/issues/6169

### Context / Background

This spike 

https://github.com/ministryofjustice/modernisation-platform/issues/6169

### Useful Contacts

Simon Pledger, Edd Proctor

### Definition of Done

- [ ] Role has been assessed, and PR create to reduce permissions in that role.
- [ ] Deployed and tested, to make sure it does not impact teams.
- [ ] Shown the team.

**Comment by ep-93** [comment]
I looked into all roles, but the core shared service roles trust policies were the ones raised as open.

Here's what I could do



Restrict by Account ID - A pain, but could be done.. I would need to get all account IDs so in my eyes, not worth it. 
json

```
"StringEquals": {
    "aws:PrincipalAccount": "123456789012"
}
```
Restrict Service Access: If I get a reply about what this policy and role does I can restrict the service access, like so

```
"Principal": {
    "Service": "ec2.amazonaws.com"
}
```

**Comment by ep-93** [comment]
None to change, or worth it. However, the two will be raised as open permissions in IAM. This is something I think we should live with, raised a ticket about IAM Unused access analyser for firebreak!

**Comment by mikereiddigital** [comment]
We discussed this as a team last week. Moving to done.
