### ISSUE TITLE
V3 of actions/upload-artifact & actions/download-artefact to be deprecated on 30/11/2024

### ISSUE THREAD

**Issue by mikereiddigital** [ministryofjustice/modernisation-platform#8422]
### User Story

As a Modernisation Platform Engineer 
I need to update the versions of the GitHub actions/upload-artifact & actions/download-artefact to v4
So that the upcoming deprecation of v3 does not impact our workflows.

Brownouts of this action are scheduled as follows:

November 14, 12pm - 1pm EST
November 21, 9am - 5pm EST

### Value / Purpose

It has been announced that v3 of actions/upload-artifact & actions/download-artefact are being deprecated on 30th November 2024. This will impact the following workflows:

- scorecards.yml - https://github.com/ministryofjustice/modernisation-platform/blob/ab83f66befb5ce96078d7236baacd678c220b5f5/.github/workflows/scorecards.yml#L62

- publish-gh-pages - https://github.com/ministryofjustice/modernisation-platform/blob/ab83f66befb5ce96078d7236baacd678c220b5f5/.github/workflows/publish-gh-pages.yml#L35

These need to be updated to v4 (the latest) and tested.

### Context / Background

See above.

This was also posted by Anthony Bishop in the 

### Additional Information

* https://github.com/actions/upload-artifact?tab=readme-ov-file#breaking-changes
* https://github.com/actions/upload-artifact/blob/main/docs/MIGRATION.md

### Definition of Done

- [ ] Update both actions and test before the first brownout.
- [ ] Search for any other MP workflows that may be impacted & update those.
- [ ] Review & close.

**Comment by dms1981** [comment]
Having taken a look at this one I think we might not need to do it - or if we choose to, it would be centered around applying improvements to how/where we use `upload-artifact`.

You can see the hash value for `v4.4.3` of the `upload-artifact` action is [SHA:b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882](https://github.com/actions/upload-artifact/releases/tag/v4.4.3).
If you search for this value in our GitHub organisation you can see that it's [already being used](https://github.com/search?q=org%3Aministryofjustice%20b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882&type=code).

That being said I don't _personally)_ think we're using this for its intended purpose. We generally use this to create a blob that's consumed within the same workflow, whereas the intent of `upload-artifact` is to store data for use later outside of the workflow - eg, outputting build logs or binaries from a build. The `cache` action - for passing files between jobs in a workflow - i[s probably more appropriate for our uses](https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/caching-dependencies-to-speed-up-workflows#comparing-artifacts-and-dependency-caching).

**Comment by SimonPPledger** [comment]
see above, not required
