### ISSUE TITLE
fix secure baseline module issue

### ISSUE THREAD

**Issue by philhorrocks** [ministryofjustice/modernisation-platform#854]
## Expected Behavior

The baseline process calls the secure baseline module to run against the member account. This fails with the ERROR:

Error: Creating GuardDuty Detector failed: BadRequestException: The request is rejected because a detector already exists for the current account.
{
  RespMetadata: {
    StatusCode: 400,
    RequestID: "e2fd13ad-dbf8-40e0-afab-1583625c6204"
  },
  Message_: "The request is rejected because a detector already exists for the current account.",
  Type: "InvalidInputException"
}

  on .terraform/modules/baselines/modules/guardduty/main.tf line 1, in resource "aws_guardduty_detector" "default":
   1: resource "aws_guardduty_detector" "default" {

## Actual Behavior

The secure baseline module should update the secure baseline code.

**Comment by philhorrocks** [comment]
This ticket is linked to https://github.com/ministryofjustice/modernisation-platform/issues/795

**Comment by davidkelliott** [comment]
Fixed when removing Guardduty as part of #864 864
