### ISSUE TITLE
Glue IAM permissions check

### ISSUE THREAD

**Issue by markgov** [ministryofjustice/modernisation-platform#8549]
### User Story

As a Modernisation platform engineer
I need to check glue permissions due to a bug that has been found by AWS
So that users do not lose access

### Value / Purpose

Hello,

We identified an issue with AWS Glue BatchGet APIs that requires your action. Currently, Glue BatchGet* APIs run successfully despite a Deny condition on one or more of the underlying Get operations. On December 16, 2024, we will deploy a fix for this to ensure BatchGet* APIs will fail with an AccessDeniedException if there is a Deny condition on one of the corresponding Get* operations. Your account has policies which include these contradicting statements. Please refer to the 'Affected resources' tab of your AWS Health Dashboard to see your impacted IAM resources.

You must update your policies to deny or allow AWS Glue Batch* APIs and their corresponding Get* API operations by this date. If you do not take action, the Batch API will not retrieve the resources of the Batch API call being made. Please refer to our "Actions, resources, and condition keys for AWS Glue" user guide for additional information [1].

The following is a list of the affected Glue BatchGet* APIs operations:

BatchGetDevEndpoints
BatchGetJobs
BatchGetBlueprints
BatchGetTriggers
BatchGetWorkflows

The following is a list of the affected Get* API operations:

GetDevEndpoints
GetJobs
GetBlueprints
GetTriggers
GetWorkflows

### Context / Background

Email from AWS

### Definition of Done

- [x] check IAM permissions
- [ ] change permissions 
- [ ] Reviewed by team

**Comment by Khatraf** [comment]
Affected resources:
- data_engineering_policy
- modernisation-platform-oidc-cicd-policy

**Comment by mikereiddigital** [comment]
Or create a follow-up ticket to check?

**Comment by Khatraf** [comment]
I set up a calendar reminder for myself, but might be better to have a follow up ticket. Please see here: https://github.com/ministryofjustice/modernisation-platform/issues/8665. Putting ticket back to review.

**Comment by mikereiddigital** [comment]
Thanks @Khatraf. Happy to move to done.
