### ISSUE TITLE
Analytical Platform Shared Services Environment

### ISSUE THREAD

**Issue by jacobwoffenden** [ministryofjustice/modernisation-platform#8621]
### Environment details

This environment will contain our ECR registry

### Application Name

analytical-platform-common
(formerly `analytical-platform-shared-services`)

### Description of application

Our new Airflow service will consume ECR images from a central location that is separate to Analytical Platform Compute

### SSO Group Name

analytical-platform

### GitHub code owner team slug

analytical-platform

### GitHub actions reviewer team slug

analytical-platform

### Environments

- [ ] Development
- [ ] test
- [ ] Preproduction
- [x] Production

### Environment access level Development

N/A

### Environment access level Test

N/A

### Environment access level Preproduction

N/A

### Environment access level Production

developer

### application

analytical-platform-common

### business-unit

Platforms

### infrastructure-support

analytical-platform@digital.justice.gov.uk

### owner

analytical-platform@digital.justice.gov.uk

### Subnet sets

- [x] General
- [ ] Isolated

### How do users connect to the application

Over the public internet

### Additional features

Please check any additional features required
- [ ] Additional VPC Endpoints
- [ ] Extended DNS Zones
- [ ] Other - please specify

### Definition of Done

Definition of Done
- [ ] account created
- [ ] customer informed

**Comment by SimonPPledger** [comment]
agreed to do this for production only - analytical-platform-shared-services-production

**Comment by ewastempel** [comment]
Due to the character limit when naming application, the `analytical-platform-common` name was requested.
