### ISSUE TITLE
Create testing member account

### ISSUE THREAD

**Issue by davidkelliott** [ministryofjustice/modernisation-platform#878]
## User Story

As a modernisation platform engineer
I need a testing account 
With an account type of member
So that I can run terratest for modules in a member account that I know will be clear to avoid false failures

## Value

When creating module we have decided to use Terratest to test the module.  Whilst we can use local stack for some basic modules, most modules will have functionality that we want to ensure works with our member account structure and functionality that cannot be simulated locally.  Therefore if we have a clean test account, where resources are only created and destroyed with Terratest, we can test the modules.

## Questions / Assumptions

**New account details**

Account name: testing
Account type: member
Environment: test
Github team slug: modernisation-platform
Access: developer

Networking:
Business unit: platforms
Subnet sets: general

## Definition of done

- [ ] new testing account created
- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] tests are green

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by jackstockley89** [comment]
Completed Steps 1 to 6 on the the Runbook for creating the account / environment some bugs found and issues have been raised for this
