### ISSUE TITLE
Delete lab environments that are no longer used

### ISSUE THREAD

**Issue by davidkelliott** [ministryofjustice/modernisation-platform#880]
## User Story

Delete the following environments and their relevant VPC's

- sprinkler production

- bench development
- bench production
 
- heater development
- heater production

- cooker production

## Value

These accounts were created to aid with testing when building the platform, but their names are confusing and they will be replaced by the sandbox, testing and example accounts detailed here: #877 #878 #879 

This will also be a good exercise in developing and documenting the process for deleting accounts, which we have not tried yet.

We will keep development environments for sprinkler and cooker for the moment until we have created a test account

## Definition of done

- [ ] accounts and vpcs have been deleted
- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] tests are green

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by donmasters** [comment]
Terraform used to remove resources from below accounts.
Heater - development

**Comment by donmasters** [comment]
This work is now complete, all specified accounts have been deleted
