### ISSUE TITLE
Move Windows ECS module to own repo and document how to implement

### ISSUE THREAD

**Issue by davidkelliott** [ministryofjustice/modernisation-platform#909]
## User Story

Getting Windows ECS working was tricky, we should make sure to avoid this pain in future by create a Windows ECS module with instructions and example code so that future Windows ECS applications can make use of this.

## Value

By creating a reusable module we make things easier for the next application and speed up future onboarding.

## Questions / Assumptions

The module should follow the guidelines here - https://github.com/ministryofjustice/modernisation-platform/blob/main/architecture-decision-record/0010-terraform-module-strategy.md

## Definition of done

- [x] module created
- [x] example code given
- [x] readme has been updated
- [x] user docs have been updated
- [ ] another team member has reviewed
- [ ] tests are written

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by zuriguardiola** [comment]
https://github.com/ministryofjustice/modernisation-platform-terraform-ecs to review
