### ISSUE TITLE
Harden NAT outbound NACL rules for internet traffic

### ISSUE THREAD

**Issue by philhorrocks** [ministryofjustice/modernisation-platform#917]
## User Story

We need to harden to private subnet NACL rules and restrict outbound connections to TCP port 80 and port 443. We also require an inbound rule for TCP traffic on ephemeral ports only.  

Inbound:
140 | 0.0.0.0/0 | TCP | 1024-65535 | ALLOW | Allows inbound return traffic from the NAT device in the public subnet for requests originating in the private subnet.

Outbound: 

100 | 0.0.0.0/0 | TCP | 80 | ALLOW | Allows outbound HTTP traffic from the subnet to the internet.
110 | 0.0.0.0/0 | TCP | 443 | ALLOW | Allows outbound HTTPS traffic from the subnet to the internet.

These rules need to be updated in the the Terraform NACL config.

**Comment by donmasters** [comment]
Reviewed current configuration

In addition to the listed changes I also found that public and private subnets are controlled with the same NACL rules in the automation, this requires to be changed in this ticket. The requirements for private and public subnets with regards to NACL rules are not the same.

**Comment by donmasters** [comment]
Separated Public and Private NACL rule configuration
    Configured private NACLs to allow ingress high ports only for
    centralised NAT
    Configured public NACLs to all ingress for 443 only as default
