### ISSUE TITLE
Create Bastion module for Nomis

### ISSUE THREAD

**Issue by seanprivett** [ministryofjustice/modernisation-platform#954]
## User Story

In order to do manual deployments for Nomis, the Nomis engineers and DBAs require a Bastion host

## Definition of done

- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] tests are green

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by gfou-al** [comment]
https://github.com/ministryofjustice/modernisation-platform-environments/pull/86
