### ISSUE TITLE
VPN lab and testing

### ISSUE THREAD

**Issue by seanprivett** [ministryofjustice/modernisation-platform#987]
## User Story

VPN test lab

set up a dummy VPN to imitate the Global Protect VPN
Test scenarios:

## Value

Identify any gotchas for VPN connectivity

## Definition of done

- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] tests are green

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by donmasters** [comment]
We have now learned as much as we need from this work, closing this ticket.
