### ISSUE TITLE
Add versioning to json files to trigger workflows

### ISSUE THREAD

**Issue by zuriguardiola** [ministryofjustice/modernisation-platform#995]
## User Story

Some times we need to trigger a workflow, currently we are changing the unused bastion flag from true to false.  Having a version would give us something to increment if workflow triggers are needed.

## Definition of done

- [ ] readme has been updated
- [ ] user docs have been updated
- [ ] another team member has reviewed
- [ ] tests are green

## Reference

[How to write good user stories](https://www.gov.uk/service-manual/agile-delivery/writing-user-stories)

**Comment by davidkelliott** [comment]
Closing, we don't need to do this often now
