### ISSUE TITLE
New AWS account for Analytical Platform Development Data

### ISSUE THREAD

**Issue by andylightfoot** [ministryofjustice/modernisation-platform#998]
### Application Name

analytical-platform-data

### Github team slug

analytical-platform

### Environments

- [ x] Development
- [ ] Test
- [ ] Preproduction
- [ ] Production

### Tags

tag | value
--- | ---
application | analytical-platform-data
business-unit |  Platforms
owner |  "Analytical Platform: analytical_platform@digital.justice.gov.uk"

### Connectivity
Just Internet connectivity required

### Additional features

Account-type: member-unrestricted

## Other information

This account will be used to store development data for the Analytical Platform

**Comment by davidkelliott** [comment]
Updated description with details clarified with Andy, this is the equivalent of their data account, their existing account is their management account so this should be a new json file analytical-platform-data.json
